/*
*
* Copyright (c) 2024 Texas Instruments Incorporated
*
* All rights reserved not granted herein.
*
* Limited License.
*
* Texas Instruments Incorporated grants a world-wide, royalty-free, non-exclusive
* license under copyrights and patents it now or hereafter owns or controls to make,
* have made, use, import, offer to sell and sell ("Utilize") this software subject to the
* terms herein.  With respect to the foregoing patent license, such license is granted
* solely to the extent that any such patent is necessary to Utilize the software alone.
* The patent license shall not apply to any combinations which include this software,
* other than combinations with devices manufactured by or for TI ("TI Devices").
* No hardware patent is licensed hereunder.
*
* Redistributions must preserve existing copyright notices and reproduce this license
* (including the above copyright notice and the disclaimer and (if applicable) source
* code license limitations below) in the documentation and/or other materials provided
* with the distribution
*
* Redistribution and use in binary form, without modification, are permitted provided
* that the following conditions are met:
*
* No reverse engineering, decompilation, or disassembly of this software is
* permitted with respect to any software provided in binary form.
*
* any redistribution and use are licensed by TI for use only with TI Devices.
*
* Nothing shall obligate TI to provide you with source code for the software
* licensed and provided to you in object code.
*
* If software source code is provided to you, modification and redistribution of the
* source code are permitted provided that the following conditions are met:
*
* any redistribution and use of the source code, including any resulting derivative
* works, are licensed by TI for use only with TI Devices.
*
* any redistribution and use of any object code compiled from the source code
* and any resulting derivative works, are licensed by TI for use only with TI Devices.
*
* Neither the name of Texas Instruments Incorporated nor the names of its suppliers
*
* may be used to endorse or promote products derived from this software without
* specific prior written permission.
*
* DISCLAIMER.
*
* THIS SOFTWARE IS PROVIDED BY TI AND TI'S LICENSORS "AS IS" AND ANY EXPRESS
* OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
* OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL TI AND TI'S LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
* BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
* DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
* OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
/**
 *  \file     Fls_Cfg.h
 *
 *  \brief    This file contains generated pre compile configuration file
 *            for FLS MCAL driver
 */

  /*****************************************************************************
    Project: [!"$project"!]
    This file is generated by EB Tresos
    Do not modify this file, otherwise the software may behave in unexpected way.
 ******************************************************************************/


[!AUTOSPACING!] [!/* Do not delete this line, spacing would be lost */!]

#ifndef FLS_CFG_H_
#define FLS_CFG_H_

/**
 * \addtogroup FLS Fls
 * @{
 */

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */
[!IF "as:modconf('Fls')[1]/FlsGeneral/FlsDevErrorDetect = 'true'"!]#include "Det.h"[!ENDIF!]

#include "Std_Types.h"
#include "Os.h"
#include "Fee_Cbk.h"
#include "MemIf_Types.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DOXYGEN_SHOULD_SKIP_THIS

#define FLS_QSPI_RX_LINES_SINGLE  1U
#define FLS_QSPI_RX_LINES_DUAL    2U
#define FLS_QSPI_RX_LINES_QUAD    3U


/**
 *  \name Fls Driver Configuration SW Version Info
 *
 *  Defines for Fls Driver configuration version
 *  @{
 */
/** \brief Fls configuration Major Version */
#define FLS_CFG_MAJOR_VERSION           ([!"substring-before($moduleSoftwareVer,'.')"!]U)
/** \brief Fls configuration Minor Version */
#define FLS_CFG_MINOR_VERSION           ([!"substring-before(substring-after($moduleSoftwareVer,'.'),'.')"!]U)
/** \brief Fls configuration Patch Version */
#define FLS_CFG_PATCH_VERSION           ([!"substring-after(substring-after($moduleSoftwareVer,'.'),'.')"!]U)
/* @} */

/**
*  \brief FLS Build Variant.
*   Build variants.(i.e Pre Compile,Post Build or Link time)
*/

#define FLS_PRE_COMPILE_VARIANT    ([!IF "as:modconf('Fls')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPreCompile'"!]STD_ON[!ELSE!]STD_OFF[!ENDIF!])

#define FLS_POST_BUILD_VARIANT     ([!IF "as:modconf('Fls')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPostBuild'"!]STD_ON[!ELSE!]STD_OFF[!ENDIF!])

/**  \brief Pre Compile config macro name. */
[!IF "as:modconf('Fls')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPreCompile'"!]
[!LOOP "as:modconf('Fls')[1]/FlsConfigSet"!]
#define FLS_INIT_CONFIG_PC       Fls_Config
[!ENDLOOP!]
[!ENDIF!]


/** \brief Enable/disable FLS Blank Check API */
#define FLS_BLANK_CHECK_API          ([!IF "as:modconf('Fls')[1]/FlsGeneral/FlsBlankCheckApi = 'true'"!]STD_ON[!ELSE!]STD_OFF[!ENDIF!])

/** \brief Enable/disable FLS compare API */
#define FLS_COMPARE_API              ([!IF "as:modconf('Fls')[1]/FlsGeneral/FlsCompareApi = 'true'"!]STD_ON[!ELSE!]STD_OFF[!ENDIF!])

/** \brief Enable/disable FLS cancel API */
#define FLS_CANCEL_API              ([!IF "as:modconf('Fls')[1]/FlsGeneral/FlsCancelApi = 'true'"!]STD_ON[!ELSE!]STD_OFF[!ENDIF!])

/** \brief Enable/disable FlsEraseVerificationEnabled */
#define FLS_ERASE_VERIFICATION_ENABLED             ([!IF "as:modconf('Fls')[1]/FlsGeneral/FlsEraseVerificationEnabled = 'true'"!]STD_ON[!ELSE!]STD_OFF[!ENDIF!])

/** \brief Enable/disable FlsWriteVerificationEnabled */
#define FLS_WRITE_VERIFICATION_ENABLED             ([!IF "as:modconf('Fls')[1]/FlsGeneral/FlsWriteVerificationEnabled = 'true'"!]STD_ON[!ELSE!]STD_OFF[!ENDIF!])

/** \brief Enable/disable FlsTimeoutSupervisionEnabled */
#define FLS_TIMEOUT_SUPERVISION_ENABLED             ([!IF "as:modconf('Fls')[1]/FlsGeneral/FlsTimeoutSupervisionEnabled = 'true'"!]STD_ON[!ELSE!]STD_OFF[!ENDIF!])

/** \brief Enable/disable FLS dev detect error */
#define FLS_DEV_ERROR_DETECT         ([!IF "as:modconf('Fls')[1]/FlsGeneral/FlsDevErrorDetect = 'true'"!]STD_ON[!ELSE!]STD_OFF[!ENDIF!])

/** \brief Index of driver, used by FEE */
#define FLS_DRIVER_INDEX             ([!"as:modconf('Fls')[1]/FlsGeneral/FlsDriverIndex"!]U)

/** \brief Enable/disable FLS  Fls_GetJobResult function API */
#define FLS_GET_JOB_RESULT_API        ([!IF "as:modconf('Fls')[1]/FlsGeneral/FlsGetJobResultApi = 'true'"!]STD_ON[!ELSE!]STD_OFF[!ENDIF!])

/** \brief Enable/disable FLS  Fls_GetStatus function API */
#define FLS_GET_STATUS_API            ([!IF "as:modconf('Fls')[1]/FlsGeneral/FlsGetStatusApi = 'true'"!]STD_ON[!ELSE!]STD_OFF[!ENDIF!])

/** \brief Total amount of flash memory in bytes */
#define FLS_TOTAL_SIZE                ([!"as:modconf('Fls')[1]/FlsGeneral/FlsTotalSize"!]U)


/** \brief Enable/disable FLS get version info API */
#define FLS_VERSION_INFO_API           ([!IF "as:modconf('Fls')[1]/FlsGeneral/FlsVersionInfoApi = 'true'"!]STD_ON[!ELSE!]STD_OFF[!ENDIF!])

/** \brief Enable/disable FLS set mode API*/
#define FLS_SETMODE_API                 ([!IF "as:modconf('Fls')[1]/FlsGeneral/FlsSetModeApi = 'true'"!]STD_ON[!ELSE!]STD_OFF[!ENDIF!])

/** \brief Counter ID for counter used to count wait ticks */
#define FLS_OS_COUNTER_ID              ([!IF "not(node:empty(as:modconf('Fls')[1]/FlsGeneral/FlsOsCounterRef))"!](CounterType)[!"node:name(node:ref(as:modconf('Fls')[1]/FlsGeneral/FlsOsCounterRef))"!][!ELSE!][!"as:modconf('Fls')[1]/FlsGeneral/FlsDefaultOSCounterId"!]U[!ENDIF!])

/** \brief Base Address of QSPI */
#define FLS_QSPI_CTRL_BASE_ADDR        ([!"as:modconf('Fls')[1]/FlsGeneral/FlsQspiCtrlBaseAddr "!]UL)

/** \brief Flash Base Address */
#define FLS_BASE_ADDRESS                ([!"as:modconf('Fls')[1]/FlsGeneral/FlsBaseAddress "!]UL)

/** \brief Enable/disable memory mapped FLS read*/
#define FLS_MEM_MAP_MODE                ([!IF "as:modconf('Fls')[1]/FlsConfigSet/FlsMemMapMode = 'true'"!]STD_ON[!ELSE!]STD_OFF[!ENDIF!])

/** \brief Max Erase time in millisec*/
#define FLS_MAX_ERASE_TIME                ([!"as:modconf('Fls')[1]/FlsPublishedInformation/FlsEraseTime"!])

/** \brief Max Write time in millisec*/
#define FLS_MAX_WRITE_TIME                ([!"as:modconf('Fls')[1]/FlsPublishedInformation/FlsWriteTime"!])

/** \brief Enable/Disable FLS RegisterReadback API */
#define FLS_REGISTER_READBACK_API       ([!IF "as:modconf('Fls')[1]/FlsGeneral/FlsEnableRegisterReadbackApi"!]STD_ON[!ELSE!]STD_OFF[!ENDIF!])
/** \brief Number of Sectorlist configured */
[!LOOP "as:modconf('Fls')[1]/FlsConfigSet"!][!//
[!VAR "NumOfSectorCfg" = "0"!]
[!WS "4"!][!LOOP "FlsSectorList/FlsSector/*"!]
[!VAR "NumOfSectorCfg" = "$NumOfSectorCfg + 1"!]
[!WS "4"!][!ENDLOOP!]
[!ENDLOOP!][!//

#define FLS_NUMBER_OF_SECTOR_CFG             ([!"num:i($NumOfSectorCfg)"!]U)

/** \brief Enable/disable FLS DMA Support */
#define FLS_DMA_ENABLE  ([!IF "as:modconf('Fls')[1]/FlsConfigSet/FlsEnableDMA = 'true'"!]STD_ON[!ELSE!]STD_OFF[!ENDIF!])
[!IF "FlsConfigSet/FlsEnableDMA = 'true'"!]
[!IF "FlsConfigSet/FlsMemMapMode = 'true'"!]
[!IF "not(node:empty(FlsConfigSet/FlsHwUnitCddDmaHandler))"!]
#define FLS_UNIT_EDMA_HANDLER  (CddDmaConf_[!"node:name(node:ref(FlsConfigSet/FlsHwUnitCddDmaHandler))"!])
[!ELSE!]
[!ERROR!][!//
        "Reference to the DMA handler cannot be NULL"[!//
[!ENDERROR!][!//
[!ENDIF!][!//
[!ELSE!]
[!ERROR!][!//
        "MemMapMode should be Selected to Enable DMA"[!//
[!ENDERROR!][!//
[!ENDIF!][!//
[!ENDIF!][!//

#define FLS_OSPI_PHY_ENABLE                   (STD_OFF)

/* @} */

/**
 * \name FLS interrupt configuration
 * @{
 */
 /**  \brief Job processing triggered by hardware interrupt.*/
#define FLS_USE_INTERRUPTS             ([!IF "as:modconf('Fls')[1]/FlsGeneral/FlsUseInterrupts = 'true'"!]STD_ON[!ELSE!]STD_OFF[!ENDIF!])

/** \brief ISR type */
#define FLS_ISR_TYPE                ([!"as:modconf('Fls')[1]/FlsGeneral/FlsIrqType"!])

#endif /* DOXYGEN_SHOULD_SKIP_THIS */

/* ========================================================================== */
/*                         Structures and Enums                               */
/* ========================================================================== */
[!LOOP "as:modconf('Fls')[1]/FlsConfigSet"!]
/** \brief FLS Configuration struct declaration */
extern const struct Fls_ConfigType_s Fls_Config;
[!ENDLOOP!]
extern struct Fls_ConfigSfdp_s *Fls_Config_SFDP_Ptr;


/* ========================================================================== */
/*                          Function Declarations                             */
/* ========================================================================== */

/* None */

#ifdef __cplusplus
}
#endif

/**
* @}
*/

#endif  /* #ifndef FLS_CFG_H_ */
