/*
 * TEXAS INSTRUMENTS TEXT FILE LICENSE
 *
 * Copyright (c) 2025 Texas Instruments Incorporated
 *
 * All rights reserved not granted herein.
 *
 * Limited License.
 *
 * Texas Instruments Incorporated grants a world-wide, royalty-free, non-exclusive
 * license under copyrights and patents it now or hereafter owns or controls to
 * make, have made, use, import, offer to sell and sell ("Utilize") this software
 * subject to the terms herein. With respect to the foregoing patent license,
 * such license is granted solely to the extent that any such patent is necessary
 * to Utilize the software alone. The patent license shall not apply to any
 * combinations which include this software, other than combinations with devices
 * manufactured by or for TI ("TI Devices"). No hardware patent is licensed hereunder.
 *
 * Redistributions must preserve existing copyright notices and reproduce this license
 * (including the above copyright notice and the disclaimer and (if applicable) source
 * code license limitations below) in the documentation and/or other materials provided
 * with the distribution.
 *
 * Redistribution and use in binary form, without modification, are permitted provided
 * that the following conditions are met:
 * No reverse engineering, decompilation, or disassembly of this software is
 * permitted with respect to any software provided in binary form.
 * Any redistribution and use are licensed by TI for use only with TI Devices.
 * Nothing shall obligate TI to provide you with source code for the software
 * licensed and provided to you in object code.
 *
 * If software source code is provided to you, modification and redistribution of the
 * source code are permitted provided that the following conditions are met:
 * Any redistribution and use of the source code, including any resulting derivative
 * works, are licensed by TI for use only with TI Devices.
 * Any redistribution and use of any object code compiled from the source code
 * and any resulting derivative works, are licensed by TI for use only with TI Devices.
 *
 * Neither the name of Texas Instruments Incorporated nor the names of its suppliers
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * DISCLAIMER.
 *
 * THIS SOFTWARE IS PROVIDED BY TI AND TI'S LICENSORS "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL TI AND TI'S
 * LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/**
 *  \file     Cdd_Uart_Cfg.c
 *
 *  \brief    This file contains generated pre-compile configuration file
 *            for UART Complex Device Driver
 */

  /*********************************************************************************************************************
  Project: Mcal_Demo_Cfg


    This file is generated by EB Tresos
    Do not modify this file, otherwise the software may behave in unexpected way.

 *********************************************************************************************************************/


#define CDD_UART_CFG_SOURCE 1U

/**********************************************************************************************************************
 *  INCLUDES
 *********************************************************************************************************************/
#include "Cdd_Uart_Cfg.h"
#include "Cdd_Uart_Irq.h"
#include "soc.h"

/**********************************************************************************************************************
 *  VERSION CHECK
 *********************************************************************************************************************/
#if ( (CDD_UART_CFG_MAJOR_VERSION != (10U)) \
    ||(CDD_UART_CFG_MINOR_VERSION != (2U)))
  #error "Version numbers of Cdd_Uart_Cfg.c and Cdd_Uart_Cfg.h are inconsistent!"
#endif

/**********************************************************************************************************************
 *  LOCAL CONSTANT MACROS
 **********************************************************************************************************************/

/**********************************************************************************************************************
 *  LOCAL FUNCTION MACROS
 **********************************************************************************************************************/

/**********************************************************************************************************************
 *  LOCAL DATA TYPES AND STRUCTURES
 **********************************************************************************************************************/

/**********************************************************************************************************************
 *  LOCAL DATA PROTOTYPES
 **********************************************************************************************************************/

/**********************************************************************************************************************
 *  GLOBAL DATA
 **********************************************************************************************************************/

#define CDD_UART_START_SEC_VAR_INIT_32
#include "Cdd_Uart_MemMap.h"

/** \brief CDD UART Channel base addresses on AM263Px */
uint32 baseAddresses[CDD_UART_MAXIMUM_CHANNELS] = { 0x52300000U, 0x52301000U, 0x52302000U, 0x52303000U, 0x52304000U, 0x52305000U };

#define CDD_UART_STOP_SEC_VAR_INIT_32
#include "Cdd_Uart_MemMap.h"

#define  CDD_UART_START_SEC_CONFIG_DATA
#include "Cdd_Uart_MemMap.h"

/* Callback Notify Functions */
/** \brief Prototype for the read notification callback function */
extern void CddUart_CallbackReadNotify(void);
/** \brief Prototype for the write notification callback function */
extern void CddUart_CallbackWriteNotify(void);
/** \brief Prototype for the error notification callback function */
extern void CddUart_CallbackErrorNotify(void);

/* Generation of runtime configuration */
CONST(Cdd_Uart_CfgType, CDD_UART_CFG) Cdd_Uart_Config =
{
  .netChannels = 1,
  .channelCfg = {
    [0] =
    {
      .uartHwUnitID = CDD_UART_CHANNEL_ID_0,
      .uartClockFrequency = 48000000U,
      .uartBaudRate = 115200,
      .uartIOMode = CDD_UART_MODE_DMA,
      .uartTXTriggerLevel = CDD_UART_TRIGGER_LEVEL_1,
      .uartRXTriggerLevel = CDD_UART_TRIGGER_LEVEL_1,
      .uartHwFlowControlThreshold = CDD_UART_TRIGGER_LEVEL_1,
      .uartWordLength = CDD_UART_WORD_LENGTH_8,
      .uartParity = CDD_UART_PARITY_NONE,
      .uartReadReturnMode = CDD_UART_FULL_READ_RETURN,
      .uartOperatingMode = CDD_UART_16x_OPER,
      .uartStopBits = CDD_UART_STOP_BIT_1,
      .edmaXbarRxHandleID = CddDmaConf_CddDmaDriverHandler_0_Uart_Rx,
      .edmaXbarTxHandleID = CddDmaConf_CddDmaDriverHandler_0_Uart_Tx,
      .uartNotificationHandlers.uartNotificationReadHandler = CddUart_CallbackReadNotify,
      .uartNotificationHandlers.uartNotificationWriteHandler = CddUart_CallbackWriteNotify,
      .uartNotificationHandlers.uartNotificationErrorHandler = CddUart_CallbackErrorNotify,
    },
  }
};

#define  CDD_UART_STOP_SEC_CONFIG_DATA
#include "Cdd_Uart_MemMap.h"



/**********************************************************************************************************************
 *  END OF FILE: Cdd_Uart_Cfg.c
 *********************************************************************************************************************/
