/* ======================================================================
 *   Copyright (C) 2024 Texas Instruments Incorporated
 *
 *   All rights reserved. Property of Texas Instruments Incorporated.
 *   Restricted rights to use, duplicate or disclose this code are
 *   granted through contract.
 *
 *   The program may not be used without the written permission
 *   of Texas Instruments Incorporated or against the terms and conditions
 *   stipulated in the agreement under which this program has been
 *   supplied.
 * ==================================================================== */

/**
 *  \file     Cdd_Uart_Cfg.c
 *
 *  \brief    This file contains generated pre-compile configuration file
 *            for UART Complex Device Driver
 */

  /*********************************************************************************************************************
  Project: Cdd_uart_am273x
	Date   : 2024-02-12 12:22:14

    This file is generated by EB Tresos
    Do not modify this file, otherwise the software may behave in unexpected way.

 *********************************************************************************************************************/


#define CDD_UART_CFG_SOURCE 1U

/**********************************************************************************************************************
 *  INCLUDES
 *********************************************************************************************************************/
#include "Cdd_Uart_Cfg.h"
#include "Cdd_Uart_Irq.h"
#include "soc.h"

/**********************************************************************************************************************
 *  VERSION CHECK
 *********************************************************************************************************************/
#if ( (CDD_UART_MAJOR_VERSION != (10U)) \
    ||(CDD_UART_MINOR_VERSION != (1U)))
  #error "Version numbers of Cdd_Uart_Cfg.c and Cdd_Uart_Cfg.h are inconsistent!"
#endif

/**********************************************************************************************************************
 *  LOCAL CONSTANT MACROS
 **********************************************************************************************************************/

/**********************************************************************************************************************
 *  LOCAL FUNCTION MACROS
 **********************************************************************************************************************/

/**********************************************************************************************************************
 *  LOCAL DATA TYPES AND STRUCTURES
 **********************************************************************************************************************/

/**********************************************************************************************************************
 *  LOCAL DATA PROTOTYPES
 **********************************************************************************************************************/

/**********************************************************************************************************************
 *  GLOBAL DATA
 **********************************************************************************************************************/

#define CDD_UART_START_SEC_VAR_INIT_32
#include "Cdd_Uart_MemMap.h"

/** \brief CDD UART Channel base addresses on AM273x */
uint32 baseAddresses[CDD_UART_MAXIMUM_CHANNELS] = { 0x02F7EC00U, 0x02F7ED00U };

#define CDD_UART_STOP_SEC_VAR_INIT_32
#include "Cdd_Uart_MemMap.h"

#define  CDD_UART_START_SEC_CONFIG_DATA
#include "Cdd_Uart_MemMap.h"

/* Callback Notify Functions */
/** \brief Prototype for the read notification callback function */
extern void CddUart_CallbackReadNotify(void);
/** \brief Prototype for the write notification callback function */
extern void CddUart_CallbackWriteNotify(void);
/** \brief Prototype for the error notification callback function */
extern void CddUart_CallbackErrorNotify(void);

/* Generation of runtime configuration */
CONST(Cdd_Uart_CfgType, CDD_UART_CFG) CddUartDriver_0 =
{
  .netChannels = 1,
  .channelCfg = {
    [0] =
    {
      .uartHwUnitID = CDD_UART_CHANNEL_MSS_SCIA,
      .uartClockFrequency = 200000000U,
      .uartBaudRate = 115200,
      .uartIOMode = CDD_UART_MODE_DMA,
      .uartWordLength = CDD_UART_WORD_LENGTH_8,
      .uartParity = CDD_UART_PARITY_NONE,
      .uartStopBits = CDD_UART_STOP_BIT_1,
      .edmaXbarRxHandleID = CddDmaConf_CddDmaDriverHandler_0_Uart_Rx,
      .edmaXbarTxHandleID = CddDmaConf_CddDmaDriverHandler_0_Uart_Tx,
      .uartNotificationHandlers.uartNotificationReadHandler = CddUart_CallbackReadNotify,
      .uartNotificationHandlers.uartNotificationWriteHandler = CddUart_CallbackWriteNotify,
      .uartNotificationHandlers.uartNotificationErrorHandler = CddUart_CallbackErrorNotify,
    },
  }
};

#define  CDD_UART_STOP_SEC_CONFIG_DATA
#include "Cdd_Uart_MemMap.h"



/**********************************************************************************************************************
 *  END OF FILE: Cdd_Uart_Cfg.c
 *********************************************************************************************************************/
