/*
 * TEXAS INSTRUMENTS TEXT FILE LICENSE
 *
 * Copyright (c) 2022 Texas Instruments Incorporated
 *
 * All rights reserved not granted herein.
 *
 * Limited License.
 *
 * Texas Instruments Incorporated grants a world-wide, royalty-free, non-exclusive
 * license under copyrights and patents it now or hereafter owns or controls to
 * make, have made, use, import, offer to sell and sell ("Utilize") this software
 * subject to the terms herein. With respect to the foregoing patent license,
 * such license is granted solely to the extent that any such patent is necessary
 * to Utilize the software alone. The patent license shall not apply to any
 * combinations which include this software, other than combinations with devices
 * manufactured by or for TI ("TI Devices"). No hardware patent is licensed hereunder.
 *
 * Redistributions must preserve existing copyright notices and reproduce this license
 * (including the above copyright notice and the disclaimer and (if applicable) source
 * code license limitations below) in the documentation and/or other materials provided
 * with the distribution.
 *
 * Redistribution and use in binary form, without modification, are permitted provided
 * that the following conditions are met:
 * No reverse engineering, decompilation, or disassembly of this software is
 * permitted with respect to any software provided in binary form.
 * Any redistribution and use are licensed by TI for use only with TI Devices.
 * Nothing shall obligate TI to provide you with source code for the software
 * licensed and provided to you in object code.
 *
 * If software source code is provided to you, modification and redistribution of the
 * source code are permitted provided that the following conditions are met:
 * Any redistribution and use of the source code, including any resulting derivative
 * works, are licensed by TI for use only with TI Devices.
 * Any redistribution and use of any object code compiled from the source code
 * and any resulting derivative works, are licensed by TI for use only with TI Devices.
 *
 * Neither the name of Texas Instruments Incorporated nor the names of its suppliers
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * DISCLAIMER.
 *
 * THIS SOFTWARE IS PROVIDED BY TI AND TI'S LICENSORS "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL TI AND TI'S
 * LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/**
 *  \file     Cdd_Ipc_PBCfg.c
 *
 *  \brief    This file contains generated post build configuration file
 *            for Complex device driver
 */

  /*********************************************************************************************************************
  Project: ipc_am263p
    Date   : 2024-02-26 14:21:47

    This file is generated by EB Tresos
    Do not modify this file, otherwise the software may behave in unexpected way.

 *********************************************************************************************************************/


#define CDD_PBCFG_SOURCE 1U

/**********************************************************************************************************************
 *  INCLUDES
 *********************************************************************************************************************/
#include "Cdd_Ipc.h"
#include "soc.h"

/**********************************************************************************************************************
 *  VERSION CHECK
 *********************************************************************************************************************/
#if (   (CDD_IPC_CFG_MAJOR_VERSION != (10U)) \
    || (CDD_IPC_CFG_MINOR_VERSION != (2U)))
  #error "Version numbers of Cdd_Ipc_PbCfg.c and Cdd_Ipc_Cfg.h are inconsistent!"
#endif
/**********************************************************************************************************************
 *  LOCAL CONSTANT MACROS
 **********************************************************************************************************************/

/**********************************************************************************************************************
 *  LOCAL FUNCTION MACROS
 **********************************************************************************************************************/


extern sint32 App_CrcHookFxn(uint8 *data, uint16 dataLen, uint8 crcSize, void* crc);
/**********************************************************************************************************************
 *  LOCAL DATA TYPES AND STRUCTURES
 **********************************************************************************************************************/

/**********************************************************************************************************************
 *  LOCAL DATA PROTOTYPES
 **********************************************************************************************************************/

/**********************************************************************************************************************
 *  GLOBAL DATA
 **********************************************************************************************************************/

#define  CDD_IPC_START_SEC_CONFIG_DATA
#include "Cdd_Ipc_MemMap.h"

/*
 * Requirements : AUTORADAR_MCAL-66, AUTORADAR_MCAL-65
*/

CONST(Cdd_IpcConfigType, CDD_PBCFG) Cdd_Ipc_Config =
{
    .Cdd_Ipc_SelfCoreId = CDD_IPC_R5FSS0_1_ID,
    .Cdd_Ipc_numCores = 1,
    .Cdd_Ipc_coreIdList = {
        CDD_IPC_R5FSS0_0_ID,
        },
    .Cdd_Ipc_RpMsgParams =
    {
                [0] =
        {
        .Cdd_Ipc_localEndPt = 13,
        .recvCallback = NULL_PTR,
        .recvCallbackArgs = NULL_PTR,
        .recvNotifyCallback = NULL_PTR,
        .recvNotifyCallbackArgs = NULL_PTR,
        },
    },


    .Cdd_Ipc_CrcHookFunc = App_CrcHookFxn
};

P2CONST(Cdd_IpcConfigType, AUTOMATIC, CDD_PBCFG)CfgPtr = &Cdd_Ipc_Config;
#define  CDD_IPC_STOP_SEC_CONFIG_DATA
#include "Cdd_Ipc_MemMap.h"

/* IPC RPMessage init objects */
#define CDD_IPC_START_SEC_VAR_NO_INIT_UNSPECIFIED
#include "Cdd_Ipc_MemMap.h"
RPMessageLLD_InitObject CddIpc_RPMessageInitObj;
#define CDD_IPC_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#include "Cdd_Ipc_MemMap.h"
extern IpcNotify_Object CddIpc_NotifyObject;



#define CDD_IPC_START_SEC_VAR_NO_INIT_8
#include "Cdd_Ipc_MemMap.h"
uint8 Cdd_Ipc_SharedMem[CDD_IPC_SHARED_MEMORY_SIZE] __attribute__((aligned(128), section("ipc_vring")));
#define  CDD_IPC_STOP_SEC_VAR_NO_INIT_8
#include "Cdd_Ipc_MemMap.h"




#define CDD_IPC_START_SEC_CODE
#include "Cdd_Ipc_MemMap.h"
void Cdd_Ipc_SafeIpcMemoryAllocation(IpcNotify_MailboxConfig *mailboxConfig)
{
    IpcNotify_MailboxConfig (*mailboxConfigPtr)[MCAL_CSL_CORE_ID_MAX] = (void *)mailboxConfig;


    mailboxConfigPtr[0][1].swQ = (IpcNotify_SwQueue *)(&Cdd_Ipc_SharedMem[0]);
    mailboxConfigPtr[1][0].swQ = (IpcNotify_SwQueue *)(&Cdd_Ipc_SharedMem[32]);

    CddIpc_RPMessageInitObj.vringRxBaseAddr[0] = (uintptr_t)(&Cdd_Ipc_SharedMem[64]);
    CddIpc_RPMessageInitObj.vringTxBaseAddr[0] = (uintptr_t)(&Cdd_Ipc_SharedMem[1376]);


    CddIpc_RPMessageInitObj.vringSize = CDD_IPC_VRING_SIZE;
    CddIpc_RPMessageInitObj.vringNumBuf = CDD_IPC_NUM_OF_BUFFERS;
    CddIpc_RPMessageInitObj.vringMsgSize = CDD_IPC_MAX_BUFFER_SIZE;
    CddIpc_RPMessageInitObj.hIpcNotify = &CddIpc_NotifyObject;
};
#define CDD_IPC_STOP_SEC_CODE
#include "Cdd_Ipc_MemMap.h"

/**********************************************************************************************************************
 *  END OF FILE: Cdd_PBcfg.c
 *********************************************************************************************************************/
