/* ======================================================================
 *   Copyright (C) 2025 Texas Instruments Incorporated

 *
 *   All rights reserved. Property of Texas Instruments Incorporated.
 *   Restricted rights to use, duplicate or disclose this code are
 *   granted through contract.
 *
 *   The program may not be used without the written permission
 *   of Texas Instruments Incorporated or against the terms and conditions
 *   stipulated in the agreement under which this program has been
 *   supplied.
 * ==================================================================== */

/**
 *  \file     Cdd_Dma_Cfg.h
 *
 *  \brief    This file contains generated pre compile configuration file
 *            for Complex device driver
 */

  /*********************************************************************************************************************
    Project: MCAL_AM261x_CDD_Dma_for_CDD_FSI
    Date   : 2025-01-21 16:51:07

    This file is generated by EB Tresos
    Do not modify this file, otherwise the software may behave in unexpected way.

 *********************************************************************************************************************/

#ifndef CDD_DMA_CFG_H_
#define CDD_DMA_CFG_H_

/**
 * \addtogroup DMA Dma
 * @{
 */

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */
#include "Std_Types.h"
#include "Os.h"
#include "Dem.h"
#include "Cdd_Dma.h"
#include "mcal_hw_soc.h"
#include "Det.h"


#ifdef __cplusplus
extern "C" {
#endif

#ifndef DOXYGEN_SHOULD_SKIP_THIS

/**
 *  \name CDD DMA Driver Configuration SW Version Info
 *
 *  Defines for CDD DMA Driver configuration version
 *  @{
 */
/** \brief CDD DMA configuration Major Version */
#define CDD_DMA_MAJOR_VERSION                 (10U)
/** \brief CDD DMA configuration Minor Version */
#define CDD_DMA_MINOR_VERSION                 (1U)
/** \brief CDD DMA configuration Patch Version */
#define CDD_DMA_PATCH_VERSION                 (0U)
/* @} */

/* ========================================================================== */
/*                           Macros & Typedefs                                */
/* ========================================================================== */

/** \brief CDD DMA Config ID */
#define CDD_DMA_ID                                                        (0x1U)

/** \brief Enable/Disable CDD DMA dev detect error */
/* Requirements: ___ */
#define CDD_DMA_DEV_ERROR_DETECT                                          (STD_ON)

/**
 *  \name Pre-Compile Switches for API Services
 */
/** \brief Enable/Disable CDD DMA get version info API */
#define CDD_DMA_VERSION_INFO_API                                          (STD_ON)
#define CDD_DMA_DEINIT_API                                                (STD_ON)
#define CDD_DMA_REGISTER_READBACK_API                                     (STD_ON)

#define CDD_DMA_MAX_HANDLER                                               28U
#define CDD_DMA_MAX_CHANNEL                                               2U
#define CDD_DMA_MAX_PARAM                                                 2U

/** \brief CDD DMA resources amount */
#define CDD_DMA_NUM_DMACH_SOC                                             64U
#define CDD_DMA_NUM_PARAMSETS_SOC                                         256U

/** \brief CDD DMA Interrupt Service Routine Category */
#define CDD_DMA_ISR_TYPE                                                  CDD_DMA_ISR_VOID

/** \brief CDD DMA Instances */
#define CDD_DMA_RCSS_A                                                    0U
#define CDD_DMA_MSS_A                                                     1U
#define CDD_DMA_MSS_B                                                     2U
#define CDD_DMA_DSS_A                                                     3U
#define CDD_DMA_DSS_B                                                     4U
#define CDD_DMA_DSS_C                                                     5U

/** \brief CSL Base Addresses for Sitara AM261x */
#define MCAL_MSS_CTRL_U_BASE                                              (0x50D00000U)
#define MCAL_MSS_TPCC_A_U_BASE                                            (0x52A00000U)

/** \brief CDD DMA Completion Interrupt Number */
#define MCAL_MSS_INTR_MSS_TPCC_A_INTAGG                                   106

/** \brief CDD DMA field MSS and DSS TPCC Adresseses for Interrupt Aggregate */
#define MCAL_MSS_CTRL_MSS_TPCC_A_INTAGG_MASK                              (0x00000848U)
#define MCAL_MSS_CTRL_MSS_TPCC_A_INTAGG_STATUS                            (0x0000084CU)

/** \brief CDD DMA  Shift Mask. */
#define CDD_DMA_CSL_R5_MPIDR_AFF0_MASK                                   (0x000000FFU)
#define CDD_DMA_CSL_R5_MPIDR_AFF0_SHIFT                                  (0U)
#define CDD_DMA_CSL_R5_MPIDR_AFF1_MASK                                   (0x0000FF00U)
#define CDD_DMA_CSL_R5_MPIDR_AFF1_SHIFT                                  (8U)

/** \brief CDD DMA  Base address. */
#define CDD_DMA_CSL_MSS_CTRL_U_BASE                                      (0x50D00000U)

/** \brief CDD DMA Lock Step. */
#define CDD_DMA_CSL_MSS_CTRL_R5_STATUS_REG_R5_STATUS_REG_LOCK_STEP_MASK                (0x00000100U)
#define CDD_DMA_CSL_MSS_CTRL_R5_STATUS_REG_R5_STATUS_REG_LOCK_STEP_SHIFT               (0x00000008U)
#define CDD_DMA_CSL_MSS_CTRL_R5_STATUS_REG_R5_STATUS_REG_LOCK_STEP_RESETVAL            (0x00000000U)
#define CDD_DMA_CSL_MSS_CTRL_R5_STATUS_REG_R5_STATUS_REG_LOCK_STEP_MAX                 (0x00000001U)

/** \brief CDD DMA RAM Size and address. */
#define CDD_DMA_CSL_MSS_TCMA_RAM_BASE               (0x00000000U)
#define CDD_DMA_CSL_MSS_TCMA_RAM_SIZE               (0x00008000U)  
#define CDD_DMA_CSL_MSS_TCMB_RAM_BASE               (0x00080000U)
#define CDD_DMA_CSL_MSS_TCMB_RAM_SIZE               (0x00008000U)

/* PRE-COMPLIE variant related macro(s) */
#define CDD_DMA_PRE_COMPILE_VARIANT                                       STD_ON

#endif /* DOXYGEN_SHOULD_SKIP_THIS */

/* ========================================================================== */
/*                         Structures and Enums                               */
/* ========================================================================== */

/**
 *  \brief This type defines a range of specific status for Complex driver
 */
/* Requirements :  SitaraMCU_MCAL-__ */
/* Design: SitaraMCU_MCAL-__ */
typedef enum
{
    /** \brief The Complex Driver is not initialized or not usable */
    CDD_DMA_UNINIT =       0U,
    /** \brief The Complex Driver is not currently transferring */
    CDD_DMA_IDLE =         1U,
    /** \brief The Complex Driver is currently open */
    CDD_DMA_ALLOW_ACCESS = 2U,
    /** \brief The Complex Driver is performing a write operation */
    CDD_DMA_BUSY =         3U,
    /** \brief The Complex Driver is currently closed */
    CDD_DMA_CLOSE =        4U,
} CddDma_StatusType;

#define CDD_DMA_TRIG_XBAR_EDMA_MODULE_0_INPUT   CDD_DMA_TRIG_XBAR_USART0_DMA_0
#define CDD_DMA_TRIG_XBAR_EDMA_MODULE_1_INPUT   CDD_DMA_TRIG_XBAR_USART0_DMA_1
#define CDD_DMA_TRIG_XBAR_EDMA_MODULE_2_INPUT   CDD_DMA_TRIG_XBAR_USART1_DMA_0
#define CDD_DMA_TRIG_XBAR_EDMA_MODULE_3_INPUT   CDD_DMA_TRIG_XBAR_USART1_DMA_1
#define CDD_DMA_TRIG_XBAR_EDMA_MODULE_4_INPUT   CDD_DMA_TRIG_XBAR_USART2_DMA_0
#define CDD_DMA_TRIG_XBAR_EDMA_MODULE_5_INPUT   CDD_DMA_TRIG_XBAR_USART2_DMA_1
#define CDD_DMA_TRIG_XBAR_EDMA_MODULE_6_INPUT   CDD_DMA_TRIG_XBAR_USART3_DMA_0
#define CDD_DMA_TRIG_XBAR_EDMA_MODULE_7_INPUT   CDD_DMA_TRIG_XBAR_USART3_DMA_1
#define CDD_DMA_TRIG_XBAR_EDMA_MODULE_8_INPUT   CDD_DMA_TRIG_XBAR_USART4_DMA_0
#define CDD_DMA_TRIG_XBAR_EDMA_MODULE_9_INPUT   CDD_DMA_TRIG_XBAR_USART4_DMA_1
#define CDD_DMA_TRIG_XBAR_EDMA_MODULE_10_INPUT   CDD_DMA_TRIG_XBAR_DMA_XBAR_OUT_0
#define CDD_DMA_TRIG_XBAR_EDMA_MODULE_11_INPUT   CDD_DMA_TRIG_XBAR_DMA_XBAR_OUT_1
#define CDD_DMA_TRIG_XBAR_EDMA_MODULE_12_INPUT   CDD_DMA_TRIG_XBAR_DMA_XBAR_OUT_2
#define CDD_DMA_TRIG_XBAR_EDMA_MODULE_20_INPUT   CDD_DMA_TRIG_XBAR_SPI0_DMA_WRITE_REQ0
#define CDD_DMA_TRIG_XBAR_EDMA_MODULE_21_INPUT   CDD_DMA_TRIG_XBAR_SPI0_DMA_READ_REQ0
#define CDD_DMA_TRIG_XBAR_EDMA_MODULE_22_INPUT   CDD_DMA_TRIG_XBAR_SPI1_DMA_WRITE_REQ0
#define CDD_DMA_TRIG_XBAR_EDMA_MODULE_23_INPUT   CDD_DMA_TRIG_XBAR_SPI1_DMA_READ_REQ0
#define CDD_DMA_TRIG_XBAR_EDMA_MODULE_24_INPUT   CDD_DMA_TRIG_XBAR_SPI2_DMA_WRITE_REQ0
#define CDD_DMA_TRIG_XBAR_EDMA_MODULE_25_INPUT   CDD_DMA_TRIG_XBAR_SPI2_DMA_READ_REQ0
#define CDD_DMA_TRIG_XBAR_EDMA_MODULE_26_INPUT   CDD_DMA_TRIG_XBAR_SPI3_DMA_WRITE_REQ0
#define CDD_DMA_TRIG_XBAR_EDMA_MODULE_27_INPUT   CDD_DMA_TRIG_XBAR_SPI3_DMA_READ_REQ0
#define CDD_DMA_TRIG_XBAR_EDMA_MODULE_30_INPUT   CDD_DMA_TRIG_XBAR_DMA_XBAR_OUT_7
#define CDD_DMA_TRIG_XBAR_EDMA_MODULE_34_INPUT   CDD_DMA_TRIG_XBAR_DMA_XBAR_OUT_10

#define CddDmaConf_CddDmaDriverHandler_0_Uart_Tx  0
#define CddDmaConf_CddDmaDriverHandler_0_Uart_Rx  1
#define CddDmaConf_CddDmaDriverHandler_1_Uart_Tx  2
#define CddDmaConf_CddDmaDriverHandler_1_Uart_Rx  3
#define CddDmaConf_CddDmaDriverHandler_2_Uart_Tx  4
#define CddDmaConf_CddDmaDriverHandler_2_Uart_Rx  5
#define CddDmaConf_CddDmaDriverHandler_3_Uart_Tx  6
#define CddDmaConf_CddDmaDriverHandler_3_Uart_Rx  7
#define CddDmaConf_CddDmaDriverHandler_4_Uart_Tx  8
#define CddDmaConf_CddDmaDriverHandler_4_Uart_Rx  9
#define CddDmaConf_CddDmaDriverHandler_0_Adc  10
#define CddDmaConf_CddDmaDriverHandler_1_Adc  11
#define CddDmaConf_CddDmaDriverHandler_2_Adc  12
#define CddDmaConf_CddDmaDriverHandler_MemoryTransfer_Interrupt  13
#define CddDmaConf_CddDmaDriverHandler_MemoryTransfer_Linking  14
#define CddDmaConf_CddDmaDriverHandler_MemoryTransfer_Polling  15
#define CddDmaConf_CddDmaDriverHandler_MemoryTransfer_Chaining  16
#define CddDmaConf_CddDmaDriverHandler_Spi_0_Tx  17
#define CddDmaConf_CddDmaDriverHandler_Spi_0_Rx  18
#define CddDmaConf_CddDmaDriverHandler_Spi_1_Tx  19
#define CddDmaConf_CddDmaDriverHandler_Spi_1_Rx  20
#define CddDmaConf_CddDmaDriverHandler_Spi_2_Tx  21
#define CddDmaConf_CddDmaDriverHandler_Spi_2_Rx  22
#define CddDmaConf_CddDmaDriverHandler_Spi_3_Tx  23
#define CddDmaConf_CddDmaDriverHandler_Spi_3_Rx  24
#define CddDmaConf_CddDmaDriverHandler_0_FsiTx  25
#define CddDmaConf_CddDmaDriverHandler_0_FsiRx  26
#define CddDmaConf_CddDmaDriverHandler_0_Fls  27

/** \brief Cdd Configuration struct declaration */
extern CONST(Cdd_Dma_ConfigType, CDD_DMA_CFG) CddDmaDriverHandler;
  
extern volatile uint8 Cdd_Dma_handleAlreadyInUse[CDD_DMA_MAX_HANDLER];

/**
* @}
*/

/* ========================================================================== */
/*                          Function Declarations                             */
/* ========================================================================== */
extern void Cdd_Dma_TrigXbar(void);
extern void Cdd_Dma_Xbar(void);

#ifdef __cplusplus
}
#endif

#endif  /* #ifndef CDD_DMA_CFG_H_ */
