/*
 * TEXAS INSTRUMENTS TEXT FILE LICENSE
 *
 * Copyright (c) 2022-2023 Texas Instruments Incorporated
 *
 * All rights reserved not granted herein.
 *
 * Limited License.
 *
 * Texas Instruments Incorporated grants a world-wide, royalty-free, non-exclusive
 * license under copyrights and patents it now or hereafter owns or controls to
 * make, have made, use, import, offer to sell and sell ("Utilize") this software
 * subject to the terms herein. With respect to the foregoing patent license,
 * such license is granted solely to the extent that any such patent is necessary
 * to Utilize the software alone. The patent license shall not apply to any
 * combinations which include this software, other than combinations with devices
 * manufactured by or for TI ("TI Devices"). No hardware patent is licensed hereunder.
 *
 * Redistributions must preserve existing copyright notices and reproduce this license
 * (including the above copyright notice and the disclaimer and (if applicable) source
 * code license limitations below) in the documentation and/or other materials provided
 * with the distribution.
 *
 * Redistribution and use in binary form, without modification, are permitted provided
 * that the following conditions are met:
 * No reverse engineering, decompilation, or disassembly of this software is
 * permitted with respect to any software provided in binary form.
 * Any redistribution and use are licensed by TI for use only with TI Devices.
 * Nothing shall obligate TI to provide you with source code for the software
 * licensed and provided to you in object code.
 *
 * If software source code is provided to you, modification and redistribution of the
 * source code are permitted provided that the following conditions are met:
 * Any redistribution and use of the source code, including any resulting derivative
 * works, are licensed by TI for use only with TI Devices.
 * Any redistribution and use of any object code compiled from the source code
 * and any resulting derivative works, are licensed by TI for use only with TI Devices.
 *
 * Neither the name of Texas Instruments Incorporated nor the names of its suppliers
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * DISCLAIMER.
 *
 * THIS SOFTWARE IS PROVIDED BY TI AND TI'S LICENSORS "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL TI AND TI'S
 * LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/**
 *  \file     Wdg_Cfg.h
 *
 *  \brief    This file contains generated pre compile configuration file
 *            for WDG MCAL driver
 *
 */

/*******************************************************************************
    Project: wdg_skip_reset_app


    This file is generated by EB Tresos
    Do not modify this file, otherwise the software may behave in unexpected way.

*******************************************************************************/

/* Protection against multiple inclusion */
#ifndef WDG_CFG_H_
#define WDG_CFG_H_

/**
 * \addtogroup WDG Wdg
 * @{
 */

/*******************************************************************************
 * Standard Header Files
 ******************************************************************************/

/*******************************************************************************
 * Other Header Files
 ******************************************************************************/
#include "Dem.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*******************************************************************************
 * Version Check
 *******************************************************************************/
/**
 *  \name Wdg Driver Configuration SW Version Info
 *
 *  Defines for Wdg Driver configuration version
 *  @{
 */
/** \brief Wdg configuration Major Version */
#define WDG_CFG_MAJOR_VERSION           (10U)
/** \brief Wdg configuration Minor Version */
#define WDG_CFG_MINOR_VERSION           (2U)
/** \brief Wdg configuration Patch Version */
#define WDG_CFG_PATCH_VERSION           (2U)
/* @} */
/**
*  \name WDG Build Variant.
*   Build variants.(i.e Pre Compile,Post Build or Link time)
* @{
*/
#define WDG_VARIANT_PRE_COMPILE       (STD_OFF)

#define WDG_VARIANT_POST_BUILD        (STD_ON)

#define WDG_VARIANT_LINK_TIME         (STD_OFF)
/* @} */

/** \brief WDG configuration index*/
#define WDG_CFG_ID          (0x1U)

#define WDG_MAX_INSTANCES             	(4U)

/*******************************************************************************
 * Exported Preprocessor #define Constants
 ******************************************************************************/


/**
 *  \name Pre-Compile Switches for API Services
 *  @{
 */
/** \brief Enable/Disable Development Error Detection */
#define WDG_DEV_ERROR_DETECT       (STD_ON)

/** \brief Enable/Disable Version Info API */
#define WDG_GET_VERSION_INFO_API   (STD_ON)

/** \brief Enable/Disable Register Readback API */
#define WDG_REGISTER_READBACK_API  (STD_ON)

/** \brief Watchdog Disable Allowed*/
#define WDG_DISABLE_ALLOWED        (STD_OFF)

/** \brief Enable/Disable skipping force reset of WDG when 0 timeout is passed in Wdg_SetTriggerCondition */
#define WDG_SKIP_FORCE_RESET       (STD_ON)
/** @} */

/** \brief Watchdog Initial Timeout */
#define WDG_INITIAL_TIMEOUT        (1 * 1000)

/** \brief Watchdog Maximum Timeout */
#define WDG_MAX_TIMEOUT            (65 * 1000)


/** \brief Watchdog Maximum preload value */
#define WDG_MAX_PRELOAD_VALUE       (0xFFFU)

/** \brief RTI Clock Frequency */
#define WDG_RTI_FREQUENCY          ((uint32)200)

/**
 *  \name WDG DEM Error codes to report
 *
 *  Pre-compile switches for enabling/disabling DEM events
 *  @{
 */

/** \brief  WDG failed */
#ifndef WDG_E_MODE_FAILED
#define WDG_E_MODE_FAILED           (DemConf_DemEventParameter_WDG_E_MODE_FAILED)
#endif

/** \brief  WDG disable rejected */
#ifndef WDG_E_DISABLE_REJECTED
#define WDG_E_DISABLE_REJECTED     (DemConf_DemEventParameter_WDG_E_DISABLE_REJECTED)
#endif

#ifndef WDG_E_HARDWARE_ERROR
/** \brief Hardware failed */
#define WDG_E_HARDWARE_ERROR          (DemConf_DemEventParameter_WDG_E_HARDWARE_ERROR)
#endif
/* @} */
/*******************************************************************************
 * Exported Preprocessor #define Macros
 ******************************************************************************/

/** \brief WDG Configuration struct declaration */
extern const struct Wdg_ConfigType_s Wdg_Config;

#ifdef __cplusplus
}
#endif

#endif /* DOXYGEN_SHOULD_SKIP_THIS */

/**
* @}
*/

#endif  /* WDG_CFG_H_ */
/*******************************************************************************
 *  End of File: Wdg_Cfg.h
 ******************************************************************************/
