/* ======================================================================
 *   Copyright (C) 2025 Texas Instruments Incorporated
 *
 *   All rights reserved. Property of Texas Instruments Incorporated.
 *   Restricted rights to use, duplicate or disclose this code are
 *   granted through contract.
 *
 *   The program may not be used without the written permission
 *   of Texas Instruments Incorporated or against the terms and conditions
 *   stipulated in the agreement under which this program has been
 *   supplied.
 * ==================================================================== */

/*

 *  -------------------------------------------------------------------------------------------------------------------
 *  FILE DESCRIPTION
 *  -------------------------------------------------------------------------------------------------------------------
 *         File:  Cdd_Pwm_Cfg.h
 *      Project:  TI Sitara CDD_PWM driver configuration
 *       Module:  Cdd_Pwm
 *    Generator:  EB Tresos
 *

*******************************************************************************************************************/


/**********************************************************************************************************************
    Project: Cdd_pwm_am263x
	Date   : 2024-02-13 15:15:23

    This file is generated by EB Tresos
    Do not modify this file, otherwise the software may behave in unexpected way.

 *********************************************************************************************************************/
#ifndef CDD_PWM_CFG_H
#define CDD_PWM_CFG_H

/**
 * \addtogroup CDD_PWM Epwm API GUIDE Header file
 * @{
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DOXYGEN_SHOULD_SKIP_THIS

/* ========================================================================== */
/*                           Macros & Typedefs                                */
/* ========================================================================== */
/**
 *  \brief CDD_PWM Build Variant.
 *   Build variants.(i.e Pre-compile or Post-build)
 */
#define CDD_PWM_PRE_COMPILE_VARIANT        (STD_OFF)
#define CDD_PWM_POST_BUILD_VARIANT         (STD_ON )

/**
 *  \name Cdd_Pwm Driver Configuration SW Version Info
 *
 *  Defines for Cdd_Pwm Driver configuration version
 *  @{
 */
/** \brief Cdd_Pwm configuration Major Version */
#define CDD_PWM_CFG_MAJOR_VERSION           (10U)
/** \brief Cdd_Pwm configuration Minor Version */
#define CDD_PWM_CFG_MINOR_VERSION           (1U)
/** \brief Cdd_Pwm configuration Patch Version */
#define CDD_PWM_CFG_PATCH_VERSION           (0U)
/* @} */



/** \brief Enable/Disable CDD_PWM DeInit API */
#define CDD_PWM_DEINIT_API      (STD_ON)

/** \brief Enable/Disable CDD_PWM Cdd_Pwm_GetCounter API */
#define CDD_PWM_GET_COUNTER_API      (STD_ON)

/** \brief Enable/Disable CDD_PWM VersionInfo API */
#define CDD_PWM_VERSION_INFO_API    (STD_ON)

/** \brief Enable/Disable CDD_PWM RegisterReadback API */
#define CDD_PWM_REGISTER_READBACK_API       (STD_ON)

/** \brief Enable/Disable CDD_PWM RegisterReadback API */
#define CDD_PWM_ADC_ENABLE_DISABLE_API       (STD_ON)

/** \brief Enable/Disable CDD_PWM Cdd_Pwm_SetRelativeThreshold API. */
#define CDD_PWM_SET_RELATIVE_THRESHOLD_API    (STD_ON)

/** \brief Enable/Disable CDD_PWM Cdd_Pwm_SetAbsoluteThreshold API. */
#define CDD_PWM_SET_ABSOLUTE_THRESHOLD_API    (STD_ON)

/** \brief Enable/Disable CDD_PWM Cdd_Pwm_SetPinAction API. */
#define CDD_PWM_SET_PIN_ACTION_API            (STD_ON)

/** \brief Enable/Disable CDD_PWM Cdd_Pwm_SetPeriodDutyPhase API. */
#define CDD_PWM_SET_PERIOD_DUTY_PHASE_API     (STD_ON)

/** \brief Enable/Disable CDD_PWM Cdd_Pwm_SetOutputToIdle API. */
#define CDD_PWM_SET_OUTPUT_TO_IDLE_API        (STD_ON)

/** \brief Enable/Disable CDD_PWM Cdd_Pwm_GetCounterStatus API. */
#define CDD_PWM_COUNTER_STATUS_MODE        (STD_ON)

/** \brief Enable/Disable CDD_PWM Cdd_Pwm_CounterComparatorCfg API. */
#define CDD_PWM_COUNTER_COMPARE_CFG        (STD_ON)

/** \brief Enable/Disable CDD_PWM Dutycycle update always at the end of the period */
#define CDD_PWM_NOTIFICATION_SUPPORTED     (STD_ON)

/** \brief ISR type */
#define CDD_PWM_ISR_TYPE    (CDD_PWM_ISR_VOID)

/** \brief System Clock. */
#define CDD_PWM_SYSTEM_CLK_FREQ   (200000000U)

/** \brief Max Duty Cycle. */
#define CDD_PWM_DUTYCYCLE_MAX   (65536U)

/** \brief Enable/Disable CDD_PWM Development Error. */
#define CDD_PWM_DEV_ERROR_DETECT              (STD_ON)

/** \brief Enable/Disable CDD_PWM Action Qualifier. */
#define CDD_PWM_ACTION_QUALIFIER              (STD_ON)

/** \brief Enable/Disable CDD_PWM Event Trigger. */
#define CDD_PWM_EVENT_TRIGGER                 (STD_ON)

/** \brief Enable/Disable CDD_PWM Trip Zone. */
#define CDD_PWM_TRIP_ZONE                     (STD_ON)

/** \brief Enable/Disable CDD_PWM DigitalCompare. */
#define CDD_PWM_DIGITALCOMPARE                (STD_ON)

/** \brief Enable/Disable CDD_PWM Dead Band. */
#define CDD_PWM_DEAD_BAND                     (STD_ON)

/** \brief Enable/Disable CDD_PWM Chopper. */
#define CDD_PWM_CHOPPER                       (STD_ON)

/** \brief Enable/Disable CDD_PWM Sync functionality. */
#define CDD_PWM_BASE_CLK_SYNC                 (STD_ON)

/** \brief Enable/Disable Cdd_Pwm_HrSetPeriodDutyPhase API. */
#define CDD_PWM_HR_SET_HRPWM_API			  (STD_ON)

/** \brief Enable/Disable Cdd_Pwm_HrSfoCalibration API. */
#define CDD_PWM_HR_SFO_CAL_API				  (STD_ON)

/** \brief Enable/Disable Cdd_Pwm_HrSfoStatus API. */
#define CDD_PWM_HR_SFO_STATUS_API			  (STD_ON)


/** \brief Number of configured channels */
#define CDD_PWM_MAX_NUM_CHANNELS   (2U)


/** \brief Number of configured channels */
#define CDD_PWM_TIMER_BASE_NUM_CHANNELS   (1U)


/** \brief Number of configured channels */
#define CDD_PWM_COUNTER_NUM_CHANNELS   (2U)


/** \brief Number of configured channels */
#define CDD_PWM_TIMER_BASE_SYNC_NUM_CHANNELS   (2U)


/** \brief Number of configured channels */
#define CDD_PWM_TIMER_AQ_NUM_CHANNELS   (2U)


/** \brief Number of configured channels */
#define CDD_PWM_TIMER_EVENT_NUM_CHANNELS   (2U)


/** \brief Number of configured channels */
#define CDD_PWM_TIMER_ADC_EVENT_NUM_CHANNELS   (2U)


/** \brief Number of configured channels */
#define CDD_PWM_TIMER_TRIP_ZONE_NUM_CHANNELS   (2U)

/** \brief Number of configured channels */
#define CDD_PWM_DIGITAL_COMPARE_NUM_CHANNELS   (1U)

/** \brief Number of configured channels */
#define CDD_PWM_TIMER_DEAD_BAND_NUM_CHANNELS   (2U)


/** \brief Number of configured channels */
#define CDD_PWM_TIMER_CHOPPER_NUM_CHANNELS   (2U)


/** \brief Number of configured channels */
#define CDD_PWM_TIMER_HRPWM_NUM_CHANNELS   (2U)

/** \brief MAX Number of PWM Channels.  */
#define CDD_PWM_HW_MAX_NUM_CHANNELS        (128U)

/** \brief Number of EPWM channels */
#define CDD_PWM_CHANNEL_0   0U
#define CDD_PWM_CHANNEL_1   1U
#define CDD_PWM_CHANNEL_2   2U
#define CDD_PWM_CHANNEL_3   3U
#define CDD_PWM_CHANNEL_4   4U
#define CDD_PWM_CHANNEL_5   5U
#define CDD_PWM_CHANNEL_6   6U
#define CDD_PWM_CHANNEL_7   7U
#define CDD_PWM_CHANNEL_8   8U
#define CDD_PWM_CHANNEL_9   9U
#define CDD_PWM_CHANNEL_10  10U
#define CDD_PWM_CHANNEL_11  11U
#define CDD_PWM_CHANNEL_12  12U
#define CDD_PWM_CHANNEL_13  13U
#define CDD_PWM_CHANNEL_14  14U
#define CDD_PWM_CHANNEL_15  15U
#define CDD_PWM_CHANNEL_16  16U
#define CDD_PWM_CHANNEL_17  17U
#define CDD_PWM_CHANNEL_18  18U
#define CDD_PWM_CHANNEL_19  19U
#define CDD_PWM_CHANNEL_20  20U
#define CDD_PWM_CHANNEL_21  21U
#define CDD_PWM_CHANNEL_22  22U
#define CDD_PWM_CHANNEL_23  23U
#define CDD_PWM_CHANNEL_24  24U
#define CDD_PWM_CHANNEL_25  25U
#define CDD_PWM_CHANNEL_26  26U
#define CDD_PWM_CHANNEL_27  27U
#define CDD_PWM_CHANNEL_28  28U
#define CDD_PWM_CHANNEL_29  29U
#define CDD_PWM_CHANNEL_30  30U
#define CDD_PWM_CHANNEL_31  31U

/**
*  \brief Channel ID
*  Symbolic Names Configured channel ID(s)
*/
#define CddPwmConf_CddPwmConfigSet_0_CddPwmChannel_CddPwmChannel_0          (0U)
#define CddPwmConf_CddPwmConfigSet_0_CddPwmChannel_CddPwmChannel_1          (1U)



/**
 *  \brief CDD PWM GROUP ID's.
 */
#define CDD_PWM_CONTROLSS_G0 0U
#define CDD_PWM_CONTROLSS_G1 1U
#define CDD_PWM_CONTROLSS_G2 2U
#define CDD_PWM_CONTROLSS_G3 3U

/**
 *  \brief CDD PWM total channel count.
 */
#define CDD_PWM_MAX_CHANNELS_IN_EACH_GROUP  (32U)

/**
 *  \brief CDD PWM Calcualtion of channel ID
 */
#define CDD_PWM_CHANNEL_ID(GroupNumber,Channel)         ((GroupNumber*CDD_PWM_MAX_CHANNELS_IN_EACH_GROUP)+Channel)

/** \brief CDD_PWM Channel CddPwmConf_CddPwmChannel_CddPwmChannel_0 */
#define CDD_PWM_G0_CHANNEL_0 (0U)
/** \brief CDD_PWM Channel CddPwmConf_CddPwmChannel_CddPwmChannel_1 */
#define CDD_PWM_G0_CHANNEL_1 (1U)

#endif /* DOXYGEN_SHOULD_SKIP_THIS */

/* ========================================================================== */
/*                         Structures and Enums                               */
/* ========================================================================== */
/** \brief CDD_PWM Configuration structure declaration */
extern const struct Cdd_Pwm_ConfigType_s CddPwmConfigSet_0;



#ifdef __cplusplus
}
#endif

/**
 * @}
 */

#endif /* CDD_PWM_CFG_H */


/**********************************************************************************************************************
 *  END OF FILE: Cdd_Pwm_Cfg.h
 *********************************************************************************************************************/


