/** @file soc_rcm.h
 *   @brief Porting of RCM clock config from mcu_plus_sdk
 *   @date 05.Jan.2024
 *   @version 01.00.00
 *
 */

/*
 * Copyright (C) 2024 Texas Instruments Incorporated - TI web adress www.ti.com
 *
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

#ifndef SOC_RCM_H
#define SOC_RCM_H

#ifdef __cplusplus
extern "C" {
#endif

/* PLL_CORE_M2NDIV */

#define CSL_MSS_TOPRCM_PLL_CORE_M2NDIV_PLL_CORE_M2NDIV_N_MASK     (0x000000FFU)
#define CSL_MSS_TOPRCM_PLL_CORE_M2NDIV_PLL_CORE_M2NDIV_N_SHIFT    (0x00000000U)
#define CSL_MSS_TOPRCM_PLL_CORE_M2NDIV_PLL_CORE_M2NDIV_N_RESETVAL (0x00000000U)
#define CSL_MSS_TOPRCM_PLL_CORE_M2NDIV_PLL_CORE_M2NDIV_N_MAX      (0x000000FFU)

#define CSL_MSS_TOPRCM_PLL_CORE_M2NDIV_PLL_CORE_M2NDIV_M2_MASK     (0x007F0000U)
#define CSL_MSS_TOPRCM_PLL_CORE_M2NDIV_PLL_CORE_M2NDIV_M2_SHIFT    (0x00000010U)
#define CSL_MSS_TOPRCM_PLL_CORE_M2NDIV_PLL_CORE_M2NDIV_M2_RESETVAL (0x00000000U)
#define CSL_MSS_TOPRCM_PLL_CORE_M2NDIV_PLL_CORE_M2NDIV_M2_MAX      (0x0000007FU)

#define CSL_MSS_TOPRCM_PLL_CORE_M2NDIV_RESETVAL (0x00000000U)

/* PLL_CORE_MN2DIV */

#define CSL_MSS_TOPRCM_PLL_CORE_MN2DIV_PLL_CORE_MN2DIV_M_MASK     (0x00000FFFU)
#define CSL_MSS_TOPRCM_PLL_CORE_MN2DIV_PLL_CORE_MN2DIV_M_SHIFT    (0x00000000U)
#define CSL_MSS_TOPRCM_PLL_CORE_MN2DIV_PLL_CORE_MN2DIV_M_RESETVAL (0x00000174U)
#define CSL_MSS_TOPRCM_PLL_CORE_MN2DIV_PLL_CORE_MN2DIV_M_MAX      (0x00000FFFU)

#define CSL_MSS_TOPRCM_PLL_CORE_MN2DIV_PLL_CORE_MN2DIV_N2_MASK     (0x000F0000U)
#define CSL_MSS_TOPRCM_PLL_CORE_MN2DIV_PLL_CORE_MN2DIV_N2_SHIFT    (0x00000010U)
#define CSL_MSS_TOPRCM_PLL_CORE_MN2DIV_PLL_CORE_MN2DIV_N2_RESETVAL (0x00000000U)
#define CSL_MSS_TOPRCM_PLL_CORE_MN2DIV_PLL_CORE_MN2DIV_N2_MAX      (0x0000000FU)

#define CSL_MSS_TOPRCM_PLL_CORE_MN2DIV_RESETVAL (0x00000174U)

/* PLL_CORE_FRACDIV */

#define CSL_MSS_TOPRCM_PLL_CORE_FRACDIV_PLL_CORE_FRACDIV_FRACTIONALM_MASK     (0x0003FFFFU)
#define CSL_MSS_TOPRCM_PLL_CORE_FRACDIV_PLL_CORE_FRACDIV_FRACTIONALM_SHIFT    (0x00000000U)
#define CSL_MSS_TOPRCM_PLL_CORE_FRACDIV_PLL_CORE_FRACDIV_FRACTIONALM_RESETVAL (0x00000000U)
#define CSL_MSS_TOPRCM_PLL_CORE_FRACDIV_PLL_CORE_FRACDIV_FRACTIONALM_MAX      (0x0003FFFFU)

#define CSL_MSS_TOPRCM_PLL_CORE_FRACDIV_PLL_CORE_FRACDIV_REGSD_MASK     (0xFF000000U)
#define CSL_MSS_TOPRCM_PLL_CORE_FRACDIV_PLL_CORE_FRACDIV_REGSD_SHIFT    (0x00000018U)
#define CSL_MSS_TOPRCM_PLL_CORE_FRACDIV_PLL_CORE_FRACDIV_REGSD_RESETVAL (0x00000008U)
#define CSL_MSS_TOPRCM_PLL_CORE_FRACDIV_PLL_CORE_FRACDIV_REGSD_MAX      (0x000000FFU)

#define CSL_MSS_TOPRCM_PLL_CORE_FRACDIV_RESETVAL (0x08000000U)

/* PLL_CORE_CLKCTRL */

#define CSL_MSS_TOPRCM_PLL_CORE_CLKCTRL_PLL_CORE_CLKCTRL_ULOWCLKEN_MASK     (0x00040000U)
#define CSL_MSS_TOPRCM_PLL_CORE_CLKCTRL_PLL_CORE_CLKCTRL_ULOWCLKEN_SHIFT    (0x00000012U)
#define CSL_MSS_TOPRCM_PLL_CORE_CLKCTRL_PLL_CORE_CLKCTRL_ULOWCLKEN_RESETVAL (0x00000000U)
#define CSL_MSS_TOPRCM_PLL_CORE_CLKCTRL_PLL_CORE_CLKCTRL_ULOWCLKEN_MAX      (0x00000001U)

/* PLL_CORE_HSDIVIDER_CLKOUT0 */

#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT0_PLL_CORE_HSDIVIDER_CLKOUT0_DIV_MASK     (0x0000001FU)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT0_PLL_CORE_HSDIVIDER_CLKOUT0_DIV_SHIFT    (0x00000000U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT0_PLL_CORE_HSDIVIDER_CLKOUT0_DIV_RESETVAL (0x00000004U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT0_PLL_CORE_HSDIVIDER_CLKOUT0_DIV_MAX      (0x0000001FU)

#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT0_PLL_CORE_HSDIVIDER_CLKOUT0_DIVCHACK_MASK     (0x00000020U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT0_PLL_CORE_HSDIVIDER_CLKOUT0_DIVCHACK_SHIFT    (0x00000005U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT0_PLL_CORE_HSDIVIDER_CLKOUT0_DIVCHACK_RESETVAL (0x00000001U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT0_PLL_CORE_HSDIVIDER_CLKOUT0_DIVCHACK_MAX      (0x00000001U)

#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT0_PLL_CORE_HSDIVIDER_CLKOUT0_GATE_CTRL_MASK     (0x00000100U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT0_PLL_CORE_HSDIVIDER_CLKOUT0_GATE_CTRL_SHIFT    (0x00000008U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT0_PLL_CORE_HSDIVIDER_CLKOUT0_GATE_CTRL_RESETVAL (0x00000000U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT0_PLL_CORE_HSDIVIDER_CLKOUT0_GATE_CTRL_MAX      (0x00000001U)

#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT0_PLL_CORE_HSDIVIDER_CLKOUT0_STATUS_MASK     (0x00000200U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT0_PLL_CORE_HSDIVIDER_CLKOUT0_STATUS_SHIFT    (0x00000009U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT0_PLL_CORE_HSDIVIDER_CLKOUT0_STATUS_RESETVAL (0x00000000U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT0_PLL_CORE_HSDIVIDER_CLKOUT0_STATUS_MAX      (0x00000001U)

#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT0_PLL_CORE_HSDIVIDER_CLKOUT0_PWDN_MASK     (0x00001000U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT0_PLL_CORE_HSDIVIDER_CLKOUT0_PWDN_SHIFT    (0x0000000CU)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT0_PLL_CORE_HSDIVIDER_CLKOUT0_PWDN_RESETVAL (0x00000000U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT0_PLL_CORE_HSDIVIDER_CLKOUT0_PWDN_MAX      (0x00000001U)

#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT0_RESETVAL (0x00000024U)

/* PLL_CORE_HSDIVIDER_CLKOUT1 */

#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT1_PLL_CORE_HSDIVIDER_CLKOUT1_DIV_MASK     (0x0000001FU)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT1_PLL_CORE_HSDIVIDER_CLKOUT1_DIV_SHIFT    (0x00000000U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT1_PLL_CORE_HSDIVIDER_CLKOUT1_DIV_RESETVAL (0x00000004U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT1_PLL_CORE_HSDIVIDER_CLKOUT1_DIV_MAX      (0x0000001FU)

#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT1_PLL_CORE_HSDIVIDER_CLKOUT1_DIVCHACK_MASK     (0x00000020U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT1_PLL_CORE_HSDIVIDER_CLKOUT1_DIVCHACK_SHIFT    (0x00000005U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT1_PLL_CORE_HSDIVIDER_CLKOUT1_DIVCHACK_RESETVAL (0x00000001U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT1_PLL_CORE_HSDIVIDER_CLKOUT1_DIVCHACK_MAX      (0x00000001U)

#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT1_PLL_CORE_HSDIVIDER_CLKOUT1_GATE_CTRL_MASK     (0x00000100U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT1_PLL_CORE_HSDIVIDER_CLKOUT1_GATE_CTRL_SHIFT    (0x00000008U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT1_PLL_CORE_HSDIVIDER_CLKOUT1_GATE_CTRL_RESETVAL (0x00000000U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT1_PLL_CORE_HSDIVIDER_CLKOUT1_GATE_CTRL_MAX      (0x00000001U)

#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT1_PLL_CORE_HSDIVIDER_CLKOUT1_STATUS_MASK     (0x00000200U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT1_PLL_CORE_HSDIVIDER_CLKOUT1_STATUS_SHIFT    (0x00000009U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT1_PLL_CORE_HSDIVIDER_CLKOUT1_STATUS_RESETVAL (0x00000000U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT1_PLL_CORE_HSDIVIDER_CLKOUT1_STATUS_MAX      (0x00000001U)

#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT1_PLL_CORE_HSDIVIDER_CLKOUT1_PWDN_MASK     (0x00001000U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT1_PLL_CORE_HSDIVIDER_CLKOUT1_PWDN_SHIFT    (0x0000000CU)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT1_PLL_CORE_HSDIVIDER_CLKOUT1_PWDN_RESETVAL (0x00000000U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT1_PLL_CORE_HSDIVIDER_CLKOUT1_PWDN_MAX      (0x00000001U)

#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT1_RESETVAL (0x00000024U)

/* PLL_CORE_HSDIVIDER_CLKOUT2 */

#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT2_PLL_CORE_HSDIVIDER_CLKOUT2_DIV_MASK     (0x0000001FU)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT2_PLL_CORE_HSDIVIDER_CLKOUT2_DIV_SHIFT    (0x00000000U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT2_PLL_CORE_HSDIVIDER_CLKOUT2_DIV_RESETVAL (0x00000004U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT2_PLL_CORE_HSDIVIDER_CLKOUT2_DIV_MAX      (0x0000001FU)

#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT2_PLL_CORE_HSDIVIDER_CLKOUT2_DIVCHACK_MASK     (0x00000020U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT2_PLL_CORE_HSDIVIDER_CLKOUT2_DIVCHACK_SHIFT    (0x00000005U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT2_PLL_CORE_HSDIVIDER_CLKOUT2_DIVCHACK_RESETVAL (0x00000001U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT2_PLL_CORE_HSDIVIDER_CLKOUT2_DIVCHACK_MAX      (0x00000001U)

#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT2_PLL_CORE_HSDIVIDER_CLKOUT2_GATE_CTRL_MASK     (0x00000100U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT2_PLL_CORE_HSDIVIDER_CLKOUT2_GATE_CTRL_SHIFT    (0x00000008U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT2_PLL_CORE_HSDIVIDER_CLKOUT2_GATE_CTRL_RESETVAL (0x00000000U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT2_PLL_CORE_HSDIVIDER_CLKOUT2_GATE_CTRL_MAX      (0x00000001U)

#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT2_PLL_CORE_HSDIVIDER_CLKOUT2_STATUS_MASK     (0x00000200U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT2_PLL_CORE_HSDIVIDER_CLKOUT2_STATUS_SHIFT    (0x00000009U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT2_PLL_CORE_HSDIVIDER_CLKOUT2_STATUS_RESETVAL (0x00000000U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT2_PLL_CORE_HSDIVIDER_CLKOUT2_STATUS_MAX      (0x00000001U)

#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT2_PLL_CORE_HSDIVIDER_CLKOUT2_PWDN_MASK     (0x00001000U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT2_PLL_CORE_HSDIVIDER_CLKOUT2_PWDN_SHIFT    (0x0000000CU)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT2_PLL_CORE_HSDIVIDER_CLKOUT2_PWDN_RESETVAL (0x00000000U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT2_PLL_CORE_HSDIVIDER_CLKOUT2_PWDN_MAX      (0x00000001U)

#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT2_RESETVAL (0x00000024U)

/* PLL_CORE_HSDIVIDER_CLKOUT3 */

#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT3_PLL_CORE_HSDIVIDER_CLKOUT3_DIV_MASK     (0x0000001FU)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT3_PLL_CORE_HSDIVIDER_CLKOUT3_DIV_SHIFT    (0x00000000U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT3_PLL_CORE_HSDIVIDER_CLKOUT3_DIV_RESETVAL (0x00000004U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT3_PLL_CORE_HSDIVIDER_CLKOUT3_DIV_MAX      (0x0000001FU)

#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT3_PLL_CORE_HSDIVIDER_CLKOUT3_DIVCHACK_MASK     (0x00000020U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT3_PLL_CORE_HSDIVIDER_CLKOUT3_DIVCHACK_SHIFT    (0x00000005U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT3_PLL_CORE_HSDIVIDER_CLKOUT3_DIVCHACK_RESETVAL (0x00000001U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT3_PLL_CORE_HSDIVIDER_CLKOUT3_DIVCHACK_MAX      (0x00000001U)

#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT3_PLL_CORE_HSDIVIDER_CLKOUT3_GATE_CTRL_MASK     (0x00000100U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT3_PLL_CORE_HSDIVIDER_CLKOUT3_GATE_CTRL_SHIFT    (0x00000008U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT3_PLL_CORE_HSDIVIDER_CLKOUT3_GATE_CTRL_RESETVAL (0x00000000U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT3_PLL_CORE_HSDIVIDER_CLKOUT3_GATE_CTRL_MAX      (0x00000001U)

#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT3_PLL_CORE_HSDIVIDER_CLKOUT3_STATUS_MASK     (0x00000200U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT3_PLL_CORE_HSDIVIDER_CLKOUT3_STATUS_SHIFT    (0x00000009U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT3_PLL_CORE_HSDIVIDER_CLKOUT3_STATUS_RESETVAL (0x00000000U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT3_PLL_CORE_HSDIVIDER_CLKOUT3_STATUS_MAX      (0x00000001U)

#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT3_PLL_CORE_HSDIVIDER_CLKOUT3_PWDN_MASK     (0x00001000U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT3_PLL_CORE_HSDIVIDER_CLKOUT3_PWDN_SHIFT    (0x0000000CU)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT3_PLL_CORE_HSDIVIDER_CLKOUT3_PWDN_RESETVAL (0x00000000U)
#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT3_PLL_CORE_HSDIVIDER_CLKOUT3_PWDN_MAX      (0x00000001U)

#define CSL_MSS_TOPRCM_PLL_CORE_HSDIVIDER_CLKOUT3_RESETVAL (0x00000024U)

/* copy from soc_rcm.h */
#define SOC_RCM_FREQ_HZ2MHZ(hz)  ((hz) / (1000000U))
#define SOC_RCM_FREQ_MHZ2HZ(mhz) ((mhz) * (1000000U))

/* copy from soc_rcm.c */
#define SOC_RCM_L3MEMCONFIG_START_BIT              (7U)
#define SOC_RCM_L3MEMCONFIG_END_BIT                (10U)
#define SOC_RCM_FLASHMODECONFIG_START_BIT          (15U)
#define SOC_RCM_FLASHMODECONFIG_END_BIT            (16U)
#define SOC_RCM_QSPIFREQCONFIG_START_BIT           (17U)
#define SOC_RCM_QSPIFREQCONFIG_END_BIT             (18U)
#define SOC_RCM_BISTENABLECONFIG_START_BIT         (1U)
#define SOC_RCM_BISTENABLECONFIG_END_BIT           (9U)
#define SOC_RCM_COREADPLLTRIMCONFIG_START_BIT      (0U)
#define SOC_RCM_COREADPLLTRIMCONFIG_END_BIT        (11U)
#define SOC_RCM_DSPADPLLTRIMCONFIG_START_BIT       (12U)
#define SOC_RCM_DSPADPLLTRIMCONFIG_END_BIT         (23U)
#define SOC_RCM_PERADPLLTRIMCONFIG_START_BIT       (0U)
#define SOC_RCM_PERADPLLTRIMCONFIG_END_BIT         (11U)
#define SOC_RCM_COREADPLLTRIMVALIDCONFIG_START_BIT (12U)
#define SOC_RCM_COREADPLLTRIMVALIDCONFIG_END_BIT   (12U)
#define SOC_RCM_DSPADPLLTRIMVALIDCONFIG_START_BIT  (13U)
#define SOC_RCM_DSPADPLLTRIMVALIDCONFIG_END_BIT    (13U)
#define SOC_RCM_PERADPLLTRIMVALIDCONFIG_START_BIT  (14U)
#define SOC_RCM_PERADPLLTRIMVALIDCONFIG_END_BIT    (14U)
#define SOC_RCM_PARTID_START_BIT                   (13U)
#define SOC_RCM_PARTID_END_BIT                     (24U)
#define SOC_RCM_PARTNUMBER_START_BIT               (0U)
#define SOC_RCM_PARTNUMBER_END_BIT                 (2U)
#define SOC_RCM_PGVERSION_START_BIT                (0U)
#define SOC_RCM_PGVERSION_END_BIT                  (3U)
#define SOC_RCM_ROMVERSION_START_BIT               (4U)
#define SOC_RCM_ROMVERSION_END_BIT                 (6U)
#define SOC_RCM_METALVERSION_START_BIT             (7U)
#define SOC_RCM_METALVERSION_END_BIT               (9U)
#define SOC_RCM_XTAL_FREQ_SCALE_START_BIT          (25U)
#define SOC_RCM_XTAL_FREQ_SCALE_END_BIT            (25U)

#define SOC_RCM_CORE_ADPLL_DEFAULT_VALUE       (0x9U)
#define SOC_RCM_DSP_ADPLL_DEFAULT_VALUE        (0x9U)
#define SOC_RCM_PER_ADPLL_DEFAULT_VALUE        (0x9U)
#define SOC_RCM_PLL_SYS_CLK_FREQUENCY_HZ       (200000000U)
#define SOC_RCM_PLL_HSDIV_CLKOUT2_FREQUENCY_HZ (400000000U)
#define SOC_RCM_XTAL_CLK_40MHZ                 (40000000U)
#define SOC_RCM_XTAL_CLK_50MHZ                 (50000000U)
#define SOC_RCM_XTAL_CLK_49p152MHZ             (49152000U)
#define SOC_RCM_XTAL_CLK_45p1584MHZ            (45158400U)
#define SOC_RCM_XTAL_CLK_20MHZ                 (20000000U)
#define SOC_RCM_XTAL_CLK_25MHZ                 (25000000U)
#define SOC_RCM_XTAL_CLK_24p576MHZ             (24576000U)
#define SOC_RCM_XTAL_CLK_22p5792MHZ            (22579200U)

#define SOC_RCM_UTILS_ARRAYSIZE(x) (sizeof(x) / sizeof(x[0]))

#define SOC_RCM_FREQ_1GHZ (1000U * 1000U * 1000U)

/* the Field EXTract macro */
#define CSL_FEXT(reg, PER_REG_FIELD) (((reg) & CSL_##PER_REG_FIELD##_MASK) >> CSL_##PER_REG_FIELD##_SHIFT)

/* typedef for soc_rcm porting */
typedef uint32 uint32_t;
typedef uint16 uint16_t;
typedef uint8  uint8_t;

typedef enum SOC_RcmXtalFreqId_e
{
    SOC_RcmXtalFreqId_CLK_40MHZ,
    SOC_RcmXtalFreqId_CLK_50MHZ,
    SOC_RcmXtalFreqId_CLK_49p152MHZ,
    SOC_RcmXtalFreqId_CLK_45p1584MHZ,
    SOC_RcmXtalFreqId_CLK_20MHZ,
    SOC_RcmXtalFreqId_CLK_25MHZ,
    SOC_RcmXtalFreqId_CLK_24p576MHZ,
    SOC_RcmXtalFreqId_CLK_22p5792MHZ
} SOC_RcmXtalFreqId;

typedef enum SOC_RcmPllHsDivOutId_e
{
    SOC_RcmPllHsDivOutId_0,
    SOC_RcmPllHsDivOutId_1,
    SOC_RcmPllHsDivOutId_2,
    SOC_RcmPllHsDivOutId_3,
    SOC_RcmPllHsDivOutId_NONE,
} SOC_RcmPllHsDivOutId;

typedef struct SOC_RcmXtalInfo_s
{
    uint32_t Finp;
    uint32_t div2flag;
} SOC_RcmXtalInfo;

typedef struct SOC_RcmADPLLJConfig_s
{
    uint32_t N;     /* Input Clock divider/Pre-divider (N) */
    uint32_t M2;    /* Post divider (M2) */
    uint32_t M;     /* Multiplier integer (M) */
    uint32_t FracM; /* Multiplier fractional (M) */
    uint32_t Fout;  /* Output frequency of PLL */
    uint32_t Finp;  /* Output frequency of PLL */
} SOC_RcmADPLLJConfig;

#ifdef __cplusplus
}
#endif

#endif /* SOC_RCM_H */
