/* ======================================================================
 *   Copyright (c) 2022 Texas Instruments Incorporated
 *
 *   All rights reserved. Property of Texas Instruments Incorporated.
 *   Restricted rights to use, duplicate or disclose this code are
 *   granted through contract.
 *
 *   The program may not be used without the written permission
 *   of Texas Instruments Incorporated or against the terms and conditions
 *   stipulated in the agreement under which this program has been
 *   supplied.
 * ==================================================================== */

#ifndef HW_OSPI_H_
#define HW_OSPI_H_

#ifdef __cplusplus
extern "C"
{
#endif

/**************************************************************************
* Register Definitions
**************************************************************************/

#define OSPI_CONFIG_REG                                          (0x00000000U)
#define OSPI_DEV_INSTR_RD_CONFIG_REG                             (0x00000004U)
#define OSPI_DEV_INSTR_WR_CONFIG_REG                             (0x00000008U)
#define OSPI_DEV_DELAY_REG                                       (0x0000000CU)
#define OSPI_RD_DATA_CAPTURE_REG                                 (0x00000010U)
#define OSPI_DEV_SIZE_CONFIG_REG                                 (0x00000014U)
#define OSPI_SRAM_PARTITION_CFG_REG                              (0x00000018U)
#define OSPI_IND_AHB_ADDR_TRIGGER_REG                            (0x0000001CU)
#define OSPI_DMA_PERIPH_CONFIG_REG                               (0x00000020U)
#define OSPI_REMAP_ADDR_REG                                      (0x00000024U)
#define OSPI_MODE_BIT_CONFIG_REG                                 (0x00000028U)
#define OSPI_SRAM_FILL_REG                                       (0x0000002CU)
#define OSPI_TX_THRESH_REG                                       (0x00000030U)
#define OSPI_RX_THRESH_REG                                       (0x00000034U)
#define OSPI_WRITE_COMPLETION_CTRL_REG                           (0x00000038U)
#define OSPI_NO_OF_POLLS_BEF_EXP_REG                             (0x0000003CU)
#define OSPI_IRQ_STATUS_REG                                      (0x00000040U)
#define OSPI_IRQ_MASK_REG                                        (0x00000044U)
#define OSPI_LOWER_WR_PROT_REG                                   (0x00000050U)
#define OSPI_UPPER_WR_PROT_REG                                   (0x00000054U)
#define OSPI_WR_PROT_CTRL_REG                                    (0x00000058U)
#define OSPI_INDIRECT_READ_XFER_CTRL_REG                         (0x00000060U)
#define OSPI_INDIRECT_READ_XFER_WATERMARK_REG                    (0x00000064U)
#define OSPI_INDIRECT_READ_XFER_START_REG                        (0x00000068U)
#define OSPI_INDIRECT_READ_XFER_NUM_BYTES_REG                    (0x0000006CU)
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG                        (0x00000070U)
#define OSPI_INDIRECT_WRITE_XFER_WATERMARK_REG                   (0x00000074U)
#define OSPI_INDIRECT_WRITE_XFER_START_REG                       (0x00000078U)
#define OSPI_INDIRECT_WRITE_XFER_NUM_BYTES_REG                   (0x0000007CU)
#define OSPI_INDIRECT_TRIGGER_ADDR_RANGE_REG                     (0x00000080U)
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG                          (0x0000008CU)
#define OSPI_FLASH_CMD_CTRL_REG                                  (0x00000090U)
#define OSPI_FLASH_CMD_ADDR_REG                                  (0x00000094U)
#define OSPI_FLASH_RD_DATA_LOWER_REG                             (0x000000A0U)
#define OSPI_FLASH_RD_DATA_UPPER_REG                             (0x000000A4U)
#define OSPI_FLASH_WR_DATA_LOWER_REG                             (0x000000A8U)
#define OSPI_FLASH_WR_DATA_UPPER_REG                             (0x000000ACU)
#define OSPI_POLLING_FLASH_STATUS_REG                            (0x000000B0U)
#define OSPI_PHY_CONFIGURATION_REG                               (0x000000B4U)
#define OSPI_PHY_MASTER_CONTROL_REG                              (0x000000B8U)
#define OSPI_DLL_OBSERVABLE_LOWER_REG                            (0x000000BCU)
#define OSPI_DLL_OBSERVABLE_UPPER_REG                            (0x000000C0U)
#define OSPI_OPCODE_EXT_LOWER_REG                                (0x000000E0U)
#define OSPI_OPCODE_EXT_UPPER_REG                                (0x000000E4U)
#define OSPI_MODULE_ID_REG                                       (0x000000FCU)

/**************************************************************************
* Field Definition Macros
**************************************************************************/


/* CONFIG_REG */

#define OSPI_CONFIG_REG_ENB_SPI_FLD_MASK                         (0x00000001U)
#define OSPI_CONFIG_REG_ENB_SPI_FLD_SHIFT                        (0x00000000U)
#define OSPI_CONFIG_REG_ENB_SPI_FLD_MAX                          (0x00000001U)

#define OSPI_CONFIG_REG_SEL_CLK_POL_FLD_MASK                     (0x00000002U)
#define OSPI_CONFIG_REG_SEL_CLK_POL_FLD_SHIFT                    (0x00000001U)
#define OSPI_CONFIG_REG_SEL_CLK_POL_FLD_MAX                      (0x00000001U)

#define OSPI_CONFIG_REG_SEL_CLK_PHASE_FLD_MASK                   (0x00000004U)
#define OSPI_CONFIG_REG_SEL_CLK_PHASE_FLD_SHIFT                  (0x00000002U)
#define OSPI_CONFIG_REG_SEL_CLK_PHASE_FLD_MAX                    (0x00000001U)

#define OSPI_CONFIG_REG_PHY_MODE_ENABLE_FLD_MASK                 (0x00000008U)
#define OSPI_CONFIG_REG_PHY_MODE_ENABLE_FLD_SHIFT                (0x00000003U)
#define OSPI_CONFIG_REG_PHY_MODE_ENABLE_FLD_MAX                  (0x00000001U)

#define OSPI_CONFIG_REG_HOLD_PIN_FLD_MASK                        (0x00000010U)
#define OSPI_CONFIG_REG_HOLD_PIN_FLD_SHIFT                       (0x00000004U)
#define OSPI_CONFIG_REG_HOLD_PIN_FLD_MAX                         (0x00000001U)

#define OSPI_CONFIG_REG_RESET_PIN_FLD_MASK                       (0x00000020U)
#define OSPI_CONFIG_REG_RESET_PIN_FLD_SHIFT                      (0x00000005U)
#define OSPI_CONFIG_REG_RESET_PIN_FLD_MAX                        (0x00000001U)

#define OSPI_CONFIG_REG_RESET_CFG_FLD_MASK                       (0x00000040U)
#define OSPI_CONFIG_REG_RESET_CFG_FLD_SHIFT                      (0x00000006U)
#define OSPI_CONFIG_REG_RESET_CFG_FLD_MAX                        (0x00000001U)

#define OSPI_CONFIG_REG_ENB_DIR_ACC_CTLR_FLD_MASK                (0x00000080U)
#define OSPI_CONFIG_REG_ENB_DIR_ACC_CTLR_FLD_SHIFT               (0x00000007U)
#define OSPI_CONFIG_REG_ENB_DIR_ACC_CTLR_FLD_MAX                 (0x00000001U)

#define OSPI_CONFIG_REG_ENB_LEGACY_IP_MODE_FLD_MASK              (0x00000100U)
#define OSPI_CONFIG_REG_ENB_LEGACY_IP_MODE_FLD_SHIFT             (0x00000008U)
#define OSPI_CONFIG_REG_ENB_LEGACY_IP_MODE_FLD_MAX               (0x00000001U)

#define OSPI_CONFIG_REG_PERIPH_SEL_DEC_FLD_MASK                  (0x00000200U)
#define OSPI_CONFIG_REG_PERIPH_SEL_DEC_FLD_SHIFT                 (0x00000009U)
#define OSPI_CONFIG_REG_PERIPH_SEL_DEC_FLD_MAX                   (0x00000001U)

#define OSPI_CONFIG_REG_PERIPH_CS_LINES_FLD_MASK                 (0x00003C00U)
#define OSPI_CONFIG_REG_PERIPH_CS_LINES_FLD_SHIFT                (0x0000000AU)
#define OSPI_CONFIG_REG_PERIPH_CS_LINES_FLD_MAX                  (0x0000000FU)

#define OSPI_CONFIG_REG_WR_PROT_FLASH_FLD_MASK                   (0x00004000U)
#define OSPI_CONFIG_REG_WR_PROT_FLASH_FLD_SHIFT                  (0x0000000EU)
#define OSPI_CONFIG_REG_WR_PROT_FLASH_FLD_MAX                    (0x00000001U)

#define OSPI_CONFIG_REG_ENB_DMA_IF_FLD_MASK                      (0x00008000U)
#define OSPI_CONFIG_REG_ENB_DMA_IF_FLD_SHIFT                     (0x0000000FU)
#define OSPI_CONFIG_REG_ENB_DMA_IF_FLD_MAX                       (0x00000001U)

#define OSPI_CONFIG_REG_ENB_AHB_ADDR_REMAP_FLD_MASK              (0x00010000U)
#define OSPI_CONFIG_REG_ENB_AHB_ADDR_REMAP_FLD_SHIFT             (0x00000010U)
#define OSPI_CONFIG_REG_ENB_AHB_ADDR_REMAP_FLD_MAX               (0x00000001U)

#define OSPI_CONFIG_REG_ENTER_XIP_MODE_FLD_MASK                  (0x00020000U)
#define OSPI_CONFIG_REG_ENTER_XIP_MODE_FLD_SHIFT                 (0x00000011U)
#define OSPI_CONFIG_REG_ENTER_XIP_MODE_FLD_MAX                   (0x00000001U)

#define OSPI_CONFIG_REG_ENTER_XIP_MODE_IMM_FLD_MASK              (0x00040000U)
#define OSPI_CONFIG_REG_ENTER_XIP_MODE_IMM_FLD_SHIFT             (0x00000012U)
#define OSPI_CONFIG_REG_ENTER_XIP_MODE_IMM_FLD_MAX               (0x00000001U)

#define OSPI_CONFIG_REG_MSTR_BAUD_DIV_FLD_MASK                   (0x00780000U)
#define OSPI_CONFIG_REG_MSTR_BAUD_DIV_FLD_SHIFT                  (0x00000013U)
#define OSPI_CONFIG_REG_MSTR_BAUD_DIV_FLD_MAX                    (0x0000000FU)

#define OSPI_CONFIG_REG_ENABLE_AHB_DECODER_FLD_MASK              (0x00800000U)
#define OSPI_CONFIG_REG_ENABLE_AHB_DECODER_FLD_SHIFT             (0x00000017U)
#define OSPI_CONFIG_REG_ENABLE_AHB_DECODER_FLD_MAX               (0x00000001U)

#define OSPI_CONFIG_REG_ENABLE_DTR_PROTOCOL_FLD_MASK             (0x01000000U)
#define OSPI_CONFIG_REG_ENABLE_DTR_PROTOCOL_FLD_SHIFT            (0x00000018U)
#define OSPI_CONFIG_REG_ENABLE_DTR_PROTOCOL_FLD_MAX              (0x00000001U)

#define OSPI_CONFIG_REG_PIPELINE_PHY_FLD_MASK                    (0x02000000U)
#define OSPI_CONFIG_REG_PIPELINE_PHY_FLD_SHIFT                   (0x00000019U)
#define OSPI_CONFIG_REG_PIPELINE_PHY_FLD_MAX                     (0x00000001U)

#define OSPI_CONFIG_REG_CONFIG_RESV2_FLD_MASK                    (0x1C000000U)
#define OSPI_CONFIG_REG_CONFIG_RESV2_FLD_SHIFT                   (0x0000001AU)
#define OSPI_CONFIG_REG_CONFIG_RESV2_FLD_MAX                     (0x00000007U)

#define OSPI_CONFIG_REG_CRC_ENABLE_FLD_MASK                      (0x20000000U)
#define OSPI_CONFIG_REG_CRC_ENABLE_FLD_SHIFT                     (0x0000001DU)
#define OSPI_CONFIG_REG_CRC_ENABLE_FLD_MAX                       (0x00000001U)

#define OSPI_CONFIG_REG_DUAL_BYTE_OPCODE_EN_FLD_MASK             (0x40000000U)
#define OSPI_CONFIG_REG_DUAL_BYTE_OPCODE_EN_FLD_SHIFT            (0x0000001EU)
#define OSPI_CONFIG_REG_DUAL_BYTE_OPCODE_EN_FLD_MAX              (0x00000001U)

#define OSPI_CONFIG_REG_IDLE_FLD_MASK                            (0x80000000U)
#define OSPI_CONFIG_REG_IDLE_FLD_SHIFT                           (0x0000001FU)
#define OSPI_CONFIG_REG_IDLE_FLD_MAX                             (0x00000001U)

/* DEV_INSTR_RD_CONFIG_REG */

#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_OPCODE_NON_XIP_FLD_MASK  (0x000000FFU)
#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_OPCODE_NON_XIP_FLD_SHIFT (0x00000000U)
#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_OPCODE_NON_XIP_FLD_MAX   (0x000000FFU)

#define OSPI_DEV_INSTR_RD_CONFIG_REG_INSTR_TYPE_FLD_MASK         (0x00000300U)
#define OSPI_DEV_INSTR_RD_CONFIG_REG_INSTR_TYPE_FLD_SHIFT        (0x00000008U)
#define OSPI_DEV_INSTR_RD_CONFIG_REG_INSTR_TYPE_FLD_MAX          (0x00000003U)

#define OSPI_DEV_INSTR_RD_CONFIG_REG_DDR_EN_FLD_MASK             (0x00000400U)
#define OSPI_DEV_INSTR_RD_CONFIG_REG_DDR_EN_FLD_SHIFT            (0x0000000AU)
#define OSPI_DEV_INSTR_RD_CONFIG_REG_DDR_EN_FLD_MAX              (0x00000001U)

#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_INSTR_RESV1_FLD_MASK     (0x00000800U)
#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_INSTR_RESV1_FLD_SHIFT    (0x0000000BU)
#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_INSTR_RESV1_FLD_MAX      (0x00000001U)

#define OSPI_DEV_INSTR_RD_CONFIG_REG_ADDR_XFER_TYPE_STD_MODE_FLD_MASK (0x00003000U)
#define OSPI_DEV_INSTR_RD_CONFIG_REG_ADDR_XFER_TYPE_STD_MODE_FLD_SHIFT (0x0000000CU)
#define OSPI_DEV_INSTR_RD_CONFIG_REG_ADDR_XFER_TYPE_STD_MODE_FLD_MAX (0x00000003U)

#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_INSTR_RESV2_FLD_MASK     (0x0000C000U)
#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_INSTR_RESV2_FLD_SHIFT    (0x0000000EU)
#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_INSTR_RESV2_FLD_MAX      (0x00000003U)

#define OSPI_DEV_INSTR_RD_CONFIG_REG_DATA_XFER_TYPE_EXT_MODE_FLD_MASK (0x00030000U)
#define OSPI_DEV_INSTR_RD_CONFIG_REG_DATA_XFER_TYPE_EXT_MODE_FLD_SHIFT (0x00000010U)
#define OSPI_DEV_INSTR_RD_CONFIG_REG_DATA_XFER_TYPE_EXT_MODE_FLD_MAX (0x00000003U)

#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_INSTR_RESV3_FLD_MASK     (0x000C0000U)
#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_INSTR_RESV3_FLD_SHIFT    (0x00000012U)
#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_INSTR_RESV3_FLD_MAX      (0x00000003U)

#define OSPI_DEV_INSTR_RD_CONFIG_REG_MODE_BIT_ENABLE_FLD_MASK    (0x00100000U)
#define OSPI_DEV_INSTR_RD_CONFIG_REG_MODE_BIT_ENABLE_FLD_SHIFT   (0x00000014U)
#define OSPI_DEV_INSTR_RD_CONFIG_REG_MODE_BIT_ENABLE_FLD_MAX     (0x00000001U)

#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_INSTR_RESV4_FLD_MASK     (0x00E00000U)
#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_INSTR_RESV4_FLD_SHIFT    (0x00000015U)
#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_INSTR_RESV4_FLD_MAX      (0x00000007U)

#define OSPI_DEV_INSTR_RD_CONFIG_REG_DUMMY_RD_CLK_CYCLES_FLD_MASK (0x1F000000U)
#define OSPI_DEV_INSTR_RD_CONFIG_REG_DUMMY_RD_CLK_CYCLES_FLD_SHIFT (0x00000018U)
#define OSPI_DEV_INSTR_RD_CONFIG_REG_DUMMY_RD_CLK_CYCLES_FLD_MAX (0x0000001FU)

#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_INSTR_RESV5_FLD_MASK     (0xE0000000U)
#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_INSTR_RESV5_FLD_SHIFT    (0x0000001DU)
#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_INSTR_RESV5_FLD_MAX      (0x00000007U)

/* DEV_INSTR_WR_CONFIG_REG */

#define OSPI_DEV_INSTR_WR_CONFIG_REG_WR_OPCODE_FLD_MASK          (0x000000FFU)
#define OSPI_DEV_INSTR_WR_CONFIG_REG_WR_OPCODE_FLD_SHIFT         (0x00000000U)
#define OSPI_DEV_INSTR_WR_CONFIG_REG_WR_OPCODE_FLD_MAX           (0x000000FFU)

#define OSPI_DEV_INSTR_WR_CONFIG_REG_WEL_DIS_FLD_MASK            (0x00000100U)
#define OSPI_DEV_INSTR_WR_CONFIG_REG_WEL_DIS_FLD_SHIFT           (0x00000008U)
#define OSPI_DEV_INSTR_WR_CONFIG_REG_WEL_DIS_FLD_MAX             (0x00000001U)

#define OSPI_DEV_INSTR_WR_CONFIG_REG_WR_INSTR_RESV1_FLD_MASK     (0x00000E00U)
#define OSPI_DEV_INSTR_WR_CONFIG_REG_WR_INSTR_RESV1_FLD_SHIFT    (0x00000009U)
#define OSPI_DEV_INSTR_WR_CONFIG_REG_WR_INSTR_RESV1_FLD_MAX      (0x00000007U)

#define OSPI_DEV_INSTR_WR_CONFIG_REG_ADDR_XFER_TYPE_STD_MODE_FLD_MASK (0x00003000U)
#define OSPI_DEV_INSTR_WR_CONFIG_REG_ADDR_XFER_TYPE_STD_MODE_FLD_SHIFT (0x0000000CU)
#define OSPI_DEV_INSTR_WR_CONFIG_REG_ADDR_XFER_TYPE_STD_MODE_FLD_MAX (0x00000003U)

#define OSPI_DEV_INSTR_WR_CONFIG_REG_WR_INSTR_RESV2_FLD_MASK     (0x0000C000U)
#define OSPI_DEV_INSTR_WR_CONFIG_REG_WR_INSTR_RESV2_FLD_SHIFT    (0x0000000EU)
#define OSPI_DEV_INSTR_WR_CONFIG_REG_WR_INSTR_RESV2_FLD_MAX      (0x00000003U)

#define OSPI_DEV_INSTR_WR_CONFIG_REG_DATA_XFER_TYPE_EXT_MODE_FLD_MASK (0x00030000U)
#define OSPI_DEV_INSTR_WR_CONFIG_REG_DATA_XFER_TYPE_EXT_MODE_FLD_SHIFT (0x00000010U)
#define OSPI_DEV_INSTR_WR_CONFIG_REG_DATA_XFER_TYPE_EXT_MODE_FLD_MAX (0x00000003U)

#define OSPI_DEV_INSTR_WR_CONFIG_REG_WR_INSTR_RESV3_FLD_MASK     (0x00FC0000U)
#define OSPI_DEV_INSTR_WR_CONFIG_REG_WR_INSTR_RESV3_FLD_SHIFT    (0x00000012U)
#define OSPI_DEV_INSTR_WR_CONFIG_REG_WR_INSTR_RESV3_FLD_MAX      (0x0000003FU)

#define OSPI_DEV_INSTR_WR_CONFIG_REG_DUMMY_WR_CLK_CYCLES_FLD_MASK (0x1F000000U)
#define OSPI_DEV_INSTR_WR_CONFIG_REG_DUMMY_WR_CLK_CYCLES_FLD_SHIFT (0x00000018U)
#define OSPI_DEV_INSTR_WR_CONFIG_REG_DUMMY_WR_CLK_CYCLES_FLD_MAX (0x0000001FU)

#define OSPI_DEV_INSTR_WR_CONFIG_REG_WR_INSTR_RESV4_FLD_MASK     (0xE0000000U)
#define OSPI_DEV_INSTR_WR_CONFIG_REG_WR_INSTR_RESV4_FLD_SHIFT    (0x0000001DU)
#define OSPI_DEV_INSTR_WR_CONFIG_REG_WR_INSTR_RESV4_FLD_MAX      (0x00000007U)

/* DEV_DELAY_REG */

#define OSPI_DEV_DELAY_REG_D_INIT_FLD_MASK                       (0x000000FFU)
#define OSPI_DEV_DELAY_REG_D_INIT_FLD_SHIFT                      (0x00000000U)
#define OSPI_DEV_DELAY_REG_D_INIT_FLD_MAX                        (0x000000FFU)

#define OSPI_DEV_DELAY_REG_D_AFTER_FLD_MASK                      (0x0000FF00U)
#define OSPI_DEV_DELAY_REG_D_AFTER_FLD_SHIFT                     (0x00000008U)
#define OSPI_DEV_DELAY_REG_D_AFTER_FLD_MAX                       (0x000000FFU)

#define OSPI_DEV_DELAY_REG_D_BTWN_FLD_MASK                       (0x00FF0000U)
#define OSPI_DEV_DELAY_REG_D_BTWN_FLD_SHIFT                      (0x00000010U)
#define OSPI_DEV_DELAY_REG_D_BTWN_FLD_MAX                        (0x000000FFU)

#define OSPI_DEV_DELAY_REG_D_NSS_FLD_MASK                        (0xFF000000U)
#define OSPI_DEV_DELAY_REG_D_NSS_FLD_SHIFT                       (0x00000018U)
#define OSPI_DEV_DELAY_REG_D_NSS_FLD_MAX                         (0x000000FFU)

/* RD_DATA_CAPTURE_REG */

#define OSPI_RD_DATA_CAPTURE_REG_BYPASS_FLD_MASK                 (0x00000001U)
#define OSPI_RD_DATA_CAPTURE_REG_BYPASS_FLD_SHIFT                (0x00000000U)
#define OSPI_RD_DATA_CAPTURE_REG_BYPASS_FLD_MAX                  (0x00000001U)

#define OSPI_RD_DATA_CAPTURE_REG_DELAY_FLD_MASK                  (0x0000001EU)
#define OSPI_RD_DATA_CAPTURE_REG_DELAY_FLD_SHIFT                 (0x00000001U)
#define OSPI_RD_DATA_CAPTURE_REG_DELAY_FLD_MAX                   (0x0000000FU)

#define OSPI_RD_DATA_CAPTURE_REG_SAMPLE_EDGE_SEL_FLD_MASK        (0x00000020U)
#define OSPI_RD_DATA_CAPTURE_REG_SAMPLE_EDGE_SEL_FLD_SHIFT       (0x00000005U)
#define OSPI_RD_DATA_CAPTURE_REG_SAMPLE_EDGE_SEL_FLD_MAX         (0x00000001U)

#define OSPI_RD_DATA_CAPTURE_REG_RD_DATA_RESV1_FLD_MASK          (0x000000C0U)
#define OSPI_RD_DATA_CAPTURE_REG_RD_DATA_RESV1_FLD_SHIFT         (0x00000006U)
#define OSPI_RD_DATA_CAPTURE_REG_RD_DATA_RESV1_FLD_MAX           (0x00000003U)

#define OSPI_RD_DATA_CAPTURE_REG_DQS_ENABLE_FLD_MASK             (0x00000100U)
#define OSPI_RD_DATA_CAPTURE_REG_DQS_ENABLE_FLD_SHIFT            (0x00000008U)
#define OSPI_RD_DATA_CAPTURE_REG_DQS_ENABLE_FLD_MAX              (0x00000001U)

#define OSPI_RD_DATA_CAPTURE_REG_RD_DATA_RESV2_FLD_MASK          (0x0000FE00U)
#define OSPI_RD_DATA_CAPTURE_REG_RD_DATA_RESV2_FLD_SHIFT         (0x00000009U)
#define OSPI_RD_DATA_CAPTURE_REG_RD_DATA_RESV2_FLD_MAX           (0x0000007FU)

#define OSPI_RD_DATA_CAPTURE_REG_DDR_READ_DELAY_FLD_MASK         (0x000F0000U)
#define OSPI_RD_DATA_CAPTURE_REG_DDR_READ_DELAY_FLD_SHIFT        (0x00000010U)
#define OSPI_RD_DATA_CAPTURE_REG_DDR_READ_DELAY_FLD_MAX          (0x0000000FU)

#define OSPI_RD_DATA_CAPTURE_REG_RD_DATA_RESV3_FLD_MASK          (0xFFF00000U)
#define OSPI_RD_DATA_CAPTURE_REG_RD_DATA_RESV3_FLD_SHIFT         (0x00000014U)
#define OSPI_RD_DATA_CAPTURE_REG_RD_DATA_RESV3_FLD_MAX           (0x00000FFFU)

/* DEV_SIZE_CONFIG_REG */

#define OSPI_DEV_SIZE_CONFIG_REG_NUM_ADDR_BYTES_FLD_MASK         (0x0000000FU)
#define OSPI_DEV_SIZE_CONFIG_REG_NUM_ADDR_BYTES_FLD_SHIFT        (0x00000000U)
#define OSPI_DEV_SIZE_CONFIG_REG_NUM_ADDR_BYTES_FLD_MAX          (0x0000000FU)

#define OSPI_DEV_SIZE_CONFIG_REG_BYTES_PER_DEVICE_PAGE_FLD_MASK  (0x0000FFF0U)
#define OSPI_DEV_SIZE_CONFIG_REG_BYTES_PER_DEVICE_PAGE_FLD_SHIFT (0x00000004U)
#define OSPI_DEV_SIZE_CONFIG_REG_BYTES_PER_DEVICE_PAGE_FLD_MAX   (0x00000FFFU)

#define OSPI_DEV_SIZE_CONFIG_REG_BYTES_PER_SUBSECTOR_FLD_MASK    (0x001F0000U)
#define OSPI_DEV_SIZE_CONFIG_REG_BYTES_PER_SUBSECTOR_FLD_SHIFT   (0x00000010U)
#define OSPI_DEV_SIZE_CONFIG_REG_BYTES_PER_SUBSECTOR_FLD_MAX     (0x0000001FU)

#define OSPI_DEV_SIZE_CONFIG_REG_MEM_SIZE_ON_CS0_FLD_MASK        (0x00600000U)
#define OSPI_DEV_SIZE_CONFIG_REG_MEM_SIZE_ON_CS0_FLD_SHIFT       (0x00000015U)
#define OSPI_DEV_SIZE_CONFIG_REG_MEM_SIZE_ON_CS0_FLD_MAX         (0x00000003U)

#define OSPI_DEV_SIZE_CONFIG_REG_MEM_SIZE_ON_CS1_FLD_MASK        (0x01800000U)
#define OSPI_DEV_SIZE_CONFIG_REG_MEM_SIZE_ON_CS1_FLD_SHIFT       (0x00000017U)
#define OSPI_DEV_SIZE_CONFIG_REG_MEM_SIZE_ON_CS1_FLD_MAX         (0x00000003U)

#define OSPI_DEV_SIZE_CONFIG_REG_MEM_SIZE_ON_CS2_FLD_MASK        (0x06000000U)
#define OSPI_DEV_SIZE_CONFIG_REG_MEM_SIZE_ON_CS2_FLD_SHIFT       (0x00000019U)
#define OSPI_DEV_SIZE_CONFIG_REG_MEM_SIZE_ON_CS2_FLD_MAX         (0x00000003U)

#define OSPI_DEV_SIZE_CONFIG_REG_MEM_SIZE_ON_CS3_FLD_MASK        (0x18000000U)
#define OSPI_DEV_SIZE_CONFIG_REG_MEM_SIZE_ON_CS3_FLD_SHIFT       (0x0000001BU)
#define OSPI_DEV_SIZE_CONFIG_REG_MEM_SIZE_ON_CS3_FLD_MAX         (0x00000003U)

#define OSPI_DEV_SIZE_CONFIG_REG_DEV_SIZE_RESV_FLD_MASK          (0xE0000000U)
#define OSPI_DEV_SIZE_CONFIG_REG_DEV_SIZE_RESV_FLD_SHIFT         (0x0000001DU)
#define OSPI_DEV_SIZE_CONFIG_REG_DEV_SIZE_RESV_FLD_MAX           (0x00000007U)

/* SRAM_PARTITION_CFG_REG */

#define OSPI_SRAM_PARTITION_CFG_REG_ADDR_FLD_MASK                (0x000000FFU)
#define OSPI_SRAM_PARTITION_CFG_REG_ADDR_FLD_SHIFT               (0x00000000U)
#define OSPI_SRAM_PARTITION_CFG_REG_ADDR_FLD_MAX                 (0x000000FFU)

#define OSPI_SRAM_PARTITION_CFG_REG_SRAM_PARTITION_RESV_FLD_MASK (0xFFFFFF00U)
#define OSPI_SRAM_PARTITION_CFG_REG_SRAM_PARTITION_RESV_FLD_SHIFT (0x00000008U)
#define OSPI_SRAM_PARTITION_CFG_REG_SRAM_PARTITION_RESV_FLD_MAX  (0x00FFFFFFU)

/* IND_AHB_ADDR_TRIGGER_REG */

#define OSPI_IND_AHB_ADDR_TRIGGER_REG_ADDR_FLD_MASK              (0xFFFFFFFFU)
#define OSPI_IND_AHB_ADDR_TRIGGER_REG_ADDR_FLD_SHIFT             (0x00000000U)
#define OSPI_IND_AHB_ADDR_TRIGGER_REG_ADDR_FLD_MAX               (0xFFFFFFFFU)

/* DMA_PERIPH_CONFIG_REG */

#define OSPI_DMA_PERIPH_CONFIG_REG_NUM_SINGLE_REQ_BYTES_FLD_MASK (0x0000000FU)
#define OSPI_DMA_PERIPH_CONFIG_REG_NUM_SINGLE_REQ_BYTES_FLD_SHIFT (0x00000000U)
#define OSPI_DMA_PERIPH_CONFIG_REG_NUM_SINGLE_REQ_BYTES_FLD_MAX  (0x0000000FU)

#define OSPI_DMA_PERIPH_CONFIG_REG_DMA_PERIPH_RESV1_FLD_MASK     (0x000000F0U)
#define OSPI_DMA_PERIPH_CONFIG_REG_DMA_PERIPH_RESV1_FLD_SHIFT    (0x00000004U)
#define OSPI_DMA_PERIPH_CONFIG_REG_DMA_PERIPH_RESV1_FLD_MAX      (0x0000000FU)

#define OSPI_DMA_PERIPH_CONFIG_REG_NUM_BURST_REQ_BYTES_FLD_MASK  (0x00000F00U)
#define OSPI_DMA_PERIPH_CONFIG_REG_NUM_BURST_REQ_BYTES_FLD_SHIFT (0x00000008U)
#define OSPI_DMA_PERIPH_CONFIG_REG_NUM_BURST_REQ_BYTES_FLD_MAX   (0x0000000FU)

#define OSPI_DMA_PERIPH_CONFIG_REG_DMA_PERIPH_RESV2_FLD_MASK     (0xFFFFF000U)
#define OSPI_DMA_PERIPH_CONFIG_REG_DMA_PERIPH_RESV2_FLD_SHIFT    (0x0000000CU)
#define OSPI_DMA_PERIPH_CONFIG_REG_DMA_PERIPH_RESV2_FLD_MAX      (0x000FFFFFU)

/* REMAP_ADDR_REG */

#define OSPI_REMAP_ADDR_REG_VALUE_FLD_MASK                       (0xFFFFFFFFU)
#define OSPI_REMAP_ADDR_REG_VALUE_FLD_SHIFT                      (0x00000000U)
#define OSPI_REMAP_ADDR_REG_VALUE_FLD_MAX                        (0xFFFFFFFFU)

/* MODE_BIT_CONFIG_REG */

#define OSPI_MODE_BIT_CONFIG_REG_MODE_FLD_MASK                   (0x000000FFU)
#define OSPI_MODE_BIT_CONFIG_REG_MODE_FLD_SHIFT                  (0x00000000U)
#define OSPI_MODE_BIT_CONFIG_REG_MODE_FLD_MAX                    (0x000000FFU)

#define OSPI_MODE_BIT_CONFIG_REG_CHUNK_SIZE_FLD_MASK             (0x00000700U)
#define OSPI_MODE_BIT_CONFIG_REG_CHUNK_SIZE_FLD_SHIFT            (0x00000008U)
#define OSPI_MODE_BIT_CONFIG_REG_CHUNK_SIZE_FLD_MAX              (0x00000007U)

#define OSPI_MODE_BIT_CONFIG_REG_MODE_BIT_RESV1_FLD_MASK         (0x00007800U)
#define OSPI_MODE_BIT_CONFIG_REG_MODE_BIT_RESV1_FLD_SHIFT        (0x0000000BU)
#define OSPI_MODE_BIT_CONFIG_REG_MODE_BIT_RESV1_FLD_MAX          (0x0000000FU)

#define OSPI_MODE_BIT_CONFIG_REG_CRC_OUT_ENABLE_FLD_MASK         (0x00008000U)
#define OSPI_MODE_BIT_CONFIG_REG_CRC_OUT_ENABLE_FLD_SHIFT        (0x0000000FU)
#define OSPI_MODE_BIT_CONFIG_REG_CRC_OUT_ENABLE_FLD_MAX          (0x00000001U)

#define OSPI_MODE_BIT_CONFIG_REG_RX_CRC_DATA_UP_FLD_MASK         (0x00FF0000U)
#define OSPI_MODE_BIT_CONFIG_REG_RX_CRC_DATA_UP_FLD_SHIFT        (0x00000010U)
#define OSPI_MODE_BIT_CONFIG_REG_RX_CRC_DATA_UP_FLD_MAX          (0x000000FFU)

#define OSPI_MODE_BIT_CONFIG_REG_RX_CRC_DATA_LOW_FLD_MASK        (0xFF000000U)
#define OSPI_MODE_BIT_CONFIG_REG_RX_CRC_DATA_LOW_FLD_SHIFT       (0x00000018U)
#define OSPI_MODE_BIT_CONFIG_REG_RX_CRC_DATA_LOW_FLD_MAX         (0x000000FFU)

/* SRAM_FILL_REG */

#define OSPI_SRAM_FILL_REG_SRAM_FILL_INDAC_READ_FLD_MASK         (0x0000FFFFU)
#define OSPI_SRAM_FILL_REG_SRAM_FILL_INDAC_READ_FLD_SHIFT        (0x00000000U)
#define OSPI_SRAM_FILL_REG_SRAM_FILL_INDAC_READ_FLD_MAX          (0x0000FFFFU)

#define OSPI_SRAM_FILL_REG_SRAM_FILL_INDAC_WRITE_FLD_MASK        (0xFFFF0000U)
#define OSPI_SRAM_FILL_REG_SRAM_FILL_INDAC_WRITE_FLD_SHIFT       (0x00000010U)
#define OSPI_SRAM_FILL_REG_SRAM_FILL_INDAC_WRITE_FLD_MAX         (0x0000FFFFU)

/* TX_THRESH_REG */

#define OSPI_TX_THRESH_REG_LEVEL_FLD_MASK                        (0x0000001FU)
#define OSPI_TX_THRESH_REG_LEVEL_FLD_SHIFT                       (0x00000000U)
#define OSPI_TX_THRESH_REG_LEVEL_FLD_MAX                         (0x0000001FU)

#define OSPI_TX_THRESH_REG_TX_THRESH_RESV_FLD_MASK               (0xFFFFFFE0U)
#define OSPI_TX_THRESH_REG_TX_THRESH_RESV_FLD_SHIFT              (0x00000005U)
#define OSPI_TX_THRESH_REG_TX_THRESH_RESV_FLD_MAX                (0x07FFFFFFU)

/* RX_THRESH_REG */

#define OSPI_RX_THRESH_REG_LEVEL_FLD_MASK                        (0x0000001FU)
#define OSPI_RX_THRESH_REG_LEVEL_FLD_SHIFT                       (0x00000000U)
#define OSPI_RX_THRESH_REG_LEVEL_FLD_MAX                         (0x0000001FU)

#define OSPI_RX_THRESH_REG_RX_THRESH_RESV_FLD_MASK               (0xFFFFFFE0U)
#define OSPI_RX_THRESH_REG_RX_THRESH_RESV_FLD_SHIFT              (0x00000005U)
#define OSPI_RX_THRESH_REG_RX_THRESH_RESV_FLD_MAX                (0x07FFFFFFU)

/* WRITE_COMPLETION_CTRL_REG */

#define OSPI_WRITE_COMPLETION_CTRL_REG_OPCODE_FLD_MASK           (0x000000FFU)
#define OSPI_WRITE_COMPLETION_CTRL_REG_OPCODE_FLD_SHIFT          (0x00000000U)
#define OSPI_WRITE_COMPLETION_CTRL_REG_OPCODE_FLD_MAX            (0x000000FFU)

#define OSPI_WRITE_COMPLETION_CTRL_REG_POLLING_BIT_INDEX_FLD_MASK (0x00000700U)
#define OSPI_WRITE_COMPLETION_CTRL_REG_POLLING_BIT_INDEX_FLD_SHIFT (0x00000008U)
#define OSPI_WRITE_COMPLETION_CTRL_REG_POLLING_BIT_INDEX_FLD_MAX (0x00000007U)

#define OSPI_WRITE_COMPLETION_CTRL_REG_WR_COMP_CTRL_RESV1_FLD_MASK (0x00001800U)
#define OSPI_WRITE_COMPLETION_CTRL_REG_WR_COMP_CTRL_RESV1_FLD_SHIFT (0x0000000BU)
#define OSPI_WRITE_COMPLETION_CTRL_REG_WR_COMP_CTRL_RESV1_FLD_MAX (0x00000003U)

#define OSPI_WRITE_COMPLETION_CTRL_REG_POLLING_POLARITY_FLD_MASK (0x00002000U)
#define OSPI_WRITE_COMPLETION_CTRL_REG_POLLING_POLARITY_FLD_SHIFT (0x0000000DU)
#define OSPI_WRITE_COMPLETION_CTRL_REG_POLLING_POLARITY_FLD_MAX  (0x00000001U)

#define OSPI_WRITE_COMPLETION_CTRL_REG_DISABLE_POLLING_FLD_MASK  (0x00004000U)
#define OSPI_WRITE_COMPLETION_CTRL_REG_DISABLE_POLLING_FLD_SHIFT (0x0000000EU)
#define OSPI_WRITE_COMPLETION_CTRL_REG_DISABLE_POLLING_FLD_MAX   (0x00000001U)

#define OSPI_WRITE_COMPLETION_CTRL_REG_ENABLE_POLLING_EXP_FLD_MASK (0x00008000U)
#define OSPI_WRITE_COMPLETION_CTRL_REG_ENABLE_POLLING_EXP_FLD_SHIFT (0x0000000FU)
#define OSPI_WRITE_COMPLETION_CTRL_REG_ENABLE_POLLING_EXP_FLD_MAX (0x00000001U)

#define OSPI_WRITE_COMPLETION_CTRL_REG_POLL_COUNT_FLD_MASK       (0x00FF0000U)
#define OSPI_WRITE_COMPLETION_CTRL_REG_POLL_COUNT_FLD_SHIFT      (0x00000010U)
#define OSPI_WRITE_COMPLETION_CTRL_REG_POLL_COUNT_FLD_MAX        (0x000000FFU)

#define OSPI_WRITE_COMPLETION_CTRL_REG_POLL_REP_DELAY_FLD_MASK   (0xFF000000U)
#define OSPI_WRITE_COMPLETION_CTRL_REG_POLL_REP_DELAY_FLD_SHIFT  (0x00000018U)
#define OSPI_WRITE_COMPLETION_CTRL_REG_POLL_REP_DELAY_FLD_MAX    (0x000000FFU)

/* NO_OF_POLLS_BEF_EXP_REG */

#define OSPI_NO_OF_POLLS_BEF_EXP_REG_NO_OF_POLLS_BEF_EXP_FLD_MASK (0xFFFFFFFFU)
#define OSPI_NO_OF_POLLS_BEF_EXP_REG_NO_OF_POLLS_BEF_EXP_FLD_SHIFT (0x00000000U)
#define OSPI_NO_OF_POLLS_BEF_EXP_REG_NO_OF_POLLS_BEF_EXP_FLD_MAX (0xFFFFFFFFU)

/* IRQ_STATUS_REG */

#define OSPI_IRQ_STATUS_REG_MODE_M_FAIL_FLD_MASK                 (0x00000001U)
#define OSPI_IRQ_STATUS_REG_MODE_M_FAIL_FLD_SHIFT                (0x00000000U)
#define OSPI_IRQ_STATUS_REG_MODE_M_FAIL_FLD_MAX                  (0x00000001U)

#define OSPI_IRQ_STATUS_REG_UNDERFLOW_DET_FLD_MASK               (0x00000002U)
#define OSPI_IRQ_STATUS_REG_UNDERFLOW_DET_FLD_SHIFT              (0x00000001U)
#define OSPI_IRQ_STATUS_REG_UNDERFLOW_DET_FLD_MAX                (0x00000001U)

#define OSPI_IRQ_STATUS_REG_INDIRECT_OP_DONE_FLD_MASK            (0x00000004U)
#define OSPI_IRQ_STATUS_REG_INDIRECT_OP_DONE_FLD_SHIFT           (0x00000002U)
#define OSPI_IRQ_STATUS_REG_INDIRECT_OP_DONE_FLD_MAX             (0x00000001U)

#define OSPI_IRQ_STATUS_REG_INDIRECT_READ_REJECT_FLD_MASK        (0x00000008U)
#define OSPI_IRQ_STATUS_REG_INDIRECT_READ_REJECT_FLD_SHIFT       (0x00000003U)
#define OSPI_IRQ_STATUS_REG_INDIRECT_READ_REJECT_FLD_MAX         (0x00000001U)

#define OSPI_IRQ_STATUS_REG_PROT_WR_ATTEMPT_FLD_MASK             (0x00000010U)
#define OSPI_IRQ_STATUS_REG_PROT_WR_ATTEMPT_FLD_SHIFT            (0x00000004U)
#define OSPI_IRQ_STATUS_REG_PROT_WR_ATTEMPT_FLD_MAX              (0x00000001U)

#define OSPI_IRQ_STATUS_REG_ILLEGAL_ACCESS_DET_FLD_MASK          (0x00000020U)
#define OSPI_IRQ_STATUS_REG_ILLEGAL_ACCESS_DET_FLD_SHIFT         (0x00000005U)
#define OSPI_IRQ_STATUS_REG_ILLEGAL_ACCESS_DET_FLD_MAX           (0x00000001U)

#define OSPI_IRQ_STATUS_REG_INDIRECT_XFER_LEVEL_BREACH_FLD_MASK  (0x00000040U)
#define OSPI_IRQ_STATUS_REG_INDIRECT_XFER_LEVEL_BREACH_FLD_SHIFT (0x00000006U)
#define OSPI_IRQ_STATUS_REG_INDIRECT_XFER_LEVEL_BREACH_FLD_MAX   (0x00000001U)

#define OSPI_IRQ_STATUS_REG_RECV_OVERFLOW_FLD_MASK               (0x00000080U)
#define OSPI_IRQ_STATUS_REG_RECV_OVERFLOW_FLD_SHIFT              (0x00000007U)
#define OSPI_IRQ_STATUS_REG_RECV_OVERFLOW_FLD_MAX                (0x00000001U)

#define OSPI_IRQ_STATUS_REG_TX_FIFO_NOT_FULL_FLD_MASK            (0x00000100U)
#define OSPI_IRQ_STATUS_REG_TX_FIFO_NOT_FULL_FLD_SHIFT           (0x00000008U)
#define OSPI_IRQ_STATUS_REG_TX_FIFO_NOT_FULL_FLD_MAX             (0x00000001U)

#define OSPI_IRQ_STATUS_REG_TX_FIFO_FULL_FLD_MASK                (0x00000200U)
#define OSPI_IRQ_STATUS_REG_TX_FIFO_FULL_FLD_SHIFT               (0x00000009U)
#define OSPI_IRQ_STATUS_REG_TX_FIFO_FULL_FLD_MAX                 (0x00000001U)

#define OSPI_IRQ_STATUS_REG_RX_FIFO_NOT_EMPTY_FLD_MASK           (0x00000400U)
#define OSPI_IRQ_STATUS_REG_RX_FIFO_NOT_EMPTY_FLD_SHIFT          (0x0000000AU)
#define OSPI_IRQ_STATUS_REG_RX_FIFO_NOT_EMPTY_FLD_MAX            (0x00000001U)

#define OSPI_IRQ_STATUS_REG_RX_FIFO_FULL_FLD_MASK                (0x00000800U)
#define OSPI_IRQ_STATUS_REG_RX_FIFO_FULL_FLD_SHIFT               (0x0000000BU)
#define OSPI_IRQ_STATUS_REG_RX_FIFO_FULL_FLD_MAX                 (0x00000001U)

#define OSPI_IRQ_STATUS_REG_INDRD_SRAM_FULL_FLD_MASK             (0x00001000U)
#define OSPI_IRQ_STATUS_REG_INDRD_SRAM_FULL_FLD_SHIFT            (0x0000000CU)
#define OSPI_IRQ_STATUS_REG_INDRD_SRAM_FULL_FLD_MAX              (0x00000001U)

#define OSPI_IRQ_STATUS_REG_POLL_EXP_INT_FLD_MASK                (0x00002000U)
#define OSPI_IRQ_STATUS_REG_POLL_EXP_INT_FLD_SHIFT               (0x0000000DU)
#define OSPI_IRQ_STATUS_REG_POLL_EXP_INT_FLD_MAX                 (0x00000001U)

#define OSPI_IRQ_STATUS_REG_STIG_REQ_INT_FLD_MASK                (0x00004000U)
#define OSPI_IRQ_STATUS_REG_STIG_REQ_INT_FLD_SHIFT               (0x0000000EU)
#define OSPI_IRQ_STATUS_REG_STIG_REQ_INT_FLD_MAX                 (0x00000001U)

#define OSPI_IRQ_STATUS_REG_IRQ_STAT_RESV1_FLD_MASK              (0x00008000U)
#define OSPI_IRQ_STATUS_REG_IRQ_STAT_RESV1_FLD_SHIFT             (0x0000000FU)
#define OSPI_IRQ_STATUS_REG_IRQ_STAT_RESV1_FLD_MAX               (0x00000001U)

#define OSPI_IRQ_STATUS_REG_RX_CRC_DATA_ERR_FLD_MASK             (0x00010000U)
#define OSPI_IRQ_STATUS_REG_RX_CRC_DATA_ERR_FLD_SHIFT            (0x00000010U)
#define OSPI_IRQ_STATUS_REG_RX_CRC_DATA_ERR_FLD_MAX              (0x00000001U)

#define OSPI_IRQ_STATUS_REG_RX_CRC_DATA_VAL_FLD_MASK             (0x00020000U)
#define OSPI_IRQ_STATUS_REG_RX_CRC_DATA_VAL_FLD_SHIFT            (0x00000011U)
#define OSPI_IRQ_STATUS_REG_RX_CRC_DATA_VAL_FLD_MAX              (0x00000001U)

#define OSPI_IRQ_STATUS_REG_TX_CRC_CHUNK_BRK_FLD_MASK            (0x00040000U)
#define OSPI_IRQ_STATUS_REG_TX_CRC_CHUNK_BRK_FLD_SHIFT           (0x00000012U)
#define OSPI_IRQ_STATUS_REG_TX_CRC_CHUNK_BRK_FLD_MAX             (0x00000001U)

#define OSPI_IRQ_STATUS_REG_ECC_FAIL_FLD_MASK                    (0x00080000U)
#define OSPI_IRQ_STATUS_REG_ECC_FAIL_FLD_SHIFT                   (0x00000013U)
#define OSPI_IRQ_STATUS_REG_ECC_FAIL_FLD_MAX                     (0x00000001U)

#define OSPI_IRQ_STATUS_REG_IRQ_STAT_RESV_FLD_MASK               (0xFFF00000U)
#define OSPI_IRQ_STATUS_REG_IRQ_STAT_RESV_FLD_SHIFT              (0x00000014U)
#define OSPI_IRQ_STATUS_REG_IRQ_STAT_RESV_FLD_MAX                (0x00000FFFU)

/* IRQ_MASK_REG */

#define OSPI_IRQ_MASK_REG_MODE_M_FAIL_MASK_FLD_MASK              (0x00000001U)
#define OSPI_IRQ_MASK_REG_MODE_M_FAIL_MASK_FLD_SHIFT             (0x00000000U)
#define OSPI_IRQ_MASK_REG_MODE_M_FAIL_MASK_FLD_MAX               (0x00000001U)

#define OSPI_IRQ_MASK_REG_UNDERFLOW_DET_MASK_FLD_MASK            (0x00000002U)
#define OSPI_IRQ_MASK_REG_UNDERFLOW_DET_MASK_FLD_SHIFT           (0x00000001U)
#define OSPI_IRQ_MASK_REG_UNDERFLOW_DET_MASK_FLD_MAX             (0x00000001U)

#define OSPI_IRQ_MASK_REG_INDIRECT_OP_DONE_MASK_FLD_MASK         (0x00000004U)
#define OSPI_IRQ_MASK_REG_INDIRECT_OP_DONE_MASK_FLD_SHIFT        (0x00000002U)
#define OSPI_IRQ_MASK_REG_INDIRECT_OP_DONE_MASK_FLD_MAX          (0x00000001U)

#define OSPI_IRQ_MASK_REG_INDIRECT_READ_REJECT_MASK_FLD_MASK     (0x00000008U)
#define OSPI_IRQ_MASK_REG_INDIRECT_READ_REJECT_MASK_FLD_SHIFT    (0x00000003U)
#define OSPI_IRQ_MASK_REG_INDIRECT_READ_REJECT_MASK_FLD_MAX      (0x00000001U)

#define OSPI_IRQ_MASK_REG_PROT_WR_ATTEMPT_MASK_FLD_MASK          (0x00000010U)
#define OSPI_IRQ_MASK_REG_PROT_WR_ATTEMPT_MASK_FLD_SHIFT         (0x00000004U)
#define OSPI_IRQ_MASK_REG_PROT_WR_ATTEMPT_MASK_FLD_MAX           (0x00000001U)

#define OSPI_IRQ_MASK_REG_ILLEGAL_ACCESS_DET_MASK_FLD_MASK       (0x00000020U)
#define OSPI_IRQ_MASK_REG_ILLEGAL_ACCESS_DET_MASK_FLD_SHIFT      (0x00000005U)
#define OSPI_IRQ_MASK_REG_ILLEGAL_ACCESS_DET_MASK_FLD_MAX        (0x00000001U)

#define OSPI_IRQ_MASK_REG_INDIRECT_XFER_LEVEL_BREACH_MASK_FLD_MASK (0x00000040U)
#define OSPI_IRQ_MASK_REG_INDIRECT_XFER_LEVEL_BREACH_MASK_FLD_SHIFT (0x00000006U)
#define OSPI_IRQ_MASK_REG_INDIRECT_XFER_LEVEL_BREACH_MASK_FLD_MAX (0x00000001U)

#define OSPI_IRQ_MASK_REG_RECV_OVERFLOW_MASK_FLD_MASK            (0x00000080U)
#define OSPI_IRQ_MASK_REG_RECV_OVERFLOW_MASK_FLD_SHIFT           (0x00000007U)
#define OSPI_IRQ_MASK_REG_RECV_OVERFLOW_MASK_FLD_MAX             (0x00000001U)

#define OSPI_IRQ_MASK_REG_TX_FIFO_NOT_FULL_MASK_FLD_MASK         (0x00000100U)
#define OSPI_IRQ_MASK_REG_TX_FIFO_NOT_FULL_MASK_FLD_SHIFT        (0x00000008U)
#define OSPI_IRQ_MASK_REG_TX_FIFO_NOT_FULL_MASK_FLD_MAX          (0x00000001U)

#define OSPI_IRQ_MASK_REG_TX_FIFO_FULL_MASK_FLD_MASK             (0x00000200U)
#define OSPI_IRQ_MASK_REG_TX_FIFO_FULL_MASK_FLD_SHIFT            (0x00000009U)
#define OSPI_IRQ_MASK_REG_TX_FIFO_FULL_MASK_FLD_MAX              (0x00000001U)

#define OSPI_IRQ_MASK_REG_RX_FIFO_NOT_EMPTY_MASK_FLD_MASK        (0x00000400U)
#define OSPI_IRQ_MASK_REG_RX_FIFO_NOT_EMPTY_MASK_FLD_SHIFT       (0x0000000AU)
#define OSPI_IRQ_MASK_REG_RX_FIFO_NOT_EMPTY_MASK_FLD_MAX         (0x00000001U)

#define OSPI_IRQ_MASK_REG_RX_FIFO_FULL_MASK_FLD_MASK             (0x00000800U)
#define OSPI_IRQ_MASK_REG_RX_FIFO_FULL_MASK_FLD_SHIFT            (0x0000000BU)
#define OSPI_IRQ_MASK_REG_RX_FIFO_FULL_MASK_FLD_MAX              (0x00000001U)

#define OSPI_IRQ_MASK_REG_INDRD_SRAM_FULL_MASK_FLD_MASK          (0x00001000U)
#define OSPI_IRQ_MASK_REG_INDRD_SRAM_FULL_MASK_FLD_SHIFT         (0x0000000CU)
#define OSPI_IRQ_MASK_REG_INDRD_SRAM_FULL_MASK_FLD_MAX           (0x00000001U)

#define OSPI_IRQ_MASK_REG_POLL_EXP_INT_MASK_FLD_MASK             (0x00002000U)
#define OSPI_IRQ_MASK_REG_POLL_EXP_INT_MASK_FLD_SHIFT            (0x0000000DU)
#define OSPI_IRQ_MASK_REG_POLL_EXP_INT_MASK_FLD_MAX              (0x00000001U)

#define OSPI_IRQ_MASK_REG_STIG_REQ_MASK_FLD_MASK                 (0x00004000U)
#define OSPI_IRQ_MASK_REG_STIG_REQ_MASK_FLD_SHIFT                (0x0000000EU)
#define OSPI_IRQ_MASK_REG_STIG_REQ_MASK_FLD_MAX                  (0x00000001U)

#define OSPI_IRQ_MASK_REG_IRQ_MASK_RESV1_FLD_MASK                (0x00008000U)
#define OSPI_IRQ_MASK_REG_IRQ_MASK_RESV1_FLD_SHIFT               (0x0000000FU)
#define OSPI_IRQ_MASK_REG_IRQ_MASK_RESV1_FLD_MAX                 (0x00000001U)

#define OSPI_IRQ_MASK_REG_RX_CRC_DATA_ERR_MASK_FLD_MASK          (0x00010000U)
#define OSPI_IRQ_MASK_REG_RX_CRC_DATA_ERR_MASK_FLD_SHIFT         (0x00000010U)
#define OSPI_IRQ_MASK_REG_RX_CRC_DATA_ERR_MASK_FLD_MAX           (0x00000001U)

#define OSPI_IRQ_MASK_REG_RX_CRC_DATA_VAL_MASK_FLD_MASK          (0x00020000U)
#define OSPI_IRQ_MASK_REG_RX_CRC_DATA_VAL_MASK_FLD_SHIFT         (0x00000011U)
#define OSPI_IRQ_MASK_REG_RX_CRC_DATA_VAL_MASK_FLD_MAX           (0x00000001U)

#define OSPI_IRQ_MASK_REG_TX_CRC_CHUNK_BRK_MASK_FLD_MASK         (0x00040000U)
#define OSPI_IRQ_MASK_REG_TX_CRC_CHUNK_BRK_MASK_FLD_SHIFT        (0x00000012U)
#define OSPI_IRQ_MASK_REG_TX_CRC_CHUNK_BRK_MASK_FLD_MAX          (0x00000001U)

#define OSPI_IRQ_MASK_REG_ECC_FAIL_MASK_FLD_MASK                 (0x00080000U)
#define OSPI_IRQ_MASK_REG_ECC_FAIL_MASK_FLD_SHIFT                (0x00000013U)
#define OSPI_IRQ_MASK_REG_ECC_FAIL_MASK_FLD_MAX                  (0x00000001U)

#define OSPI_IRQ_MASK_REG_IRQ_MASK_RESV_FLD_MASK                 (0xFFF00000U)
#define OSPI_IRQ_MASK_REG_IRQ_MASK_RESV_FLD_SHIFT                (0x00000014U)
#define OSPI_IRQ_MASK_REG_IRQ_MASK_RESV_FLD_MAX                  (0x00000FFFU)

/* LOWER_WR_PROT_REG */

#define OSPI_LOWER_WR_PROT_REG_SUBSECTOR_FLD_MASK                (0xFFFFFFFFU)
#define OSPI_LOWER_WR_PROT_REG_SUBSECTOR_FLD_SHIFT               (0x00000000U)
#define OSPI_LOWER_WR_PROT_REG_SUBSECTOR_FLD_MAX                 (0xFFFFFFFFU)

/* UPPER_WR_PROT_REG */

#define OSPI_UPPER_WR_PROT_REG_SUBSECTOR_FLD_MASK                (0xFFFFFFFFU)
#define OSPI_UPPER_WR_PROT_REG_SUBSECTOR_FLD_SHIFT               (0x00000000U)
#define OSPI_UPPER_WR_PROT_REG_SUBSECTOR_FLD_MAX                 (0xFFFFFFFFU)

/* WR_PROT_CTRL_REG */

#define OSPI_WR_PROT_CTRL_REG_INV_FLD_MASK                       (0x00000001U)
#define OSPI_WR_PROT_CTRL_REG_INV_FLD_SHIFT                      (0x00000000U)
#define OSPI_WR_PROT_CTRL_REG_INV_FLD_MAX                        (0x00000001U)

#define OSPI_WR_PROT_CTRL_REG_ENB_FLD_MASK                       (0x00000002U)
#define OSPI_WR_PROT_CTRL_REG_ENB_FLD_SHIFT                      (0x00000001U)
#define OSPI_WR_PROT_CTRL_REG_ENB_FLD_MAX                        (0x00000001U)

#define OSPI_WR_PROT_CTRL_REG_WR_PROT_CTRL_RESV_FLD_MASK         (0xFFFFFFFCU)
#define OSPI_WR_PROT_CTRL_REG_WR_PROT_CTRL_RESV_FLD_SHIFT        (0x00000002U)
#define OSPI_WR_PROT_CTRL_REG_WR_PROT_CTRL_RESV_FLD_MAX          (0x3FFFFFFFU)

/* INDIRECT_READ_XFER_CTRL_REG */

#define OSPI_INDIRECT_READ_XFER_CTRL_REG_START_FLD_MASK          (0x00000001U)
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_START_FLD_SHIFT         (0x00000000U)
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_START_FLD_MAX           (0x00000001U)

#define OSPI_INDIRECT_READ_XFER_CTRL_REG_CANCEL_FLD_MASK         (0x00000002U)
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_CANCEL_FLD_SHIFT        (0x00000001U)
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_CANCEL_FLD_MAX          (0x00000001U)

#define OSPI_INDIRECT_READ_XFER_CTRL_REG_RD_STATUS_FLD_MASK      (0x00000004U)
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_RD_STATUS_FLD_SHIFT     (0x00000002U)
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_RD_STATUS_FLD_MAX       (0x00000001U)

#define OSPI_INDIRECT_READ_XFER_CTRL_REG_SRAM_FULL_FLD_MASK      (0x00000008U)
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_SRAM_FULL_FLD_SHIFT     (0x00000003U)
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_SRAM_FULL_FLD_MAX       (0x00000001U)

#define OSPI_INDIRECT_READ_XFER_CTRL_REG_RD_QUEUED_FLD_MASK      (0x00000010U)
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_RD_QUEUED_FLD_SHIFT     (0x00000004U)
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_RD_QUEUED_FLD_MAX       (0x00000001U)

#define OSPI_INDIRECT_READ_XFER_CTRL_REG_IND_OPS_DONE_STATUS_FLD_MASK (0x00000020U)
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_IND_OPS_DONE_STATUS_FLD_SHIFT (0x00000005U)
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_IND_OPS_DONE_STATUS_FLD_MAX (0x00000001U)

#define OSPI_INDIRECT_READ_XFER_CTRL_REG_NUM_IND_OPS_DONE_FLD_MASK (0x000000C0U)
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_NUM_IND_OPS_DONE_FLD_SHIFT (0x00000006U)
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_NUM_IND_OPS_DONE_FLD_MAX (0x00000003U)

#define OSPI_INDIRECT_READ_XFER_CTRL_REG_INDIR_RD_XFER_RESV_FLD_MASK (0xFFFFFF00U)
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_INDIR_RD_XFER_RESV_FLD_SHIFT (0x00000008U)
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_INDIR_RD_XFER_RESV_FLD_MAX (0x00FFFFFFU)

/* INDIRECT_READ_XFER_WATERMARK_REG */

#define OSPI_INDIRECT_READ_XFER_WATERMARK_REG_LEVEL_FLD_MASK     (0xFFFFFFFFU)
#define OSPI_INDIRECT_READ_XFER_WATERMARK_REG_LEVEL_FLD_SHIFT    (0x00000000U)
#define OSPI_INDIRECT_READ_XFER_WATERMARK_REG_LEVEL_FLD_MAX      (0xFFFFFFFFU)

/* INDIRECT_READ_XFER_START_REG */

#define OSPI_INDIRECT_READ_XFER_START_REG_ADDR_FLD_MASK          (0xFFFFFFFFU)
#define OSPI_INDIRECT_READ_XFER_START_REG_ADDR_FLD_SHIFT         (0x00000000U)
#define OSPI_INDIRECT_READ_XFER_START_REG_ADDR_FLD_MAX           (0xFFFFFFFFU)

/* INDIRECT_READ_XFER_NUM_BYTES_REG */

#define OSPI_INDIRECT_READ_XFER_NUM_BYTES_REG_VALUE_FLD_MASK     (0xFFFFFFFFU)
#define OSPI_INDIRECT_READ_XFER_NUM_BYTES_REG_VALUE_FLD_SHIFT    (0x00000000U)
#define OSPI_INDIRECT_READ_XFER_NUM_BYTES_REG_VALUE_FLD_MAX      (0xFFFFFFFFU)

/* INDIRECT_WRITE_XFER_CTRL_REG */

#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_START_FLD_MASK         (0x00000001U)
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_START_FLD_SHIFT        (0x00000000U)
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_START_FLD_MAX          (0x00000001U)

#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_CANCEL_FLD_MASK        (0x00000002U)
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_CANCEL_FLD_SHIFT       (0x00000001U)
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_CANCEL_FLD_MAX         (0x00000001U)

#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_WR_STATUS_FLD_MASK     (0x00000004U)
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_WR_STATUS_FLD_SHIFT    (0x00000002U)
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_WR_STATUS_FLD_MAX      (0x00000001U)

#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_INDIR_WR_XFER_RESV1_FLD_MASK (0x00000008U)
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_INDIR_WR_XFER_RESV1_FLD_SHIFT (0x00000003U)
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_INDIR_WR_XFER_RESV1_FLD_MAX (0x00000001U)

#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_WR_QUEUED_FLD_MASK     (0x00000010U)
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_WR_QUEUED_FLD_SHIFT    (0x00000004U)
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_WR_QUEUED_FLD_MAX      (0x00000001U)

#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_IND_OPS_DONE_STATUS_FLD_MASK (0x00000020U)
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_IND_OPS_DONE_STATUS_FLD_SHIFT (0x00000005U)
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_IND_OPS_DONE_STATUS_FLD_MAX (0x00000001U)

#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_NUM_IND_OPS_DONE_FLD_MASK (0x000000C0U)
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_NUM_IND_OPS_DONE_FLD_SHIFT (0x00000006U)
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_NUM_IND_OPS_DONE_FLD_MAX (0x00000003U)

#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_INDIR_WR_XFER_RESV2_FLD_MASK (0xFFFFFF00U)
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_INDIR_WR_XFER_RESV2_FLD_SHIFT (0x00000008U)
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_INDIR_WR_XFER_RESV2_FLD_MAX (0x00FFFFFFU)

/* INDIRECT_WRITE_XFER_WATERMARK_REG */

#define OSPI_INDIRECT_WRITE_XFER_WATERMARK_REG_LEVEL_FLD_MASK    (0xFFFFFFFFU)
#define OSPI_INDIRECT_WRITE_XFER_WATERMARK_REG_LEVEL_FLD_SHIFT   (0x00000000U)
#define OSPI_INDIRECT_WRITE_XFER_WATERMARK_REG_LEVEL_FLD_MAX     (0xFFFFFFFFU)

/* INDIRECT_WRITE_XFER_START_REG */

#define OSPI_INDIRECT_WRITE_XFER_START_REG_ADDR_FLD_MASK         (0xFFFFFFFFU)
#define OSPI_INDIRECT_WRITE_XFER_START_REG_ADDR_FLD_SHIFT        (0x00000000U)
#define OSPI_INDIRECT_WRITE_XFER_START_REG_ADDR_FLD_MAX          (0xFFFFFFFFU)

/* INDIRECT_WRITE_XFER_NUM_BYTES_REG */

#define OSPI_INDIRECT_WRITE_XFER_NUM_BYTES_REG_VALUE_FLD_MASK    (0xFFFFFFFFU)
#define OSPI_INDIRECT_WRITE_XFER_NUM_BYTES_REG_VALUE_FLD_SHIFT   (0x00000000U)
#define OSPI_INDIRECT_WRITE_XFER_NUM_BYTES_REG_VALUE_FLD_MAX     (0xFFFFFFFFU)

/* INDIRECT_TRIGGER_ADDR_RANGE_REG */

#define OSPI_INDIRECT_TRIGGER_ADDR_RANGE_REG_IND_RANGE_WIDTH_FLD_MASK (0x0000000FU)
#define OSPI_INDIRECT_TRIGGER_ADDR_RANGE_REG_IND_RANGE_WIDTH_FLD_SHIFT (0x00000000U)
#define OSPI_INDIRECT_TRIGGER_ADDR_RANGE_REG_IND_RANGE_WIDTH_FLD_MAX (0x0000000FU)

#define OSPI_INDIRECT_TRIGGER_ADDR_RANGE_REG_IND_RANGE_RESV1_FLD_MASK (0xFFFFFFF0U)
#define OSPI_INDIRECT_TRIGGER_ADDR_RANGE_REG_IND_RANGE_RESV1_FLD_SHIFT (0x00000004U)
#define OSPI_INDIRECT_TRIGGER_ADDR_RANGE_REG_IND_RANGE_RESV1_FLD_MAX (0x0FFFFFFFU)

/* FLASH_COMMAND_CTRL_MEM_REG */

#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_TRIGGER_MEM_BANK_REQ_FLD_MASK (0x00000001U)
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_TRIGGER_MEM_BANK_REQ_FLD_SHIFT (0x00000000U)
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_TRIGGER_MEM_BANK_REQ_FLD_MAX (0x00000001U)

#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_MEM_BANK_REQ_IN_PROGRESS_FLD_MASK (0x00000002U)
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_MEM_BANK_REQ_IN_PROGRESS_FLD_SHIFT (0x00000001U)
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_MEM_BANK_REQ_IN_PROGRESS_FLD_MAX (0x00000001U)

#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_FLASH_COMMAND_CTRL_MEM_RESV3_FLD_MASK (0x000000FCU)
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_FLASH_COMMAND_CTRL_MEM_RESV3_FLD_SHIFT (0x00000002U)
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_FLASH_COMMAND_CTRL_MEM_RESV3_FLD_MAX (0x0000003FU)

#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_MEM_BANK_READ_DATA_FLD_MASK (0x0000FF00U)
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_MEM_BANK_READ_DATA_FLD_SHIFT (0x00000008U)
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_MEM_BANK_READ_DATA_FLD_MAX (0x000000FFU)

#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_NB_OF_STIG_READ_BYTES_FLD_MASK (0x00070000U)
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_NB_OF_STIG_READ_BYTES_FLD_SHIFT (0x00000010U)
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_NB_OF_STIG_READ_BYTES_FLD_MAX (0x00000007U)

#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_FLASH_COMMAND_CTRL_MEM_RESV2_FLD_MASK (0x00080000U)
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_FLASH_COMMAND_CTRL_MEM_RESV2_FLD_SHIFT (0x00000013U)
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_FLASH_COMMAND_CTRL_MEM_RESV2_FLD_MAX (0x00000001U)

#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_MEM_BANK_ADDR_FLD_MASK   (0x1FF00000U)
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_MEM_BANK_ADDR_FLD_SHIFT  (0x00000014U)
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_MEM_BANK_ADDR_FLD_MAX    (0x000001FFU)

#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_FLASH_COMMAND_CTRL_MEM_RESV1_FLD_MASK (0xE0000000U)
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_FLASH_COMMAND_CTRL_MEM_RESV1_FLD_SHIFT (0x0000001DU)
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_FLASH_COMMAND_CTRL_MEM_RESV1_FLD_MAX (0x00000007U)

/* FLASH_CMD_CTRL_REG */

#define OSPI_FLASH_CMD_CTRL_REG_CMD_EXEC_FLD_MASK                (0x00000001U)
#define OSPI_FLASH_CMD_CTRL_REG_CMD_EXEC_FLD_SHIFT               (0x00000000U)
#define OSPI_FLASH_CMD_CTRL_REG_CMD_EXEC_FLD_MAX                 (0x00000001U)

#define OSPI_FLASH_CMD_CTRL_REG_CMD_EXEC_STATUS_FLD_MASK         (0x00000002U)
#define OSPI_FLASH_CMD_CTRL_REG_CMD_EXEC_STATUS_FLD_SHIFT        (0x00000001U)
#define OSPI_FLASH_CMD_CTRL_REG_CMD_EXEC_STATUS_FLD_MAX          (0x00000001U)

#define OSPI_FLASH_CMD_CTRL_REG_STIG_MEM_BANK_EN_FLD_MASK        (0x00000004U)
#define OSPI_FLASH_CMD_CTRL_REG_STIG_MEM_BANK_EN_FLD_SHIFT       (0x00000002U)
#define OSPI_FLASH_CMD_CTRL_REG_STIG_MEM_BANK_EN_FLD_MAX         (0x00000001U)

#define OSPI_FLASH_CMD_CTRL_REG_FLASH_CMD_CTRL_RESV1_FLD_MASK    (0x00000078U)
#define OSPI_FLASH_CMD_CTRL_REG_FLASH_CMD_CTRL_RESV1_FLD_SHIFT   (0x00000003U)
#define OSPI_FLASH_CMD_CTRL_REG_FLASH_CMD_CTRL_RESV1_FLD_MAX     (0x0000000FU)

#define OSPI_FLASH_CMD_CTRL_REG_NUM_DUMMY_CYCLES_FLD_MASK        (0x00000F80U)
#define OSPI_FLASH_CMD_CTRL_REG_NUM_DUMMY_CYCLES_FLD_SHIFT       (0x00000007U)
#define OSPI_FLASH_CMD_CTRL_REG_NUM_DUMMY_CYCLES_FLD_MAX         (0x0000001FU)

#define OSPI_FLASH_CMD_CTRL_REG_NUM_WR_DATA_BYTES_FLD_MASK       (0x00007000U)
#define OSPI_FLASH_CMD_CTRL_REG_NUM_WR_DATA_BYTES_FLD_SHIFT      (0x0000000CU)
#define OSPI_FLASH_CMD_CTRL_REG_NUM_WR_DATA_BYTES_FLD_MAX        (0x00000007U)

#define OSPI_FLASH_CMD_CTRL_REG_ENB_WRITE_DATA_FLD_MASK          (0x00008000U)
#define OSPI_FLASH_CMD_CTRL_REG_ENB_WRITE_DATA_FLD_SHIFT         (0x0000000FU)
#define OSPI_FLASH_CMD_CTRL_REG_ENB_WRITE_DATA_FLD_MAX           (0x00000001U)

#define OSPI_FLASH_CMD_CTRL_REG_NUM_ADDR_BYTES_FLD_MASK          (0x00030000U)
#define OSPI_FLASH_CMD_CTRL_REG_NUM_ADDR_BYTES_FLD_SHIFT         (0x00000010U)
#define OSPI_FLASH_CMD_CTRL_REG_NUM_ADDR_BYTES_FLD_MAX           (0x00000003U)

#define OSPI_FLASH_CMD_CTRL_REG_ENB_MODE_BIT_FLD_MASK            (0x00040000U)
#define OSPI_FLASH_CMD_CTRL_REG_ENB_MODE_BIT_FLD_SHIFT           (0x00000012U)
#define OSPI_FLASH_CMD_CTRL_REG_ENB_MODE_BIT_FLD_MAX             (0x00000001U)

#define OSPI_FLASH_CMD_CTRL_REG_ENB_COMD_ADDR_FLD_MASK           (0x00080000U)
#define OSPI_FLASH_CMD_CTRL_REG_ENB_COMD_ADDR_FLD_SHIFT          (0x00000013U)
#define OSPI_FLASH_CMD_CTRL_REG_ENB_COMD_ADDR_FLD_MAX            (0x00000001U)

#define OSPI_FLASH_CMD_CTRL_REG_NUM_RD_DATA_BYTES_FLD_MASK       (0x00700000U)
#define OSPI_FLASH_CMD_CTRL_REG_NUM_RD_DATA_BYTES_FLD_SHIFT      (0x00000014U)
#define OSPI_FLASH_CMD_CTRL_REG_NUM_RD_DATA_BYTES_FLD_MAX        (0x00000007U)

#define OSPI_FLASH_CMD_CTRL_REG_ENB_READ_DATA_FLD_MASK           (0x00800000U)
#define OSPI_FLASH_CMD_CTRL_REG_ENB_READ_DATA_FLD_SHIFT          (0x00000017U)
#define OSPI_FLASH_CMD_CTRL_REG_ENB_READ_DATA_FLD_MAX            (0x00000001U)

#define OSPI_FLASH_CMD_CTRL_REG_CMD_OPCODE_FLD_MASK              (0xFF000000U)
#define OSPI_FLASH_CMD_CTRL_REG_CMD_OPCODE_FLD_SHIFT             (0x00000018U)
#define OSPI_FLASH_CMD_CTRL_REG_CMD_OPCODE_FLD_MAX               (0x000000FFU)

/* FLASH_CMD_ADDR_REG */

#define OSPI_FLASH_CMD_ADDR_REG_ADDR_FLD_MASK                    (0xFFFFFFFFU)
#define OSPI_FLASH_CMD_ADDR_REG_ADDR_FLD_SHIFT                   (0x00000000U)
#define OSPI_FLASH_CMD_ADDR_REG_ADDR_FLD_MAX                     (0xFFFFFFFFU)

/* FLASH_RD_DATA_LOWER_REG */

#define OSPI_FLASH_RD_DATA_LOWER_REG_DATA_FLD_MASK               (0xFFFFFFFFU)
#define OSPI_FLASH_RD_DATA_LOWER_REG_DATA_FLD_SHIFT              (0x00000000U)
#define OSPI_FLASH_RD_DATA_LOWER_REG_DATA_FLD_MAX                (0xFFFFFFFFU)

/* FLASH_RD_DATA_UPPER_REG */

#define OSPI_FLASH_RD_DATA_UPPER_REG_DATA_FLD_MASK               (0xFFFFFFFFU)
#define OSPI_FLASH_RD_DATA_UPPER_REG_DATA_FLD_SHIFT              (0x00000000U)
#define OSPI_FLASH_RD_DATA_UPPER_REG_DATA_FLD_MAX                (0xFFFFFFFFU)

/* FLASH_WR_DATA_LOWER_REG */

#define OSPI_FLASH_WR_DATA_LOWER_REG_DATA_FLD_MASK               (0xFFFFFFFFU)
#define OSPI_FLASH_WR_DATA_LOWER_REG_DATA_FLD_SHIFT              (0x00000000U)
#define OSPI_FLASH_WR_DATA_LOWER_REG_DATA_FLD_MAX                (0xFFFFFFFFU)

/* FLASH_WR_DATA_UPPER_REG */

#define OSPI_FLASH_WR_DATA_UPPER_REG_DATA_FLD_MASK               (0xFFFFFFFFU)
#define OSPI_FLASH_WR_DATA_UPPER_REG_DATA_FLD_SHIFT              (0x00000000U)
#define OSPI_FLASH_WR_DATA_UPPER_REG_DATA_FLD_MAX                (0xFFFFFFFFU)

/* POLLING_FLASH_STATUS_REG */

#define OSPI_POLLING_FLASH_STATUS_REG_DEVICE_STATUS_FLD_MASK     (0x000000FFU)
#define OSPI_POLLING_FLASH_STATUS_REG_DEVICE_STATUS_FLD_SHIFT    (0x00000000U)
#define OSPI_POLLING_FLASH_STATUS_REG_DEVICE_STATUS_FLD_MAX      (0x000000FFU)

#define OSPI_POLLING_FLASH_STATUS_REG_DEVICE_STATUS_VALID_FLD_MASK (0x00000100U)
#define OSPI_POLLING_FLASH_STATUS_REG_DEVICE_STATUS_VALID_FLD_SHIFT (0x00000008U)
#define OSPI_POLLING_FLASH_STATUS_REG_DEVICE_STATUS_VALID_FLD_MAX (0x00000001U)

#define OSPI_POLLING_FLASH_STATUS_REG_DEVICE_STATUS_RSVD_FLD1_MASK (0x0000FE00U)
#define OSPI_POLLING_FLASH_STATUS_REG_DEVICE_STATUS_RSVD_FLD1_SHIFT (0x00000009U)
#define OSPI_POLLING_FLASH_STATUS_REG_DEVICE_STATUS_RSVD_FLD1_MAX (0x0000007FU)

#define OSPI_POLLING_FLASH_STATUS_REG_DEVICE_STATUS_NB_DUMMY_MASK (0x000F0000U)
#define OSPI_POLLING_FLASH_STATUS_REG_DEVICE_STATUS_NB_DUMMY_SHIFT (0x00000010U)
#define OSPI_POLLING_FLASH_STATUS_REG_DEVICE_STATUS_NB_DUMMY_MAX (0x0000000FU)

#define OSPI_POLLING_FLASH_STATUS_REG_DEVICE_STATUS_RSVD_FLD2_MASK (0xFFF00000U)
#define OSPI_POLLING_FLASH_STATUS_REG_DEVICE_STATUS_RSVD_FLD2_SHIFT (0x00000014U)
#define OSPI_POLLING_FLASH_STATUS_REG_DEVICE_STATUS_RSVD_FLD2_MAX (0x00000FFFU)

/* PHY_CONFIGURATION_REG */

#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RX_DLL_DELAY_FLD_MASK (0x0000007FU)
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RX_DLL_DELAY_FLD_SHIFT (0x00000000U)
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RX_DLL_DELAY_FLD_MAX (0x0000007FU)

#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RESV1_FLD_MASK     (0x0000FF80U)
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RESV1_FLD_SHIFT    (0x00000007U)
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RESV1_FLD_MAX      (0x000001FFU)

#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_TX_DLL_DELAY_FLD_MASK (0x007F0000U)
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_TX_DLL_DELAY_FLD_SHIFT (0x00000010U)
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_TX_DLL_DELAY_FLD_MAX (0x0000007FU)

#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RESV2_FLD_MASK     (0x1F800000U)
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RESV2_FLD_SHIFT    (0x00000017U)
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RESV2_FLD_MAX      (0x0000003FU)

#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RX_DLL_BYPASS_FLD_MASK (0x20000000U)
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RX_DLL_BYPASS_FLD_SHIFT (0x0000001DU)
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RX_DLL_BYPASS_FLD_MAX (0x00000001U)

#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RESET_FLD_MASK     (0x40000000U)
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RESET_FLD_SHIFT    (0x0000001EU)
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RESET_FLD_MAX      (0x00000001U)

#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RESYNC_FLD_MASK    (0x80000000U)
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RESYNC_FLD_SHIFT   (0x0000001FU)
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RESYNC_FLD_MAX     (0x00000001U)

/* PHY_MASTER_CONTROL_REG */

#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_INITIAL_DELAY_FLD_MASK (0x0000007FU)
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_INITIAL_DELAY_FLD_SHIFT (0x00000000U)
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_INITIAL_DELAY_FLD_MAX (0x0000007FU)

#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_CONTROL_RESV1_FLD_MASK (0x0000FF80U)
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_CONTROL_RESV1_FLD_SHIFT (0x00000007U)
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_CONTROL_RESV1_FLD_MAX (0x000001FFU)

#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_NB_INDICATIONS_FLD_MASK (0x00070000U)
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_NB_INDICATIONS_FLD_SHIFT (0x00000010U)
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_NB_INDICATIONS_FLD_MAX (0x00000007U)

#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_CONTROL_RESV2_FLD_MASK (0x00080000U)
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_CONTROL_RESV2_FLD_SHIFT (0x00000013U)
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_CONTROL_RESV2_FLD_MAX (0x00000001U)

#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_PHASE_DETECT_SELECTOR_FLD_MASK (0x00700000U)
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_PHASE_DETECT_SELECTOR_FLD_SHIFT (0x00000014U)
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_PHASE_DETECT_SELECTOR_FLD_MAX (0x00000007U)

#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_BYPASS_MODE_FLD_MASK (0x00800000U)
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_BYPASS_MODE_FLD_SHIFT (0x00000017U)
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_BYPASS_MODE_FLD_MAX (0x00000001U)

#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_LOCK_MODE_FLD_MASK (0x01000000U)
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_LOCK_MODE_FLD_SHIFT (0x00000018U)
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_LOCK_MODE_FLD_MAX (0x00000001U)

#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_CONTROL_RESV3_FLD_MASK (0xFE000000U)
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_CONTROL_RESV3_FLD_SHIFT (0x00000019U)
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_CONTROL_RESV3_FLD_MAX (0x0000007FU)

/* DLL_OBSERVABLE_LOWER_REG */

#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_DLL_LOCK_FLD_MASK (0x00000001U)
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_DLL_LOCK_FLD_SHIFT (0x00000000U)
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_DLL_LOCK_FLD_MAX (0x00000001U)

#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_LOCK_MODE_FLD_MASK (0x00000006U)
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_LOCK_MODE_FLD_SHIFT (0x00000001U)
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_LOCK_MODE_FLD_MAX (0x00000003U)

#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_UNLOCK_COUNTER_FLD_MASK (0x000000F8U)
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_UNLOCK_COUNTER_FLD_SHIFT (0x00000003U)
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_UNLOCK_COUNTER_FLD_MAX (0x0000001FU)

#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_LOCK_VALUE_FLD_MASK (0x00007F00U)
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_LOCK_VALUE_FLD_SHIFT (0x00000008U)
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_LOCK_VALUE_FLD_MAX (0x0000007FU)

#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_LOOPBACK_LOCK_FLD_MASK (0x00008000U)
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_LOOPBACK_LOCK_FLD_SHIFT (0x0000000FU)
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_LOOPBACK_LOCK_FLD_MAX (0x00000001U)

#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_DLL_LOCK_DEC_FLD_MASK (0x00FF0000U)
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_DLL_LOCK_DEC_FLD_SHIFT (0x00000010U)
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_DLL_LOCK_DEC_FLD_MAX (0x000000FFU)

#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_DLL_LOCK_INC_FLD_MASK (0xFF000000U)
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_DLL_LOCK_INC_FLD_SHIFT (0x00000018U)
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_DLL_LOCK_INC_FLD_MAX (0x000000FFU)

/* DLL_OBSERVABLE_UPPER_REG */

#define OSPI_DLL_OBSERVABLE_UPPER_REG_DLL_OBSERVABLE__UPPER_RX_DECODER_OUTPUT_FLD_MASK (0x0000007FU)
#define OSPI_DLL_OBSERVABLE_UPPER_REG_DLL_OBSERVABLE__UPPER_RX_DECODER_OUTPUT_FLD_SHIFT (0x00000000U)
#define OSPI_DLL_OBSERVABLE_UPPER_REG_DLL_OBSERVABLE__UPPER_RX_DECODER_OUTPUT_FLD_MAX (0x0000007FU)

#define OSPI_DLL_OBSERVABLE_UPPER_REG_DLL_OBSERVABLE_UPPER_RESV1_FLD_MASK (0x0000FF80U)
#define OSPI_DLL_OBSERVABLE_UPPER_REG_DLL_OBSERVABLE_UPPER_RESV1_FLD_SHIFT (0x00000007U)
#define OSPI_DLL_OBSERVABLE_UPPER_REG_DLL_OBSERVABLE_UPPER_RESV1_FLD_MAX (0x000001FFU)

#define OSPI_DLL_OBSERVABLE_UPPER_REG_DLL_OBSERVABLE_UPPER_TX_DECODER_OUTPUT_FLD_MASK (0x007F0000U)
#define OSPI_DLL_OBSERVABLE_UPPER_REG_DLL_OBSERVABLE_UPPER_TX_DECODER_OUTPUT_FLD_SHIFT (0x00000010U)
#define OSPI_DLL_OBSERVABLE_UPPER_REG_DLL_OBSERVABLE_UPPER_TX_DECODER_OUTPUT_FLD_MAX (0x0000007FU)

#define OSPI_DLL_OBSERVABLE_UPPER_REG_DLL_OBSERVABLE_UPPER_RESV2_FLD_MASK (0xFF800000U)
#define OSPI_DLL_OBSERVABLE_UPPER_REG_DLL_OBSERVABLE_UPPER_RESV2_FLD_SHIFT (0x00000017U)
#define OSPI_DLL_OBSERVABLE_UPPER_REG_DLL_OBSERVABLE_UPPER_RESV2_FLD_MAX (0x000001FFU)

/* OPCODE_EXT_LOWER_REG */

#define OSPI_OPCODE_EXT_LOWER_REG_EXT_STIG_OPCODE_FLD_MASK       (0x000000FFU)
#define OSPI_OPCODE_EXT_LOWER_REG_EXT_STIG_OPCODE_FLD_SHIFT      (0x00000000U)
#define OSPI_OPCODE_EXT_LOWER_REG_EXT_STIG_OPCODE_FLD_MAX        (0x000000FFU)

#define OSPI_OPCODE_EXT_LOWER_REG_EXT_POLL_OPCODE_FLD_MASK       (0x0000FF00U)
#define OSPI_OPCODE_EXT_LOWER_REG_EXT_POLL_OPCODE_FLD_SHIFT      (0x00000008U)
#define OSPI_OPCODE_EXT_LOWER_REG_EXT_POLL_OPCODE_FLD_MAX        (0x000000FFU)

#define OSPI_OPCODE_EXT_LOWER_REG_EXT_WRITE_OPCODE_FLD_MASK      (0x00FF0000U)
#define OSPI_OPCODE_EXT_LOWER_REG_EXT_WRITE_OPCODE_FLD_SHIFT     (0x00000010U)
#define OSPI_OPCODE_EXT_LOWER_REG_EXT_WRITE_OPCODE_FLD_MAX       (0x000000FFU)

#define OSPI_OPCODE_EXT_LOWER_REG_EXT_READ_OPCODE_FLD_MASK       (0xFF000000U)
#define OSPI_OPCODE_EXT_LOWER_REG_EXT_READ_OPCODE_FLD_SHIFT      (0x00000018U)
#define OSPI_OPCODE_EXT_LOWER_REG_EXT_READ_OPCODE_FLD_MAX        (0x000000FFU)

/* OPCODE_EXT_UPPER_REG */

#define OSPI_OPCODE_EXT_UPPER_REG_OPCODE_EXT_UPPER_RESV1_FLD_MASK (0x0000FFFFU)
#define OSPI_OPCODE_EXT_UPPER_REG_OPCODE_EXT_UPPER_RESV1_FLD_SHIFT (0x00000000U)
#define OSPI_OPCODE_EXT_UPPER_REG_OPCODE_EXT_UPPER_RESV1_FLD_MAX (0x0000FFFFU)

#define OSPI_OPCODE_EXT_UPPER_REG_EXT_WEL_OPCODE_FLD_MASK        (0x00FF0000U)
#define OSPI_OPCODE_EXT_UPPER_REG_EXT_WEL_OPCODE_FLD_SHIFT       (0x00000010U)
#define OSPI_OPCODE_EXT_UPPER_REG_EXT_WEL_OPCODE_FLD_MAX         (0x000000FFU)

#define OSPI_OPCODE_EXT_UPPER_REG_WEL_OPCODE_FLD_MASK            (0xFF000000U)
#define OSPI_OPCODE_EXT_UPPER_REG_WEL_OPCODE_FLD_SHIFT           (0x00000018U)
#define OSPI_OPCODE_EXT_UPPER_REG_WEL_OPCODE_FLD_MAX             (0x000000FFU)

/* MODULE_ID_REG */

#define OSPI_MODULE_ID_REG_CONF_FLD_MASK                         (0x00000003U)
#define OSPI_MODULE_ID_REG_CONF_FLD_SHIFT                        (0x00000000U)
#define OSPI_MODULE_ID_REG_CONF_FLD_MAX                          (0x00000003U)

#define OSPI_MODULE_ID_REG_MODULE_ID_RESV_FLD_MASK               (0x000000FCU)
#define OSPI_MODULE_ID_REG_MODULE_ID_RESV_FLD_SHIFT              (0x00000002U)
#define OSPI_MODULE_ID_REG_MODULE_ID_RESV_FLD_MAX                (0x0000003FU)

#define OSPI_MODULE_ID_REG_MODULE_ID_FLD_MASK                    (0x00FFFF00U)
#define OSPI_MODULE_ID_REG_MODULE_ID_FLD_SHIFT                   (0x00000008U)
#define OSPI_MODULE_ID_REG_MODULE_ID_FLD_MAX                     (0x0000FFFFU)

#define OSPI_MODULE_ID_REG_FIX_PATCH_FLD_MASK                    (0xFF000000U)
#define OSPI_MODULE_ID_REG_FIX_PATCH_FLD_SHIFT                   (0x00000018U)
#define OSPI_MODULE_ID_REG_FIX_PATCH_FLD_MAX                     (0x000000FFU)


#ifdef __cplusplus
}
#endif

#endif /* _HW_OSPI_H_ */
