/*
*
* Copyright (c) 2023 Texas Instruments Incorporated
*
* All rights reserved not granted herein.
*
* Limited License.
*
* Texas Instruments Incorporated grants a world-wide, royalty-free, non-exclusive
* license under copyrights and patents it now or hereafter owns or controls to make,
* have made, use, import, offer to sell and sell ("Utilize") this software subject to the
* terms herein.  With respect to the foregoing patent license, such license is granted
* solely to the extent that any such patent is necessary to Utilize the software alone.
* The patent license shall not apply to any combinations which include this software,
* other than combinations with devices manufactured by or for TI ("TI Devices").
* No hardware patent is licensed hereunder.
*
* Redistributions must preserve existing copyright notices and reproduce this license
* (including the above copyright notice and the disclaimer and (if applicable) source
* code license limitations below) in the documentation and/or other materials provided
* with the distribution
*
* Redistribution and use in binary form, without modification, are permitted provided
* that the following conditions are met:
*
* *       No reverse engineering, decompilation, or disassembly of this software is
* permitted with respect to any software provided in binary form.
*
* *       any redistribution and use are licensed by TI for use only with TI Devices.
*
* *       Nothing shall obligate TI to provide you with source code for the software
* licensed and provided to you in object code.
*
* If software source code is provided to you, modification and redistribution of the
* source code are permitted provided that the following conditions are met:
*
* *       any redistribution and use of the source code, including any resulting derivative
* works, are licensed by TI for use only with TI Devices.
*
* *       any redistribution and use of any object code compiled from the source code
* and any resulting derivative works, are licensed by TI for use only with TI Devices.
*
* Neither the name of Texas Instruments Incorporated nor the names of its suppliers
*
* may be used to endorse or promote products derived from this software without
* specific prior written permission.
*
* DISCLAIMER.
*
* THIS SOFTWARE IS PROVIDED BY TI AND TI'S LICENSORS "AS IS" AND ANY EXPRESS
* OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
* OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL TI AND TI'S LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
* BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
* DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
* OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
[!IF "(as:modconf('Cdd_FsiTx')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPreCompile')"!]
  /*****************************************************************************
    Project: [!"$project"!]
    This file is generated by EB Tresos
    Do not modify this file, otherwise the software may behave in unexpected way

 ******************************************************************************/

/*******************************************************************************
 *  INCLUDES
 ******************************************************************************/
#include "Std_Types.h"
#include "Cdd_FsiTx.h"
#include "Cdd_FsiTx_Irq.h"
#include "Cdd_FsiTx_Cfg.h"

/******************************************************************************
 *  VERSION CHECK
 ******************************************************************************/
#if ( (CDD_FSI_TX_CFG_MAJOR_VERSION != ([!"substring-before($moduleSoftwareVer,'.')"!]U)) \
    ||(CDD_FSI_TX_CFG_MINOR_VERSION != ([!"substring-before(substring-after($moduleSoftwareVer,'.'),'.')"!]U)))
  #error "Version numbers of Cdd_FsiTx_Cfg.c and Cdd_FsiTx_Cfg.h are inconsistent!"
#endif

/*******************************************************************************
 *  GLOBAL CONFIG DATA
 ******************************************************************************/
#define CDD_FSITX_START_SEC_CONFIG_DATA
#include "Cdd_FsiTx_MemMap.h"

#ifdef __cplusplus
extern "C" {
#endif
[!AUTOSPACING!]

[!NOCODE!]
/**
 **Tx0 Base address - 0x5028 0000h
   Tx1-Base address - 0x5028 1000h
   Tx2 Base address - 0x502A 0000h
   Tx3 Base address - 0x502A 1000h
  The offset here given is 4096 which is 1000 in hex.

  So for the first instance (TX0), offset is not needed. Base adress will be 1344798720 itself.
  [That is why HWunitBase"   = "$HWunitOffset*0". which gives HWunitOffset=0 which will added to
  1344798720. So base adress for Tx0 is same.]

  For Instance TX1 offset will be 1000. so   HWunitBase"   = "$HWunitOffset*1"
  which gives HWunitOffset=4096 which will added to   1344798720. So base adress for Tx1 will be 0x5028 1000h.

  For Instance TX2 offset will be 20000 (502A0000-50280000),. so offset will be  HWunitBase"   = "$HWunitOffset*32" (which is equal to 4096*32)
  Hwhich gives HWunitOffset=131072 which will added to   1344798720. So base adress for TX2 will be 0x502A 0000h.

  For Instance TX3 offset will be 21000 (502A1000-50280000),. so offset will be  HWunitBase"   = "$HWunitOffset*33" (which is equal to 4096*33)
  Hwhich gives HWunitOffset=135168 which will added to   1344798720. So base adress for TX2 will be 0x502A 1000h.

*/
[!ENDNOCODE!][!//
[!MACRO "GetAddress", "HWNumber"!][!//
[!NOCODE!]
    [!VAR "BaseAddr" = "BaseAddr + 1344798720"!]
    [!VAR "HWunitOffset" = "HWunitOffset + 4096"!]


    [!IF "($HWNumber = 'CDD_FSI_TX_HWUNIT_0')"!]
    [!VAR "HWunitBase"   = "$HWunitOffset*0"!]
    [!ENDIF!]

    [!IF "($HWNumber = 'CDD_FSI_TX_HWUNIT_1')"!]
    [!VAR "HWunitBase"   = "$HWunitOffset*1"!]
    [!ENDIF!]


    [!IF "($HWNumber = 'CDD_FSI_TX_HWUNIT_2')"!]
    [!VAR "HWunitBase"   = "$HWunitOffset*32"!]
    [!ENDIF!]


    [!IF "($HWNumber = 'CDD_FSI_TX_HWUNIT_3')"!]
    [!VAR "HWunitBase"   = "$HWunitOffset*33"!]
    [!ENDIF!]

    [!CODE!][!"num:inttohex($BaseAddr+$HWunitBase)"!][!ENDCODE!]
[!ENDNOCODE!][!//
[!ENDMACRO!][!//


[!VAR "notifyFxnList" = "' '"!]
[!SELECT "as:modconf('Cdd_FsiTx')[1]/CddFsiTxConfigSet/*[@name = 'CddFsiTxNotification']"!]
[!IF "not(node:empty(.)) and not(text:match(node:value(.),'NULL_PTR'))"!][!//
[!IF "not(node:containsValue(text:split($notifyFxnList),node:value(.)))"!][!//
[!"concat('extern void ',name(),'(Cdd_FsiTx_HWUnitType hwUnitId);')"!]
[!VAR "notifyFxnList" = "concat($notifyFxnList,' ',node:value(.))"!][!//
[!ENDIF!][!//
[!ENDIF!][!//
[!ENDSELECT!]

[!VAR "notifyFxnList" = "' '"!]
[!SELECT "as:modconf('Cdd_FsiTx')[1]/CddFsiTxConfigSet/*[@name = 'CddFsiTxOverRunNotification']"!]
[!IF "not(node:empty(.)) and not(text:match(node:value(.),'NULL_PTR'))"!][!//
[!IF "not(node:containsValue(text:split($notifyFxnList),node:value(.)))"!][!//
[!"concat('extern void ',name(),'(Cdd_FsiTx_HWUnitType hwUnitId);')"!]
[!VAR "notifyFxnList" = "concat($notifyFxnList,' ',node:value(.))"!][!//
[!ENDIF!][!//
[!ENDIF!][!//
[!ENDSELECT!]

[!VAR "notifyFxnList" = "' '"!]
[!SELECT "as:modconf('Cdd_FsiTx')[1]/CddFsiTxConfigSet/*[@name = 'CddFsiTxUnderRunNotification']"!]
[!IF "not(node:empty(.)) and not(text:match(node:value(.),'NULL_PTR'))"!][!//
[!IF "not(node:containsValue(text:split($notifyFxnList),node:value(.)))"!][!//
[!"concat('extern void ',name(),'(Cdd_FsiTx_HWUnitType hwUnitId);')"!]
[!VAR "notifyFxnList" = "concat($notifyFxnList,' ',node:value(.))"!][!//
[!ENDIF!][!//
[!ENDIF!][!//
[!ENDSELECT!]

/* Create runtime configurations. */
[!LOOP "as:modconf('Cdd_FsiTx')[1]/CddFsiTxConfigSet"!]
[!VAR "HwLpCnt" = "0"!]
CONST(struct Cdd_FsiTx_ConfigType_s, CDD_FSI_TX_CONFIG_DATA) Cdd_FsiTx_Config =
{
    .maxHwUnit = [!"num:i(count(CddFsiTxHwUnit/*))"!]U,
    .cddFsiTxNotification = [!IF "not(node:empty(CddFsiTxNotification))"!] [!"CddFsiTxNotification"!][!ELSE!]NULL_PTR[!ENDIF!],
    .cddFsiTxOverRunNotification = [!IF "not(node:empty(CddFsiTxOverRunNotification))"!] [!"CddFsiTxOverRunNotification"!][!ELSE!]NULL_PTR[!ENDIF!],
    .cddFsiTxUnderRunNotification = [!IF "not(node:empty(CddFsiTxUnderRunNotification))"!] [!"CddFsiTxUnderRunNotification"!][!ELSE!]NULL_PTR[!ENDIF!],
    .hwUnitCfg  =
    {
        [!VAR "HwLpCnt" = "0"!][!//
        [!LOOP "CddFsiTxHwUnit/*"!]
        [[!"num:i($HwLpCnt)"!]] =
        {
            .hwId = CddFsiTxConf_CddFsiTxHwUnit_[!"@name"!],
            .hwUnitId = [!"CddFsiTxHwUnitId"!],
            .baseAddr = [!CALL "GetAddress", "HWNumber" = "CddFsiTxHwUnitId"!]UL,
            .triggSrc = [!"CddFsiTxTriggerSrc"!],
            .Prescalar = [!"CddFsiTxPrescale"!],
            .transmitMode = [!"CddFsiTxTransmissionMethod"!],
            .pingTriggerTimeout = [!"CddFsiTxPingTimerTimeout"!],
            [!NOCODE!][!//
            [!IF "CddFsiTxTriggerSrc = 'CDD_FSI_TX_TRIGG_SRC_HW'"!]
            [!CODE!]
            #if (STD_ON == CDD_FSI_TX_EXTERNAL_TRIGGER_ENABLE)
            .extFrameTriggsrc  =  [!"CddFsiTxExtHwTrigSrc"!],
            .extPingsrc  =  [!"CddFsiTxExtPingTrigSrc"!],
            #endif
             [!ENDCODE!]
            [!ENDIF!]
            [!ENDNOCODE!][!//
            [!NOCODE!][!//
            [!IF "(as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxDMAEnable = 'true') and (node:exists(as:modconf('Cdd_Dma')[1]/CddDmaGeneral)) and (not(node:empty(CddFsiTxDmaReference))) and (CddFsiTxTransmissionMethod = 'CDD_FSI_TX_DMA_MODE')"!][!//
            [!CODE!]
             #if (STD_ON == CDD_FSI_TX_DMA_ENABLE)
            .CddFsiTxDmaInstance = CddFsiTxConf_[!"@name"!]_DmaGroup,
           #endif
          [!ENDCODE!]
          [!ENDIF!]
          [!ENDNOCODE!][!//
        },
         [!VAR "HwLpCnt" = "$HwLpCnt+1"!]
        [!ENDLOOP!]
    },
};

[!ENDLOOP!]

#ifdef __cplusplus
}
#endif

#define CDD_FSITX_STOP_SEC_CONFIG_DATA
#include "Cdd_FsiTx_MemMap.h"

[!ENDIF!][!//
/*******************************************************************************
 *  END OF FILE: Cdd_FsiTx_Cfg.c
 ******************************************************************************/
