[!IF "(as:modconf('Can')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPreCompile') or (as:modconf('Can')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPostBuild')"!]
/* ======================================================================
*   Copyright (C) 2022-2023 Texas Instruments Incorporated
*
*   All rights reserved. Property of Texas Instruments Incorporated.
*   Restricted rights to use, duplicate or disclose this code are
*   granted through contract.
*
*   The program may not be used without the written permission
*   of Texas Instruments Incorporated or against the terms and conditions
*   stipulated in the agreement under which this program has been
*   supplied.
* ==================================================================== */
 /***************************************************************************
  Project: [!"$project"!]
  

  This file is generated by EB Tresos
  Do not modify this file, otherwise the software may behave in unexpected way.

 *****************************************************************************/

/*
 * Module switch
 */
/**********************************************************************************************************************
 *  INCLUDES
 *********************************************************************************************************************/
 #include "Can.h"
 #include "Can_Cfg.h"

/**********************************************************************************************************************
 *  VERSION CHECK
 *********************************************************************************************************************/

/** \brief Can configuration Major Version */
#define CAN_CFG_C_MAJOR_VERSION           ([!"substring-before($moduleSoftwareVer,'.')"!]U)
/** \brief Can configuration Minor Version */
#define CAN_CFG_C_MINOR_VERSION           ([!"substring-before(substring-after($moduleSoftwareVer,'.'),'.')"!]U)
/** \brief Can configuration Patch Version */
#define CAN_CFG_C_PATCH_VERSION           ([!"substring-after(substring-after($moduleSoftwareVer,'.'),'.')"!]U)

/*  Version checking  */
 #if (   (CAN_SW_MAJOR_VERSION != ([!"substring-before($moduleSoftwareVer,'.')"!]U))||(CAN_SW_MINOR_VERSION != ([!"substring-before(substring-after($moduleSoftwareVer,'.'),'.')"!]U)))
  #error "Version numbers of Can_Cfg.c and Can.h are inconsistent!"
#endif
#if (   (CAN_CFG_MAJOR_VERSION != ([!"substring-before($moduleSoftwareVer,'.')"!]U))||(CAN_CFG_MINOR_VERSION != ([!"substring-before(substring-after($moduleSoftwareVer,'.'),'.')"!]U)))
  #error "Version numbers of Can_Cfg.c and Can_Cfg.h are inconsistent!"
#endif
/**********************************************************************************************************************
 *  GLOBAL DATA
 *********************************************************************************************************************/
#define CAN_START_SEC_CONFIG_DATA
#include "Can_MemMap.h"

[!AUTOSPACING!]

[!IF "(as:modconf('Can')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPreCompile')"!]
/* Baud Rate Structure for all configsets */
[!VAR "CLK" = "1"!]
[!LOOP "as:modconf('Can')[1]/CanConfigSet/CanController/*"!]
[!VAR "CLK" = "node:value(node:ref(node:current()/CanCpuClockRef)/McuClockReferencePointFrequency)"!][!//
[!LOOP "CanControllerBaudrateConfig/*"!]
static Can_BaudConfigType
    [!"../../../../@name"!]_[!"../../@name"!]_[!"@name"!] =
{
    [!"CanControllerBaudRate"!]U,      /* in Kbps */
    [!"CanControllerPropSeg"!]U,       /* Prop Segement value */
    [!"CanControllerSeg1"!]U,          /* Phase Segment 1 */
    [!"CanControllerSeg2"!]U,          /* Phase Segment 2 */
    [!"CanControllerSyncJumpWidth"!]U, /* Sync jump width */
    [!"num:i(CanControllerPropSeg+CanControllerSeg1+CanControllerSeg2+CanControllerSyncJumpWidth)"!]U, /* Sum of all timing parameters */
    [!VAR "brp" = "(num:i(round(($CLK)div(CanControllerBaudRate*(1+CanControllerPropSeg+CanControllerSeg1+CanControllerSeg2)*1000))))"!]
    [!ASSERT "num:i($brp) < 512","STOP: BRP more than 512 for a controller is not allowed"!]
    [!"num:i($brp)"!]U,   /* Controller BRP value for Baud */
	[!IF "node:exists(CanControllerFdBaudrateConfig/*) = 'true'"!]
 /* Data phase Baudrate */
    {
        [!"CanControllerFdBaudrateConfig/*/CanControllerFdBaudRate"!]U,     /* in Kbps */
        [!"CanControllerFdBaudrateConfig/*/CanControllerPropSeg"!]U,        /* Prop Segement value */
        [!"CanControllerFdBaudrateConfig/*/CanControllerSeg1"!]U,           /* Phase Segment 1 */
        [!"CanControllerFdBaudrateConfig/*/CanControllerSeg2"!]U,           /* Phase Segment 2 */
        [!"CanControllerFdBaudrateConfig/*/CanControllerSyncJumpWidth"!]U,  /* Sync jump width */
        [!"num:i(CanControllerFdBaudrateConfig/*/CanControllerPropSeg+CanControllerFdBaudrateConfig/*/CanControllerSeg1+CanControllerFdBaudrateConfig/*/CanControllerSeg2+CanControllerFdBaudrateConfig/*/CanControllerSyncJumpWidth)"!]U, /* Sum of all timing parameters */
        [!VAR "brp" = "(num:i(round(($CLK)div((CanControllerFdBaudrateConfig/*/CanControllerFdBaudRate)*(1+CanControllerFdBaudrateConfig/*/CanControllerPropSeg+CanControllerFdBaudrateConfig/*/CanControllerSeg1+CanControllerFdBaudrateConfig/*/CanControllerSeg2)*1000))))"!]
        [!ASSERT "num:i($brp) < 32","STOP: BRP more than 32 for a controller is not allowed"!]
        [!"num:i($brp)"!]U,   /* Controller BRP value for Baud */
        [!VAR "timeQuanta" = "CanControllerFdBaudrateConfig/*/CanControllerTrcvDelayCompensationOffset/*"!][!//
        [!"num:i(round(($CLK)*($timeQuanta)div(1000000000)))"!]U, /* Specifies the Transceiver Delay Compensation Offset */
        (boolean) [!IF "CanControllerFdBaudrateConfig/*/CanControllerTxBitRateSwitch   = 'true'"!]TRUE[!ELSE!]FALSE[!ENDIF!], /* Specifies if the bit rate switching shall be used */
        [!IF "node:empty(CanControllerFdBaudrateConfig/*/CanControllerTrcvDelayCompensationOffset/*) = 'true'"!][!ERROR "CanControllerTrcvDelayCompensationOffset is not configured"!][!ENDIF!]
    }
[!ENDIF!]};
[!ENDLOOP!][!ENDLOOP!]

/*List of the Baudrate structures */
[!LOOP "as:modconf('Can')[1]/CanConfigSet/CanController/*"!]
static Can_BaudConfigType
    *[!"../../@name"!]_[!"@name"!]_BaudRateConfigList[]=
{
    [!LOOP "CanControllerBaudrateConfig/*"!]    &[!"../../../../@name"!]_[!"../../@name"!]_[!"@name"!],
    [!ENDLOOP!]
};

[!ENDLOOP!]

/* Controller structure defined here for all config sets */
[!LOOP "as:modconf('Can')[1]/CanConfigSet"!]
[!LOOP "CanController/*"!]
static Can_ControllerType
    [!"../../@name"!]_[!"@name"!] =
{
    &[!"../../@name"!]_[!"@name"!]_[!"node:name(node:ref(node:current()/CanControllerDefaultBaudrate))"!],  /* pointer to default Baud structure */
    [!"../../@name"!]_[!"@name"!]_BaudRateConfigList,  /* List of available Baudrate structs */
};
[!ENDLOOP!][!ENDLOOP!]

[!ENDIF!][!// /* VariantPreCompile or VariantPostBuild */

[!IF "(as:modconf('Can')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPreCompile') or (as:modconf('Can')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPostBuild')"!]
/* Controller structure defined here for all config sets */

[!VAR "CanController0AlreadyConfigured" = "0"!][!//
[!VAR "CanController1AlreadyConfigured" = "0"!][!//
[!VAR "CanController2AlreadyConfigured" = "0"!][!//
[!VAR "CanController3AlreadyConfigured" = "0"!][!//

[!LOOP "as:modconf('Can')[1]/CanConfigSet"!]
[!VAR "CanControllerIdIndx" = "0"!]
[!LOOP "CanController/*"!]
const struct Can_ControllerStruct_PC
    [!"../../@name"!]_PC_[!"@name"!] =
{
    CanConf_CanController_[!"@name"!],      /* Id as provided by GUI */
    [!IF "(num:i($CanControllerIdIndx)) != CanControllerId"!][!ERROR "Can Controller Id should start with 0,should be unique, increment by 1 and continue without any gaps"!][!ENDIF!]
    [!IF "(num:i($CanControllerIdIndx)) >= '4'"!][!ERROR "Number of controllers supported is 4 only"!][!ENDIF!]

    (boolean) [!IF "CanControllerActivation = 'true'"!]TRUE[!ELSE!]FALSE[!ENDIF!],   /* Contoller is used=1 or not_used=0*/
    [!"num:inttohex(CanControllerBaseAddress)"!]U, /* Can Controller Base Address */
    [!IF "CanControllerBaseAddress = '1382023168'"!]
    [!VAR "CanController0AlreadyConfigured" = "$CanController0AlreadyConfigured+1"!][!//
    [!IF "(num:i($CanController0AlreadyConfigured)) > '1'"!][!ERROR "Controller Instance MCAN0 is already configured"!][!ENDIF!]
    [!ENDIF!]
    [!IF "CanControllerInstance = 'MCAN0'"!]
    [!IF "CanControllerBaseAddress != '1382023168'"!]
    [!ERROR "Invalid Can Controller BaseAddress configured for selected instance, please check TRM"!]
    [!ENDIF!]
    [!ENDIF!]
    [!IF "CanControllerBaseAddress = '1382088704'"!]
    [!VAR "CanController1AlreadyConfigured" = "$CanController1AlreadyConfigured+1"!][!//
    [!IF "(num:i($CanController1AlreadyConfigured)) > '1'"!][!ERROR "Controller Instance MCAN1 is already configured"!][!ENDIF!]
    [!ENDIF!]
    [!IF "CanControllerInstance = 'MCAN1'"!]
    [!IF "CanControllerBaseAddress != '1382088704'"!]
    [!ERROR "Invalid Can Controller BaseAddress configured for selected instance, please check TRM"!]
    [!ENDIF!]
    [!ENDIF!]
	[!IF "CanControllerBaseAddress = '1382154240'"!]
    [!VAR "CanController2AlreadyConfigured" = "$CanController2AlreadyConfigured+1"!][!//
    [!IF "(num:i($CanController2AlreadyConfigured)) > '1'"!][!ERROR "Controller Instance MCAN2 is already configured"!][!ENDIF!]
    [!ENDIF!]
    [!IF "CanControllerInstance = 'MCAN2'"!]
    [!IF "CanControllerBaseAddress != '1382154240'"!]
    [!ERROR "Invalid Can Controller BaseAddress configured for selected instance, please check TRM"!]
    [!ENDIF!]
    [!ENDIF!]
	[!IF "CanControllerBaseAddress = '1382219776'"!]
    [!VAR "CanController3AlreadyConfigured" = "$CanController3AlreadyConfigured+1"!][!//
    [!IF "(num:i($CanController3AlreadyConfigured)) > '1'"!][!ERROR "Controller Instance MCAN3 is already configured"!][!ENDIF!]
    [!ENDIF!]
    [!IF "CanControllerInstance = 'MCAN3'"!]
    [!IF "CanControllerBaseAddress != '1382219776'"!]
    [!ERROR "Invalid Can Controller BaseAddress configured for selected instance, please check TRM"!]
    [!ENDIF!]
    [!ENDIF!]
	(boolean) [!IF "CanWakeupSupport = 'true'"!]TRUE[!ELSE!]FALSE[!ENDIF!],[!WS "4"!]/* Automatic wakeup via bus activity */
    [!WS "4"!][!IF "CanRxProcessing   = 'INTERRUPT'"!]CAN_TX_RX_PROCESSING_INTERRUPT[!ELSEIF "CanRxProcessing = 'MIXED'"!]CAN_TX_RX_PROCESSING_MIXED[!ELSE!]CAN_TX_RX_PROCESSING_POLLING[!ENDIF!],  /* Can Rx Processing Type */
    [!WS "4"!][!IF "CanTxProcessing   = 'INTERRUPT'"!]CAN_TX_RX_PROCESSING_INTERRUPT[!ELSEIF "CanTxProcessing = 'MIXED'"!]CAN_TX_RX_PROCESSING_MIXED[!ELSE!]CAN_TX_RX_PROCESSING_POLLING[!ENDIF!],  /* Can Tx Processing Type */
    (boolean) [!IF "CanBusoffProcessing = 'INTERRUPT'"!]TRUE[!ELSE!]FALSE[!ENDIF!],/* BusOff  TRUE = Interrupt FALSE = Polling */
	(boolean) [!IF "CanWakeupProcessing = 'INTERRUPT'"!]TRUE[!ELSE!]FALSE[!ENDIF!],[!WS "4"!]/* TRUE = Interrupt FALSE = Polling */
	(boolean) [!IF "CanDisableAutoRetranmission = 'true'"!]TRUE[!ELSE!]FALSE[!ENDIF!],[!WS "4"!]/* Auto retransmission on Tx error Enable/Disable */
	NULL_PTR,
	[!IF "CanControllerInstance ='MCAN0'"!]
    CAN_CONTROLLER_INSTANCE_MCAN0,  /* Controller Instance */
    [!ELSEIF "CanControllerInstance ='MCAN1'"!]
    CAN_CONTROLLER_INSTANCE_MCAN1,  /* Controller Instance */
    [!ELSEIF "CanControllerInstance ='MCAN2'"!]
    CAN_CONTROLLER_INSTANCE_MCAN2,  /* Controller Instance */
    [!ELSEIF "CanControllerInstance ='MCAN3'"!]
    CAN_CONTROLLER_INSTANCE_MCAN3,  /* Controller Instance */
	[!ENDIF!]
};
[!VAR "CanControllerIdIndx" = "$CanControllerIdIndx+1"!]
[!ENDLOOP!][!ENDLOOP!]

[!ENDIF!][!// /* VariantPreCompile */

[!IF "(as:modconf('Can')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPreCompile')"!]
/*List of the Controller structures */
[!LOOP "as:modconf('Can')[1]/CanConfigSet"!]
static Can_ControllerType
    *[!"@name"!]_CanController_List[]=
{
    [!LOOP "CanController/*"!]    &[!"../../@name"!]_[!"@name"!],
    [!ENDLOOP!]
};
[!ENDLOOP!]
[!ENDIF!][!//

[!IF "(as:modconf('Can')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPreCompile') or (as:modconf('Can')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPostBuild')"!]
[!LOOP "as:modconf('Can')[1]/CanConfigSet"!]
const struct Can_ControllerStruct_PC
    *[!"@name"!]_CanController_List_PC[CAN_NUM_CONTROLLER]=
{
    [!LOOP "CanController/*"!]    &[!"../../@name"!]_PC_[!"@name"!],
    [!ENDLOOP!]
};
[!ENDLOOP!]
[!ENDIF!][!//

[!IF "(as:modconf('Can')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPreCompile')"!]
/* HW Filter structure for all configsets */
[!LOOP "as:modconf('Can')[1]/CanConfigSet/CanHardwareObject/*"!]
[!IF "CanObjectType = 'RECEIVE'"!]
[!IF "node:empty(CanHwFilter/*/CanHwFilterCode) = 'true'"!]
[!ERROR "Please configure HW filter struct as this mailbox object is HRH "!]
[!ENDIF!]
[!LOOP "CanHwFilter/*"!]
static Can_HwFilterType
    [!"../../../../@name"!]_[!"../../@name"!]_[!"@name"!] =
{
    [!"CanHwFilterCode"!]U,  /*CanHwFilterCode*/
    [!"CanHwFilterMask"!]U,  /*Filter Mask*/
};
[!ENDLOOP!]
[!ENDIF!]
[!ENDLOOP!]

/*List of the HW Filter structures */
[!LOOP "as:modconf('Can')[1]/CanConfigSet/CanHardwareObject/*"!]
[!IF "CanObjectType = 'RECEIVE'"!]
static Can_HwFilterType
    *[!"../../@name"!]_[!"@name"!]_HwFilterConfigList[]=
{
    [!LOOP "CanHwFilter/*"!]    &[!"../../../../@name"!]_[!"../../@name"!]_[!"@name"!],
    [!ENDLOOP!]
};
[!ENDIF!]
[!ENDLOOP!]

[!ENDIF!][!//

[!IF "(as:modconf('Can')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPreCompile')"!]
/* All the Mailbox objects(MB's) will be defined here for all config sets */
[!VAR "MCANTxCnt" = "0"!]
[!VAR "MCAN0TxCnt" = "0"!] [!VAR "MCAN0RxCnt" = "0"!] [!VAR "MCAN0TxFifoCnt" = "0"!] [!VAR "MCAN0RxFifoCnt" = "0"!]
[!VAR "MCAN1TxCnt" = "0"!] [!VAR "MCAN1RxCnt" = "0"!] [!VAR "MCAN1TxFifoCnt" = "0"!] [!VAR "MCAN1RxFifoCnt" = "0"!]
[!VAR "MCAN2TxCnt" = "0"!] [!VAR "MCAN2RxCnt" = "0"!] [!VAR "MCAN2TxFifoCnt" = "0"!] [!VAR "MCAN2RxFifoCnt" = "0"!]
[!VAR "MCAN3TxCnt" = "0"!] [!VAR "MCAN3RxCnt" = "0"!] [!VAR "MCAN3TxFifoCnt" = "0"!] [!VAR "MCAN3RxFifoCnt" = "0"!]
[!VAR "MCAN0StdFilterCnt" = "0"!] [!VAR "MCAN0ExtdFilterCnt" = "0"!]
[!VAR "MCAN1StdFilterCnt" = "0"!] [!VAR "MCAN1ExtdFilterCnt" = "0"!]
[!VAR "MCAN2StdFilterCnt" = "0"!] [!VAR "MCAN2ExtdFilterCnt" = "0"!]
[!VAR "MCAN3StdFilterCnt" = "0"!] [!VAR "MCAN3ExtdFilterCnt" = "0"!]

[!LOOP "as:modconf('Can')[1]/CanConfigSet"!]
[!LOOP "CanHardwareObject/*"!]
static Can_MailboxType
    [!"../../@name"!]_[!"@name"!] =
{
    [!WS "4"!][!IF "CanHandleType='FULL'"!]0U[!ELSE!]1U[!ENDIF!],  /*  CanHandleType 0=Full, 1=Basic */
    [!WS "4"!][!IF "CanIdType = 'EXTENDED'"!]1U[!ELSEIF "CanIdType = 'STANDARD'"!]0U[!ELSE!]2U[!ENDIF!],  /* CanIdType 0=standard 1=Extended 2=Mixed*/[!CR!]
    [!IF "'MCAN0' = node:value(node:ref(node:current()/CanControllerRef)/CanControllerInstance)"!][!//
    [!IF "CanObjectType = 'TRANSMIT'"!][!//
    [!VAR "MCAN0TxCnt" = "node:value(CanHwObjectCount) + $MCAN0TxCnt"!][!//
    [!"num:i($MCANTxCnt)"!]U,  /* HwHandle i.e Mailbox - Hw object in the controller */
    [!VAR "MCANTxCnt" = "$MCANTxCnt + 1"!][!//
    [!IF "num:i($MCAN0TxCnt) > '32'"!][!ERROR "Number of Transmit mailboxes supported is 32 only"!][!ENDIF!][!//
    [!ELSEIF "node:value(CanHwObjectCount) = '1'"!][!//
    [!"num:i($MCAN0RxCnt)"!]U,  /* HwHandle i.e Mailbox - Hw object in the controller */
    [!VAR "MCAN0RxCnt" = "$MCAN0RxCnt+1"!][!//
    [!IF "(num:i($MCAN0RxCnt)) > '64'"!][!ERROR "Number of Receive mailboxes supported is 64 only"!][!ENDIF!][!//
    [!ELSE!][!//
    [!VAR "MCAN0RxFifoCnt" = "$MCAN0RxFifoCnt + node:value(CanHwObjectCount)"!][!//
    [!IF "(num:i($MCAN0RxFifoCnt)) > '64'"!][!ERROR "Number of Receive FiFo mailboxes supported is 64 only"!][!ENDIF!][!//
    0U,  /* HwHandle i.e Mailbox - Hw object in the controller */
    [!ENDIF!][!//
    [!ENDIF!][!//
    [!IF "'MCAN1' = node:value(node:ref(node:current()/CanControllerRef)/CanControllerInstance)"!][!//
    [!IF "CanObjectType = 'TRANSMIT'"!][!//
    [!VAR "MCAN1TxCnt" = "node:value(CanHwObjectCount) + $MCAN1TxCnt"!][!//
    [!"num:i($MCANTxCnt)"!]U,  /* HwHandle i.e Mailbox - Hw object in the controller */
    [!VAR "MCANTxCnt" = "$MCANTxCnt + 1"!][!//
    [!IF "num:i($MCAN1TxCnt) > '32'"!][!ERROR "Number of Transmit mailboxes supported is 32 only"!][!ENDIF!][!//
    [!ELSEIF "node:value(CanHwObjectCount) = '1'"!][!//
    [!"num:i($MCAN1RxCnt)"!]U,  /* HwHandle i.e Mailbox - Hw object in the controller */
    [!VAR "MCAN1RxCnt" = "$MCAN1RxCnt+1"!][!//
    [!IF "(num:i($MCAN1RxCnt)) > '64'"!][!ERROR "Number of Receive mailboxes supported is 64 only"!][!ENDIF!][!//
    [!ELSE!][!//
    [!VAR "MCAN1RxFifoCnt" = "$MCAN1RxFifoCnt + node:value(CanHwObjectCount)"!][!//
    [!IF "(num:i($MCAN1RxFifoCnt)) > '64'"!][!ERROR "Number of Receive FiFo mailboxes supported is 64 only"!][!ENDIF!][!//
    0U,  /* HwHandle i.e Mailbox - Hw object in the controller */
    [!ENDIF!][!//
    [!ENDIF!][!//
    [!IF "'MCAN2' = node:value(node:ref(node:current()/CanControllerRef)/CanControllerInstance)"!][!//
    [!IF "CanObjectType = 'TRANSMIT'"!][!//
    [!VAR "MCAN2TxCnt" = "node:value(CanHwObjectCount) + $MCAN2TxCnt"!][!//
    [!"num:i($MCANTxCnt)"!]U,  /* HwHandle i.e Mailbox - Hw object in the controller */
    [!VAR "MCANTxCnt" = "$MCANTxCnt + 1"!][!//
    [!IF "num:i($MCAN2TxCnt) > '32'"!][!ERROR "Number of Transmit mailboxes supported is 32 only"!][!ENDIF!][!//
    [!ELSEIF "node:value(CanHwObjectCount) = '1'"!][!//
    [!"num:i($MCAN2RxCnt)"!]U,  /* HwHandle i.e Mailbox - Hw object in the controller */
    [!VAR "MCAN2RxCnt" = "$MCAN2RxCnt+1"!][!//
    [!IF "(num:i($MCAN2RxCnt)) > '64'"!][!ERROR "Number of Receive mailboxes supported is 64 only"!][!ENDIF!][!//
    [!ELSE!][!//
    [!VAR "MCAN2RxFifoCnt" = "$MCAN2RxFifoCnt + node:value(CanHwObjectCount)"!][!//
    [!IF "(num:i($MCAN2RxFifoCnt)) > '64'"!][!ERROR "Number of Receive FiFo mailboxes supported is 64 only"!][!ENDIF!][!//
    0U,  /* HwHandle i.e Mailbox - Hw object in the controller */
    [!ENDIF!][!//
    [!ENDIF!][!//
    [!IF "'MCAN3' = node:value(node:ref(node:current()/CanControllerRef)/CanControllerInstance)"!][!//
    [!IF "CanObjectType = 'TRANSMIT'"!][!//
    [!VAR "MCAN3TxCnt" = "node:value(CanHwObjectCount) + $MCAN3TxCnt"!][!//
    [!"num:i($MCANTxCnt)"!]U,  /* HwHandle i.e Mailbox - Hw object in the controller */
    [!VAR "MCANTxCnt" = "$MCANTxCnt + 1"!][!//
    [!IF "num:i($MCAN3TxCnt) > '32'"!][!ERROR "Number of Transmit mailboxes supported is 32 only"!][!ENDIF!][!//
    [!ELSEIF "node:value(CanHwObjectCount) = '1'"!][!//
    [!"num:i($MCAN3RxCnt)"!]U,  /* HwHandle i.e Mailbox - Hw object in the controller */
    [!VAR "MCAN3RxCnt" = "$MCAN3RxCnt+1"!][!//
    [!IF "(num:i($MCAN3RxCnt)) > '64'"!][!ERROR "Number of Receive mailboxes supported is 64 only"!][!ENDIF!][!//
    [!ELSE!][!//
    [!VAR "MCAN3RxFifoCnt" = "$MCAN3RxFifoCnt + node:value(CanHwObjectCount)"!][!//
    [!IF "(num:i($MCAN3RxFifoCnt)) > '64'"!][!ERROR "Number of Receive FiFo mailboxes supported is 64 only"!][!ENDIF!][!//
    0U,  /* HwHandle i.e Mailbox - Hw object in the controller */
    [!ENDIF!][!//
    [!ENDIF!][!//
    [!WS "4"!][!IF "node:exists(CanHwObjectCount)"!][!"node:value(CanHwObjectCount)"!]U[!ELSE!]1U[!ENDIF!],   /* Length of the Mailbox */
    [!IF "node:value(CanHwObjectCount) = '0' "!][!ERROR "Hw Object count cannot be 0.Minimum value should be 1"!][!ENDIF!]
    [!WS "4"!][!IF "CanObjectType = 'TRANSMIT'"!]CAN_MAILBOX_DIRECTION_TX[!ELSE!]CAN_MAILBOX_DIRECTION_RX[!ENDIF!],  /* CanObjectType - Direction of Mailbox*/
    [!VAR "cntName" = "node:name(node:ref(node:current()/CanControllerRef))"!][!//
    &[!"../../@name"!]_PC_[!"$cntName"!],  /* Controller */[!//
    [!IF "CanObjectType = 'RECEIVE'"!][!CR!]
    [!WS "4"!][!"../../@name"!]_[!"@name"!]_HwFilterConfigList,  /* List of HW Filter structs */
    [!WS "4"!][!VAR "varHwFilterCnt" = "0"!][!LOOP "CanHwFilter/*"!][!VAR "varHwFilterCnt" = "$varHwFilterCnt+1"!][!ENDLOOP!][!"num:i($varHwFilterCnt)"!]U, /* Hw Filter Count */
    [!ELSE!][!CR!]
    [!WS "4"!]NULL_PTR,  /* List of HW Filter structs */
    [!WS "4"!]0U,   /* Hw Filter Count */
    [!ENDIF!]
    [!"CanFdPaddingValue/*"!]U,   /* Padding value for CAN FD message */
    [!IF "node:empty(CanFdPaddingValue/*) = 'true'"!][!ERROR "CanFdPaddingValue is not configured"!][!ENDIF!][!//
    [!IF "'MIXED' = node:value(node:ref(node:current()/CanControllerRef)/CanTxProcessing) or 'MIXED' = node:value(node:ref(node:current()/CanControllerRef)/CanRxProcessing)"!]
    (boolean)[!IF "CanHardwareObjectUsesPolling/* = 'true'"!]TRUE[!ELSE!]FALSE[!ENDIF!],  /* CanHardwareObjectUsesPolling */
    [!IF "node:empty(CanHardwareObjectUsesPolling/*) = 'true'"!][!ERROR "CanHardwareObjectUsesPolling is not configured"!][!ENDIF!][!//
    [!ELSE!]
    (boolean)FALSE,   /* CanHardwareObjectUsesPolling */
    [!ENDIF!]
    [!IF "CanObjectType = 'TRANSMIT'"!]
    (boolean)[!IF "CanTriggerTransmitEnable/* = 'true'"!]TRUE[!ELSE!]FALSE[!ENDIF!],  /* CanTriggerTransmitEnable */
    [!IF "node:empty(CanTriggerTransmitEnable/*) = 'true'"!][!ERROR "CanTriggerTransmitEnable is not configured"!][!ENDIF!][!//
    [!ELSE!]
	[!IF "CanTriggerTransmitEnable/* = 'true'"!][!ERROR "CanTriggerTransmitEnable should be configured as False in Receive"!][!ENDIF!][!//
    (boolean)FALSE,   /* CanTriggerTransmitEnable */
    [!ENDIF!]
};
    [!VAR "HwFilterCnt" = "0"!][!LOOP "CanHwFilter/*"!][!VAR "HwFilterCnt" = "$HwFilterCnt+1"!][!ENDLOOP!]
    [!IF "'MCAN0' = node:value(node:ref(node:current()/CanControllerRef)/CanControllerInstance)"!]
    [!IF "CanIdType = 'EXTENDED' and CanObjectType = 'RECEIVE'"!]
    [!VAR "MCAN0ExtdFilterCnt" = "num:i($HwFilterCnt) + num:i($MCAN0ExtdFilterCnt)"!]
    [!ELSEIF "CanIdType = 'STANDARD' and CanObjectType = 'RECEIVE'"!]
    [!VAR "MCAN0StdFilterCnt" = "num:i($HwFilterCnt) + num:i($MCAN0StdFilterCnt)"!]
    [!ELSEIF "CanIdType = 'MIXED' and CanObjectType = 'RECEIVE'"!]
    [!VAR "MCAN0StdFilterCnt" = "num:i($HwFilterCnt) + num:i($MCAN0StdFilterCnt)"!]
    [!VAR "MCAN0ExtdFilterCnt" = "num:i($HwFilterCnt) + num:i($MCAN0ExtdFilterCnt)"!]
    [!ENDIF!]
    [!IF "(num:i($MCAN0StdFilterCnt)) > '128'"!][!ERROR "Number of Standard ID Filter elements supported is 128 only"!][!ENDIF!]
    [!IF "(num:i($MCAN0ExtdFilterCnt)) > '64'"!][!ERROR "Number of Extended ID Filter elements supported is 64 only"!][!ENDIF!]
    [!ELSEIF "'MCAN1' = node:value(node:ref(node:current()/CanControllerRef)/CanControllerInstance)"!]
    [!IF "CanIdType = 'EXTENDED' and CanObjectType = 'RECEIVE'"!]
    [!VAR "MCAN1ExtdFilterCnt" = "num:i($HwFilterCnt) + num:i($MCAN1ExtdFilterCnt)"!]
    [!ELSEIF "CanIdType = 'STANDARD' and CanObjectType = 'RECEIVE'"!]
    [!VAR "MCAN1StdFilterCnt" = "num:i($HwFilterCnt) + num:i($MCAN1StdFilterCnt)"!]
    [!ELSEIF "CanIdType = 'MIXED' and CanObjectType = 'RECEIVE'"!]
    [!VAR "MCAN1StdFilterCnt" = "num:i($HwFilterCnt) + num:i($MCAN1StdFilterCnt)"!]
    [!VAR "MCAN1ExtdFilterCnt" = "num:i($HwFilterCnt) + num:i($MCAN1ExtdFilterCnt)"!]
    [!ENDIF!]
    [!IF "(num:i($MCAN1StdFilterCnt)) > '128'"!][!ERROR "Number of Standard ID Filter elements supported is 128 only"!][!ENDIF!]
    [!IF "(num:i($MCAN1ExtdFilterCnt)) > '64'"!][!ERROR "Number of Extended ID Filter elements supported is 64 only"!][!ENDIF!]
    [!ELSEIF "'MCAN2' = node:value(node:ref(node:current()/CanControllerRef)/CanControllerInstance)"!]
    [!IF "CanIdType = 'EXTENDED' and CanObjectType = 'RECEIVE'"!]
    [!VAR "MCAN2ExtdFilterCnt" = "num:i($HwFilterCnt) + num:i($MCAN2ExtdFilterCnt)"!]
    [!ELSEIF "CanIdType = 'STANDARD' and CanObjectType = 'RECEIVE'"!]
    [!VAR "MCAN2StdFilterCnt" = "num:i($HwFilterCnt) + num:i($MCAN2StdFilterCnt)"!]
    [!ELSEIF "CanIdType = 'MIXED' and CanObjectType = 'RECEIVE'"!]
    [!VAR "MCAN2StdFilterCnt" = "num:i($HwFilterCnt) + num:i($MCAN2StdFilterCnt)"!]
    [!VAR "MCAN2ExtdFilterCnt" = "num:i($HwFilterCnt) + num:i($MCAN2ExtdFilterCnt)"!]
    [!ENDIF!]
    [!IF "(num:i($MCAN2StdFilterCnt)) > '128'"!][!ERROR "Number of Standard ID Filter elements supported is 128 only"!][!ENDIF!]
    [!IF "(num:i($MCAN2ExtdFilterCnt)) > '64'"!][!ERROR "Number of Extended ID Filter elements supported is 64 only"!][!ENDIF!]
    [!ELSEIF "'MCAN3' = node:value(node:ref(node:current()/CanControllerRef)/CanControllerInstance)"!]
    [!IF "CanIdType = 'EXTENDED' and CanObjectType = 'RECEIVE'"!]
    [!VAR "MCAN3ExtdFilterCnt" = "num:i($HwFilterCnt) + num:i($MCAN3ExtdFilterCnt)"!]
    [!ELSEIF "CanIdType = 'STANDARD' and CanObjectType = 'RECEIVE'"!]
    [!VAR "MCAN3StdFilterCnt" = "num:i($HwFilterCnt) + num:i($MCAN3StdFilterCnt)"!]
    [!ELSEIF "CanIdType = 'MIXED' and CanObjectType = 'RECEIVE'"!]
    [!VAR "MCAN3StdFilterCnt" = "num:i($HwFilterCnt) + num:i($MCAN3StdFilterCnt)"!]
    [!VAR "MCAN3ExtdFilterCnt" = "num:i($HwFilterCnt) + num:i($MCAN3ExtdFilterCnt)"!]
    [!ENDIF!]
    [!IF "(num:i($MCAN3StdFilterCnt)) > '128'"!][!ERROR "Number of Standard ID Filter elements supported is 128 only"!][!ENDIF!]
    [!IF "(num:i($MCAN3ExtdFilterCnt)) > '64'"!][!ERROR "Number of Extended ID Filter elements supported is 64 only"!][!ENDIF!]
    [!ENDIF!]

[!ENDLOOP!][!ENDLOOP!]
[!ENDIF!][!//

[!IF "(as:modconf('Can')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPreCompile') or (as:modconf('Can')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPostBuild')"!]
/* All the Mailbox objects(MB's) will be defined here for all config sets */
[!LOOP "as:modconf('Can')[1]/CanConfigSet"!]
[!LOOP "CanHardwareObject/*"!]
static const struct Can_MailboxStruct_PC
    [!"../../@name"!]_PC_[!"@name"!] =
{
    CanConf_CanHardwareObject_[!"@name"!],  /* CanObjectId - Holds handle Id */
};
[!ENDLOOP!][!ENDLOOP!]
[!ENDIF!][!//

[!IF "(as:modconf('Can')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPreCompile')"!]
/* List of the Mailboxes */
[!LOOP "as:modconf('Can')[1]/CanConfigSet"!]
static Can_MailboxType
    *[!"@name"!]_CanHardwareObject_List[] =
{
    [!LOOP "CanHardwareObject/*"!]
    [!WS "4"!]&[!"../../@name"!]_[!"@name"!],
    [!ENDLOOP!]
};
[!ENDLOOP!]
[!ENDIF!][!//

[!IF "(as:modconf('Can')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPreCompile') or (as:modconf('Can')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPostBuild')"!]
/* List of the Mailboxes */
[!LOOP "as:modconf('Can')[1]/CanConfigSet"!]
const struct Can_MailboxStruct_PC
    *[!"@name"!]_CanHardwareObject_List_PC[CAN_NUM_MAILBOXES] =
{
    [!LOOP "CanHardwareObject/*"!]
    [!WS "4"!]&[!"../../@name"!]_PC_[!"@name"!],
    [!ENDLOOP!]
};
[!ENDLOOP!]
[!ENDIF!][!//

[!IF "(as:modconf('Can')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPreCompile')"!]
/*Can Config struct */
[!LOOP "as:modconf('Can')[1]/CanConfigSet"!]
const struct Can_ConfigType_s [!"@name"!] =
{
    [!"@name"!]_CanController_List, /* Controller List Pointer */
    [!WS "4"!][!VAR "maxController" = "0"!][!LOOP "./CanController/*"!][!VAR "maxController" = "$maxController+1"!][!ENDLOOP!]([!"num:i($maxController)"!]U),  /* max Controllers */
    [!"@name"!]_CanHardwareObject_List, /* Mailbox List Pointer */
    [!WS "4"!][!VAR "varmax" = "0"!][!LOOP "./CanHardwareObject/*"!][!VAR "varmax" = "$varmax+1"!][!ENDLOOP!]([!"num:i($varmax)"!]U),/* total number of mail boxes in this configset */
    .MaxBaudConfigID =
    {
        [!LOOP "./CanController/*"!][!//
        [[!"@index"!]] = [!"num:i(num:sub(num:i(count(CanControllerBaudrateConfig/*)),1))"!]U[!//
            [!IF "not(node:islast())"!],[!ENDIF!][!CR!][!//
        [!ENDLOOP!][!//
    }, /* Baud rate structure id */
};
[!ENDLOOP!]
[!ENDIF!][!//

#define  CAN_STOP_SEC_CONFIG_DATA
#include "Can_MemMap.h"

[!ENDIF!][!//
/*******************************************************************************
 *  End of File: Can_Cfg.c
 ******************************************************************************/
