/* ======================================================================
 *   Copyright (C) 2023 Texas Instruments Incorporated
 *
 *   All rights reserved. Property of Texas Instruments Incorporated.
 *   Restricted rights to use, duplicate or disclose this code are
 *   granted through contract.
 *
 *   The program may not be used without the written permission
 *   of Texas Instruments Incorporated or against the terms and conditions
 *   stipulated in the agreement under which this program has been
 *   supplied.
 * ==================================================================== */
/**
 *  \file     Cdd_Uart_PBcfg.c
 *
 *  \brief    This file contains generated post build configuration file
 *            for UART Complex Device Driver
 */

  /*********************************************************************************************************************
  Project: Mcal_Demo_Cfg


    This file is generated by EB Tresos
    Do not modify this file, otherwise the software may behave in unexpected way.

 *********************************************************************************************************************/

/* The last generated configuration variant is not POST-BUILD variant. Please look for other variants */


/**********************************************************************************************************************
 *  END OF FILE: Cdd_Uart_PBcfg.c
 *********************************************************************************************************************/
