/*
 * TEXAS INSTRUMENTS TEXT FILE LICENSE
 *
 * Copyright (c) 2025 Texas Instruments Incorporated
 *
 * All rights reserved not granted herein.
 *
 * Limited License.
 *
 * Texas Instruments Incorporated grants a world-wide, royalty-free, non-exclusive
 * license under copyrights and patents it now or hereafter owns or controls to
 * make, have made, use, import, offer to sell and sell ("Utilize") this software
 * subject to the terms herein. With respect to the foregoing patent license,
 * such license is granted solely to the extent that any such patent is necessary
 * to Utilize the software alone. The patent license shall not apply to any
 * combinations which include this software, other than combinations with devices
 * manufactured by or for TI ("TI Devices"). No hardware patent is licensed hereunder.
 *
 * Redistributions must preserve existing copyright notices and reproduce this license
 * (including the above copyright notice and the disclaimer and (if applicable) source
 * code license limitations below) in the documentation and/or other materials provided
 * with the distribution.
 *
 * Redistribution and use in binary form, without modification, are permitted provided
 * that the following conditions are met:
 * No reverse engineering, decompilation, or disassembly of this software is
 * permitted with respect to any software provided in binary form.
 * Any redistribution and use are licensed by TI for use only with TI Devices.
 * Nothing shall obligate TI to provide you with source code for the software
 * licensed and provided to you in object code.
 *
 * If software source code is provided to you, modification and redistribution of the
 * source code are permitted provided that the following conditions are met:
 * Any redistribution and use of the source code, including any resulting derivative
 * works, are licensed by TI for use only with TI Devices.
 * Any redistribution and use of any object code compiled from the source code
 * and any resulting derivative works, are licensed by TI for use only with TI Devices.
 *
 * Neither the name of Texas Instruments Incorporated nor the names of its suppliers
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * DISCLAIMER.
 *
 * THIS SOFTWARE IS PROVIDED BY TI AND TI'S LICENSORS "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL TI AND TI'S
 * LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/******************************************************************************
    Project         : Mcal_Demo_Cfg
    SW Ver          : 11.0.2
    Module Rele Ver : AUTOSAR 4.3.1 0

    This file is generated by EB Tresos
    Do not modify this file,otherwise the software may behave in unexpected way.
******************************************************************************/

/**
 *  \file     Cdd_I2c_Cfg.h
 *
 *  \brief    This file contains pre compile configurations for the I2C MCAL
 */

/**
 *  \addtogroup CDD_I2C I2C Configuration Header file
 *
 *  This files defines I2C configuration structures
 *  @{
 */

#ifndef CDD_I2C_CFG_H_
#define CDD_I2C_CFG_H_

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */

#include "Std_Types.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ========================================================================== */
/*                           Macros & Typedefs                                */
/* ========================================================================== */

/**
 *  \name I2C Driver Configuration SW Version Info
 *
 *  Defines for I2C Driver configuration version
 *  @{
 */
/** \brief I2C configuration Major Version */
#define CDD_I2C_CFG_MAJOR_VERSION       (11U)
/** \brief I2C configuration Minor Version */
#define CDD_I2C_CFG_MINOR_VERSION       (0U)
/** \brief I2C configuration Patch Version */
#define CDD_I2C_CFG_PATCH_VERSION       (2U)
/** @} */

/**
 *  \brief I2C Build Variant.
 *   Build variants.(i.e Pre Compile and Post Build)
 */
#define CDD_I2C_PRE_COMPILE_VARIANT     (STD_ON)
/** \brief Precompile variant macro */
#define CDD_I2C_CONFIG_PC               Cdd_I2c_Config


/** \brief Enable/disable Interrupts */
#define CDD_I2C_POLLING_MODE            (STD_OFF)

/** \brief Enable/Disable I2C dev detect error */
#define CDD_I2C_DEV_ERROR_DETECT        (STD_ON)

/** \brief Version info API macro */
#define CDD_I2C_VERSION_INFO_API        (STD_ON)

/** \brief Check to enable cancel API */
#define CDD_I2C_CANCEL_API              (STD_ON)

/** \brief Check to enable get driver status API */
#define CDD_I2C_GET_STATUS_API          (STD_ON)

/** \brief Check to readback register API */
#define CDD_I2C_REGISTER_READBACK_API   (STD_ON)

/**
 *  \name I2C HW Unit ID
 *
 *  Specifies the HW identification (ID) for I2C
 *  @{
 */
/** \brief HW unit 0 */
#define CDD_I2C_HW_UNIT_0               ((Cdd_I2c_HwUnitType)0U)
/** \brief HW unit 1 */
#define CDD_I2C_HW_UNIT_1               ((Cdd_I2c_HwUnitType)1U)
/** \brief HW unit 2 */
#define CDD_I2C_HW_UNIT_2               ((Cdd_I2c_HwUnitType)2U)
/** \brief HW unit 3 */
#define CDD_I2C_HW_UNIT_3               ((Cdd_I2c_HwUnitType)3U)
/** @} */
/** \brief Maximum supported HW units for the SOC */
#define CDD_I2C_HW_UNIT_MAX             (4U)


/** \brief ISR type */
#define CDD_I2C_ISR_TYPE                (CDD_I2C_ISR_CAT1)


/*
 * All below macros are used for static memory allocation and can be changed to
 * match the usecase requirements.
 */
/** \brief Maximum channels allowed per sequence */
#define CDD_I2C_MAX_CH_PER_SEQ          (2U)

/** \brief Maximum channels across all sequence/hwunit */
#define CDD_I2C_MAX_CH                  (24U)

/** \brief Maximum sequence across all hwunit */
#define CDD_I2C_MAX_SEQ                 (16U)

/** \brief Maximum HW unit */
#define CDD_I2C_MAX_HW_UNIT             (4U)

/*
 * All below macros are used for enabling a particular hardware.
 */
#define CDD_I2C_HW_UNIT_0_ACTIVE
#define CDD_I2C_HW_UNIT_1_ACTIVE
#define CDD_I2C_HW_UNIT_2_ACTIVE
#define CDD_I2C_HW_UNIT_3_ACTIVE

/** \brief Symbolic Name for I2c Sequence 0 */
#define CddI2cConf_CddI2cSequence_CddI2cSequence_0      (0U)
/** \brief Symbolic Name for I2c Sequence 1 */
#define CddI2cConf_CddI2cSequence_CddI2cSequence_1      (1U)
/** \brief Symbolic Name for I2c Sequence 2 */
#define CddI2cConf_CddI2cSequence_CddI2cSequence_2      (2U)
/** \brief Symbolic Name for I2c Sequence 3 */
#define CddI2cConf_CddI2cSequence_CddI2cSequence_3      (3U)
/** \brief Symbolic Name for I2c Sequence 4 */
#define CddI2cConf_CddI2cSequence_CddI2cSequence_4      (4U)
/** \brief Symbolic Name for I2c Sequence 5 */
#define CddI2cConf_CddI2cSequence_CddI2cSequence_5      (5U)
/** \brief Symbolic Name for I2c Sequence 6 */
#define CddI2cConf_CddI2cSequence_CddI2cSequence_6      (6U)
/** \brief Symbolic Name for I2c Sequence 7 */
#define CddI2cConf_CddI2cSequence_CddI2cSequence_7      (7U)
/** \brief Symbolic Name for I2c Sequence 8 */
#define CddI2cConf_CddI2cSequence_CddI2cSequence_8      (8U)
/** \brief Symbolic Name for I2c Sequence 9 */
#define CddI2cConf_CddI2cSequence_CddI2cSequence_9      (9U)
/** \brief Symbolic Name for I2c Sequence 10 */
#define CddI2cConf_CddI2cSequence_CddI2cSequence_10      (10U)
/** \brief Symbolic Name for I2c Sequence 11 */
#define CddI2cConf_CddI2cSequence_CddI2cSequence_11      (11U)
/** \brief Symbolic Name for I2c Sequence 12 */
#define CddI2cConf_CddI2cSequence_CddI2cSequence_12      (12U)
/** \brief Symbolic Name for I2c Sequence 13 */
#define CddI2cConf_CddI2cSequence_CddI2cSequence_13      (13U)
/** \brief Symbolic Name for I2c Sequence 14 */
#define CddI2cConf_CddI2cSequence_CddI2cSequence_14      (14U)
/** \brief Symbolic Name for I2c Sequence 15 */
#define CddI2cConf_CddI2cSequence_CddI2cSequence_15      (15U)

/** \brief Symbolic Name for I2c Channel 0 */
#define CddI2cConf_CddI2cChannel_CddI2cChannel_0        (0U)
/** \brief Symbolic Name for I2c Channel 1 */
#define CddI2cConf_CddI2cChannel_CddI2cChannel_1        (1U)
/** \brief Symbolic Name for I2c Channel 2 */
#define CddI2cConf_CddI2cChannel_CddI2cChannel_2        (2U)
/** \brief Symbolic Name for I2c Channel 3 */
#define CddI2cConf_CddI2cChannel_CddI2cChannel_3        (3U)
/** \brief Symbolic Name for I2c Channel 4 */
#define CddI2cConf_CddI2cChannel_CddI2cChannel_4        (4U)
/** \brief Symbolic Name for I2c Channel 5 */
#define CddI2cConf_CddI2cChannel_CddI2cChannel_5        (5U)
/** \brief Symbolic Name for I2c Channel 6 */
#define CddI2cConf_CddI2cChannel_CddI2cChannel_6        (6U)
/** \brief Symbolic Name for I2c Channel 7 */
#define CddI2cConf_CddI2cChannel_CddI2cChannel_7        (7U)
/** \brief Symbolic Name for I2c Channel 8 */
#define CddI2cConf_CddI2cChannel_CddI2cChannel_8        (8U)
/** \brief Symbolic Name for I2c Channel 9 */
#define CddI2cConf_CddI2cChannel_CddI2cChannel_9        (9U)
/** \brief Symbolic Name for I2c Channel 10 */
#define CddI2cConf_CddI2cChannel_CddI2cChannel_10        (10U)
/** \brief Symbolic Name for I2c Channel 11 */
#define CddI2cConf_CddI2cChannel_CddI2cChannel_11        (11U)
/** \brief Symbolic Name for I2c Channel 12 */
#define CddI2cConf_CddI2cChannel_CddI2cChannel_12        (12U)
/** \brief Symbolic Name for I2c Channel 13 */
#define CddI2cConf_CddI2cChannel_CddI2cChannel_13        (13U)
/** \brief Symbolic Name for I2c Channel 14 */
#define CddI2cConf_CddI2cChannel_CddI2cChannel_14        (14U)
/** \brief Symbolic Name for I2c Channel 15 */
#define CddI2cConf_CddI2cChannel_CddI2cChannel_15        (15U)
/** \brief Symbolic Name for I2c Channel 16 */
#define CddI2cConf_CddI2cChannel_CddI2cChannel_16        (16U)
/** \brief Symbolic Name for I2c Channel 17 */
#define CddI2cConf_CddI2cChannel_CddI2cChannel_17        (17U)
/** \brief Symbolic Name for I2c Channel 18 */
#define CddI2cConf_CddI2cChannel_CddI2cChannel_18        (18U)
/** \brief Symbolic Name for I2c Channel 19 */
#define CddI2cConf_CddI2cChannel_CddI2cChannel_19        (19U)
/** \brief Symbolic Name for I2c Channel 20 */
#define CddI2cConf_CddI2cChannel_CddI2cChannel_20        (20U)
/** \brief Symbolic Name for I2c Channel 21 */
#define CddI2cConf_CddI2cChannel_CddI2cChannel_21        (21U)
/** \brief Symbolic Name for I2c Channel 22 */
#define CddI2cConf_CddI2cChannel_CddI2cChannel_22        (22U)
/** \brief Symbolic Name for I2c Channel 23 */
#define CddI2cConf_CddI2cChannel_CddI2cChannel_23        (23U)

/* ========================================================================== */
/*                         Structures and Enums                               */
/* ========================================================================== */

/* None */

/* ========================================================================== */
/*                      Exported Object Declarations                          */
/* ========================================================================== */

extern CONST(struct Cdd_I2c_ConfigTag, CDD_I2C_CONFIG_DATA) Cdd_I2c_Config;
extern CONST(uint32, CDD_I2C_CONST) Cdd_I2c_HwUnitBaseAddr[CDD_I2C_HW_UNIT_MAX];

/* ========================================================================== */
/*                          Function Declarations                             */
/* ========================================================================== */

extern void I2c_utilsSeq0Complete(void);
extern void I2c_utilsSeq1Complete(void);
extern void I2c_utilsSeq2Complete(void);
extern void I2c_utilsSeq3Complete(void);
extern void I2c_utilsSeq4Complete(void);
extern void I2c_utilsSeq5Complete(void);
extern void I2c_utilsSeq6Complete(void);
extern void I2c_utilsSeq7Complete(void);
extern void I2c_utilsSeq8Complete(void);
extern void I2c_utilsSeq9Complete(void);
extern void I2c_utilsSeq10Complete(void);
extern void I2c_utilsSeq11Complete(void);
extern void I2c_utilsSeq12Complete(void);
extern void I2c_utilsSeq13Complete(void);
extern void I2c_utilsSeq14Complete(void);
extern void I2c_utilsSeq15Complete(void);

extern void I2c_utilsSeq0Fail(uint8 errorCode);
extern void I2c_utilsSeq1Fail(uint8 errorCode);
extern void I2c_utilsSeq2Fail(uint8 errorCode);
extern void I2c_utilsSeq3Fail(uint8 errorCode);
extern void I2c_utilsSeq4Fail(uint8 errorCode);
extern void I2c_utilsSeq5Fail(uint8 errorCode);
extern void I2c_utilsSeq6Fail(uint8 errorCode);
extern void I2c_utilsSeq7Fail(uint8 errorCode);
extern void I2c_utilsSeq8Fail(uint8 errorCode);
extern void I2c_utilsSeq9Fail(uint8 errorCode);
extern void I2c_utilsSeq10Fail(uint8 errorCode);
extern void I2c_utilsSeq11Fail(uint8 errorCode);
extern void I2c_utilsSeq12Fail(uint8 errorCode);
extern void I2c_utilsSeq13Fail(uint8 errorCode);
extern void I2c_utilsSeq14Fail(uint8 errorCode);
extern void I2c_utilsSeq15Fail(uint8 errorCode);

#ifdef __cplusplus
}
#endif

#endif  /* #ifndef I2C_CFG_H_ */

/** @} */
