/* ======================================================================
 *   Copyright (c) 2022-2023 Texas Instruments Incorporated
 *
 *   All rights reserved. Property of Texas Instruments Incorporated.
 *   Restricted rights to use, duplicate or disclose this code are
 *   granted through contract.
 *
 *   The program may not be used without the written permission
 *   of Texas Instruments Incorporated or against the terms and conditions
 *   stipulated in the agreement under which this program has been
 *   supplied.
 * ==================================================================== */
/***********************************************************************
    Project: Dio_am273x
	Date   : 2024-01-25 00:46:18

    This file is generated by EB Tresos
    Do not modify this file, otherwise the software may behave in 
	unexpected way.

 ***********************************************************************/
/**
 *  \file     Dio_Cfg.h
 *
 *  \brief    This file contains generated pre compile configuration file
 *            for DIO MCAL driver
 *
 */

/**
 *  \defgroup MCAL_DIO_CFG DIO Configuration
 *
 *  This files defines DIO MCAL configuration structures
 *  @{
 */

#ifndef DIO_CFG_H_
#define DIO_CFG_H_

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */

#include "Dem.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ========================================================================== */
/*                           Macros & Typedefs                                */
/* ========================================================================== */
/** \brief DIO Config ID */
#define DIO_CFG_ID                      (0x1U)

/**
 *  \name Dio Driver Configuration SW Version Info
 *
 *  Defines for Dio Driver configuration version
 *  @{
 */
/** \brief Dio configuration Major Version */
#define DIO_CFG_MAJOR_VERSION           (10U)
/** \brief Dio configuration Minor Version */
#define DIO_CFG_MINOR_VERSION    (1U)
/** \brief Dio configuration Patch Version */
#define DIO_CFG_PATCH_VERSION           (0U)
/* @} */

/** \brief DIO Driver Instance ID */
#define DIO_INSTANCE_ID                 ((uint8) 0U)

/**
 *  \name GPIO register identifiers
 *
 *  Defines mapping to physical GPIO registers
 *  @{
 */
/** \brief GPIO REG0 identifier */
#define DIO_GPIO_REG_0                 (0U)
/** \brief GPIO REG1 identifier */
#define DIO_GPIO_REG_1                 (1U)
/** \brief GPIO REG2 identifier */
#define DIO_GPIO_REG_2                 (2U)
/** \brief GPIO REG3 identifier */
#define DIO_GPIO_REG_3                 (3U)
/** \brief GPIO REG4 identifier */
#define DIO_GPIO_REG_4                 (4U)
/** \brief GPIO REG5 identifier */
#define DIO_GPIO_REG_5                 (5U)
/** \brief GPIO REG6 identifier */
#define DIO_GPIO_REG_6                 (6U)
/** \brief GPIO REG7 identifier */
#define DIO_GPIO_REG_7                 (7U)
/* @} */

/* Requirements : SWS_Dio_00103 */
/** \brief Width of GPIO register in this platform */
#define DIO_PORT_WIDTH                 (8U)

/**
 *  \name DIO service enable/diable defines
 *
 *  Pre-compile switches for enabling/disabling DIO MCAL APIs
 *  @{
 */
/** \brief Enable/Disable DEV error detection */
#define DIO_DEV_ERROR_DETECT            (STD_ON)

/** \brief Enable/Disable Dio_GetVersionInfo() */
#define DIO_VERSION_INFO_API            (STD_ON)

/** \brief Enable/Disable Dio_FlipChannel() */
#define DIO_FLIP_CHANNEL_API            (STD_ON)

/** \brief Enable/Disable Dio_RegisterReadback() */
#define DIO_REGISTER_READBACK_API            (STD_ON)
/* @} */

/* Requirements : SWS_Dio_00026, SWS_Dio_00113, SWS_Dio_00020 */
/**
 *  \name Symbolic name of DIO PORTs
 *
 *  This is symbolic name of DIO ports generated from configurator
 *  These defines map to physical GPIO register numbers.
 *  @{
 */
/** \brief Symbolic name for GPIO REG #0 */
#define DioConf_DioPort_GPIOA ((Dio_PortType)  DIO_GPIO_REG_0)

/** \brief Symbolic name for GPIO REG #1 */
#define DioConf_DioPort_GPIOB ((Dio_PortType)  DIO_GPIO_REG_1)

/** \brief Symbolic name for GPIO REG #2 */
#define DioConf_DioPort_GPIOC ((Dio_PortType)  DIO_GPIO_REG_2)

/** \brief Symbolic name for GPIO REG #3 */
#define DioConf_DioPort_GPIOD ((Dio_PortType)  DIO_GPIO_REG_3)

/** \brief Symbolic name for GPIO REG #4 */
#define DioConf_DioPort_GPIOE ((Dio_PortType)  DIO_GPIO_REG_4)

/** \brief Symbolic name for GPIO REG #5 */
#define DioConf_DioPort_GPIOF ((Dio_PortType)  DIO_GPIO_REG_5)

/** \brief Symbolic name for GPIO REG #6 */
#define DioConf_DioPort_GPIOG ((Dio_PortType)  DIO_GPIO_REG_6)

/** \brief Symbolic name for GPIO REG #7 */
#define DioConf_DioPort_GPIOH ((Dio_PortType)  DIO_GPIO_REG_7)

/* @} */

 /** \brief Max number of DIO ports */
#define DIO_ENABLED_PORT_MASK             (0U    | (1U << 0) | (1U << 1) | (1U << 2) | (1U << 3) | (1U << 4) | (1U << 5) | (1U << 6) | (1U << 7))


/** \brief Max number of DIO ports */
#define DIO_MAX_NO_OF_PORTS             8U

/* Requirements : SWS_Dio_00026, SWS_Dio_00113, SWS_Dio_00017 */
/**
 *  \name Symbolic name of DIO Channels
 *
 *  This is symbolic name of DIO channels generated from configurator
 *  These defines map to GPIO register channels
 *  The channel numbers are mapped as
 *  GPIO_REG_0: Channel 0  - Channel 7
 *  GPIO_REG_1: Channel 8 - Channel 15
 *  GPIO_REG_2: Channel 16 - Channel 23
 *  GPIO_REG_3: Channel 24 - Channel 31
 *  GPIO_REG_4: Channel 32  - Channel 39
 *  GPIO_REG_5: Channel 40  - Channel 47
 *  GPIO_REG_6: Channel 48  - Channel 55
 *  GPIO_REG_7: Channel 56  - Channel 63
 *  @{
 */
/** \brief Symbolic name for GPIO channel #0 GPIOA_Ch0 */
#define DioConf_DioChannel_GPIOA_Ch0 ((Dio_ChannelType) 0U)
/** \brief Symbolic name for GPIO channel #1 GPIOA_Ch1 */
#define DioConf_DioChannel_GPIOA_Ch1 ((Dio_ChannelType) 1U)
/** \brief Symbolic name for GPIO channel #2 GPIOA_Ch2 */
#define DioConf_DioChannel_GPIOA_Ch2 ((Dio_ChannelType) 2U)
/** \brief Symbolic name for GPIO channel #3 GPIOA_Ch3 */
#define DioConf_DioChannel_GPIOA_Ch3 ((Dio_ChannelType) 3U)
/** \brief Symbolic name for GPIO channel #4 GPIOA_Ch4 */
#define DioConf_DioChannel_GPIOA_Ch4 ((Dio_ChannelType) 4U)
/** \brief Symbolic name for GPIO channel #5 GPIOA_Ch5 */
#define DioConf_DioChannel_GPIOA_Ch5 ((Dio_ChannelType) 5U)
/** \brief Symbolic name for GPIO channel #6 GPIOA_Ch6 */
#define DioConf_DioChannel_GPIOA_Ch6 ((Dio_ChannelType) 6U)
/** \brief Symbolic name for GPIO channel #7 GPIOA_Ch7 */
#define DioConf_DioChannel_GPIOA_Ch7 ((Dio_ChannelType) 7U)
/** \brief Symbolic name for GPIO channel #8 GPIOB_Ch0 */
#define DioConf_DioChannel_GPIOB_Ch0 ((Dio_ChannelType) 8U)
/** \brief Symbolic name for GPIO channel #9 GPIOB_Ch1 */
#define DioConf_DioChannel_GPIOB_Ch1 ((Dio_ChannelType) 9U)
/** \brief Symbolic name for GPIO channel #10 GPIOB_Ch2 */
#define DioConf_DioChannel_GPIOB_Ch2 ((Dio_ChannelType) 10U)
/** \brief Symbolic name for GPIO channel #11 GPIOB_Ch3 */
#define DioConf_DioChannel_GPIOB_Ch3 ((Dio_ChannelType) 11U)
/** \brief Symbolic name for GPIO channel #12 GPIOB_Ch4 */
#define DioConf_DioChannel_GPIOB_Ch4 ((Dio_ChannelType) 12U)
/** \brief Symbolic name for GPIO channel #13 GPIOB_Ch5 */
#define DioConf_DioChannel_GPIOB_Ch5 ((Dio_ChannelType) 13U)
/** \brief Symbolic name for GPIO channel #14 GPIOB_Ch6 */
#define DioConf_DioChannel_GPIOB_Ch6 ((Dio_ChannelType) 14U)
/** \brief Symbolic name for GPIO channel #15 GPIOB_Ch7 */
#define DioConf_DioChannel_GPIOB_Ch7 ((Dio_ChannelType) 15U)
/** \brief Symbolic name for GPIO channel #16 GPIOC_Ch0 */
#define DioConf_DioChannel_GPIOC_Ch0 ((Dio_ChannelType) 16U)
/** \brief Symbolic name for GPIO channel #17 GPIOC_Ch1 */
#define DioConf_DioChannel_GPIOC_Ch1 ((Dio_ChannelType) 17U)
/** \brief Symbolic name for GPIO channel #18 GPIOC_Ch2 */
#define DioConf_DioChannel_GPIOC_Ch2 ((Dio_ChannelType) 18U)
/** \brief Symbolic name for GPIO channel #19 GPIOC_Ch3 */
#define DioConf_DioChannel_GPIOC_Ch3 ((Dio_ChannelType) 19U)
/** \brief Symbolic name for GPIO channel #20 GPIOC_Ch4 */
#define DioConf_DioChannel_GPIOC_Ch4 ((Dio_ChannelType) 20U)
/** \brief Symbolic name for GPIO channel #21 GPIOC_Ch5 */
#define DioConf_DioChannel_GPIOC_Ch5 ((Dio_ChannelType) 21U)
/** \brief Symbolic name for GPIO channel #22 GPIOC_Ch6 */
#define DioConf_DioChannel_GPIOC_Ch6 ((Dio_ChannelType) 22U)
/** \brief Symbolic name for GPIO channel #23 GPIOC_Ch7 */
#define DioConf_DioChannel_GPIOC_Ch7 ((Dio_ChannelType) 23U)
/** \brief Symbolic name for GPIO channel #24 GPIOD_Ch0 */
#define DioConf_DioChannel_GPIOD_Ch0 ((Dio_ChannelType) 24U)
/** \brief Symbolic name for GPIO channel #25 GPIOD_Ch1 */
#define DioConf_DioChannel_GPIOD_Ch1 ((Dio_ChannelType) 25U)
/** \brief Symbolic name for GPIO channel #26 GPIOD_Ch2 */
#define DioConf_DioChannel_GPIOD_Ch2 ((Dio_ChannelType) 26U)
/** \brief Symbolic name for GPIO channel #27 GPIOD_Ch3 */
#define DioConf_DioChannel_GPIOD_Ch3 ((Dio_ChannelType) 27U)
/** \brief Symbolic name for GPIO channel #28 GPIOD_Ch4 */
#define DioConf_DioChannel_GPIOD_Ch4 ((Dio_ChannelType) 28U)
/** \brief Symbolic name for GPIO channel #29 GPIOD_Ch5 */
#define DioConf_DioChannel_GPIOD_Ch5 ((Dio_ChannelType) 29U)
/** \brief Symbolic name for GPIO channel #30 GPIOD_Ch6 */
#define DioConf_DioChannel_GPIOD_Ch6 ((Dio_ChannelType) 30U)
/** \brief Symbolic name for GPIO channel #31 GPIOD_Ch7 */
#define DioConf_DioChannel_GPIOD_Ch7 ((Dio_ChannelType) 31U)
/** \brief Symbolic name for GPIO channel #32 GPIOE_Ch0 */
#define DioConf_DioChannel_GPIOE_Ch0 ((Dio_ChannelType) 32U)
/** \brief Symbolic name for GPIO channel #33 GPIOE_Ch1 */
#define DioConf_DioChannel_GPIOE_Ch1 ((Dio_ChannelType) 33U)
/** \brief Symbolic name for GPIO channel #34 GPIOE_Ch2 */
#define DioConf_DioChannel_GPIOE_Ch2 ((Dio_ChannelType) 34U)
/** \brief Symbolic name for GPIO channel #35 GPIOE_Ch3 */
#define DioConf_DioChannel_GPIOE_Ch3 ((Dio_ChannelType) 35U)
/** \brief Symbolic name for GPIO channel #36 GPIOE_Ch4 */
#define DioConf_DioChannel_GPIOE_Ch4 ((Dio_ChannelType) 36U)
/** \brief Symbolic name for GPIO channel #37 GPIOE_Ch5 */
#define DioConf_DioChannel_GPIOE_Ch5 ((Dio_ChannelType) 37U)
/** \brief Symbolic name for GPIO channel #38 GPIOE_Ch6 */
#define DioConf_DioChannel_GPIOE_Ch6 ((Dio_ChannelType) 38U)
/** \brief Symbolic name for GPIO channel #39 GPIOE_Ch7 */
#define DioConf_DioChannel_GPIOE_Ch7 ((Dio_ChannelType) 39U)
/** \brief Symbolic name for GPIO channel #40 GPIOF_Ch0 */
#define DioConf_DioChannel_GPIOF_Ch0 ((Dio_ChannelType) 40U)
/** \brief Symbolic name for GPIO channel #41 GPIOF_Ch1 */
#define DioConf_DioChannel_GPIOF_Ch1 ((Dio_ChannelType) 41U)
/** \brief Symbolic name for GPIO channel #42 GPIOF_Ch2 */
#define DioConf_DioChannel_GPIOF_Ch2 ((Dio_ChannelType) 42U)
/** \brief Symbolic name for GPIO channel #43 GPIOF_Ch3 */
#define DioConf_DioChannel_GPIOF_Ch3 ((Dio_ChannelType) 43U)
/** \brief Symbolic name for GPIO channel #44 GPIOF_Ch4 */
#define DioConf_DioChannel_GPIOF_Ch4 ((Dio_ChannelType) 44U)
/** \brief Symbolic name for GPIO channel #45 GPIOF_Ch5 */
#define DioConf_DioChannel_GPIOF_Ch5 ((Dio_ChannelType) 45U)
/** \brief Symbolic name for GPIO channel #46 GPIOF_Ch6 */
#define DioConf_DioChannel_GPIOF_Ch6 ((Dio_ChannelType) 46U)
/** \brief Symbolic name for GPIO channel #47 GPIOF_Ch7 */
#define DioConf_DioChannel_GPIOF_Ch7 ((Dio_ChannelType) 47U)
/** \brief Symbolic name for GPIO channel #48 GPIOG_Ch0 */
#define DioConf_DioChannel_GPIOG_Ch0 ((Dio_ChannelType) 48U)
/** \brief Symbolic name for GPIO channel #49 GPIOG_Ch1 */
#define DioConf_DioChannel_GPIOG_Ch1 ((Dio_ChannelType) 49U)
/** \brief Symbolic name for GPIO channel #50 GPIOG_Ch2 */
#define DioConf_DioChannel_GPIOG_Ch2 ((Dio_ChannelType) 50U)
/** \brief Symbolic name for GPIO channel #51 GPIOG_Ch3 */
#define DioConf_DioChannel_GPIOG_Ch3 ((Dio_ChannelType) 51U)
/** \brief Symbolic name for GPIO channel #52 GPIOG_Ch4 */
#define DioConf_DioChannel_GPIOG_Ch4 ((Dio_ChannelType) 52U)
/** \brief Symbolic name for GPIO channel #53 GPIOG_Ch5 */
#define DioConf_DioChannel_GPIOG_Ch5 ((Dio_ChannelType) 53U)
/** \brief Symbolic name for GPIO channel #54 GPIOG_Ch6 */
#define DioConf_DioChannel_GPIOG_Ch6 ((Dio_ChannelType) 54U)
/** \brief Symbolic name for GPIO channel #55 GPIOG_Ch7 */
#define DioConf_DioChannel_GPIOG_Ch7 ((Dio_ChannelType) 55U)
/** \brief Symbolic name for GPIO channel #56 GPIOH_Ch0 */
#define DioConf_DioChannel_GPIOH_Ch0 ((Dio_ChannelType) 56U)
/** \brief Symbolic name for GPIO channel #57 GPIOH_Ch1 */
#define DioConf_DioChannel_GPIOH_Ch1 ((Dio_ChannelType) 57U)
/** \brief Symbolic name for GPIO channel #58 GPIOH_Ch2 */
#define DioConf_DioChannel_GPIOH_Ch2 ((Dio_ChannelType) 58U)
/** \brief Symbolic name for GPIO channel #59 GPIOH_Ch3 */
#define DioConf_DioChannel_GPIOH_Ch3 ((Dio_ChannelType) 59U)
/** \brief Symbolic name for GPIO channel #60 GPIOH_Ch4 */
#define DioConf_DioChannel_GPIOH_Ch4 ((Dio_ChannelType) 60U)
/** \brief Symbolic name for GPIO channel #61 GPIOH_Ch5 */
#define DioConf_DioChannel_GPIOH_Ch5 ((Dio_ChannelType) 61U)
/** \brief Symbolic name for GPIO channel #62 GPIOH_Ch6 */
#define DioConf_DioChannel_GPIOH_Ch6 ((Dio_ChannelType) 62U)
/** \brief Symbolic name for GPIO channel #63 GPIOH_Ch7 */
#define DioConf_DioChannel_GPIOH_Ch7 ((Dio_ChannelType) 63U)
/* @} */

/* Requirements : SWS_Dio_00026, SWS_Dio_00113, SWS_Dio_00022 */
/**
 *  \name Symbolic name of DIO Channel Groups
 *
 *  This is the symbolic name of DIO channel groups generated from configurator
 *  The definition of the channel groups is present in the generated
 *  Dio_PBCfg.c file. The other modules will invoke the Dio_channelGroup APIs
 *  using the symbolic name defines
 *
 *  @{
 */
#define DioConf_DioChannelGroup_GPIOA_Bit5_8_PTR ((Dio_ChannelGroupRefType)(DioConfig_0_GPIOA_ChannelGroupRef[0]))
#define DioConf_DioChannelGroup_GPIOA_Bit1_5_PTR ((Dio_ChannelGroupRefType)(DioConfig_0_GPIOA_ChannelGroupRef[1]))
#define DioConf_DioChannelGroup_GPIOB_Bit5_8_PTR ((Dio_ChannelGroupRefType)(DioConfig_0_GPIOB_ChannelGroupRef[0]))
#define DioConf_DioChannelGroup_GPIOB_Bit1_5_PTR ((Dio_ChannelGroupRefType)(DioConfig_0_GPIOB_ChannelGroupRef[1]))
#define DioConf_DioChannelGroup_GPIOC_Bit5_8_PTR ((Dio_ChannelGroupRefType)(DioConfig_0_GPIOC_ChannelGroupRef[0]))
#define DioConf_DioChannelGroup_GPIOC_Bit1_5_PTR ((Dio_ChannelGroupRefType)(DioConfig_0_GPIOC_ChannelGroupRef[1]))
#define DioConf_DioChannelGroup_GPIOD_Bit5_8_PTR ((Dio_ChannelGroupRefType)(DioConfig_0_GPIOD_ChannelGroupRef[0]))
#define DioConf_DioChannelGroup_GPIOD_Bit1_5_PTR ((Dio_ChannelGroupRefType)(DioConfig_0_GPIOD_ChannelGroupRef[1]))
#define DioConf_DioChannelGroup_GPIOE_Bit5_7_PTR ((Dio_ChannelGroupRefType)(DioConfig_0_GPIOE_ChannelGroupRef[0]))
#define DioConf_DioChannelGroup_GPIOF_Bit8_8_PTR ((Dio_ChannelGroupRefType)(DioConfig_0_GPIOF_ChannelGroupRef[0]))
#define DioConf_DioChannelGroup_GPIOG_Bit7_6_PTR ((Dio_ChannelGroupRefType)(DioConfig_0_GPIOG_ChannelGroupRef[0]))
#define DioConf_DioChannelGroup_GPIOH_Bit7_7_PTR ((Dio_ChannelGroupRefType)(DioConfig_0_GPIOH_ChannelGroupRef[0]))
/* @} */

/** \brief Enable/Disable GIO support in DIO */
#define DIO_SUPPORT_GIO             (STD_ON)

/**
 *  \name DIO DEM Error codes to report
 *
 *  Pre-compile switches for enabling/disabling DEM events
 *  @{
 */


/* DIO IO check Dem IDs */

#ifndef DIO_E_HARDWARE_ERROR
/** \brief Hardware failed */
#define DIO_E_HARDWARE_ERROR          (DemConf_DemEventParameter_DIO_E_HARDWARE_ERROR)
#endif


/* @} */

/* Static tests for configuration integrity can be conducted here */
/* This check throws an error if Dio is configured to support neither Can nor
 * Gio */
#if ((DIO_SUPPORT_GIO == STD_OFF))
  #error "Must enable GPIO. This configuration is not valid."
#endif


/* ========================================================================== */
/*                         Structures and Enums                               */
/* ========================================================================== */
/** \brief Dio reference to the channel group*/

extern P2CONST(void, AUTOMATIC, DIO_CONST) DioConfig_0_GPIOA_ChannelGroupRef[2];

extern P2CONST(void, AUTOMATIC, DIO_CONST) DioConfig_0_GPIOB_ChannelGroupRef[2];

extern P2CONST(void, AUTOMATIC, DIO_CONST) DioConfig_0_GPIOC_ChannelGroupRef[2];

extern P2CONST(void, AUTOMATIC, DIO_CONST) DioConfig_0_GPIOD_ChannelGroupRef[2];

extern P2CONST(void, AUTOMATIC, DIO_CONST) DioConfig_0_GPIOE_ChannelGroupRef[1];

extern P2CONST(void, AUTOMATIC, DIO_CONST) DioConfig_0_GPIOF_ChannelGroupRef[1];

extern P2CONST(void, AUTOMATIC, DIO_CONST) DioConfig_0_GPIOG_ChannelGroupRef[1];

extern P2CONST(void, AUTOMATIC, DIO_CONST) DioConfig_0_GPIOH_ChannelGroupRef[1];


/*LDRA_INSPECTED 33 D: MISRAC_2012_8.6
 * "Reason -  Dio configuration structure declaration" */
/** \brief global DIO channel configuration mask */
extern CONST (uint32,DIO_CONST) gDioConfigValidChannelMask[DIO_MAX_NO_OF_PORTS];

/** This type is used to access the GIO Base Registers */
typedef struct
{
	uint32 mssBaseAddr;
	uint32 rcssBaseAddr;
} Dio_RegisterReadbackType;

/* ========================================================================== */
/*                          Function Declarations                             */
/* ========================================================================== */
/* None */

#ifdef __cplusplus
}
#endif

#endif  /* #ifndef DIO_CFG_H_ */

/* @} */

