/*
*
* Copyright (c) 2023 Texas Instruments Incorporated
*
* All rights reserved not granted herein.
*
* Limited License.
*
* Texas Instruments Incorporated grants a world-wide, royalty-free, non-exclusive
* license under copyrights and patents it now or hereafter owns or controls to make,
* have made, use, import, offer to sell and sell ("Utilize") this software subject to the
* terms herein.  With respect to the foregoing patent license, such license is granted
* solely to the extent that any such patent is necessary to Utilize the software alone.
* The patent license shall not apply to any combinations which include this software,
* other than combinations with devices manufactured by or for TI ("TI Devices").
* No hardware patent is licensed hereunder.
*
* Redistributions must preserve existing copyright notices and reproduce this license
* (including the above copyright notice and the disclaimer and (if applicable) source
* code license limitations below) in the documentation and/or other materials provided
* with the distribution
*
* Redistribution and use in binary form, without modification, are permitted provided
* that the following conditions are met:
*
* *       No reverse engineering, decompilation, or disassembly of this software is
* permitted with respect to any software provided in binary form.
*
* *       any redistribution and use are licensed by TI for use only with TI Devices.
*
* *       Nothing shall obligate TI to provide you with source code for the software
* licensed and provided to you in object code.
*
* If software source code is provided to you, modification and redistribution of the
* source code are permitted provided that the following conditions are met:
*
* *       any redistribution and use of the source code, including any resulting derivative
* works, are licensed by TI for use only with TI Devices.
*
* *       any redistribution and use of any object code compiled from the source code
* and any resulting derivative works, are licensed by TI for use only with TI Devices.
*
* Neither the name of Texas Instruments Incorporated nor the names of its suppliers
*
* may be used to endorse or promote products derived from this software without
* specific prior written permission.
*
* DISCLAIMER.
*
* THIS SOFTWARE IS PROVIDED BY TI AND TI'S LICENSORS "AS IS" AND ANY EXPRESS
* OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
* OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL TI AND TI'S LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
* BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
* DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
* OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/

  /*****************************************************************************
    Project: [!"$project"!]

    This file is generated by EB Tresos
    Do not modify this file, otherwise the software may behave in unexpected way.

 ******************************************************************************/

/**
 *  \file     Cdd_FsiTx_Cfg.h
 *
 *  \brief    This file contains generated pre compile configuration file
 *            for CDD FSI TX MCAL driver
 *
 */


 
#ifndef CDD_FSI_TX_CFG_H_
#define CDD_FSI_TX_CFG_H_

/**
 * \addtogroup CDD_FSITX FsiTx API GUIDE Header file
 * @{
 */

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */
#include "Std_Types.h"
[!IF "node:exists(as:modconf('Cdd_FsiTx')[1]/CddFsiTxDemEventParameterRefs)"!][!//
#include "Dem.h"
[!ENDIF!][!//
[!IF "not(node:empty(as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxOsCounterRef))"!][!//
#include "Os.h"
[!ENDIF!][!//
[!IF "as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxDMAEnable = 'true'"!][!//
[!IF "(node:exists(as:modconf('Cdd_Dma')[1]/CddDmaGeneral))"!][!//
#include "Cdd_Dma_Cfg.h"
[!ENDIF!][!//
[!ENDIF!][!//

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DOXYGEN_SHOULD_SKIP_THIS

/**
 *  \name CDD FSI TX Driver Configuration SW Version Info
 *
 *  Defines for CDD FSI TX Driver configuration version
 *  @{
 */
/** \brief CDD FSI TX configuration Major Version */
#define CDD_FSI_TX_CFG_MAJOR_VERSION                 ([!"substring-before($moduleSoftwareVer,'.')"!]U)
/** \brief CDD FSI TX configuration Minor Version */
#define CDD_FSI_TX_CFG_MINOR_VERSION                 ([!"substring-before(substring-after($moduleSoftwareVer,'.'),'.')"!]U)
/** \brief CDD FSI TX configuration Patch Version */
#define CDD_FSI_TX_CFG_PATCH_VERSION                 ([!"substring-after(substring-after($moduleSoftwareVer,'.'),'.')"!]U)
/* @} */

/* ========================================================================== */
/*                           Macros & Typedefs                                */
/* ========================================================================== */
/**
*  \name Cdd_FsiTx service enable/disable defines
*  \brief CDD FSI TX Build Variant.
*   Build variants.(i.e Pre Compile,Post Build)
* @{
*/
#define CDD_FSI_TX_VARIANT_PRE_COMPILE   [!IF "as:modconf('Cdd_FsiTx')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPreCompile'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

#define CDD_FSI_TX_VARIANT_POST_BUILD    [!IF "as:modconf('Cdd_FsiTx')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPostBuild'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

[!IF "as:modconf('Cdd_FsiTx')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPreCompile'"!]
/**
 *  \brief Pre Compile config macro name.
 */
[!LOOP "as:modconf('Cdd_FsiTx')[1]/CddFsiTxConfigSet"!]
#define CDD_FSI_TX_INIT_CONFIG_PC       [!"@name"!]
[!ENDLOOP!]
[!ENDIF!]

/**
 *  \name FsiTx DMA Id names
 *
 *  Defines for symbolic names for the DMA Channel ID's.
 *  @{
 */
[!NOCODE!][!//
[!IF "as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxDMAEnable = 'true'"!]
[!LOOP "as:modconf('Cdd_FsiTx')[1]/CddFsiTxConfigSet"!][!//
[!LOOP "CddFsiTxHwUnit/*"!][!//
[!IF "CddFsiTxTransmissionMethod = 'CDD_FSI_TX_DMA_MODE'"!]
[!CODE!]
#define  CddFsiTxConf_[!"@name"!]_DmaGroup   (CddDmaConf_[!"node:name((node:ref(CddFsiTxDmaReference)))"!])
[!ENDCODE!][!//
[!ENDIF!]
[!ENDLOOP!]
[!ENDLOOP!][!//
[!CODE!]
/* @} */
[!ENDCODE!][!//
[!ENDIF!]
[!ENDNOCODE!][!//

/** \brief Enable/disable CDD_FSI_TX dev detect error */
#define CDD_FSI_TX_DEV_ERROR_DETECT            [!IF "as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxDevErrorDetectApi   = 'true'"!] (STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]



/** \brief Enable/disable CddFsiTx de init info API */
#define CDD_FSI_TX_DEINIT_API            [!IF "as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxDeInitApi  = 'true'"!] (STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/** \brief Enable/disable CddFsiTx transmit info API */
#define CDD_FSI_TX_TRANSMIT_API            [!IF "as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxTransmitApi  = 'true'"!] (STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/** \brief Enable/disable CddFsiTx Ping API */
#define CDD_FSI_TX_PING_API            [!IF "as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxPingApi  = 'true'"!] (STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/** \brief Enable/disable External trigger API */
#define CDD_FSI_TX_EXTERNAL_TRIGGER_ENABLE           [!IF "as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxExtTriggerEnable  = 'true'"!] (STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/** \brief Enable/disable Buffer Load API */
#define CDD_FSI_TX_BUFFER_LOAD_API           [!IF "as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxBuffLoadApi  = 'true'"!] (STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/** \brief Enable/disable CddFsiTx notification  */
#define CDD_FSI_TX_NOTIFICATION_ENABLE           [!IF "as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxNotifyCapability  = 'true'"!] (STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/** \brief Enable/disable CddFsiTx get version info API */
#define CDD_FSI_TX_GET_VERSION_INFO           [!IF "as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxGetVersionInfoApi  = 'true'"!] (STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/** \brief Enable/disable DMA Transfer mode*/
#define CDD_FSI_TX_DMA_ENABLE           [!IF "as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxDMAEnable  = 'true'"!] (STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/** \brief Enable/disable CddFsiTxClearReset API */
#define CDD_FSI_TX_MAIN_FUNCTION_API           [!IF "as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxMainApi  = 'true'"!] (STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/** \brief Enable/disable CddFsiTxClearReset API */
#define CDD_FSI_TX_RESET_API           [!IF "as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxResetDriver  = 'true'"!] (STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/** \brief Enable/disable Tx Buffer OverRun Interrupt Event  */
#define CDD_FSI_TX_BUFFER_OVERRUN_INTERRUPT           [!IF "as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxBufferOverRunInterrupt  = 'true'"!] (STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/** \brief Enable/disable Tx Buffer UnderRun Interrupt Event  */
#define CDD_FSI_TX_BUFFER_UNDERRUN_INTERRUPT           [!IF "as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxBufferUnderRunInterrupt  = 'true'"!] (STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/** \brief Enable/disable Tx Ping Timeout Interrupt Event  */
#define CDD_FSI_TX_PING_TIMEOUT_INTERRUPT           [!IF "as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxPingTimeOutInterrupt  = 'true'"!] (STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/** \brief Enable/disable Tx Frame Done Interrupt Event  */
#define CDD_FSI_TX_FRAME_DONE_INTERRUPT           [!IF "as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxFrameDoneInterrupt  = 'true'"!] (STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]


/** \brief Enable/disable Multilane Transmission */
#define CDD_FSI_TX_MULTI_LANE_ENABLE           [!IF "as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxMultiLaneEnable  = 'true'"!] (STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/* @} */


/** \brief Maximum CDD FSI TX channels Configured. */
#define CDD_FSI_TX_DMA_CHANNELS_CONFIGURED   ((uint8)[!" as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxMaxDmaChannelId"!]U) 


/**
 * \name CDD FsiTx interrupt configuration
 * All below macros are used for enabling the ISR for a particular hardware.
 * @{
 */
[!LOOP "as:modconf('Cdd_FsiTx')[1]/CddFsiTxConfigSet"!][!//
[!LOOP "CddFsiTxHwUnit/*"!][!//
[!IF "CddFsiTxHwUnitId = 'CDD_FSI_TX_HWUNIT_0'"!][!//
/** \brief CDD_FSI_TX UNIT INSTANCE */
#define CDD_FSI_TX_INSTANCE_0
[!ENDIF!][!//
[!IF "CddFsiTxHwUnitId = 'CDD_FSI_TX_HWUNIT_1'"!][!//
/** \brief CDD_FSI_TX UNIT INSTANCE */
#define CDD_FSI_TX_INSTANCE_1
[!ENDIF!][!//
[!IF "CddFsiTxHwUnitId = 'CDD_FSI_TX_HWUNIT_2'"!][!//
/** \brief CDD_FSI_TX UNIT INSTANCE */
#define CDD_FSI_TX_INSTANCE_2
[!ENDIF!][!//
[!IF "CddFsiTxHwUnitId = 'CDD_FSI_TX_HWUNIT_3'"!][!//
/** \brief CDD_FSI_TX UNIT INSTANCE */
#define CDD_FSI_TX_INSTANCE_3
[!ENDIF!][!//
[!ENDLOOP!]
[!ENDLOOP!][!//

/** \brief ISR type */
#define CDD_FSI_TX_ISR_TYPE                    ([!" as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxTypeofInterruptFunction"!])

/** \brief ISR type */
#define CDD_FSI_TX_INT_TYPE                    ([!" as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxInterruptVector"!])
/* @} */
/** \brief Counter ID for counter used to count wait ticks */
#define CDD_FSI_TX_OS_COUNTER_ID               ([!IF "not(node:empty(as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxOsCounterRef))"!](CounterType)[!"node:name(node:ref(as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxOsCounterRef))"!][!ELSE!][!"as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxDefaultOSCounterId"!]U[!ENDIF!])

/**
 *  \name CddFsiTx Hw Unit Id names
 *
 *  Defines for symbolic names for the CddFsiTxHwUnitId
 *  @{
 */

[!LOOP "as:modconf('Cdd_FsiTx')[1]/CddFsiTxConfigSet"!][!//
[!LOOP "CddFsiTxHwUnit/*"!][!//
#define CddFsiTxConf_CddFsiTxHwUnit_[!"@name"!]   [!"@index"!]
#define CDD_FSI_TX_HW_UNIT_ID_[!"@index"!] ([!"CddFsiTxHwUnitId"!])
[!ENDLOOP!][!ENDLOOP!][!//
/* @} */


/**
 *  \name FSI TX HW unit Info
 *  @{
 */
/** \brief CDD_FSI_TX_0 instance */
#define CDD_FSI_TX_HWUNIT_0                      ((Cdd_FsiTx_HWUnitType) 0U)
/** \brief CDD_FSI_TX_1 instance */
#define CDD_FSI_TX_HWUNIT_1                      ((Cdd_FsiTx_HWUnitType) 1U)
/** \brief CDD_FSI_TX_2 instance */
#define CDD_FSI_TX_HWUNIT_2                      ((Cdd_FsiTx_HWUnitType) 2U)
/** \brief CDD_FSI_TX_3 instance */
#define CDD_FSI_TX_HWUNIT_3                      ((Cdd_FsiTx_HWUnitType) 3U)

#define CDD_FSI_TX_HW_UNIT_CNT                   (4U)

/* @} */

/**
 *  \name CDD FsiTx DEM Error codes to report
 *
 *  Pre-compile switches for enabling/disabling DEM events
 *  @{
 */
[!NOCODE!][!//
[!IF "node:exists(as:modconf('Cdd_FsiTx')[1]/CddFsiTxDemEventParameterRefs)"!][!//
[!IF "not(node:exists(as:modconf('Cdd_FsiTx')[1]/CddFsiTxDemEventParameterRefs/CDD_FSI_TX_E_BUFFER_UNDERRUN))"!][!WARNING "DEM enabled but no DEM error configured"!][!ENDIF!]
[!ENDIF!][!//
[!ENDNOCODE!][!//
[!IF "node:exists(as:modconf('Cdd_FsiTx')[1]/CddFsiTxDemEventParameterRefs/*)"!][!//
/* Cdd_FsiTx DEM Event Configuration*/
#ifndef CDD_FSI_TX_E_BUFFER_UNDERRUN
/** \brief Error code indicating  Buffer underrun occured */
#define CDD_FSI_TX_E_BUFFER_UNDERRUN          ([!IF "not(node:empty(as:modconf('Cdd_FsiTx')[1]/CddFsiTxDemEventParameterRefs/CDD_FSI_TX_E_BUFFER_UNDERRUN))"!]DemConf_DemEventParameter_[!"node:name(node:ref(as:modconf('Cdd_FsiTx')[1]/CddFsiTxDemEventParameterRefs/CDD_FSI_TX_E_BUFFER_UNDERRUN))"!][!ELSE!][!ERROR "No Hardawre refernece is provided but DEM is enabled "!][!ENDIF!])
#endif

/* Cdd_FsiTx DEM Event Configuration*/
#ifndef CDD_FSI_TX_E_BUFFER_OVERRUN
/** \brief Error code indicating  Buffer underrun occured */
#define CDD_FSI_TX_E_BUFFER_OVERRUN          ([!IF "not(node:empty(as:modconf('Cdd_FsiTx')[1]/CddFsiTxDemEventParameterRefs/CDD_FSI_TX_E_BUFFER_OVERRUN))"!]DemConf_DemEventParameter_[!"node:name(node:ref(as:modconf('Cdd_FsiTx')[1]/CddFsiTxDemEventParameterRefs/CDD_FSI_TX_E_BUFFER_OVERRUN))"!][!ELSE!][!ERROR "No Hardawre refernece is provided but DEM is enabled "!][!ENDIF!])
#endif
[!ENDIF!][!//
/* @} */

#endif /* DOXYGEN_SHOULD_SKIP_THIS */

/* ========================================================================== */
/*                         Structures and Enums                               */
/* ========================================================================== */
[!LOOP "as:modconf('Cdd_FsiTx')[1]/CddFsiTxConfigSet"!]
/** \brief CDD FSI TX Configuration struct declaration */
extern const struct Cdd_FsiTx_ConfigType_s [!"@name"!];
[!ENDLOOP!]

#ifdef __cplusplus
}
#endif

[!NOCODE!]
[!LOOP "as:modconf('Cdd_FsiTx')[1]/CddFsiTxConfigSet"!][!//
[!VAR "HwLpCnt" = "0"!][!//
[!LOOP "CddFsiTxHwUnit/*"!][!//
[!IF "as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxDMAEnable = 'true'"!]
[!IF "CddFsiTxTransmissionMethod != 'CDD_FSI_TX_DMA_MODE'"!]
[!ERROR!][!//
[!"'The transmission method should be configured as CDD_FSI_TX_DMA_MODE, since CddFsiTxDMAEnable is STD_ON.'"!][!"' CddFsiTxHwUnit'"!][!"'CddFsiTxTransmissionMethod should be configured as CDD_FSI_TX_DMA_MODE.'"!][!//
[!ENDERROR!][!//
[!ENDIF!]
[!ENDIF!]
[!IF "CddFsiTxDataFrameValue = 'CDD_FSI_TX_DATA_1_WORD'"!]
[!IF "CddFsiTxDataLength != 'CDD_FSI_TX_DATA_1_WORD_LENGTH'"!]
[!ERROR!][!//
[!"'The Data Length should  be configured as CDD_FSI_TX_DATA_1_WORD_LENGTH, since CddFsiTxDataFrameValue is selected as CDD_FSI_TX_DATA_1_WORD.'"!][!"' CddFsiTxHwUnit'"!][!"'CddFsiTxDataLength is not configured as CDD_FSI_TX_DATA_1_WORD_LENGTH.'"!][!//
[!ENDERROR!][!//
[!ENDIF!]
[!ENDIF!]

[!IF "CddFsiTxDataFrameValue = 'CDD_FSI_TX_DATA_2_WORD'"!]
[!IF "CddFsiTxDataLength != 'CDD_FSI_TX_DATA_2_WORD_LENGTH'"!]
[!ERROR!][!//
[!"'The Data Length should  be configured as CDD_FSI_TX_DATA_2_WORD_LENGTH, since CddFsiTxDataFrameValue is selected as CDD_FSI_TX_DATA_2_WORD.'"!][!"' CddFsiTxHwUnit'"!][!"'CddFsiTxDataLength is not configured as CDD_FSI_TX_DATA_2_WORD_LENGTH.'"!][!//
[!ENDERROR!][!//
[!ENDIF!]
[!ENDIF!]

[!IF "CddFsiTxDataFrameValue = 'CDD_FSI_TX_DATA_4_WORD'"!]
[!IF "CddFsiTxDataLength != 'CDD_FSI_TX_DATA_4_WORD_LENGTH'"!]
[!ERROR!][!//
[!"'The Data Length should  be configured as CDD_FSI_TX_DATA_4_WORD_LENGTH, since CddFsiTxDataFrameValue is selected as CDD_FSI_TX_DATA_4_WORD.'"!][!"' CddFsiTxHwUnit'"!][!"'CddFsiTxDataLength is not configured as CDD_FSI_TX_DATA_4_WORD_LENGTH.'"!][!//
[!ENDERROR!][!//
[!ENDIF!]
[!ENDIF!]

[!IF "CddFsiTxDataFrameValue = 'CDD_FSI_TX_DATA_6_WORD'"!]
[!IF "CddFsiTxDataLength != 'CDD_FSI_TX_DATA_6_WORD_LENGTH'"!]
[!ERROR!][!//
[!"'The Data Length should  be configured as CDD_FSI_TX_DATA_6_WORD_LENGTH, since CddFsiTxDataFrameValue is selected as CDD_FSI_TX_DATA_6_WORD.'"!][!"' CddFsiTxHwUnit'"!][!"'CddFsiTxDataLength is not configured as CDD_FSI_TX_DATA_6_WORD_LENGTH.'"!][!//
[!ENDERROR!][!//
[!ENDIF!]
[!ENDIF!]
[!IF "as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxMainApi = 'true'"!]
[!IF "as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxPingTimeOutInterrupt = 'true'"!]
[!ERROR!][!//
[!"'The Main API is enabled which is used for Polling Method.So Interrupt events should not be enabled.'"!][!"' CddFsiRxHwUnit'"!][!"'CddFsiTxPingTimeOutInterrupt should be STD_OFF.'"!][!//
[!ENDERROR!][!//
[!ENDIF!]
[!ENDIF!]

[!IF "as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxMainApi = 'true'"!]
[!IF "as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxBufferOverRunInterrupt = 'true'"!]
[!ERROR!][!//
[!"'The Main API is enabled which is used for Polling Method.So Interrupt events should not be enabled.'"!][!"' CddFsiRxHwUnit'"!][!"'CddFsiTxBufferOverRunInterrupt should be STD_OFF.'"!][!//
[!ENDERROR!][!//
[!ENDIF!]
[!ENDIF!]

[!IF "as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxMainApi = 'true'"!]
[!IF "as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxBufferUnderRunInterrupt = 'true'"!]
[!ERROR!][!//
[!"'The Main API is enabled which is used for Polling Method.So Interrupt events should not be enabled.'"!][!"' CddFsiRxHwUnit'"!][!"'CddFsiTxBufferUnderRunInterrupt should be STD_OFF.'"!][!//
[!ENDERROR!][!//
[!ENDIF!]
[!ENDIF!]

[!IF "as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxMainApi = 'true'"!]
[!IF "as:modconf('Cdd_FsiTx')[1]/CddFsiTxGeneral/CddFsiTxFrameDoneInterrupt = 'true'"!]
[!ERROR!][!//
[!"'The Main API is enabled which is used for Polling Method.So Interrupt events should not be enabled.'"!][!"' CddFsiRxHwUnit'"!][!"'CddFsiTxFrameDoneInterrupt should be STD_OFF.'"!][!//
[!ENDERROR!][!//
[!ENDIF!]
[!ENDIF!]

 [!VAR "HwLpCnt" = "$HwLpCnt+1"!]
[!ENDLOOP!][!ENDLOOP!][!//
[!ENDNOCODE!][!//

/**
* @} 
*/

#endif  /* #ifndef CDD_FSI_TX_CFG_H_ */


