/* ======================================================================
 *   Copyright (c) 2023-2024 Texas Instruments Incorporated
 *
 *   All rights reserved. Property of Texas Instruments Incorporated.
 *   Restricted rights to use, duplicate or disclose this code are
 *   granted through contract.
 *
 *   The program may not be used without the written permission
 *   of Texas Instruments Incorporated or against the terms and conditions
 *   stipulated in the agreement under which this program has been
 *   supplied.
 * ==================================================================== */

/**
 *  \file     Spi_PBCfg.c
 *
 *  \brief    This file contains generated post build configuration file
 *            for SPI MCAL driver
 */

  /*********************************************************************************************************************
    Project: Spi_am273x
	Date   : 2024-02-12 12:27:47
	
    This file is generated by EB Tresos
    Do not modify this file, otherwise the software may behave in unexpected way.

 *********************************************************************************************************************/


#define SPI_PBCFG_SOURCE 1U

/**********************************************************************************************************************
 *  INCLUDES
 *********************************************************************************************************************/
#include "Spi.h"
#include "hw_Mibspi.h"

/**********************************************************************************************************************
 *  VERSION CHECK
 *********************************************************************************************************************/

 #if ((SPI_CFG_MAJOR_VERSION != (10U))||(SPI_CFG_MINOR_VERSION != (1U)))
  #error "Version numbers of Spi_PbCfg.c and Spi_Cfg.h are inconsistent!"
#endif


/**********************************************************************************************************************
 *  LOCAL CONSTANT MACROS
 **********************************************************************************************************************/

/**********************************************************************************************************************
 *  LOCAL FUNCTION MACROS
 **********************************************************************************************************************/

/**********************************************************************************************************************
 *  LOCAL DATA TYPES AND STRUCTURES
 **********************************************************************************************************************/

/**********************************************************************************************************************
 *  LOCAL DATA PROTOTYPES
 **********************************************************************************************************************/

/**********************************************************************************************************************
 *  GLOBAL DATA
 **********************************************************************************************************************/

#define  SPI_START_SEC_CONFIG_DATA
/*TI_INSPECTED 338 S : MISRAC_2012_R.20.1
 * "Reason - Required to comply with AUTOSAR memmap spec " */
#include "Spi_MemMap.h"
/* generation of runtime configuration       */


/*
 *Design: MCAL-14193, MCAL-14196, MCAL-14195, MCAL-14194, MCAL-14192, MCAL-14183, MCAL-14182, MCAL-14184, MCAL-14187, MCAL-14186, MCAL-14189
 */
extern void SpiApp_MibspiJob0EndNotification(void);

extern void SpiApp_MibspiSeq0EndNotification(void);

/*
 *Design: MCAL-14211, MCAL-14212, MCAL-14206, MCAL-14209, MCAL-14210, MCAL-14201, MCAL-14205, MCAL-14213, MCAL-14207, MCAL-14215, MCAL-14223, MCAL-14204, MCAL-14236,
 */

CONST(Spi_ConfigType, SPI_PBCFG) SpiDriver_0 =
{
    .maxChannels = 1U,
    .maxJobs = 1U,
    .maxSeq  = 1U,
    .maxHwUnit = 1U,
    .maxExtDevCfg = 1U,
    .Spi_MaxDlcs = 1U,
    .extDevCfg =
    {
        [0] =
        {
            .mibspi =
            {
                .Spi_DioPin = SPI_CS0,
                .Spi_CsProperty   = SPI_HIGH,
                .Spi_Baudrate = 0x4U,
                .Spi_Mode = SPI_CLK_MODE_0,
                .Spi_ClkDelays = {0xff00U, 0x0000U },
                .Spi_CsIdleTime = 0x00U,
                .Spi_CsMode = SPI_CONTINUOUS,
                .Spi_HwInstance = 0U,
                .txRxMode     = SPI_TX_RX_MODE_BOTH,
            },
        },
    },
    .channelCfg =
    {
        [0] =
        {
            .channelId = 0U,
            .channelBufType = SPI_EB,
            .dataWidth = 32U,
            .defaultTxData = 0U,
            .maxBufLength = 32U,
            .transferType = SPI_MSB,
            .qspiChMode    = SPI_QSPI_SFI_CHMODE_DATA,
            .qspiXferCmd = SPI_QSPI_SFI_CH_XFER_CMD_4PIN_WR_SINGLE
        },

    },
    .jobCfg =
    {
        [0] =
        {
            .jobId = 0,
            .jobPriority = SPI_JOB_PRIORITY_0,
            .hwUnitId = SPI_UNIT_MIBSPI1,
            .csPin = SPI_CS0,
            .Spi_JobEndNotification = (Spi_JobEndNotifyType)SpiApp_MibspiJob0EndNotification,
            .channelPerJob = 1,
            .channelList =
            {
                0,
            },
            .externalDeviceCfgId = 0,
            .qspiEnableMemMapMode = FALSE,
        },
    },
    .seqCfg =
    {
        [0] =
        {
            .seqId = 0,
            .seqInterruptible = TRUE,
            .Spi_SequenceEndNotification = (Spi_SeqEndNotifyType)SpiApp_MibspiSeq0EndNotification,
            .jobPerSeq = 1,
            .jobList =
            {
                0,
            },
        },
    },
    .hwUnitCfg =
    {
        [SPI_UNIT_MIBSPI1] =
        {
            .hwUnitId = SPI_UNIT_MIBSPI1
        },
    },

};



#define SPI_STOP_SEC_CONFIG_DATA
#include "Spi_MemMap.h"

#define SPI_START_SEC_CONST_UNSPECIFIED

#include "Spi_MemMap.h"
/* Hardware unit array */
/*<T_SPI_HW_UNIT_OPEN/>*/
CONST(Spi_RegisterPtrType, SPI_CONST) Spi_HWUnit_at[SPI_MAX_HW_UNIT] =
{
[SPI_UNIT_MIBSPI1] = (Spi_RegisterPtrType) SPI_REGISTER_BASE_0,




};
/*<T_SPI_HW_UNIT_CLOSE/>*/

/* Spi RAM Hardware array */
/*<T_SPI_RAM_UNIT_OPEN/>*/
CONST(Spi_RamBufferPtrType, SPI_CONST) Spi_RamUnit_at[SPI_MAX_HW_UNIT] =
{
    /*<T_SPI_RAM_UNIT_DEF>*/
[SPI_UNIT_MIBSPI1] = (Spi_RamBufferPtrType) SPI_RAM_BASE_0,




    /*</T_SPI_RAM_UNIT_DEF>*/
};
/*<T_SPI_RAM_UNIT_CLOSE/>*/

/*<T_SPI_UNIT_PROPERTY_OPEN/>*/
CONST(Spi_HWUnitPropertyType, SPI_CONST) Spi_UnitProperty_at[SPI_MAX_HW_UNIT] =
{
    /*<T_SPI_UNIT_PROPERTY_DEF>*/
	[SPI_UNIT_MIBSPI1] = { 1U, 0U },




    /*</T_SPI_UNIT_PROPERTY_DEF>*/
};
/*<T_SPI_UNIT_PROPERTY_CLOSE/>*/

#define SPI_STOP_SEC_CONST_UNSPECIFIED
#include "Spi_MemMap.h"

/**********************************************************************************************************************
 *  END OF FILE: Spi_PBcfg.c
 *********************************************************************************************************************/