/*
*
* Copyright (c) 2023 Texas Instruments Incorporated
*
* All rights reserved not granted herein.
*
* Limited License.
*
* Texas Instruments Incorporated grants a world-wide, royalty-free, non-exclusive
* license under copyrights and patents it now or hereafter owns or controls to make,
* have made, use, import, offer to sell and sell ("Utilize") this software subject to the
* terms herein.  With respect to the foregoing patent license, such license is granted
* solely to the extent that any such patent is necessary to Utilize the software alone.
* The patent license shall not apply to any combinations which include this software,
* other than combinations with devices manufactured by or for TI ("TI Devices").
* No hardware patent is licensed hereunder.
*
* Redistributions must preserve existing copyright notices and reproduce this license
* (including the above copyright notice and the disclaimer and (if applicable) source
* code license limitations below) in the documentation and/or other materials provided
* with the distribution
*
* Redistribution and use in binary form, without modification, are permitted provided
* that the following conditions are met:
*
* *       No reverse engineering, decompilation, or disassembly of this software is
* permitted with respect to any software provided in binary form.
*
* *       any redistribution and use are licensed by TI for use only with TI Devices.
*
* *       Nothing shall obligate TI to provide you with source code for the software
* licensed and provided to you in object code.
*
* If software source code is provided to you, modification and redistribution of the
* source code are permitted provided that the following conditions are met:
*
* *       any redistribution and use of the source code, including any resulting derivative
* works, are licensed by TI for use only with TI Devices.
*
* *       any redistribution and use of any object code compiled from the source code
* and any resulting derivative works, are licensed by TI for use only with TI Devices.
*
* Neither the name of Texas Instruments Incorporated nor the names of its suppliers
*
* may be used to endorse or promote products derived from this software without
* specific prior written permission.
*
* DISCLAIMER.
*
* THIS SOFTWARE IS PROVIDED BY TI AND TI'S LICENSORS "AS IS" AND ANY EXPRESS
* OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
* OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL TI AND TI'S LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
* BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
* DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
* OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/

  /*****************************************************************************
    Project: FsiTx_Demo_Cfg

    This file is generated by EB Tresos
    Do not modify this file, otherwise the software may behave in unexpected way.

 ******************************************************************************/

/**
 *  \file     Cdd_FsiTx_Cfg.h
 *
 *  \brief    This file contains generated pre compile configuration file
 *            for CDD FSI TX MCAL driver
 *
 */



#ifndef CDD_FSI_TX_CFG_H_
#define CDD_FSI_TX_CFG_H_

/**
 * \addtogroup CDD_FSITX FsiTx API GUIDE Header file
 * @{
 */

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */
#include "Std_Types.h"
#include "Dem.h"


#ifdef __cplusplus
extern "C" {
#endif

#ifndef DOXYGEN_SHOULD_SKIP_THIS

/**
 *  \name CDD FSI TX Driver Configuration SW Version Info
 *
 *  Defines for CDD FSI TX Driver configuration version
 *  @{
 */
/** \brief CDD FSI TX configuration Major Version */
#define CDD_FSI_TX_CFG_MAJOR_VERSION                 (10U)
/** \brief CDD FSI TX configuration Minor Version */
#define CDD_FSI_TX_CFG_MINOR_VERSION                 (2U)
/** \brief CDD FSI TX configuration Patch Version */
#define CDD_FSI_TX_CFG_PATCH_VERSION                 (0U)
/* @} */

/* ========================================================================== */
/*                           Macros & Typedefs                                */
/* ========================================================================== */
/**
*  \name Cdd_FsiTx service enable/disable defines
*  \brief CDD FSI TX Build Variant.
*   Build variants.(i.e Pre Compile,Post Build)
* @{
*/
#define CDD_FSI_TX_VARIANT_PRE_COMPILE   (STD_OFF)

#define CDD_FSI_TX_VARIANT_POST_BUILD    (STD_ON)



/**
 *  \name FsiTx DMA Id names
 *
 *  Defines for symbolic names for the DMA Channel ID's.
 *  @{
 */

/** \brief Enable/disable CDD_FSI_TX dev detect error */
#define CDD_FSI_TX_DEV_ERROR_DETECT             (STD_ON)



/** \brief Enable/disable CddFsiTx de init info API */
#define CDD_FSI_TX_DEINIT_API             (STD_ON)

/** \brief Enable/disable CddFsiTx transmit info API */
#define CDD_FSI_TX_TRANSMIT_API             (STD_ON)

/** \brief Enable/disable CddFsiTx Ping API */
#define CDD_FSI_TX_PING_API             (STD_ON)

/** \brief Enable/disable External trigger API */
#define CDD_FSI_TX_EXTERNAL_TRIGGER_ENABLE           (STD_OFF)

/** \brief Enable/disable Buffer Load API */
#define CDD_FSI_TX_BUFFER_LOAD_API            (STD_ON)

/** \brief Enable/disable CddFsiTx notification  */
#define CDD_FSI_TX_NOTIFICATION_ENABLE            (STD_ON)

/** \brief Enable/disable CddFsiTx get version info API */
#define CDD_FSI_TX_GET_VERSION_INFO            (STD_ON)

/** \brief Enable/disable DMA Transfer mode*/
#define CDD_FSI_TX_DMA_ENABLE           (STD_OFF)

/** \brief Enable/disable CddFsiTxClearReset API */
#define CDD_FSI_TX_MAIN_FUNCTION_API           (STD_OFF)

/** \brief Enable/disable CddFsiTxClearReset API */
#define CDD_FSI_TX_RESET_API            (STD_ON)

/** \brief Enable/disable Tx Buffer OverRun Interrupt Event  */
#define CDD_FSI_TX_BUFFER_OVERRUN_INTERRUPT            (STD_ON)

/** \brief Enable/disable Tx Buffer UnderRun Interrupt Event  */
#define CDD_FSI_TX_BUFFER_UNDERRUN_INTERRUPT            (STD_ON)

/** \brief Enable/disable Tx Ping Timeout Interrupt Event  */
#define CDD_FSI_TX_PING_TIMEOUT_INTERRUPT            (STD_ON)

/** \brief Enable/disable Tx Frame Done Interrupt Event  */
#define CDD_FSI_TX_FRAME_DONE_INTERRUPT            (STD_ON)


/** \brief Enable/disable Multilane Transmission */
#define CDD_FSI_TX_MULTI_LANE_ENABLE           (STD_OFF)

/* @} */


/** \brief Maximum CDD FSI TX channels Configured. */
#define CDD_FSI_TX_DMA_CHANNELS_CONFIGURED   ((uint8)63U)


/**
 * \name CDD FsiTx interrupt configuration
 * All below macros are used for enabling the ISR for a particular hardware.
 * @{
 */
/** \brief CDD_FSI_TX UNIT INSTANCE */
#define CDD_FSI_TX_INSTANCE_0


/** \brief ISR type */
#define CDD_FSI_TX_ISR_TYPE                    (CDD_FSI_TX_ISR_CAT1)

/** \brief ISR type */
#define CDD_FSI_TX_INT_TYPE                    (CDD_FSI_TX_INT1)
/* @} */
/** \brief Counter ID for counter used to count wait ticks */
#define CDD_FSI_TX_OS_COUNTER_ID               (0U)

/**
 *  \name CddFsiTx Hw Unit Id names
 *
 *  Defines for symbolic names for the CddFsiTxHwUnitId
 *  @{
 */

#define CddFsiTxConf_CddFsiTxHwUnit_CddFsiTxHwUnit_0   0
#define CDD_FSI_TX_HW_UNIT_ID_0 (CDD_FSI_TX_HWUNIT_0)
/* @} */


/**
 *  \name FSI TX HW unit Info
 *  @{
 */
/** \brief CDD_FSI_TX_0 instance */
#define CDD_FSI_TX_HWUNIT_0                      ((Cdd_FsiTx_HWUnitType) 0U)
/** \brief CDD_FSI_TX_1 instance */


#define CDD_FSI_TX_HW_UNIT_CNT                   (1U)

/* @} */

/**
 *  \name CDD FsiTx DEM Error codes to report
 *
 *  Pre-compile switches for enabling/disabling DEM events
 *  @{
 */
/* Cdd_FsiTx DEM Event Configuration*/
#ifndef CDD_FSI_TX_E_BUFFER_UNDERRUN
/** \brief Error code indicating  Buffer underrun occured */
#define CDD_FSI_TX_E_BUFFER_UNDERRUN          (DemConf_DemEventParameter_CDD_FSI_TX_E_BUFFER_UNDERRUN)
#endif

/* Cdd_FsiTx DEM Event Configuration*/
#ifndef CDD_FSI_TX_E_BUFFER_OVERRUN
/** \brief Error code indicating  Buffer underrun occured */
#define CDD_FSI_TX_E_BUFFER_OVERRUN          (DemConf_DemEventParameter_CDD_FSI_TX_E_BUFFER_OVERRUN)
#endif
/* @} */

#endif /* DOXYGEN_SHOULD_SKIP_THIS */

/* ========================================================================== */
/*                         Structures and Enums                               */
/* ========================================================================== */

/** \brief CDD FSI TX Configuration struct declaration */
extern const struct Cdd_FsiTx_ConfigType_s Cdd_FsiTx_Config;


#ifdef __cplusplus
}
#endif


/**
* @}
*/

#endif  /* #ifndef CDD_FSI_TX_CFG_H_ */
