/* ======================================================================
 *   Copyright (c) 2022 Texas Instruments Incorporated
 *
 *   All rights reserved. Property of Texas Instruments Incorporated.
 *   Restricted rights to use, duplicate or disclose this code are
 *   granted through contract.
 *
 *   The program may not be used without the written permission
 *   of Texas Instruments Incorporated or against the terms and conditions
 *   stipulated in the agreement under which this program has been
 *   supplied.
 * ==================================================================== */

/**
 *  \file     Cdd_Ipc_PBCfg.c
 *
 *  \brief    This file contains generated post build configuration file
 *            for Complex device driver
 */

  /*********************************************************************************************************************
  Project: ipc_am261
    Date   : 2024-09-12 18:13:22
    
    This file is generated by EB Tresos
    Do not modify this file, otherwise the software may behave in unexpected way.

 *********************************************************************************************************************/


#define CDD_PBCFG_SOURCE 1U

/**********************************************************************************************************************
 *  INCLUDES
 *********************************************************************************************************************/
#include "Cdd_Ipc.h"
#include "soc.h"

/**********************************************************************************************************************
 *  VERSION CHECK
 *********************************************************************************************************************/
#if (   (CDD_IPC_CFG_MAJOR_VERSION != (10U)) \
    || (CDD_IPC_CFG_MINOR_VERSION != (2U)))
  #error "Version numbers of Cdd_Ipc_PbCfg.c and Cdd_Ipc_Cfg.h are inconsistent!"
#endif
/**********************************************************************************************************************
 *  LOCAL CONSTANT MACROS
 **********************************************************************************************************************/

/**********************************************************************************************************************
 *  LOCAL FUNCTION MACROS
 **********************************************************************************************************************/


/**********************************************************************************************************************
 *  LOCAL DATA TYPES AND STRUCTURES
 **********************************************************************************************************************/

/**********************************************************************************************************************
 *  LOCAL DATA PROTOTYPES
 **********************************************************************************************************************/

/**********************************************************************************************************************
 *  GLOBAL DATA
 **********************************************************************************************************************/
#define CDD_IPC_START_SEC_VAR_NO_INIT_8
#include "Cdd_Ipc_MemMap.h"
uint8 Cdd_RPMessageVringMem[2][CDD_IPC_VRING_SIZE] __attribute__((aligned(128), section("ipc_vring")));
#define  CDD_IPC_STOP_SEC_VAR_NO_INIT_8
#include "Cdd_Ipc_MemMap.h"

#define  CDD_IPC_START_SEC_CONFIG_DATA
#include "Cdd_Ipc_MemMap.h"

/*
 * Requirements : AUTORADAR_MCAL-66, AUTORADAR_MCAL-65
*/

CONST(Cdd_IpcConfigType, CDD_PBCFG) Cdd_Ipc_Config =
{
    .Cdd_Ipc_SelfCoreId = CDD_IPC_R5FSS0_0_ID,
    .Cdd_Ipc_numCores = 1,
    .Cdd_Ipc_coreIdList = {
        CDD_IPC_R5FSS0_1_ID,
        },
    .Cdd_Ipc_RpMsgParams = 
    {
                [0] = 
        {
        .Cdd_Ipc_localEndPt = 12,
        .recvCallback = NULL,
        .recvCallbackArgs = NULL,
        .recvNotifyCallback = NULL,
        .recvNotifyCallbackArgs = NULL,
        },
    },

    .Cdd_Ipc_CrcHookFunc = NULL
};

P2CONST(Cdd_IpcConfigType, AUTOMATIC, CDD_PBCFG)CfgPtr = &Cdd_Ipc_Config;
#define  CDD_IPC_STOP_SEC_CONFIG_DATA
#include "Cdd_Ipc_MemMap.h"

/* IPC RPMessage init objects */
#define CDD_IPC_START_SEC_VAR_NO_INIT_UNSPECIFIED
#include "Cdd_Ipc_MemMap.h"
RPMessageLLD_InitObject CddIpc_RPMessageInitObj;
#define CDD_IPC_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#include "Cdd_Ipc_MemMap.h"
extern IpcNotify_Object CddIpc_NotifyObject;





#define CDD_IPC_START_SEC_CODE
#include "Cdd_Ipc_MemMap.h"

void Cdd_Ipc_VringMemAllocation(void)
{   
    CddIpc_RPMessageInitObj.vringTxBaseAddr[1] = (uint32)Cdd_RPMessageVringMem[0];
    CddIpc_RPMessageInitObj.vringRxBaseAddr[1] = (uint32)Cdd_RPMessageVringMem[1];
    CddIpc_RPMessageInitObj.vringSize = CDD_IPC_VRING_SIZE;
    CddIpc_RPMessageInitObj.vringNumBuf = CDD_IPC_NUM_OF_BUFFERS;
    CddIpc_RPMessageInitObj.vringMsgSize = CDD_IPC_MAX_BUFFER_SIZE;
    CddIpc_RPMessageInitObj.hIpcNotify = &CddIpc_NotifyObject;
};
#define CDD_IPC_STOP_SEC_CODE
#include "Cdd_Ipc_MemMap.h"

/**********************************************************************************************************************
 *  END OF FILE: Cdd_PBcfg.c
 *********************************************************************************************************************/
