MODULE_NAME = mcal_all_libs

include $(mcal_PATH)/include/hw/inc.mk
include $(mcal_PATH)/include/memmap/inc.mk
include $(mcal_PATH)/examples/Utils/inc_autosar_stub.mk
include $(mcal_PATH)/Adc/srcs.mk
include $(mcal_PATH)/Can/srcs.mk
include $(mcal_PATH)/Cdd_Cmpss/srcs.mk
include $(mcal_PATH)/Cdd_Flc/srcs.mk
include $(mcal_PATH)/Dio/srcs.mk
include $(mcal_PATH)/Dma/srcs.mk
include $(mcal_PATH)/Epwm/srcs.mk
include $(mcal_PATH)/Eth/srcs.mk
include $(mcal_PATH)/EthTrcv/srcs.mk
include $(mcal_PATH)/Fls/srcs.mk
include $(mcal_PATH)/FsiRx/srcs.mk
include $(mcal_PATH)/FsiTx/srcs.mk
include $(mcal_PATH)/Gpt/srcs.mk
include $(mcal_PATH)/I2c/srcs.mk
include $(mcal_PATH)/Icu/srcs.mk
include $(mcal_PATH)/Ipc/srcs.mk
include $(mcal_PATH)/Lin/srcs.mk
include $(mcal_PATH)/Mcal_Lib/srcs.mk
include $(mcal_PATH)/Mcu/srcs.mk
include $(mcal_PATH)/Port/srcs.mk
include $(mcal_PATH)/Pwm/srcs.mk
include $(mcal_PATH)/Spi/srcs.mk
include $(mcal_PATH)/Uart/srcs.mk
include $(mcal_PATH)/Wdg/srcs.mk
include $(mcal_PATH)/examples_config/Adc_Demo_Cfg/srcs.mk
include $(mcal_PATH)/examples_config/Can_Demo_Cfg/srcs.mk
include $(mcal_PATH)/examples_config/Cdd_Cmpss_Demo_Cfg/srcs.mk
include $(mcal_PATH)/examples_config/Cdd_Flc_Demo_Cfg/srcs.mk
include $(mcal_PATH)/examples_config/Cdd_I2c_Demo_Cfg/srcs.mk
include $(mcal_PATH)/examples_config/Dio_Demo_Cfg/srcs.mk
include $(mcal_PATH)/examples_config/Dma_Demo_Cfg/srcs.mk
include $(mcal_PATH)/examples_config/Epwm_Demo_Cfg/srcs.mk
include $(mcal_PATH)/examples_config/Eth_Demo_Cfg/srcs.mk
include $(mcal_PATH)/examples_config/EthTrcv_Demo_Cfg/srcs.mk
include $(mcal_PATH)/examples_config/Fls_Demo_Cfg/srcs.mk
include $(mcal_PATH)/examples_config/FsiRx_Demo_Cfg/srcs.mk
include $(mcal_PATH)/examples_config/FsiTx_Demo_Cfg/srcs.mk
include $(mcal_PATH)/examples_config/Gpt_Demo_Cfg/srcs.mk
include $(mcal_PATH)/examples_config/Icu_Demo_Cfg/srcs.mk
include $(mcal_PATH)/examples_config/Ipc_Demo_Cfg/srcs.mk
include $(mcal_PATH)/examples_config/Lin_Demo_Cfg/srcs.mk
include $(mcal_PATH)/examples_config/Mcu_Demo_Cfg/srcs.mk
include $(mcal_PATH)/examples_config/Port_Demo_Cfg/srcs.mk
include $(mcal_PATH)/examples_config/Pwm_Demo_Cfg/srcs.mk
include $(mcal_PATH)/examples_config/Spi_Demo_Cfg/srcs.mk
include $(mcal_PATH)/examples_config/Uart_Demo_Cfg/srcs.mk
include $(mcal_PATH)/examples_config/Wdg_Demo_Cfg/srcs.mk

PACKAGE_SRCS_COMMON = .
CFLAGS_LOCAL_COMMON = $(MCAL_CFLAGS)

# Include common make files
include $(MAKERULEDIR)/common.mk
