[!IF "as:modconf('EthTrcv')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantLinkTime'"!]
/*
 * TEXAS INSTRUMENTS TEXT FILE LICENSE
 *
 * Copyright (c) 2022-2023 Texas Instruments Incorporated
 *
 * All rights reserved not granted herein.
 *
 * Limited License.
 *
 * Texas Instruments Incorporated grants a world-wide, royalty-free, non-exclusive
 * license under copyrights and patents it now or hereafter owns or controls to
 * make, have made, use, import, offer to sell and sell ("Utilize") this software
 * subject to the terms herein. With respect to the foregoing patent license,
 * such license is granted solely to the extent that any such patent is necessary
 * to Utilize the software alone. The patent license shall not apply to any
 * combinations which include this software, other than combinations with devices
 * manufactured by or for TI ("TI Devices"). No hardware patent is licensed hereunder.
 *
 * Redistributions must preserve existing copyright notices and reproduce this license
 * (including the above copyright notice and the disclaimer and (if applicable) source
 * code license limitations below) in the documentation and/or other materials provided
 * with the distribution.
 *
 * Redistribution and use in binary form, without modification, are permitted provided
 * that the following conditions are met:
 * No reverse engineering, decompilation, or disassembly of this software is
 * permitted with respect to any software provided in binary form.
 * Any redistribution and use are licensed by TI for use only with TI Devices.
 * Nothing shall obligate TI to provide you with source code for the software
 * licensed and provided to you in object code.
 *
 * If software source code is provided to you, modification and redistribution of the
 * source code are permitted provided that the following conditions are met:
 * Any redistribution and use of the source code, including any resulting derivative
 * works, are licensed by TI for use only with TI Devices.
 * Any redistribution and use of any object code compiled from the source code
 * and any resulting derivative works, are licensed by TI for use only with TI Devices.
 *
 * Neither the name of Texas Instruments Incorporated nor the names of its suppliers
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * DISCLAIMER.
 *
 * THIS SOFTWARE IS PROVIDED BY TI AND TI'S LICENSORS "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL TI AND TI'S
 * LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/**
 *  \file     EthTrcv_Lcfg.c
 *
 *  \brief    This file contains generated Link time configuration file for
 *            Ethernet Transceiver MCAL driver
 *
 */

 /*******************************************************************************
    Project: [!"$project"!]
    This file is generated by EB Tresos
    Do not modify this file, otherwise the software may behave in unexpected way.

*******************************************************************************/

/* Module switch */
#define ETHTRCV_LCFG_SOURCE
/*******************************************************************************
 * Standard Header Files
 ******************************************************************************/
/*******************************************************************************
 * Other Header Files
 ******************************************************************************/
#include "EthTrcv.h"

[!AUTOSPACING!]
/*******************************************************************************
 *  Version Check
 ******************************************************************************/
/*  Version checking  */
 #if ((ETHTRCV_SW_MAJOR_VERSION != ([!"substring-before($moduleSoftwareVer,'.')"!]U))||(ETHTRCV_SW_MINOR_VERSION != ([!"substring-before(substring-after($moduleSoftwareVer,'.'),'.')"!]U)))
  #error "Version numbers of EthTrcv_Lcfg.c and EthTrcv.h are inconsistent!"
#endif
#if ((ETHTRCV_CFG_MAJOR_VERSION != ([!"substring-before($moduleSoftwareVer,'.')"!]U)) || (ETHTRCV_CFG_MINOR_VERSION != ([!"substring-before(substring-after($moduleSoftwareVer,'.'),'.')"!]U)))
  #error "Version numbers of EthTrcv_Lcfg.c and EthTrcv_Cfg.h are inconsistent!"
#endif
/*******************************************************************************
 * Local Preprocessor #define Constants
 ******************************************************************************/
/*******************************************************************************
 * Local Preprocessor #define Macros
 ******************************************************************************/
/*******************************************************************************
 * Local Data Types and Structures
 ******************************************************************************/
/*******************************************************************************
 * Constants for Post-Build Configuration
 ******************************************************************************/
#define ETHTRCV_START_SEC_CONFIG_DATA
#include "EthTrcv_MemMap.h"

[!MACRO "TrcvSpeed2BaudRate", "ref" = ""!][!//
[!IF "$ref = 'TRCV_SPEED_10'"!][!//
(ETHTRCV_BAUD_RATE_10MBIT)[!//
[!ELSEIF "$ref = 'TRCV_SPEED_100'"!][!//
(ETHTRCV_BAUD_RATE_100MBIT)[!//
[!ENDIF!][!//
[!ENDMACRO!][!//
/*<ETHTRCV_CONFIG>*/
[!LOOP "as:modconf('EthTrcv')[1]/EthTrcvConfigSet/EthTrcvConfig/*"!][!//
VAR(struct EthTrcv_ControllerConfigType_s, ETHTRCV_CONFIG_DATA)
    [!"../../@name"!]_[!"@name"!] =
{
[!WS "4"!].ctrlIdx = [!"EthTrcvCtrlIdx"!]U,
[!WS "4"!].trcvIdx = [!"EthTrcvIdx"!]U,
[!WS "4"!].phyAddr = [!"EthTrcvMgmtInterface/*[1]/EthTrcvMiiIdx"!]U,
[!IF "node:exists(EthTrcvMgmtInterface/*[1]/EthTrcvMiiSelection)"!][!//
[!WS "4"!].MiiSel = [!"EthTrcvMgmtInterface/*[1]/EthTrcvMiiSelection"!],
[!ELSE!][!//
[!WS "0"!]0U,
[!ENDIF!][!//
[!WS "4"!].enableAutoNeg = (uint32 ) [!"text:toupper(EthTrcvAutoNegotiationEnabled)"!],
[!WS "4"!].connNeg = [!"EthTrcvConnNeg"!],
[!WS "4"!].advertiseCapab =
[!WS "8"!](0U
[!LOOP "EthTrcvPhyAdvertiseCapability/*"!]
[!WS "8"!]|[!"node:value(node:ref(node:current())/EthTrcvCapabTypeEnum)"!]
[!ENDLOOP!]
[!WS "8"!]),
[!WS "4"!].linkPartCapab =
[!WS "8"!](0U
				[!LOOP "EthTrcvLinkPartnerCapability/*"!]
[!WS "8"!]| [!"node:value(node:ref(node:current())/EthTrcvCapabTypeEnum)"!]
[!ENDLOOP!]
[!WS "8"!]),
[!WS "4"!].isGigCapab =  (uint32 )[!"text:toupper(EthTrcvGigabitCapabilityEnabled)"!],
[!WS "4"!].baudRate = [!CALL "TrcvSpeed2BaudRate","ref" = "EthTrcvSpeed"!],
[!WS "4"!].duplexMode = [!"EthTrcvDuplexMode"!],
[!WS "4"!].loopbackEnable = (boolean)[!"text:toupper(EthTrcvEnableLoopback)"!],
[!IF "(node:exists (EthTrcvPortMacLayerSpeed))"!][!//
[!WS "4"!].PortMacLaySpeed = [!"EthTrcvPortMacLayerSpeed/*"!],
[!ELSE!][!//
[!WS "4"!]0U,
[!ENDIF!][!//
[!IF "(node:exists (EthTrcvPortMacLayerSubType))"!][!//
[!WS "4"!].PortMacLaySubType = [!"EthTrcvPortMacLayerSubType/*"!],
[!ELSE!][!//
[!WS "4"!]0U,
[!ENDIF!][!//
[!IF "(node:exists (EthTrcvPortMacLayerType))"!][!//
[!WS "4"!].PortMacLayType = [!"EthTrcvPortMacLayerType/*"!],
[!ELSE!][!//
[!WS "4"!]0U,
[!ENDIF!][!//
[!IF "(node:exists (EthTrcvPhysLayerType))"!][!//
[!WS "4"!].PhysLayerType = [!"EthTrcvPhysLayerType/*"!]
[!ELSE!][!//
[!WS "4"!]0U
[!ENDIF!][!//
};

[!ENDLOOP!][!//

[!SELECT "as:modconf('EthTrcv')[1]/EthTrcvConfigSet"!][!///
VAR(struct EthTrcv_ConfigType_s, ETHTRCV_CONFIG_DATA)
    EthTrcv_Config =
{
   {
[!LOOP "as:modconf('EthTrcv')[1]/EthTrcvConfigSet/EthTrcvConfig/*"!]     (EthTrcv_ControllerConfigType*)&[!"../../@name"!]_[!"@name"!],
[!ENDLOOP!][!//
   }
};
[!ENDSELECT!][!//

/*</ETHTRCV_CONFIG>*/
#define ETHTRCV_STOP_SEC_CONFIG_DATA
#include "EthTrcv_MemMap.h"
/*******************************************************************************
 *  End of File: EthTrcv_Lcfg.c
 ******************************************************************************/
[!ELSE!]
/* The last generated configuration variant is not LINK-TIME variant. Refer EthTrcv_PBcfg.c/EthTrcv_Cfg.c. */
[!ENDIF!]
