/*
 * TEXAS INSTRUMENTS TEXT FILE LICENSE
 *
 * Copyright (c) 2023 Texas Instruments Incorporated
 *
 * All rights reserved not granted herein.
 *
 * Limited License.
 *
 * Texas Instruments Incorporated grants a world-wide, royalty-free, non-exclusive
 * license under copyrights and patents it now or hereafter owns or controls to
 * make, have made, use, import, offer to sell and sell ("Utilize") this software
 * subject to the terms herein. With respect to the foregoing patent license,
 * such license is granted solely to the extent that any such patent is necessary
 * to Utilize the software alone. The patent license shall not apply to any
 * combinations which include this software, other than combinations with devices
 * manufactured by or for TI ("TI Devices"). No hardware patent is licensed hereunder.
 *
 * Redistributions must preserve existing copyright notices and reproduce this license
 * (including the above copyright notice and the disclaimer and (if applicable) source
 * code license limitations below) in the documentation and/or other materials provided
 * with the distribution.
 *
 * Redistribution and use in binary form, without modification, are permitted provided
 * that the following conditions are met:
 * No reverse engineering, decompilation, or disassembly of this software is
 * permitted with respect to any software provided in binary form.
 * Any redistribution and use are licensed by TI for use only with TI Devices.
 * Nothing shall obligate TI to provide you with source code for the software
 * licensed and provided to you in object code.
 *
 * If software source code is provided to you, modification and redistribution of the
 * source code are permitted provided that the following conditions are met:
 * Any redistribution and use of the source code, including any resulting derivative
 * works, are licensed by TI for use only with TI Devices.
 * Any redistribution and use of any object code compiled from the source code
 * and any resulting derivative works, are licensed by TI for use only with TI Devices.
 *
 * Neither the name of Texas Instruments Incorporated nor the names of its suppliers
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * DISCLAIMER.
 *
 * THIS SOFTWARE IS PROVIDED BY TI AND TI'S LICENSORS "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL TI AND TI'S
 * LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

 /***************************************************************************
  Project: Mcal_Demo_Cfg


  This file is generated by EB Tresos
  Do not modify this file, otherwise the software may behave in unexpected way.

 *****************************************************************************/

/*
 * Module switch
 */
#define CAN_PBCFG_SOURCE
/**********************************************************************************************************************
 *  INCLUDES
 *********************************************************************************************************************/
 #include "Can.h"
 #include "Can_Cfg.h"

/**********************************************************************************************************************
 *  VERSION CHECK
 *********************************************************************************************************************/

/** \brief Can configuration Major Version */
#define CAN_PBCFG_C_MAJOR_VERSION           (10U)
/** \brief Can configuration Minor Version */
#define CAN_PBCFG_C_MINOR_VERSION           (2U)
/** \brief Can configuration Patch Version */
#define CAN_PBCFG_C_PATCH_VERSION           (2U)

/*  Version checking  */
 #if (   (CAN_SW_MAJOR_VERSION != (10U))||(CAN_SW_MINOR_VERSION != (2U)))
  #error "Version numbers of Can_PBcfg.c and Can.h are inconsistent!"
#endif
#if (   (CAN_CFG_MAJOR_VERSION != (10U))||(CAN_CFG_MINOR_VERSION != (2U)))
  #error "Version numbers of Can_PBcfg.c and Can_Cfg.h are inconsistent!"
#endif
/**********************************************************************************************************************
 *  GLOBAL DATA
 *********************************************************************************************************************/

#define CAN_START_SEC_VAR_INIT_UNSPECIFIED
#include "Can_MemMap.h"



/* Baud Rate Structure for all configsets */
static Can_BaudConfigType
    CanConfigSet_CanController_0_CanControllerBaudrateConfig_0 =
{
    1000U,      /* in Kbps */
    20U,       /* Prop Segement value */
    14U,          /* Phase Segment 1 */
    5U,          /* Phase Segment 2 */
    1U, /* Sync jump width */
    40U, /* Sum of all timing parameters */
    2U,   /* Controller BRP value for Baud */
	 /* Data phase Baudrate */
    {
        5000U,     /* in Kbps */
        3U,        /* Prop Segement value */
        3U,           /* Phase Segment 1 */
        1U,           /* Phase Segment 2 */
        1U,  /* Sync jump width */
        8U, /* Sum of all timing parameters */
        2U,   /* Controller BRP value for Baud */
        14U, /* Specifies the Transceiver Delay Compensation Offset */
        (boolean)TRUE, /* Specifies if the bit rate switching shall be used */
    }
};
static Can_BaudConfigType
    CanConfigSet_CanController_1_CanControllerBaudrateConfig_0 =
{
    1000U,      /* in Kbps */
    20U,       /* Prop Segement value */
    14U,          /* Phase Segment 1 */
    5U,          /* Phase Segment 2 */
    1U, /* Sync jump width */
    40U, /* Sum of all timing parameters */
    2U,   /* Controller BRP value for Baud */
	 /* Data phase Baudrate */
    {
        5000U,     /* in Kbps */
        3U,        /* Prop Segement value */
        3U,           /* Phase Segment 1 */
        1U,           /* Phase Segment 2 */
        1U,  /* Sync jump width */
        8U, /* Sum of all timing parameters */
        2U,   /* Controller BRP value for Baud */
        14U, /* Specifies the Transceiver Delay Compensation Offset */
        (boolean)TRUE, /* Specifies if the bit rate switching shall be used */
    }
};

/*List of the Baudrate structures */
static Can_BaudConfigType
    *CanConfigSet_CanController_0_BaudRateConfigList[]=
{
    &CanConfigSet_CanController_0_CanControllerBaudrateConfig_0,
};

static Can_BaudConfigType
    *CanConfigSet_CanController_1_BaudRateConfigList[]=
{
    &CanConfigSet_CanController_1_CanControllerBaudrateConfig_0,
};


/* Controller structure defined here for all config sets */
static Can_ControllerType
    CanConfigSet_CanController_0 =
{
    &CanConfigSet_CanController_0_CanControllerBaudrateConfig_0,  /* pointer to default Baud structure */
    CanConfigSet_CanController_0_BaudRateConfigList,  /* List of available Baudrate structs */
};
static Can_ControllerType
    CanConfigSet_CanController_1 =
{
    &CanConfigSet_CanController_1_CanControllerBaudrateConfig_0,  /* pointer to default Baud structure */
    CanConfigSet_CanController_1_BaudRateConfigList,  /* List of available Baudrate structs */
};

/*List of the Controller structures */
static Can_ControllerType
    *CanConfigSet_CanController_List[]=
{
    &CanConfigSet_CanController_0,
    &CanConfigSet_CanController_1,
};


static Can_HwFilterType
    CanConfigSet_CanHardwareObject_4_CanHwFilter_0 =
{
    193U,  /*CanHwFilterCode*/
    4294967295U,  /*Filter Mask*/
};
static Can_HwFilterType
    CanConfigSet_CanHardwareObject_5_CanHwFilter_0 =
{
    194U,  /*CanHwFilterCode*/
    4294967295U,  /*Filter Mask*/
};
static Can_HwFilterType
    CanConfigSet_CanHardwareObject_5_CanHwFilter_1 =
{
    195U,  /*CanHwFilterCode*/
    4294967295U,  /*Filter Mask*/
};
static Can_HwFilterType
    CanConfigSet_CanHardwareObject_6_CanHwFilter_0 =
{
    190U,  /*CanHwFilterCode*/
    4294967295U,  /*Filter Mask*/
};
static Can_HwFilterType
    CanConfigSet_CanHardwareObject_6_CanHwFilter_1 =
{
    193U,  /*CanHwFilterCode*/
    4294967295U,  /*Filter Mask*/
};
static Can_HwFilterType
    CanConfigSet_CanHardwareObject_7_CanHwFilter_0 =
{
    192U,  /*CanHwFilterCode*/
    4294967295U,  /*Filter Mask*/
};
static Can_HwFilterType
    CanConfigSet_CanHardwareObject_7_CanHwFilter_1 =
{
    64U,  /*CanHwFilterCode*/
    4294967295U,  /*Filter Mask*/
};

static Can_HwFilterType
    *CanConfigSet_CanHardwareObject_4_HwFilterConfigList[]=
{
    &CanConfigSet_CanHardwareObject_4_CanHwFilter_0,
};
static Can_HwFilterType
    *CanConfigSet_CanHardwareObject_5_HwFilterConfigList[]=
{
    &CanConfigSet_CanHardwareObject_5_CanHwFilter_0,
    &CanConfigSet_CanHardwareObject_5_CanHwFilter_1,
};
static Can_HwFilterType
    *CanConfigSet_CanHardwareObject_6_HwFilterConfigList[]=
{
    &CanConfigSet_CanHardwareObject_6_CanHwFilter_0,
    &CanConfigSet_CanHardwareObject_6_CanHwFilter_1,
};
static Can_HwFilterType
    *CanConfigSet_CanHardwareObject_7_HwFilterConfigList[]=
{
    &CanConfigSet_CanHardwareObject_7_CanHwFilter_0,
    &CanConfigSet_CanHardwareObject_7_CanHwFilter_1,
};
/* All the Mailbox objects(MB's) will be defined here for all config sets */
        
static Can_MailboxType
    CanConfigSet_CanHardwareObject_0 =
{
    0U,  /*  CanHandleType 0=Full, 1=Basic */
    2U,  /* CanIdType 0=standard 1=Extended 2=Mixed*/
    0U,  /* HwHandle i.e Mailbox - Hw object in the controller */
    1U,   /* Length of the Mailbox */
    CAN_MAILBOX_DIRECTION_TX,  /* CanObjectType - Direction of Mailbox*/
    &CanConfigSet_PC_CanController_0,  /* Controller */
    NULL_PTR,  /* List of HW Filter structs */
    0U,   /* Hw Filter Count */
    204U,   /* Padding value for CAN FD message */
    (boolean)TRUE,  /* CanHardwareObjectUsesPolling */
    (boolean)FALSE,  /* CanTriggerTransmitEnable */
	};

static Can_MailboxType
    CanConfigSet_CanHardwareObject_1 =
{
    0U,  /*  CanHandleType 0=Full, 1=Basic */
    2U,  /* CanIdType 0=standard 1=Extended 2=Mixed*/
    1U,  /* HwHandle i.e Mailbox - Hw object in the controller */
    1U,   /* Length of the Mailbox */
    CAN_MAILBOX_DIRECTION_TX,  /* CanObjectType - Direction of Mailbox*/
    &CanConfigSet_PC_CanController_0,  /* Controller */
    NULL_PTR,  /* List of HW Filter structs */
    0U,   /* Hw Filter Count */
    204U,   /* Padding value for CAN FD message */
    (boolean)FALSE,  /* CanHardwareObjectUsesPolling */
    (boolean)FALSE,  /* CanTriggerTransmitEnable */
	};

static Can_MailboxType
    CanConfigSet_CanHardwareObject_2 =
{
    0U,  /*  CanHandleType 0=Full, 1=Basic */
    2U,  /* CanIdType 0=standard 1=Extended 2=Mixed*/
    2U,  /* HwHandle i.e Mailbox - Hw object in the controller */
    3U,   /* Length of the Mailbox */
    CAN_MAILBOX_DIRECTION_TX,  /* CanObjectType - Direction of Mailbox*/
    &CanConfigSet_PC_CanController_1,  /* Controller */
    NULL_PTR,  /* List of HW Filter structs */
    0U,   /* Hw Filter Count */
    204U,   /* Padding value for CAN FD message */
    (boolean)TRUE,  /* CanHardwareObjectUsesPolling */
    (boolean)FALSE,  /* CanTriggerTransmitEnable */
	};

static Can_MailboxType
    CanConfigSet_CanHardwareObject_3 =
{
    0U,  /*  CanHandleType 0=Full, 1=Basic */
    2U,  /* CanIdType 0=standard 1=Extended 2=Mixed*/
    3U,  /* HwHandle i.e Mailbox - Hw object in the controller */
    5U,   /* Length of the Mailbox */
    CAN_MAILBOX_DIRECTION_TX,  /* CanObjectType - Direction of Mailbox*/
    &CanConfigSet_PC_CanController_1,  /* Controller */
    NULL_PTR,  /* List of HW Filter structs */
    0U,   /* Hw Filter Count */
    204U,   /* Padding value for CAN FD message */
    (boolean)FALSE,  /* CanHardwareObjectUsesPolling */
    (boolean)FALSE,  /* CanTriggerTransmitEnable */
	};

static Can_MailboxType
    CanConfigSet_CanHardwareObject_4 =
{
    1U,  /*  CanHandleType 0=Full, 1=Basic */
    2U,  /* CanIdType 0=standard 1=Extended 2=Mixed*/
    0U,  /* HwHandle i.e Mailbox - Hw object in the controller */
    1U,   /* Length of the Mailbox */
    CAN_MAILBOX_DIRECTION_RX,  /* CanObjectType - Direction of Mailbox*/
    &CanConfigSet_PC_CanController_0,  /* Controller */
    CanConfigSet_CanHardwareObject_4_HwFilterConfigList,  /* List of HW Filter structs */
    1U, /* Hw Filter Count */
    204U,   /* Padding value for CAN FD message */
    (boolean)TRUE,  /* CanHardwareObjectUsesPolling */
	    (boolean)FALSE,   /* CanTriggerTransmitEnable */
};

static Can_MailboxType
    CanConfigSet_CanHardwareObject_5 =
{
    1U,  /*  CanHandleType 0=Full, 1=Basic */
    2U,  /* CanIdType 0=standard 1=Extended 2=Mixed*/
    1U,  /* HwHandle i.e Mailbox - Hw object in the controller */
    1U,   /* Length of the Mailbox */
    CAN_MAILBOX_DIRECTION_RX,  /* CanObjectType - Direction of Mailbox*/
    &CanConfigSet_PC_CanController_0,  /* Controller */
    CanConfigSet_CanHardwareObject_5_HwFilterConfigList,  /* List of HW Filter structs */
    2U, /* Hw Filter Count */
    204U,   /* Padding value for CAN FD message */
    (boolean)FALSE,  /* CanHardwareObjectUsesPolling */
	    (boolean)FALSE,   /* CanTriggerTransmitEnable */
};

static Can_MailboxType
    CanConfigSet_CanHardwareObject_6 =
{
    1U,  /*  CanHandleType 0=Full, 1=Basic */
    2U,  /* CanIdType 0=standard 1=Extended 2=Mixed*/
    0U,  /* HwHandle i.e Mailbox - Hw object in the controller */
    1U,   /* Length of the Mailbox */
    CAN_MAILBOX_DIRECTION_RX,  /* CanObjectType - Direction of Mailbox*/
    &CanConfigSet_PC_CanController_1,  /* Controller */
    CanConfigSet_CanHardwareObject_6_HwFilterConfigList,  /* List of HW Filter structs */
    2U, /* Hw Filter Count */
    204U,   /* Padding value for CAN FD message */
    (boolean)TRUE,  /* CanHardwareObjectUsesPolling */
	    (boolean)FALSE,   /* CanTriggerTransmitEnable */
};

static Can_MailboxType
    CanConfigSet_CanHardwareObject_7 =
{
    0U,  /*  CanHandleType 0=Full, 1=Basic */
    2U,  /* CanIdType 0=standard 1=Extended 2=Mixed*/
    0U,  /* HwHandle i.e Mailbox - Hw object in the controller */
    5U,   /* Length of the Mailbox */
    CAN_MAILBOX_DIRECTION_RX,  /* CanObjectType - Direction of Mailbox*/
    &CanConfigSet_PC_CanController_1,  /* Controller */
    CanConfigSet_CanHardwareObject_7_HwFilterConfigList,  /* List of HW Filter structs */
    2U, /* Hw Filter Count */
    204U,   /* Padding value for CAN FD message */
    (boolean)FALSE,  /* CanHardwareObjectUsesPolling */
	    (boolean)FALSE,   /* CanTriggerTransmitEnable */
};



/* List of the Mailboxes */
static Can_MailboxType
    *CanConfigSet_CanHardwareObject_List[] =
{
    &CanConfigSet_CanHardwareObject_0,
    &CanConfigSet_CanHardwareObject_1,
    &CanConfigSet_CanHardwareObject_2,
    &CanConfigSet_CanHardwareObject_3,
    &CanConfigSet_CanHardwareObject_4,
    &CanConfigSet_CanHardwareObject_5,
    &CanConfigSet_CanHardwareObject_6,
    &CanConfigSet_CanHardwareObject_7,
};
#define CAN_STOP_SEC_VAR_INIT_UNSPECIFIED
#include "Can_MemMap.h"

#define CAN_START_SEC_CONFIG_DATA
#include "Can_MemMap.h"
/*Can Config struct */
const struct Can_ConfigType_s Can_Config =
{
    CanConfigSet_CanController_List,    /* List of all controllers in this config set */
    (2U),    /* max Controllers */
    CanConfigSet_CanHardwareObject_List,
    (8U),    /* total number of mail boxes in this configset */
    .MaxBaudConfigID =
    {
        [0] = 0U,
        [1] = 0U
    }
};
#define  CAN_STOP_SEC_CONFIG_DATA
#include "Can_MemMap.h"

/*********************************************************************************************************************
 *  End of File: Can_PBcfg.c
 *********************************************************************************************************************/
