[!IF "as:modconf('Eth')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPostBuild'"!]
/* ======================================================================
 *   Copyright (c) 2022-2023 Texas Instruments Incorporated
 *
 *   All rights reserved. Property of Texas Instruments Incorporated.
 *   Restricted rights to use, duplicate or disclose this code are
 *   granted through contract.
 *
 *   The program may not be used without the written permission
 *   of Texas Instruments Incorporated or against the terms and conditions
 *   stipulated in the agreement under which this program has been
 *   supplied.
 * ==================================================================== */

 /**
 *  \file     Eth_PBCfg.c
 *
 *  \brief    This file contains generated post build configuration file
 *            for ETH MCAL driver
 */

/*******************************************************************************
    Project: [!"$project"!]
    This file is generated by EB Tresos
    Do not modify this file, otherwise the software may behave in unexpected way
*******************************************************************************/

/*******************************************************************************
 * Standard Header Files
 ******************************************************************************/

/*******************************************************************************
 * Other Header Files
 ******************************************************************************/
#include "Eth.h"

/*******************************************************************************
 *  Version Check
 ******************************************************************************/

/*  Version checking  */
 #if ((ETH_SW_MAJOR_VERSION != ([!"substring-before($moduleSoftwareVer,'.')"!]U))||(ETH_SW_MINOR_VERSION != ([!"substring-before(substring-after($moduleSoftwareVer,'.'),'.')"!]U)))
  #error "Version numbers of Eth_PBcfg.c and Eth.h are inconsistent!"
#endif

#if ((ETH_CFG_MAJOR_VERSION != ([!"substring-before($moduleSoftwareVer,'.')"!]U)) || (ETH_CFG_MINOR_VERSION != ([!"substring-before(substring-after($moduleSoftwareVer,'.'),'.')"!]U)))
  #error "Version numbers of Eth_PBcfg.c and Eth_Cfg.h are inconsistent!"
#endif

/*******************************************************************************
 * Constants for Post-Build Configuration
 ******************************************************************************/
#define  ETH_START_SEC_CONFIG_DATA
#include "Eth_MemMap.h"

#ifdef __cplusplus
extern "C" {
#endif

[!AUTOSPACING!]

[!VAR "notifyFxnList" = "' '"!]
[!LOOP "as:modconf('Eth')[1]/EthConfigSet/EthCtrlConfig/*"!][!//
[!IF "not(node:empty(EthCacheFlushOps)) and not(text:match(EthCacheFlushOps,'NULL_PTR'))"!][!//
[!IF "not(node:containsValue(text:split($notifyFxnList),node:value(EthCacheFlushOps)))"!][!//
[!"concat('extern void ',EthCacheFlushOps,'(uint8 *BufPtr, uint32 LenByte);')"!]
[!VAR "notifyFxnList" = "concat($notifyFxnList,' ',EthCacheFlushOps)"!][!//
[!ENDIF!][!//
[!ENDIF!][!//
[!IF "not(node:empty(EthInvalidateOps)) and not(text:match(EthInvalidateOps,'NULL_PTR'))"!][!//
[!IF "not(node:containsValue(text:split($notifyFxnList),node:value(EthInvalidateOps)))"!][!//
[!"concat('extern void ',EthInvalidateOps,'(uint8 *BufPtr, uint32 LenByte);')"!]
[!VAR "notifyFxnList" = "concat($notifyFxnList,' ',EthInvalidateOps)"!][!//
[!ENDIF!][!//
[!ENDIF!][!//
[!ENDLOOP!][!//

/* generation of runtime configuration       */
/*<ETH_CONFIG>*/
[!LOOP "as:modconf('Eth')[1]/EthConfigSet/EthCtrlConfig/*"!]
[!IF "as:modconf('Eth')[1]/EthGeneral/EthTrafficShapingSupport = 'true'"!]
[!VAR "VarRateLimit" = "0"!]
[!ENDIF!]
VAR(struct Eth_ConfigType_s, ETH_PBCFG)
    [!"../../@name"!]_[!"@name"!] =
{
       .ctrlIdx = [!"EthCtrlIdx"!]U,
	   .portIdx = [!"EthPort"!],
       .portCfg =
       {
            .macCfg =
            {
                [!VAR "macModeFlag" = "'(0U '"!]
                [!LOOP "EthPortConfig/EthMacConfig/EthMacModeFlags/*"!]
                    [!VAR "macModeFlag"="concat($macModeFlag,' | ',.)"!]
                [!ENDLOOP!]
                [!VAR "macModeFlag"="concat($macModeFlag," )")"!]
                .macModeFlags = [!"$macModeFlag"!],
                .macConnectionType = (Eth_MacConnectionType)[!"EthPortConfig/EthMacConfig/EthMacConnectionType"!],
                .macAddr =
                {
                    [!IF "not(node:empty(EthCtrlPhyAddress/*))"!]
                    [!LOOP "text:split(EthCtrlPhyAddress/*,'-')"!]
                    0x[!"."!]U,
                    [!ENDLOOP!]
                    [!ELSE!]
                    NULL,NULL,NULL,NULL,NULL,NULL
                    [!ENDIF!]
                },
            },
       },
       .traffiShapingCfg =
       {
           
           [!LOOP "EthCpswQoSCfg/*"!]
           .enableQoS = [!IF "as:modconf('Eth')[1]/EthGeneral/EthTrafficShapingSupport = 'true'"!] 0x1U,
           [!ELSE!] 0x0U,
           [!ENDIF!]
           .prioArray = 
           {
                [!LOOP "EthCpswRateLimitCfg/*"!]
                [!IF "as:modconf('Eth')[1]/EthGeneral/EthTrafficShapingSupport = 'true'"!]
                    [!IF "not(node:empty(EthCpswRateLimitPrio))"!]
                    [!"EthCpswRateLimitPrio"!],
                        [!ASSERT "num:i(EthCpswRateLimitPrio) < '201'","STOP: Bandwidth cannot be greater than 200 Mbps num:i(EthCpswRateLimitPrio)"!]
                    [!ELSE!]
                    0U,
                    [!ENDIF!]
                [!ELSE!]
                0U,
                [!ENDIF!]
                [!ENDLOOP!]
            },
            [!ENDLOOP!]
            
       },

[!IF "EthCtrlEnableMii = 'true'"!]
#if (STD_ON == ETH_ENABLE_MII_API)
       .mdioCfg =
       {
           [!LOOP "EthMdioConfig/*"!]
           .mdioBusFreq = (uint32)[!"EthMdioBusFreq"!]U,
           .mdioClockFreq = (uint32) [!"EthMdioClockFreq"!]U
           [!ENDLOOP!]
       },
#endif
[!ENDIF!]
       .cpdmaCfg =
       {
            .pacingClkFreq = (uint32)[!"EthCpdmaConfig/EthPacingClkFreq"!]U,
            .rxInterruptPacingEnabled = (uint32) [!"text:toupper(EthCpdmaConfig/EthRxInterruptPacingEnabled)"!],
            .rxInterruptsPerMsec = [!"EthCpdmaConfig/EthRxInterruptPerMsec"!]U,
            .txInterruptPacingEnabled = (uint32) [!"text:toupper(EthCpdmaConfig/EthTxInterruptPacingEnabled)"!],
            .txInterruptsPerMsec = [!"EthCpdmaConfig/EthTxInterruptPerMsec"!]U,
            .dmaModeFlags = [!"EthCpdmaConfig/EthDmaModeFlags"!]U,
            .rxThreshCount = [!"EthCpdmaConfig/EthRxThresholdCount"!]U,
       },
#if (ETH_GLOBALTIMESUPPORT_API == STD_ON)
       .cptsCfg =
       {
           [!LOOP "EthCptsConfig/*"!]
           .cptsInputFreq = [!"EthCptsInputFreq"!]U,
           .vlanType      = [!"EthCptsVlanType"!],
           .msgTypeCfg    = (0U
                            [!LOOP "EthCptsMessageCfg/*"!]
                            | [!"EthCptsMessageCfgEnum"!]
                            [!ENDLOOP!]
                            )
           [!ENDLOOP!]
       },
#endif

       .enableCacheOps = (uint32)[!"text:toupper(string(EthEnableCacheOps))"!],
	   
       .cacheFlushOps = (Eth_CacheFlushType) [!IF "EthEnableCacheOps = 'true'"!][!"EthCacheFlushOps"!][!ELSE!]NULL_PTR[!ENDIF!],

       .cacheInvalidateOps = (Eth_CacheInvalidateType) [!IF "EthEnableCacheOps = 'true'"!][!"EthInvalidateOps"!][!ELSE!]NULL_PTR[!ENDIF!]
};
[!ENDLOOP!]
/*</ETH_CONFIG>*/

#ifdef __cplusplus
}
#endif
#define  ETH_STOP_SEC_CONFIG_DATA
#include "Eth_MemMap.h"

#define  ETH_START_SEC_VAR_INIT_UNSPECIFIED
#include "Eth_MemMap.h"
#ifdef __cplusplus
extern "C" {
#endif
/**
 *  \brief Eth  controller configuration set pointer
 */
P2CONST(Eth_ConfigType, ETH_VAR_NO_INIT, ETH_APPL_CONST) Eth_CfgPtr;

#ifdef __cplusplus
}
#endif
#define  ETH_STOP_SEC_VAR_INIT_UNSPECIFIED
#include "Eth_MemMap.h"

/*******************************************************************************
 *  End of File: Eth_PBcfg.c
 ******************************************************************************/
[!ELSE!]
/* The last generated configuration variant is not 
       POST-BUILD variant. Refer Eth_Cfg.c/Eth_Lcfg.c. */
[!ENDIF!]
