/*
 * TEXAS INSTRUMENTS TEXT FILE LICENSE
 *
 * Copyright (c) 2023 Texas Instruments Incorporated
 *
 * All rights reserved not granted herein.
 *
 * Limited License.
 *
 * Texas Instruments Incorporated grants a world-wide, royalty-free, non-exclusive
 * license under copyrights and patents it now or hereafter owns or controls to
 * make, have made, use, import, offer to sell and sell ("Utilize") this software
 * subject to the terms herein. With respect to the foregoing patent license,
 * such license is granted solely to the extent that any such patent is necessary
 * to Utilize the software alone. The patent license shall not apply to any
 * combinations which include this software, other than combinations with devices
 * manufactured by or for TI ("TI Devices"). No hardware patent is licensed hereunder.
 *
 * Redistributions must preserve existing copyright notices and reproduce this license
 * (including the above copyright notice and the disclaimer and (if applicable) source
 * code license limitations below) in the documentation and/or other materials provided
 * with the distribution.
 *
 * Redistribution and use in binary form, without modification, are permitted provided
 * that the following conditions are met:
 * No reverse engineering, decompilation, or disassembly of this software is
 * permitted with respect to any software provided in binary form.
 * Any redistribution and use are licensed by TI for use only with TI Devices.
 * Nothing shall obligate TI to provide you with source code for the software
 * licensed and provided to you in object code.
 *
 * If software source code is provided to you, modification and redistribution of the
 * source code are permitted provided that the following conditions are met:
 * Any redistribution and use of the source code, including any resulting derivative
 * works, are licensed by TI for use only with TI Devices.
 * Any redistribution and use of any object code compiled from the source code
 * and any resulting derivative works, are licensed by TI for use only with TI Devices.
 *
 * Neither the name of Texas Instruments Incorporated nor the names of its suppliers
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * DISCLAIMER.
 *
 * THIS SOFTWARE IS PROVIDED BY TI AND TI'S LICENSORS "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL TI AND TI'S
 * LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/**
 *  \file     Gpt_Cfg.h
 *
 *  \brief    This file contains generated pre compile configuration file
 *            for GPT MCAL driver
 *
 */

 /*********************************************************************************************************************
    Project: Mcal_Demo_Cfg

	10.2.2
	4.6.0
	AUTOSAR 4.3.1 0

    This file is generated by EB Tresos
    Do not modify this file, otherwise the software may behave in unexpected way.

 *********************************************************************************************************************/


#ifndef GPT_CFG_H_
#define GPT_CFG_H_

/**
 * \addtogroup GPT Gpt API GUIDE Header file
 * @{
 */

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */

#include "Os.h"


#ifdef __cplusplus
extern "C" {
#endif

#ifndef DOXYGEN_SHOULD_SKIP_THIS

/* ========================================================================== */
/*                           Macros & Typedefs                                */
/* ========================================================================== */
/**
 *  \name Gpt Driver Configuration SW Version Info
 *
 *  Defines for Gpt Driver configuration version
 *  @{
 */
/** \brief Gpt configuration Major Version */
#define GPT_CFG_MAJOR_VERSION           (10U)
/** \brief Gpt configuration Minor Version */
#define GPT_CFG_MINOR_VERSION           (2U)
/** \brief Gpt configuration Patch Version */
#define GPT_CFG_PATCH_VERSION           (2U)
/* @} */

/** \brief GPT Config ID */
#define GPT_CFG_ID                      (0x1U)



/**
*  \brief GPT Build Variant.
*   Build variants.(i.e Pre Compile,Post Build or Link time)
*/
#define GPT_PRE_COMPILE_VARIANT       (STD_OFF)

#define GPT_POST_BUILD_VARIANT        (STD_ON)




/** \brief Enable/disable GPT dev detect error */
/* Requirements: ECUC_Gpt_00321 */
#define GPT_DEV_ERROR_DETECT                (STD_ON)

/** \brief ISR type */
#define GPT_ISR_TYPE                (GPT_ISR_CAT1)

/** \brief Enable/disable wakeup source in wakeup related APIs */
/* Requirements: ECUC_Gpt_00322 */
#define GPT_REPORT_WAKEUP_SOURCE            (STD_OFF)

/**
 *  \name Pre-Compile Switches for API Services
 *  @{
 */
/** \brief Enable/disable GPT get version info API */
#define GPT_VERSION_INFO_API                           (STD_ON)
/** \brief Enable/disable GPT deinit API */
#define GPT_DEINIT_API                                 (STD_ON)
/** \brief Enable/disable GPT get time elapsed API */
#define GPT_TIME_ELAPSED_API                           (STD_ON)
/** \brief Enable/disable GPT time remaining API */
#define GPT_TIME_REMAINING_API                         (STD_ON)
/** \brief Enable/disable GPT enable/disable GPT API */
#define GPT_ENABLE_DISABLE_NOTIFICATION_API            (STD_ON)
/** \brief Enable/disable GPT wakeup functionality API */
#define GPT_WAKEUP_FUNCTIONALITY_API                   (STD_OFF)
/* @} */

/** \brief No. of channels configured for GPT driver */
#define GPT_MAX_CHANNELS                                    (28U)


/** \brief GP timer channels available for AM263Px */
#define GPT_RTI_CH_MIN              (0U)

#define GPT_RTI_CH_MAX              (31U)

#define GPT_RTI_MAX              	(32U)

/*
 * GPT channels available for user
 */
/** \brief Module 1 */
#define GPT_RTI_CHANNEL1            (0U)
#define GPT_RTI_CHANNEL2            (1U)
#define GPT_RTI_CHANNEL3            (2U)
#define GPT_RTI_CHANNEL4            (3U)
/** \brief Module 2 */
#define GPT_RTI_CHANNEL5            (4U)
#define GPT_RTI_CHANNEL6            (5U)
#define GPT_RTI_CHANNEL7            (6U)
#define GPT_RTI_CHANNEL8            (7U)
/** \brief Module 3 */
#define GPT_RTI_CHANNEL9            (8U)
#define GPT_RTI_CHANNEL10           (9U)
#define GPT_RTI_CHANNEL11           (10U)
#define GPT_RTI_CHANNEL12           (11U)
/** \brief Module 4 */
#define GPT_RTI_CHANNEL13           (12U)
#define GPT_RTI_CHANNEL14           (13U)
#define GPT_RTI_CHANNEL15           (14U)
#define GPT_RTI_CHANNEL16           (15U)
/** \brief Module 4 */
#define GPT_RTI_CHANNEL17           (16U)
#define GPT_RTI_CHANNEL18           (17U)
#define GPT_RTI_CHANNEL19           (18U)
#define GPT_RTI_CHANNEL20           (19U)
/** \brief Module 5 */
#define GPT_RTI_CHANNEL21           (20U)
#define GPT_RTI_CHANNEL22           (21U)
#define GPT_RTI_CHANNEL23           (22U)
#define GPT_RTI_CHANNEL24           (23U)
/** \brief Module 6 */
#define GPT_RTI_CHANNEL25           (24U)
#define GPT_RTI_CHANNEL26           (25U)
#define GPT_RTI_CHANNEL27           (26U)
#define GPT_RTI_CHANNEL28           (27U)
/** \brief Module 7 */
#define GPT_RTI_CHANNEL29           (28U)
#define GPT_RTI_CHANNEL30           (29U)
#define GPT_RTI_CHANNEL31           (30U)
#define GPT_RTI_CHANNEL32           (31U)

/*
 * GPT counters available for user
 */
/** \brief Counter Block 0 */
#define GPT_RTI_COUNTER0            (0U)
/** \brief Counter Block 1 */
#define GPT_RTI_COUNTER1            (1U)
/** \brief Number of Counter Blocks per RTI Module */
#define GPT_RTI_COUNTERS            (2U)

/*
 * GPT RTI modules available for user
 */
/** \brief GP timer A instance */
#define GPT_RTI_MODULE1             (0U)
/** \brief GP timer B instance */
#define GPT_RTI_MODULE2             (1U)
/** \brief GP timer C instance */
#define GPT_RTI_MODULE3             (2U)
/** \brief GP timer D instance */
#define GPT_RTI_MODULE4             (3U)
/** \brief GP timer E instance */
#define GPT_RTI_MODULE5             (4U)
/** \brief GP timer F instance */
#define GPT_RTI_MODULE6             (5U)
/** \brief GP timer G instance */
#define GPT_RTI_MODULE7             (6U)
/** \brief GP timer H instance */
#define GPT_RTI_MODULE8             (7U)
/** \brief Number of GPT Modules */
#define GPT_RTI_MODULES             (8U)

/** \brief Macro for enabling predefined timers
 *        This is in case to disable GPT Predef Timers if timers can not be
 *        supported by hardware reasons.
 */
/* Requirements: SWS_Gpt_00385 */
/* Requirements: ECUC_Gpt_00335 */
#define GPT_PREDEF_TIMER_TYPE   (GPT_PREDEF_TIMER_DISABLED)

/** \brief: Specifies the grade of enabling the GPT Predef Timers with 1s
 *         tick duration */
#define GPT_PREDEF_TIMER_1US_ENABLING_GRADE   (GPT_PREDEF_UNDEFINED)


 #define GPT_CHANNEL_4
 #define GPT_CHANNEL_5
 #define GPT_CHANNEL_6
 #define GPT_CHANNEL_7
 #define GPT_CHANNEL_8
 #define GPT_CHANNEL_9
 #define GPT_CHANNEL_10
 #define GPT_CHANNEL_11
 #define GPT_CHANNEL_12
 #define GPT_CHANNEL_13
 #define GPT_CHANNEL_14
 #define GPT_CHANNEL_15
 #define GPT_CHANNEL_16
 #define GPT_CHANNEL_17
 #define GPT_CHANNEL_18
 #define GPT_CHANNEL_19
 #define GPT_CHANNEL_20
 #define GPT_CHANNEL_21
 #define GPT_CHANNEL_22
 #define GPT_CHANNEL_23
 #define GPT_CHANNEL_24
 #define GPT_CHANNEL_25
 #define GPT_CHANNEL_26
 #define GPT_CHANNEL_27
 #define GPT_CHANNEL_28
 #define GPT_CHANNEL_29
 #define GPT_CHANNEL_30
 #define GPT_CHANNEL_31

 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_5 (4U)
 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_6 (5U)
 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_7 (6U)
 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_8 (7U)
 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_9 (8U)
 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_10 (9U)
 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_11 (10U)
 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_12 (11U)
 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_13 (12U)
 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_14 (13U)
 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_15 (14U)
 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_16 (15U)
 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_17 (16U)
 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_18 (17U)
 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_19 (18U)
 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_20 (19U)
 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_21 (20U)
 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_22 (21U)
 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_23 (22U)
 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_24 (23U)
 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_25 (24U)
 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_26 (25U)
 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_27 (26U)
 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_28 (27U)
 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_29 (28U)
 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_30 (29U)
 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_31 (30U)
 #define GptConf_GptChannelConfiguration_GptChannelConfiguration_32 (31U)


/** \brief Counter ID for counter used to count wait ticks */
#define GPT_OS_COUNTER_ID               ((CounterType)OsCounter_0)

/**
 *  \brief GPT timeout.
 *   Each tick is 31.25us (for 32K Counter). Wait for 5s which comes to
 *   below value
 */
#define GPT_TIMEOUT_DURATION            (32000U)

/** \brief Enable/disable GPT register read back API */
#define GPT_REGISTER_READBACK_API               (STD_OFF)

#define SOC_RTI1_REG_BASE       (0x52180000U)
#define SOC_RTI2_REG_BASE       (0x52181000U)
#define SOC_RTI3_REG_BASE       (0x52182000U)
#define SOC_RTI4_REG_BASE       (0x52183000U)
#define SOC_RTI5_REG_BASE       (0x52184000U)
#define SOC_RTI6_REG_BASE       (0x52185000U)
#define SOC_RTI7_REG_BASE       (0x52186000U)
#define SOC_RTI8_REG_BASE       (0x52187000U)

/*********************************************************************************************************************
 *  Exported Object Declarations
 *********************************************************************************************************************/
extern const uint32 Gpt_RTIChannelAddr[GPT_RTI_MODULES];


extern const struct Gpt_ConfigType_s Gpt_Config;


#endif /* DOXYGEN_SHOULD_SKIP_THIS */

/* ========================================================================== */
/*                          Function Declarations                             */
/* ========================================================================== */

/* None */

#ifdef __cplusplus
}
#endif

/**
* @}
 */

#endif  /* #ifndef GPT_CFG_H_ */

