/* ======================================================================
 *   Copyright (C) 2024 Texas Instruments Incorporated

 *
 *   All rights reserved. Property of Texas Instruments Incorporated.
 *   Restricted rights to use, duplicate or disclose this code are
 *   granted through contract.
 *
 *   The program may not be used without the written permission
 *   of Texas Instruments Incorporated or against the terms and conditions
 *   stipulated in the agreement under which this program has been
 *   supplied.
 * ==================================================================== */

/**
 *  \file     Cdd_Dma_Cfg.h
 *
 *  \brief    This file contains generated pre compile configuration file
 *            for Complex device driver
 */

  /*********************************************************************************************************************
    Project: dma_am273x
    Date   : 2024-02-10 13:55:04

    This file is generated by EB Tresos
    Do not modify this file, otherwise the software may behave in unexpected way.

 *********************************************************************************************************************/

/**
 *  \defgroup CDD_DMA_CFG  CDD DMA Configuration
 *
 *  This files defines CDD DMA configuration structures
 *  @{
 */

#ifndef CDD_DMA_CFG_H_
#define CDD_DMA_CFG_H_

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */
#include "Std_Types.h"
#include "Os.h"
#include "Dem.h"
#include "Cdd_Dma.h"

#include "Det.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 *  \name CDD DMA Driver Configuration SW Version Info
 *
 *  Defines for CDD DMA Driver configuration version
 *  @{
 */
/** \brief CDD DMA configuration Major Version */
#define CDD_DMA_MAJOR_VERSION                 (10U)
/** \brief CDD DMA configuration Minor Version */
#define CDD_DMA_MINOR_VERSION    (2U)
/** \brief CDD DMA configuration Patch Version */
#define CDD_DMA_PATCH_VERSION                 (0U)
/* @} */

/* ========================================================================== */
/*                           Macros & Typedefs                                */
/* ========================================================================== */

/** \brief CDD DMA Config ID */
#define CDD_DMA_ID                                                        (0x1U)

/** \brief Enable/Disable CDD DMA dev detect error */
/* Requirements: ___ */
#define CDD_DMA_DEV_ERROR_DETECT                                          (STD_ON)

/**
 *  \name Pre-Compile Switches for API Services
 */
/** \brief Enable/Disable CDD DMA get version info API */
#define CDD_DMA_VERSION_INFO_API                                          (STD_ON)
#define CDD_DMA_DEINIT_API                                                (STD_ON)
#define CDD_DMA_REGISTER_READBACK_API                                     (STD_ON)

#define CDD_DMA_MAX_HANDLER                                               9U
#define CDD_DMA_MAX_CHANNEL                                               2U
#define CDD_DMA_MAX_PARAM                                                 2U

/** \brief CDD DMA Interrupt Service Routine Category */
#define CDD_DMA_ISR_TYPE                                                  CDD_DMA_ISR_VOID

/** \brief CDD DMA resources amount */
#define CDD_DMA_NUM_DMACH_SOC                                             64U
#define CDD_DMA_NUM_PARAMSETS_SOC                                         256U

/** \brief CDD DMA Instances */
#define CDD_DMA_RCSS_A                                                    0U
#define CDD_DMA_MSS_A                                                     1U
#define CDD_DMA_MSS_B                                                     2U
#define CDD_DMA_DSS_A                                                     3U
#define CDD_DMA_DSS_B                                                     4U
#define CDD_DMA_DSS_C                                                     5U

/** \brief CSL Base Addresses for Sitara MCAL2X */
#define MCAL_MSS_CTRL_U_BASE                                              (0x2120000U)
#define MCAL_RCSS_TPCC_A_U_BASE                                           (0x5100000U)
#define MCAL_MSS_TPCC_A_U_BASE                                            (0x3100000U)
#define MCAL_MSS_TPCC_B_U_BASE                                            (0x3120000U)
#define MCAL_DSS_TPCC_A_U_BASE                                            (0x6100000U)
#define MCAL_DSS_TPCC_B_U_BASE                                            (0x6120000U)
#define MCAL_DSS_TPCC_C_U_BASE                                            (0x6140000U)

/** \brief CDD DMA Completion Interrupt Number */
#define MCAL_MSS_INTR_RCSS_TPCC_A_INTAGG                                  151
#define MCAL_MSS_INTR_MSS_TPCC_A_INTAGG                                   67
#define MCAL_MSS_INTR_MSS_TPCC_B_INTAGG                                   68
#define MCAL_MSS_INTR_DSS_TPCC_A_INTAGG                                   120
#define MCAL_MSS_INTR_DSS_TPCC_B_INTAGG                                   122
#define MCAL_MSS_INTR_DSS_TPCC_C_INTAGG                                   124

/** \brief CDD DMA field MSS and DSS TPCC Adresseses for Interrupt Aggregate */
#define MCAL_RCSS_CTRL_RCSS_TPCC_A_INTAGG_MASK                            (0x00000014U)
#define MCAL_RCSS_CTRL_RCSS_TPCC_A_INTAGG_STATUS                          (0x00000018U)
#define MCAL_MSS_CTRL_MSS_TPCC_A_INTAGG_MASK                              (0x0000017CU)
#define MCAL_MSS_CTRL_MSS_TPCC_A_INTAGG_STATUS                            (0x00000180U)
#define MCAL_MSS_CTRL_MSS_TPCC_B_INTAGG_MASK                              (0x00000194U)
#define MCAL_MSS_CTRL_MSS_TPCC_B_INTAGG_STATUS                            (0x00000198U)
#define MCAL_DSS_CTRL_DSS_TPCC_A_INTAGG_MASK                              (0x00000024U)
#define MCAL_DSS_CTRL_DSS_TPCC_A_INTAGG_STATUS                            (0x00000028U)
#define MCAL_DSS_CTRL_DSS_TPCC_B_INTAGG_MASK                              (0x0000003CU)
#define MCAL_DSS_CTRL_DSS_TPCC_B_INTAGG_STATUS                            (0x00000040U)
#define MCAL_DSS_CTRL_DSS_TPCC_C_INTAGG_MASK                              (0x00000054U)
#define MCAL_DSS_CTRL_DSS_TPCC_C_INTAGG_STATUS                            (0x00000058U)

/** \brief CDD DMA  Shift Mask. */
#define CDD_DMA_CSL_R5_MPIDR_AFF0_MASK                                   (0x000000FFU)
#define CDD_DMA_CSL_R5_MPIDR_AFF0_SHIFT                                  (0U)
#define CDD_DMA_CSL_R5_MPIDR_AFF1_MASK                                   (0x0000FF00U)
#define CDD_DMA_CSL_R5_MPIDR_AFF1_SHIFT                                  (8U)

/** \brief CDD DMA  Base address. */
#define CDD_DMA_CSL_MSS_CTRL_U_BASE                                      (0x2120000U)

/** \brief CDD DMA Lock Step. */
#define CDD_DMA_CSL_MSS_CTRL_R5_STATUS_REG_R5_STATUS_REG_LOCK_STEP_MASK       (0x00000100U)
#define CDD_DMA_CSL_MSS_CTRL_R5_STATUS_REG_R5_STATUS_REG_LOCK_STEP_SHIFT      (0x00000008U)
#define CDD_DMA_CSL_MSS_CTRL_R5_STATUS_REG_R5_STATUS_REG_LOCK_STEP_RESETVAL   (0x00000000U)
#define CDD_DMA_CSL_MSS_CTRL_R5_STATUS_REG_R5_STATUS_REG_LOCK_STEP_MAX        (0x00000001U)

/** \brief CDD DMA RAM Size and address. */
#define CDD_DMA_CSL_MSS_TCMA_RAM_SIZE               (0x00008000U)
#define CDD_DMA_CSL_MSS_TCMB_RAM_SIZE               (0x00008000U)
#define CDD_DMA_CSL_MSS_TCMA_RAM_BASE               (0x00000000U)
#define CDD_DMA_CSL_MSS_TCMB_RAM_BASE               (0x00080000U)

#define CDD_DMA_CSL_MSS_TCMA_CR5A_U_BASE            (0xC1000000U)
#define CDD_DMA_CSL_MSS_TCMB_CR5A_U_BASE            (0xC1800000U)
#define CDD_DMA_CSL_MSS_TCMA_CR5B_U_BASE            (0xC3000000U)
#define CDD_DMA_CSL_MSS_TCMB_CR5B_U_BASE            (0xC3800000U)
#define CDD_DMA_CSL_MSS_L2_U_BASE                   (0x10200000U)
#define CDD_DMA_CSL_MSS_L2_RAM_BASE                 CDD_DMA_CSL_MSS_L2_U_BASE
#define CDD_DMA_CSL_MSS_L2_U_SIZE                   (0x000F0000U)
#define CDD_DMA_CSL_MSS_L2_RAM_SIZE                 CDD_DMA_CSL_MSS_L2_U_SIZE
#define CDD_DMA_CSL_GLOB_MSS_L2_RAM_BASE            (0xC0200000U)

/* PRE-COMPLIE variant related macro(s) */
#define CDD_DMA_PRE_COMPILE_VARIANT                                       STD_ON


/* ========================================================================== */
/*                         Structures and Enums                               */
/* ========================================================================== */

/**
 *  \brief This type defines a range of specific status for Complex driver
 */
/** Requirements :  SitaraMCU_MCAL-__ */
/** Design: SitaraMCU_MCAL-__ */
typedef enum
{
    /**< The Complex Driver is not initialized or not usable */
    CDD_DMA_UNINIT =       0U,
    /**< The Complex Driver is not currently transferring */
    CDD_DMA_IDLE =         1U,
    /**< The Complex Driver is currently open */
    CDD_DMA_ALLOW_ACCESS = 2U,
    /**< The Complex Driver is performing a write operation */
    CDD_DMA_BUSY =         3U,
    /**< The Complex Driver is currently closed */
    CDD_DMA_CLOSE =        4U,
} CddDma_StatusType;

#define CddDmaConf_CddDmaDriverHandler_0_Uart_Tx  0
#define CddDmaConf_CddDmaDriverHandler_0_Uart_Rx  1
#define CddDmaConf_CddDmaDriverHandler_1_Uart_Tx  2
#define CddDmaConf_CddDmaDriverHandler_1_Uart_Rx  3
#define CddDmaConf_CddDmaDriverHandler_0_Qspi  4
#define CddDmaConf_CddDmaDriverHandler_MemoryTransfer_Interrupt  5
#define CddDmaConf_CddDmaDriverHandler_MemoryTransfer_Linking  6
#define CddDmaConf_CddDmaDriverHandler_MemoryTransfer_Polling  7
#define CddDmaConf_CddDmaDriverHandler_MemoryTransfer_Chaining  8

/** \brief Cdd Configuration struct declaration */
extern CONST(Cdd_Dma_ConfigType, CDD_DMA_CFG) CddDmaDriverHandler;
extern volatile uint8 Cdd_Dma_handleAlreadyInUse[CDD_DMA_MAX_HANDLER];
/* ========================================================================== */
/*                          Function Declarations                             */
/* ========================================================================== */
extern void Cdd_Dma_TrigXbar(void);
extern void Cdd_Dma_Xbar(void);

#ifdef __cplusplus
}
#endif

#endif  /* #ifndef CDD_DMA_CFG_H_ */

/* @} */
