[!IF "as:modconf('Dio')[1]/IMPLEMENTATION_CONFIG_VARIANT = 'VariantPreCompile'"!]
/* ======================================================================
 *   Copyright (c) 2022-2023 Texas Instruments Incorporated
 *
 *   All rights reserved. Property of Texas Instruments Incorporated.
 *   Restricted rights to use, duplicate or disclose this code are
 *   granted through contract.
 *
 *   The program may not be used without the written permission
 *   of Texas Instruments Incorporated or against the terms and conditions
 *   stipulated in the agreement under which this program has been
 *   supplied.
 * ==================================================================== */
/***********************************************************************
    Project: [!"$project"!]
	

    This file is generated by EB Tresos
    Do not modify this file, otherwise the software may behave in
	unexpected way.

 ***********************************************************************/
/**
 *  \file     Dio_Cfg.c
 *
 *  \brief    This file contains generated link time configuration file
 *            for DIO MCAL driver
 *
 */

/**********************************************************************************************************************
 *  INCLUDES
 *********************************************************************************************************************/
#include "Std_Types.h"
#include "Dio.h"


/**********************************************************************************************************************
 *  VERSION CHECK
 *********************************************************************************************************************/
#if ((DIO_CFG_MAJOR_VERSION != ([!"substring-before($moduleSoftwareVer,'.')"!]U))||(DIO_CFG_MINOR_VERSION != ([!"substring-before(substring-after($moduleSoftwareVer,'.'),'.')"!]U)))
  #error "Version numbers of Dio_Cfg.c and Dio_Cfg.h are inconsistent!"
#endif

/**********************************************************************************************************************
 *  GLOBAL DATA
 **********************************************************************************************************************/
#define DIO_START_SEC_CONFIG_DATA
/* MISRAC_19.1 "Reason - This is the format for specifying memory sections" */
#include "Dio_MemMap.h"

/*<DIO_CFG_GROUP_LIST>*/
[!LOOP "as:modconf('Dio')[1]/DioConfig/DioPort/*"!][!//
[!VAR "ChGroupNumber" = "0"!][!//
[!LOOP "DioChannelGroup/*"!][!//
[!VAR "ChGroupNumber"="$ChGroupNumber+1"!][!//
[!ENDLOOP!][!//
[!VAR "Index2" = "num:i(@index)"!][!//
[!VAR "Index1" = "1"!][!//
[!LOOP "DioChannelGroup/*"!][!//
[!IF "not(node:empty(DioPortMask)) and num:i($Index1) != '0'"!][!//
CONST(Dio_ChannelGroupType, DIO_CONST) [!"../../../../@name"!]_[!"../../@name"!]_ChannelGroup[[!"num:i($ChGroupNumber)"!]] =
{
[!LOOP "as:modconf('Dio')[1]/DioConfig/DioPort/*"!][!//
[!VAR "Index3" = "num:i(@index)"!][!//
[!LOOP "DioChannelGroup/*"!][!//
[!IF "(node:containsValue($Index3,$Index2)) and num:i($Index1) != '0' "!][!//
    [[!"@index"!]] =
	{
		.port =   [!"../../DioPortId"!]U,
		.mask =   [!"num:inttohex(DioPortMask,8)"!]U,
		.offset = [!"num:i(DioPortOffset)"!]U,
	},
[!ENDIF!][!//
[!ENDLOOP!][!//
[!ENDLOOP!][!//
[!VAR "Index1" = "0"!][!//
};[!CR!]
[!ENDIF!][!//
[!ENDLOOP!][!//
[!ENDLOOP!][!//

[!VAR "Index4" = "0"!][!//
[!LOOP "as:modconf('Dio')[1]/DioConfig/DioPort/*"!][!//
[!VAR "Index2" = "num:i(@index)"!][!//
[!VAR "Index1" = "1"!][!//
[!LOOP "DioChannelGroup/*"!][!//
[!IF "not(node:empty(DioPortMask)) and num:i($Index1) = '1'"!][!//
[!LOOP "as:modconf('Dio')[1]/DioConfig/DioPort/*"!][!//
[!VAR "Index5" = "num:i(@index)"!][!//
[!LOOP "DioChannelGroup/*"!][!//
[!IF "(node:containsValue($Index5,$Index2)) and num:i($Index1) = '1' "!][!//
[!VAR "Index4" = "$Index4+1"!][!//
[!ENDIF!][!//
[!ENDLOOP!][!//
[!ENDLOOP!][!//
[!VAR "Index1" = "2"!][!//
P2CONST(void,AUTOMATIC,  DIO_CONST) [!"../../../../@name"!]_[!"../../@name"!]_ChannelGroupRef[[!"num:i($Index4)"!]] =
{
[!LOOP "as:modconf('Dio')[1]/DioConfig/DioPort/*"!][!//
[!VAR "Index3" = "num:i(@index)"!][!//
[!VAR "ChannelGroupDefName" = "concat(../../@name,'_',@name,'_ChannelGroup')"!][!//
[!LOOP "DioChannelGroup/*"!][!//
[!IF "(node:containsValue($Index3,$Index2)) and num:i($Index1) = '2' "!][!//
    [[!"@index"!]] = &[!"concat($ChannelGroupDefName,'[',num:i(@index),']')"!],
[!ENDIF!][!//
[!ENDLOOP!][!//
[!ENDLOOP!][!//
[!VAR "Index1" = "0"!][!//
[!VAR "Index4" = "0"!][!//
};[!CR!]
[!ENDIF!][!//
[!ENDLOOP!][!//
[!ENDLOOP!][!//

CONST(uint32,DIO_CONST) DioConfig_ValidChannelMask[DIO_MAX_NO_OF_PORTS] =
{
[!LOOP "as:modconf('Dio')[1]/DioConfig/DioPort/*"!][!//
    [[!"DioPortId"!]] = (0U
[!LOOP "DioChannel/*"!][!//
        | (1U << [!"num:i(DioChannelId mod 32)"!]U)
[!ENDLOOP!][!//
    ),
[!ENDLOOP!][!//
};

/*</DIO_CFG_GROUP_LIST>*/

#define DIO_STOP_SEC_CONFIG_DATA
#include "Dio_MemMap.h"

/**********************************************************************************************************************
 *  END OF FILE: DIO_CFG.C
 *********************************************************************************************************************/
[!ELSE!]
/* The last generated configuration variant is not
PRE-COMPILE variant. Refer Dio_Lcfg.c. */
[!ENDIF!]