/* ======================================================================
 *   Copyright (C) 2025 Texas Instruments Incorporated
 *
 *   All rights reserved. Property of Texas Instruments Incorporated.
 *   Restricted rights to use, duplicate or disclose this code are
 *   granted through contract.
 *
 *   The program may not be used without the written permission
 *   of Texas Instruments Incorporated or against the terms and conditions
 *   stipulated in the agreement under which this program has been
 *   supplied.
 * ==================================================================== */

/**
 *  \file     Cdd_Uart_Cfg.h
 *
 *  \brief    This file contains generated configuration file for
 *            UART Complex Device Driver
 */

  /*********************************************************************************************************************
    Project: Mcal_Demo_Cfg

    This file is generated by EB Tresos
    Do not modify this file, otherwise the software may behave in unexpected way.

 *********************************************************************************************************************/

#ifndef CDD_UART_CFG_H_
#define CDD_UART_CFG_H_

/**
 * \addtogroup UART Uart
 * @{
 */

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */
#include "Std_Types.h"
#include "Os.h"
#include "Dem.h"
#include "Det.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DOXYGEN_SHOULD_SKIP_THIS

/**
 *  \name CDD UART Driver Configuration SW Version Info
 *
 *  Defines for CDD UART Driver configuration version
 *  @{
 */
/** \brief CDD UART configuration Major Version */
#define CDD_UART_CFG_MAJOR_VERSION                 (10U)
/** \brief CDD UART configuration Minor Version */
#define CDD_UART_CFG_MINOR_VERSION                 (2U)
/** \brief CDD UART configuration Patch Version */
#define CDD_UART_CFG_PATCH_VERSION                 (1U)
/* @} */

/* ========================================================================== */
/*                           Macros & Typedefs                                */
/* ========================================================================== */

/** \brief CDD UART Config ID */
#define CDD_UART_CFG_ID                            (0x1U)

/** \brief Enable/disable CDD UART dev detect error */
#define CDD_UART_DEV_ERROR_DETECT                  STD_ON


#define CDD_UART_DMA_ENABLE                        STD_ON

#define CDD_UART_ISR_TYPE                          CDD_UART_ISR_VOID

/** \brief CDD UART Channel Hardware IDs */
#define CDD_UART_CHANNEL_ID_0                      (0)
#define CDD_UART_CHANNEL_ID_1                      (1)
#define CDD_UART_CHANNEL_ID_2                      (2)
#define CDD_UART_CHANNEL_ID_3                      (3)
#define CDD_UART_CHANNEL_ID_4                      (4)
#define CDD_UART_CHANNEL_ID_5                      (5)

/**
 *  \name CDD UART transaction modes
 */
/*
 * Design: MCAL-22580,MCAL-22581,MCAL-22582
 */
/** \brief Polling mode */
#define CDD_UART_MODE_POLLING                      (0U)
/** \brief Interrupt mode */
#define CDD_UART_MODE_INTERRUPT                    (1U)
/** \brief DMA mode */
#define CDD_UART_MODE_DMA                          (3U)

/**
 *  \name CDD UART word length
 */
/*
 * Design: MCAL-22574
 */
/** \brief Word Length 5 */
#define CDD_UART_WORD_LENGTH_5                     (0U)
/** \brief Word Length 6 */
#define CDD_UART_WORD_LENGTH_6                     (1U)
/** \brief Word Length 7 */
#define CDD_UART_WORD_LENGTH_7                     (2U)
/** \brief Word Length 8 */
#define CDD_UART_WORD_LENGTH_8                     (3U)

/**
 *  \name CDD UART parity types
 */
/*
 * Design: MCAL-22575,MCAL-22576,MCAL-22577
 */
/** \brief None Parity */
#define CDD_UART_PARITY_NONE                       (0U)
/** \brief Odd Parity */
#define CDD_UART_PARITY_ODD                        (1U)
/** \brief Even Parity */
#define CDD_UART_PARITY_EVEN                       (3U)

/**
 *  \name CDD UART Transmit/Receive trigger levels
 */
/** \brief Trigger Level 1 */
#define CDD_UART_TRIGGER_LEVEL_1                   (1U)
/** \brief Trigger Level 8 */
#define CDD_UART_TRIGGER_LEVEL_8                   (8U)
/** \brief Trigger Level 16 */
#define CDD_UART_TRIGGER_LEVEL_16                  (16U)
/** \brief Trigger Level 32 */
#define CDD_UART_TRIGGER_LEVEL_32                  (32U)
/** \brief Trigger Level 56 */
#define CDD_UART_TRIGGER_LEVEL_56                  (56U)
/** \brief Trigger Level 60 */
#define CDD_UART_TRIGGER_LEVEL_60                  (60U)

/**
 *  \name CDD UART operational modes
 */
/** \brief UART13X mode */
#define CDD_UART_13x_OPER                          (3U)
/** \brief UART16X mode */
#define CDD_UART_16x_OPER                          (0U)
/** \brief UART16X AUTO mode */
#define CDD_UART_16x_AUTO_OPER                     (2U)

/**
 *  \name CDD UART read return modes
 */
/** \brief Full read return mode */
#define CDD_UART_FULL_READ_RETURN                  (0U)
/** \brief Partial read return mode */
#define CDD_UART_PARTIAL_READ_RETURN               (1U)

/**
 *  \name CDD UART stop bits
 */
/*
 * Design: MCAL-22578,MCAL-22579
 */
/** \brief Stop Bit 1 */
#define CDD_UART_STOP_BIT_1                        (0U)
/** \brief Stop Bit 2 */
#define CDD_UART_STOP_BITS_2                       (1U)

/**
 *  \name Pre-Compile Switches for API Services
 */
/** \brief Enable/disable CDD UART Get version info API */
#define CDD_UART_VERSION_INFO_API                  STD_ON
/** \brief Enable/disable CDD UART Register Readback API */
#define CDD_UART_REGISTER_READBACK_API             STD_OFF
/** \brief Enable/disable CDD UART DeInit API */
#define CDD_UART_DEINIT_API                        STD_ON
/** \brief Enable/disable CDD UART Write API */
#define CDD_UART_WRITE_API                         STD_ON
/** \brief Enable/disable CDD UART Read API */
#define CDD_UART_READ_API                          STD_ON
/** \brief Enable/disable CDD UART Cancel API */
#define CDD_UART_CANCEL_API                        STD_ON
/** \brief Enable/disable CDD UART GetRemainingWords API */
#define CDD_UART_GETREMAININGWORDS_API             STD_ON

/** \brief total number of UART channels allocated */
#define CDD_UART_NUM_CHANNELS                      1U

/** \brief Counter ID for counter used to count wait ticks */
#define CDD_UART_OS_COUNTER_ID                     ((CounterType)OsCounter_0)

/** \brief Symbolic Names for UART channels */
#define CddUartConf_CddUartChannelConfiguration_CddUartChannel_0 (0U)

#define CDD_UART_PRE_COMPILE_VARIANT               STD_ON
#define CDD_UART_INIT_CONFIG_PC                    Cdd_Uart_Config

/** \brief Enable/disable UART per-channel ISR */


/** \brief Maximum Channels or UART Instances on Board */
#define CDD_UART_MAXIMUM_CHANNELS                  6U

/* UART maximum channels check to ensure it is within bounds */
#if ((CDD_UART_NUM_CHANNELS < 1U) || (CDD_UART_NUM_CHANNELS > CDD_UART_MAXIMUM_CHANNELS))
    #error "CDD UART: Unsupported maximum channels in use"
#endif

#endif /* DOXYGEN_SHOULD_SKIP_THIS */

/* ========================================================================== */
/*                         Structures and Enums                               */
/* ========================================================================== */

/**
 *  \brief This type defines a range of specific status for UART Complex Driver
 */
typedef enum
{
    /** \brief The UART Complex Driver is not initialized or not usable */
    CDD_UART_UNINIT =       0U,
    /** \brief The UART Complex Driver is not currently transferring */
    CDD_UART_INIT =         1U,
    /** \brief The UART Complex Driver is performing a read/write operation */
    CDD_UART_BUSY =         2U,
} Cdd_Uart_StatusType;

/* CDD UART Notification Callbacks*/
/**
 * \brief UART notification callbacks structure
 *
 * Design: MCAL-22583, MCAL-22590
 */
typedef struct
{
    /** \brief UART Read Notification Handler */
    void (*uartNotificationReadHandler)(void);
    /** \brief UART Write Notification Handler */
    void (*uartNotificationWriteHandler)(void);
    /** \brief UART Error Notification Handler */
    void (*uartNotificationErrorHandler)(void);
} Cdd_Uart_NotifCallbacks;

/* CDD UART Config type */
/**
 *
 * \brief UART configuration type data structure for a channel
 *
 * Design: MCAL-22572,MCAL-22573,MCAL-22574,MCAL-22575,MCAL-22576,MCAL-22577,MCAL-22578,MCAL-22579,MCAL-22580,MCAL-22581,MCAL-22582
 */
typedef struct
{
    /** \brief CoreID on which the UART is instantiated */
    uint32 uartHwUnitID;
    /** \brief Clock Frequency */
    uint32 uartClockFrequency;
    /** \brief Baud Rate for signal transfer */
    uint32 uartBaudRate;
    /** \brief IO Mode for signal transfer */
    uint32 uartIOMode;
    /** \brief Trigger level for Transmission of signal */
    uint32 uartTXTriggerLevel;
    /** \brief Trigger level for Receival of signal */
    uint32 uartRXTriggerLevel;
    /** \brief Trigger threshold for signal flow control */
    uint32 uartHwFlowControlThreshold;
    /** \brief Word Length for packets */
    uint32 uartWordLength;
    /** \brief Parity for data */
    uint32 uartParity;
    /** \brief Read return mode */
    uint32 uartReadReturnMode;
    /** \brief Mode of Operation */
    uint32 uartOperatingMode;
    /** \brief Amount of stop bits per packet */
    uint32 uartStopBits;
    /** \brief UART EDMA Reception DMA Handle ID (reference from DMA configuration) */
    uint8 edmaXbarRxHandleID;
    /** \brief UART EDMA Transmission DMA Handle ID (reference from DMA configuration) */
    uint8 edmaXbarTxHandleID;
    /** \brief Callback Handles */
    Cdd_Uart_NotifCallbacks uartNotificationHandlers;
} Cdd_Uart_ConfigType;

/* CDD UART Configurations type */
/**
 *
 *  \brief UART configuration type structure for all channels in use
 */
typedef struct
{
    /** \brief Count of channels configured */
    uint8 netChannels;
    /** \brief Channel Configurations */
    Cdd_Uart_ConfigType channelCfg[CDD_UART_NUM_CHANNELS];
} Cdd_Uart_CfgType;

/** \brief CDD Uart Configuration struct declaration */
extern CONST(Cdd_Uart_CfgType, CDD_UART_CFG)Cdd_Uart_Config;

#ifdef __cplusplus
}
#endif

/**
* @}
*/

#endif  /* #ifndef CDD_UART_CFG_H_ */
