/* ======================================================================
 *   Copyright (c) 2022-2023 Texas Instruments Incorporated
 *
 *   All rights reserved. Property of Texas Instruments Incorporated.
 *   Restricted rights to use, duplicate or disclose this code are
 *   granted through contract.
 *
 *   The program may not be used without the written permission
 *   of Texas Instruments Incorporated or against the terms and conditions
 *   stipulated in the agreement under which this program has been
 *   supplied.
 * ==================================================================== */

/**
 *  \file     Port_Cfg.h
 *
 *  \brief    This file contains generated pre compile configuration file
 *            for PORT MCAL driver
 *
 */

/**
 *  \defgroup MCAL_PORT_CFG PORT Configuration
 *
 *  This files defines PORT MCAL configuration structures
 *  @{
 */

/**********************************************************************************************************************
    Project: am2732s_i2c_port
    Date   : 2024-02-16 15:20:42

    This file is generated by EB Tresos
    Do not modify this file, otherwise the software may behave in unexpected way.

 *********************************************************************************************************************/
#ifndef PORT_CFG_H
#define PORT_CFG_H

/**********************************************************************************************************************
 * INCLUDES
 *********************************************************************************************************************/
#include "Std_Types.h"

#include "Dem.h"
#include "Os.h"

#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************************************************************
 *  GLOBAL CONSTANT MACROS
 *********************************************************************************************************************/
/** \brief PORT Config ID */
#define PORT_CFG_ID                      (0x1U)

/**
 *  \name Port Driver Configuration SW Version Info
 *
 *  Defines for Port Driver configuration version
 *  @{
 */
/** \brief Port configuration Major Version */
#define PORT_CFG_MAJOR_VERSION           (10U)
/** \brief Port configuration Minor Version */
#define PORT_CFG_MINOR_VERSION    (2U)
/** \brief Port configuration Patch Version */
#define PORT_CFG_PATCH_VERSION           (0U)
/* @} */


/**
*  \brief PORT Build Variant.
*   Build variants.(i.e Pre Compile,Post Build)
*/
#define PORT_PRE_COMPILE_VARIANT   (STD_OFF)

#define PORT_POST_BUILD_VARIANT    (STD_ON)



/*
*Design: MCAL-14021,MCAL-14036, MCAL-13988
*/
/* List of symbolic names for Dio pin channels */
/*<PORT_PIN_CHANNEL_LIST>*/


#define PortConf_PortPin_GPIOA_0 (47U)

#define PortConf_PortPin_GPIOA_1 (55U)

#define PortConf_PortPin_GPIOA_2 (50U)



#define PortConf_PortPin_UARTA_TX (101U)

#define PortConf_PortPin_UARTA_RX (80U)



#define PortConf_PortPin_MCANA_RX (13U)

#define PortConf_PortPin_MCANA_TX (5U)

#define PortConf_PortPin_MCANB_RX (81U)

#define PortConf_PortPin_MCANB_TX (6U)



#define PortConf_PortPin_MSS_QSPI_CLK (30U)

#define PortConf_PortPin_MSS_QSPI_CS (40U)

#define PortConf_PortPin_MSS_QSPI_D0 (21U)

#define PortConf_PortPin_MSS_QSPI_D1 (27U)

#define PortConf_PortPin_MSS_QSPI_D2 (24U)

#define PortConf_PortPin_MSS_QSPI_D3 (34U)



#define PortConf_PortPin_MSS_MIBSPIB_CLK (25U)

#define PortConf_PortPin_MSS_MIBSPIB_CS0 (26U)

#define PortConf_PortPin_MSS_MIBSPIB_CS1 (32U)

#define PortConf_PortPin_MSS_MIBSPIB_CS2 (31U)

#define PortConf_PortPin_MSS_MIBSPIB_MISO (20U)

#define PortConf_PortPin_MSS_MIBSPIB_MOSI (79U)



#define PortConf_PortPin_EPWMA_0 (35U)



#define PortConf_PortPin_PortPin_0 (44U)



#define PortConf_PortPin_GPIO28 (46U)

#define PortConf_PortPin_GPIO49 (33U)

#define PortConf_PortPin_GPIO11 (18U)



#define PortConf_PortPin_I2CA_SCL (38U)

#define PortConf_PortPin_I2CA_SDA (37U)


/*</PORT_PIN_CHANNEL_LIST>*/

/**
 *  \name Port Driver Maximum number of configured pins.
 */
#define PORT_MAX_PIN_CONFIG					28U


/**
 *  \name Port Driver Maximum Dio Interrupts configured.
 */
#define PORT_MAX_GPIO_INTR_CONFIG			2U


/**
 *  \name Port Driver Maximum number of modes per pin
 *
 *  Maximum number of runtime changeable port pin modes per pin
 *  This value is calculated based on actual configuration and is
 *  not the maximum number of modes supported by SoC (16)
 *  @{
 */
#define PORT_MAX_MUXMODE (1U)
/* @} */

/** \brief Interrupt SubRoutine type */
#define PORT_ISR_TYPE     PORT_ISR_CAT1

/**
 *  \name Service enable/diable defines
 *
 *  Pre-compile switches for enabling/disabling PORT MCAL APIs
 *  @{
 */
/** \brief Enable/Disable Port_SetPinDirection() */
#define PORT_SET_PIN_DIRECTION_API       (STD_ON)
/** \brief Enable/Disable Port_RefreshPinDirection() */
#define PORT_REFRESH_PORT_DIRECTION_API  (STD_ON)
/** \brief Enable/Disable Port_GetVersionInfo() */
#define PORT_VERSION_INFO_API            (STD_ON)
/** \brief Enable/Disable Port_SetPinMode() */
#define PORT_SET_PIN_MODE_API            (STD_ON)
/** \brief Enable/Disable development error detection */
#define PORT_DEV_ERROR_DETECT            (STD_ON)
/** \brief Enable/Disable SAFETI Configuration register readback */
#define PORT_SAFETI_API                      (STD_OFF)
/** \brief enable/disable the use of Interrupt Functionality */
#define PORT_ENABLE_INTR_API             (STD_ON)
/* @} */

/**********************************************************************************************************************
 *  STATIC TESTS
 *********************************************************************************************************************/


/** \brief Counter ID for counter used to count wait ticks */
#define PORT_OS_COUNTER_ID               ((CounterType)OsCounter_0)

/**
*  \brief PORT timeout.
*   Each tick is 31.25us (for 32K Counter). Wait for 5s which comes to
*   below value
*/
#define PORT_TIMEOUT_DURATION            (32000U)

/* DEM Error Definitions */

#ifndef PORT_E_HARDWARE_ERROR
/** \brief Hardware failed */
#define PORT_E_HARDWARE_ERROR          (DemConf_DemEventParameter_PORT_E_HARDWARE_ERROR)
#endif
/* ========================================================================== */
/*                         Structures and Enums                               */
/* ========================================================================== */

/*
*Design: MCAL-13973, MCAL-14024, MCAL-13989
*/
/**
 *  \brief Enum of Port Direction used in Port_SetPinDirection()
 */
typedef enum
{
    PORT_PIN_IN,
    /**< PORT_PIN_IN */
    PORT_PIN_OUT,
    /**< PORT_PIN_OUT */
    PORT_PIN_DEFAULT
    /**< PORT_PIN_DEFAULT */
} Port_PinDirectionType;

/**
 *  \brief Enum of Port Level
 */
typedef enum
{
    PORT_PIN_LEVEL_LOW,
    PORT_PIN_LEVEL_HIGH
} Port_PinLevelValueType;

/**
 *  \brief Enum of Port Slew Control
 */
typedef enum
{
    PORT_PIN_SLEWCONTROL_SLOW_SLEW,
    PORT_PIN_SLEWCONTROL_FAST_SLEW,
    PORT_PIN_SLEWCONTROL_DEFAULT
} Port_PinSlewControlType;

/**
 *  \brief Enum of Port Pin Output override selection
 */
typedef enum
{
    PORT_PIN_DISABLE_OUTPUT_OVERRIDE,
    PORT_PIN_ENABLE_OUTPUT_OVERRIDE,
    PORT_PIN_OUTPUT_RETAIN_HW_CTRL
} Port_PinOutputOverrideCtrl;

/**
 *  \brief Enum of Port Pin Input override selection
 */
typedef enum
{
    PORT_PIN_DISABLE_INPUT_OVERRIDE,
    PORT_PIN_ENABLE_INPUT_OVERRIDE,
    PORT_PIN_INPUT_RETAIN_HW_CTRL
} Port_PinInputOverrideCtrl;

/**
 *  \brief Enum of Port Pin Up/Down Type selection
 */
typedef enum
{
    PORT_PIN_PULLTYPE_PULLDOWN,
    PORT_PIN_PULLTYPE_PULLUP,
    PORT_PIN_PULLTYPE_DEFAULT
} Port_PinPullSelectType;


/**
 *  \brief Enum of Port Pin pull inihibit selection
 */
typedef enum
{
    PORT_PIN_PULL_INHIBIT_ENABLE,
    PORT_PIN_PULL_INHIBIT_DISABLE,
    PORT_PIN_PULL_INHIBIT_DEFAULT

} Port_PinPullInhibitEnableType;


/** \brief Type for symbolic name of Port pins */
typedef uint16 Port_PinType;


/*
*Design: MCAL-14019, MCAL-13996, MCAL-14037, MCAL-14043
*/
/**
 *  \brief Enum of Port Pin Mode selection
 *
 *  Module level pin enable is workaround since MCAL configurator is not
 *  available. Will be removed in the next release
 */
typedef enum
{
    PORT_PIN_MODE_MSS_GPIOA,
    /**< Set Pin for GPIO Port A mode */
    PORT_PIN_MODE_MSS_GPIOB,
    /**< Set Pin for GPIO Port B mode */
    PORT_PIN_MODE_MSS_GPIOC,
    /**< Set Pin for GPIO Port C mode */
    PORT_PIN_MODE_MSS_GPIOD,
    /**< Set Pin for GPIO Port D mode */

	PORT_PIN_MODE_RCSS_GPIOA,
    /**< Set Pin for RCSS GPIO Port A mode */
    PORT_PIN_MODE_RCSS_GPIOB,
    /**< Set Pin for RCSS GPIO Port B mode */
    PORT_PIN_MODE_RCSS_GPIOC,
    /**< Set Pin for RCSS GPIO Port C mode */
    PORT_PIN_MODE_RCSS_GPIOD,
    /**< Set Pin for RCSS GPIO Port D mode */

    PORT_PIN_MODE_MSS_EPWM1,
    /**< Set Pin for EPWM1A mode */
    PORT_PIN_MODE_MSS_EPWM2,
    /**< Set Pin for EPWM2A mode */
    PORT_PIN_MODE_MSS_EPWM3,
    /**< Set Pin for EPWM3A mode */
    PORT_PIN_MODE_MSS_MCANA,
    /**< Set Pin for MCANA (CAN FD) mode */
    PORT_PIN_MODE_MSS_MCANB,
    /**< Set Pin for MCANB(CAN FD) mode */
    PORT_PIN_MODE_MSS_MIBSPIA,
    /**< Set Pin for MIBSPI mode */
    PORT_PIN_MODE_MSS_MIBSPIB,
    /**< Set Pin for MIBSPI mode */
    PORT_PIN_MODE_MSS_QSPI,
    /**< Set Pin for QSPI mode */
    PORT_PIN_MODE_JTAG,
    /**< Set Pin for JTAG mode */
    PORT_PIN_MODE_MSS_RS232,
    /**< Set Pin for RS232 mode */
    PORT_PIN_MODE_TRACE,
    /**< Set Pin for TRACE mode */
    PORT_PIN_MODE_MSS_MCU,
    /**< Set Pin for MCU CLKOUT mode */
    PORT_PIN_MODE_MSS_OBS,
    /**< Set Pin for OBS CLKOUT mode */
    PORT_PIN_MODE_MSS_UARTA,
    /**< Set Pin for MSS UART mode */
    PORT_PIN_MODE_MSS_UARTB,
    /**< Set Pin for MSS UART mode */
    PORT_PIN_MODE_MSS_I2CA,
    /**< Set Pin for I2CA mode */
    PORT_PIN_MODE_MSS_MII,
    /**< Set Pin for MII mode */
    PORT_PIN_MODE_MSS_RMII,
    /**< Set Pin for RMII mode */
    PORT_PIN_MODE_MSS_RGMII,
    /**< Set Pin for RGMII mode */
    PORT_PIN_MODE_MSS_MDIO,
    /**< Set Pin for MDIO mode */
    PORT_PIN_MODE_MSS_CPTS0,
    /**< Set Pin for CPTS0 mode */
    PORT_PIN_MODE_PMIC,
    /**< Set Pin for PMIC mode */
    PORT_PIN_MODE_SYNC_IN,
    /**< Set Pin for SYNC modes */
    PORT_PIN_MODE_SYNC_OUT,
    /**< Set Pin for SYNC modes */
    PORT_PIN_MODE_DSS_UARTA_TX,
    /**< Set Pin for DSS modes */
    PORT_PIN_MODE_DSS_UARTA_RX,
    /**< Set Pin for DSS modes */
    PORT_PIN_MODE_DSS_UARTB_TX,
    /**< Set Pin for DSS modes */
    PORT_PIN_MODE_DSS_UARTB_RX,
    /**< Set Pin for DSS modes */
    PORT_PIN_MODE_BSS_UARTA_TX,
    /**< Set Pin for BSS modes */
    PORT_PIN_MODE_BSS_UARTA_RX,
    /**< Set Pin for BSS modes */
    PORT_PIN_MODE_BSS_UARTB_TX,
    /**< Set Pin for BSS modes */
    PORT_PIN_MODE_BSS_UARTB_RX,
    /**< Set Pin for BSS modes */

	PORT_PIN_MODE_RCSS_I2CA,
    /**< Set Pin for RCSS_I2C A mode */
    PORT_PIN_MODE_RCSS_I2CB,
    /**< Set Pin for RCSS_I2C B mode */
    PORT_PIN_MODE_RCSS_ATL,
    /**< Set Pin for RCSS_ATL mode */
    PORT_PIN_MODE_RCSS_ECAPA,
    /**< Set Pin for RCSS_ECAPA mode */
    PORT_PIN_MODE_RCSS_MCASPA,
    /**< Set Pin for RCSS_MCASPA mode */
    PORT_PIN_MODE_RCSS_MCASPB,
    /**< Set Pin for RCSS_MCASPB mode */
    PORT_PIN_MODE_RCSS_MCASPC,
    /**< Set Pin for RCSS_MCASPC mode */
    PORT_PIN_MODE_RCSS_GPIO,
    /**< Set Pin for RCSS_GPIO mode */
    PORT_PIN_MODE_RCSS_MIBSPIA,
    /**< Set Pin for RCSS_MIBSPIA mode */
    PORT_PIN_MODE_RCSS_MIBSPIB,
    /**< Set Pin for RCSS_MIBSPIB mode */
    PORT_PIN_MODE_RCSS_UARTA,
    /**< Set Pin for RCSS_UARTA mode */

    PORT_PIN_MODE_MSS_EPWMA,
    /**< Set Pin for EPWMA mode */
    PORT_PIN_MODE_MSS_EPWMB,
    /**< Set Pin for EPWMB mode */
    PORT_PIN_MODE_MSS_EPWMC,
    /**< Set Pin for EPWMC mode */
    PORT_PIN_MODE_MSS_LVDSVALID,
    /**< Set Pin for LVDS mode */
    PORT_PIN_MODE_MSS_SYNCIN,
    /**< Set Pin for SYNCIN mode */
    PORT_PIN_MODE_MSS_SYNCOUT,
    /**< Set Pin for SYNCOUT mode */
    PORT_PIN_MODE_MSS_EPWM,
    /**< Set Pin for EPWM SYNC mode */
    PORT_PIN_MODE_MSS_READYINT,
    /**< Set Pin for READYINT mode */
    PORT_PIN_MODE_MSS_TRACE,
    /**< Set Pin for TRACE mode */
    PORT_PIN_MODE_MSS_MCUCLKOUT,
    /**< Set Pin for MCUCLKOUT mode */
    PORT_PIN_MODE_MSS_XREFCLK0,
    /**< Set Pin for XREFCLK0 mode */
    PORT_PIN_MODE_MSS_XREFCLK1,
    /**< Set Pin for XREFCLK1 mode */
    PORT_PIN_MODE_MSS_PMIC,
    /**< Set Pin for PMIC mode */
    PORT_PIN_MODE_MSS_CHIRPSTART,
    /**< Set Pin for CHIRPSTART mode */
    PORT_PIN_MODE_MSS_CHIRPEND,
    /**< Set Pin for CHIRPEND mode */
    PORT_PIN_MODE_MSS_DMM,
    /**< Set Pin for DMM mode */
    PORT_PIN_MODE_MSS_RCOSC,
    /**< Set Pin for ROSC mode */
    PORT_PIN_MODE_MSS_JTAG,
    /**< Set Pin for MSS_JTAG mode */
    PORT_PIN_MODE_MSS_FRAMESTART,
    /**< Set Pin for FRAMESTART mode */
    PORT_PIN_MODE_MSS_OBSCLKOUT,
    /**< Set Pin for OBS CLKOUT mode */
    PORT_PIN_MODE_MSS_ADCVALID,
    /**< Set Pin for ADC VALID mode */
    PORT_PIN_MODE_MSS_FE2REFCLK,
    /**< Set Pin for FE2REFCLK mode */
    PORT_PIN_MODE_MSS_RCOSCCLK,
    /**< Set Pin for RCOSCCLK mode */
    PORT_PIN_MODE_MSS_NDMMEN,
    /**< Set Pin for NDMMEN mode */
    PORT_PIN_MODE_INVALID,
    /**< Invalid pin mode. For internal use */
} Port_PinModeType;

/**
 *  \brief SubSystem Selection
 */
 typedef enum
{
    PORT_MSS,
    PORT_RCSS,
} Port_DioSubsystemType;

/**
 *  \brief GPIO Pin Edge trigger intruppt selection
 */
typedef enum
{
	PORT_FALLING_EDGE,
    PORT_RISING_EDGE,
    PORT_BOTH_EDGE,
} Port_EdgeTrig;

/**
 *  \brief GPIO Pin Level trigger intruppt selection
 */
typedef enum
{
    PORT_LOW_LEVEL,
    PORT_HIGH_LEVEL,
} Port_LevelTrig;

/**
 *  \brief GPIO Pin Intruppt Registers Status
 */
typedef struct
{
    uint32 MssIntrLevel;
    uint32 RcssIntrLevel;

    uint32 MssIntrEnable;
    uint32 RcssIntrEnable;

    uint8 IntrIdxNum[64];

} Port_IntrStatus;


/** \brief  Notification callback function pointer  */
typedef void (*Port_IsrNotificationType)(uint8 PinNum, Port_LevelTrig Level);


/**
 *  \brief Pin Mode map structure
 *
 *  Structure to map selected mode to corresponding PAD CONFIG MUXMODE value
 */
typedef struct
{
    Port_PinModeType mode;
    /**< Selected pin mode */
    uint32          muxmode;
    /**< Function Select/Muxmode for selected pin mode */
} Port_PinModeConfigType;

/**
 *  \brief Pin Configuration structure
 */
typedef struct
{
    Port_PinType             Port_PinId;
    /**< Port Pin Id */
    boolean                  Port_DirectionChangeable;
    /**< Flag indicating if pin direction is changeable */
    boolean                  Port_PinModeChangeable;
    /**< Flag indicating if Pin mode is changeable */
    Port_PinLevelValueType   Port_PinLevelValue;
    /**< Pin level value */
    Port_PinDirectionType    Port_PinDirection;
    /**< Pin direction  @sa Port_PinDirectionType */
    uint32                   Port_NumPortModes;
    /**< Number of modes supported for this pin */
    Port_PinModeConfigType   Port_PinMode[PORT_MAX_MUXMODE];
    /**< Pin mode @sa Port_PinModeType */
    Port_PinModeType         Port_PinInitialMode;
    /**< Pin initial mode @sa Port_PinModeType */
    Port_PinPullSelectType   Port_PullTypeSelect;
    /**< Type of PULL U/D selection @sa Port_PinPullSelectType */
    Port_PinSlewControlType  Port_SlewControl;
    /**< Slew control configuration @sa Port_PinSlewControlType */
    Port_PinPullInhibitEnableType Port_PullInhibitEnable;
    /**< Pull inhibit control configuration @sa Port_PinPullInhibitEnableType*/
    Port_PinInputOverrideCtrl Port_InputOverride_Ctrl;
    /**< Active Low input override control*/
    Port_PinOutputOverrideCtrl Port_OutputOverride_Ctrl;
    /**< Active Low output override control*/
    uint32                   Port_RegOffsetAddr;
    /**< Register base address for configuring this pin */
    uint32                   Port_PinDioRegId;
    /**< GPIO register id corresponding to this pin */
    uint32                   Port_PinDioChannelId;
    /**< GPIO channel corresponding to this pin in GPIO register */
    const sint8             *Port_PinSignalName;
    /**< Pin signal name.Just for information. Not used internally.Can be NULL
    **/
    const sint8             *Port_PinName;
    /**< Pin name.Just for information. Not used internally.Can be NULL */
} Port_PinConfigType;



/**
 *  \brief Port GPIO initialization configuration
 */
typedef struct
{
    uint8                       		Port_DioRegId;
    /**< GPIO register number */
	Port_DioSubsystemType				Port_DioSubsystem;
	/**< SubSystem Selection */
	uint8 					            Port_DioPinNumber;
	/**< GPIO Pin Interrupt Enable/Disbale */
	Port_EdgeTrig 					    Port_DioEdgeTrigger;
	/**< GPIO Edge Trigger Interrupt (Rising/Falling) */
	Port_LevelTrig 					    Port_DioLevelTrigger;
	/**< GPIO Level Trigger Interrupt (High-Level/Low-Level) */

	Port_IsrNotificationType		   Port_DioIntrNotification;
	/**< ISR callback function pointer*/

} Port_DioRegConfigType;


/*
*Design: MCAL-13969, MCAL-13974, MCAL-14011, MCAL-13983, MCAL-13999, MCAL-14042
*/
/**
 *  \brief PORT Module ROOT configuration
 */
typedef struct Port_ConfigType_s
{
    uint16 NumberOfPortPins;
    /**< Number of pins individually configure. Should not conflict with
     *   pins enabled by selecting module enable */
    P2CONST(Port_PinConfigType, AUTOMATIC, PORT_PBCFG) PinConfig_pt;
    /**< Pointer to pin configuration structure */
    uint32 NumberOfGPIORegs;
    /**< Number of GPIO registers to configure */
    P2CONST(Port_DioRegConfigType, AUTOMATIC, PORT_PBCFG) DioConfig_pt;
    /**< DIO config structure */
} Port_ConfigType;

/**********************************************************************************************************************
 *  GLOBAL DATA TYPES AND STRUCTURES
 *********************************************************************************************************************/

extern const struct Port_ConfigType_s PortConfigSet_0;


#ifdef __cplusplus
}
#endif

#endif  /* PORT_CFG_H */

/**********************************************************************************************************************
 *  END OF FILE: Port_Cfg.h
 *********************************************************************************************************************/
