/* ======================================================================
 *   Copyright (C) 2022-2023 Texas Instruments Incorporated
 *
 *   All rights reserved. Property of Texas Instruments Incorporated.
 *   Restricted rights to use, duplicate or disclose this code are
 *   granted through contract.
 *
 *   The program may not be used without the written permission
 *   of Texas Instruments Incorporated or against the terms and conditions
 *   stipulated in the agreement under which this program has been
 *   supplied.
 * ==================================================================== */

/**

 *  -------------------------------------------------------------------------------------------------------------------
 *  FILE DESCRIPTION
 *  -------------------------------------------------------------------------------------------------------------------
 *         File:  Pwm_Cfg.c
 *      Project:  TI Sitara MCU AM263x PwmDriver
 *       Module:  DriverPwm
 *    Generator:  EB Tresos
 *
 *  Description:  This component provides services for initialization and control of the microcontroller internal
 *                PWM unit (pulse width modulation). The PWM module generates pulses with variable pulse width.
 *                It allows the selection of the duty cycle and the signal period time.
 *
 *********************************************************************************************************************/


/**********************************************************************************************************************
    Project: Pwm_am263x
    Date   : 2024-02-13 15:51:12

    This file is generated by EB Tresos
    Do not modify this file, otherwise the software may behave in unexpected way.
 *********************************************************************************************************************/

#include "Std_Types.h"

#include "Pwm.h"
#ifdef __cplusplus

extern "C" {
#endif


/* ---- Perform version checking  ----------------------------------------- */
 #if ((PWM_SW_MAJOR_VERSION != (10U))||(PWM_SW_MINOR_VERSION != (2U)))
  #error "Version numbers of Pwm_PBcfg.c and Pwm_Cfg.h are inconsistent!"
#endif

#if ((PWM_CFG_MAJOR_VERSION != (10U))||(PWM_CFG_MINOR_VERSION != (2U)))
  #error "Version numbers of Pwm_Cfg.c and Pwm_Cfg.h are inconsistent!"
#endif

/*Requirements : SWS_Pwm_60075*/
/*
*Design: MCAL-13123
*/
#define PWM_START_SEC_CONFIG_DATA
#include "Pwm_MemMap.h"


extern void Pwm_Notification_Channel1 (void);

/* Pwm Channel Configuration parameters */
CONST(struct Pwm_ConfigType_PC_s, PWM_CONFIG_DATA)
    Pwm_Config_PC =
{
    .chCfg =
    {
        [0] =
        {
            .channelId = PwmConf_PwmChannel_PwmChannel_0,
            .channelHwId = PWM_CHANNEL_PWM_CONTROLSS_G0_PWMCHANNEL9,
            .outputCh = (uint32)PWM_OUTPUT_CH_BOTH_A_AND_B, /*Output Channel Select*/
        }
    },
};


#ifdef __cplusplus
}
#endif

/*</PWM_CONFIGURATION>*/
#define PWM_STOP_SEC_CONFIG_DATA
#include "Pwm_MemMap.h"

/**********************************************************************************************************************
 *  END OF FILE: Pwm_Cfg.c                                                                                          *
 *********************************************************************************************************************/
